// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResolveRequest {
    #[prost(message, optional, tag = "2")]
    pub table: ::core::option::Option<super::super::common::v1::TableRef>,
    /// Optional column projection + predicate pushdown hints (opaque to core).
    #[prost(string, repeated, tag = "3")]
    pub columns: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "4")]
    pub predicate: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResolveResponse {
    /// Out-of-band Arrow endpoint to pull matching record batches from.
    #[prost(message, optional, tag = "1")]
    pub stream: ::core::option::Option<super::super::common::v1::ArrowStream>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AppendRequest {
    #[prost(message, optional, tag = "2")]
    pub table: ::core::option::Option<super::super::common::v1::TableRef>,
    /// Source Arrow stream the format pulls rows from.
    #[prost(message, optional, tag = "3")]
    pub source: ::core::option::Option<super::super::common::v1::ArrowStream>,
    /// Stable id for THIS logical write (e.g. the run id). Makes the write idempotent
    /// under an at-least-once retry (C1, ADR-012): a repeated key that already committed
    /// is a no-op returning the original WriteResult with already_applied=true. Empty ==
    /// not idempotent. The effect-leg twin of catalog MergeBranch/CommitTable idempotency.
    #[prost(string, tag = "4")]
    pub idempotency_key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AppendResponse {
    #[prost(message, optional, tag = "1")]
    pub result: ::core::option::Option<super::super::common::v1::WriteResult>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MergeRequest {
    #[prost(message, optional, tag = "2")]
    pub table: ::core::option::Option<super::super::common::v1::TableRef>,
    #[prost(message, optional, tag = "3")]
    pub source: ::core::option::Option<super::super::common::v1::ArrowStream>,
    /// The key columns to match existing rows on.
    #[prost(string, repeated, tag = "4")]
    pub merge_keys: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Idempotent-write key — see AppendRequest.idempotency_key (C1, ADR-012). Empty ==
    /// not idempotent.
    #[prost(string, tag = "5")]
    pub idempotency_key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MergeResponse {
    #[prost(message, optional, tag = "1")]
    pub result: ::core::option::Option<super::super::common::v1::WriteResult>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OverwriteRequest {
    #[prost(message, optional, tag = "2")]
    pub table: ::core::option::Option<super::super::common::v1::TableRef>,
    #[prost(message, optional, tag = "3")]
    pub source: ::core::option::Option<super::super::common::v1::ArrowStream>,
    /// Idempotent-write key — see AppendRequest.idempotency_key (C1, ADR-012). Empty ==
    /// not idempotent.
    #[prost(string, tag = "4")]
    pub idempotency_key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OverwriteResponse {
    #[prost(message, optional, tag = "1")]
    pub result: ::core::option::Option<super::super::common::v1::WriteResult>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MaintainRequest {
    #[prost(message, optional, tag = "2")]
    pub table: ::core::option::Option<super::super::common::v1::TableRef>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MaintainResponse {
    #[prost(message, optional, tag = "1")]
    pub result: ::core::option::Option<super::super::common::v1::WriteResult>,
}
include!("rat.format.v1.tonic.rs");
// @@protoc_insertion_point(module)