// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsageEvent {
    /// Metric name, e.g. "pipeline.run", "storage.bytes", "credential.vend".
    #[prost(string, tag="1")]
    pub meter: ::prost::alloc::string::String,
    /// Quantity in the meter's natural unit (runs=1, bytes=N, etc.).
    #[prost(double, tag="2")]
    pub quantity: f64,
    #[prost(int64, tag="3")]
    pub timestamp_unix_ms: i64,
    /// Dimensions for breakdown (pipeline id, plugin id, etc.).
    #[prost(map="string, string", tag="4")]
    pub dimensions: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordRequest {
    #[prost(message, optional, tag="1")]
    pub context: ::core::option::Option<super::super::common::v1::RequestContext>,
    /// Tenant is taken from context.identity.tenant (C7); events meter per tenant.
    #[prost(message, repeated, tag="2")]
    pub events: ::prost::alloc::vec::Vec<UsageEvent>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecordResponse {
    #[prost(int64, tag="1")]
    pub recorded: i64,
}
include!("rat.billing.v1.tonic.rs");
// @@protoc_insertion_point(module)