// Notifications axis service contract. DRAFT — sub-phase 0b.
//
// A `kind: notifications` plugin (slack, email, webhook, PagerDuty) delivers
// messages triggered by platform events (pipeline failed, plane warmed, etc.).
// It is a delivery sink; WHAT to notify on is the operator's subscription config
// (overview.md reconciliation: subscriptions = [event, action]), not this plugin.
//
// Capability mapping:
//   rat://notifications/v1/send -> Send

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file rat/notifications/v1/notifications.proto (package rat.notifications.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { RequestContext } from "../../common/v1/context_pb";
import { file_rat_common_v1_context } from "../../common/v1/context_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file rat/notifications/v1/notifications.proto.
 */
export const file_rat_notifications_v1_notifications: GenFile = /*@__PURE__*/
  fileDesc("CihyYXQvbm90aWZpY2F0aW9ucy92MS9ub3RpZmljYXRpb25zLnByb3RvEhRyYXQubm90aWZpY2F0aW9ucy52MSKWAgoLU2VuZFJlcXVlc3QSLgoHY29udGV4dBgBIAEoCzIdLnJhdC5jb21tb24udjEuUmVxdWVzdENvbnRleHQSMAoIc2V2ZXJpdHkYAiABKA4yHi5yYXQubm90aWZpY2F0aW9ucy52MS5TZXZlcml0eRINCgV0aXRsZRgDIAEoCRIMCgRib2R5GAQgASgJEg4KBnRhcmdldBgFIAEoCRJFCgphdHRyaWJ1dGVzGAYgAygLMjEucmF0Lm5vdGlmaWNhdGlvbnMudjEuU2VuZFJlcXVlc3QuQXR0cmlidXRlc0VudHJ5GjEKD0F0dHJpYnV0ZXNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBIjUKDFNlbmRSZXNwb25zZRIRCglkZWxpdmVyZWQYASABKAgSEgoKbWVzc2FnZV9pZBgCIAEoCSp4CghTZXZlcml0eRIYChRTRVZFUklUWV9VTlNQRUNJRklFRBAAEhEKDVNFVkVSSVRZX0lORk8QARIUChBTRVZFUklUWV9XQVJOSU5HEAISEgoOU0VWRVJJVFlfRVJST1IQAxIVChFTRVZFUklUWV9DUklUSUNBTBAEMmUKFE5vdGlmaWNhdGlvbnNTZXJ2aWNlEk0KBFNlbmQSIS5yYXQubm90aWZpY2F0aW9ucy52MS5TZW5kUmVxdWVzdBoiLnJhdC5ub3RpZmljYXRpb25zLnYxLlNlbmRSZXNwb25zZUJBWj9naXRodWIuY29tL3JhdC1kZXYvcmF0L2dlbi9yYXQvbm90aWZpY2F0aW9ucy92MTtub3RpZmljYXRpb25zdjFiBnByb3RvMw", [file_rat_common_v1_context]);

/**
 * @generated from message rat.notifications.v1.SendRequest
 */
export type SendRequest = Message<"rat.notifications.v1.SendRequest"> & {
  /**
   * @generated from field: rat.common.v1.RequestContext context = 1;
   */
  context?: RequestContext | undefined;

  /**
   * @generated from field: rat.notifications.v1.Severity severity = 2;
   */
  severity: Severity;

  /**
   * Short title + longer body. Plugins MUST NOT include secrets (I13); the core
   * redacts, but emitters share the obligation.
   *
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * @generated from field: string body = 4;
   */
  body: string;

  /**
   * Optional routing target (channel, address) — plugin-specific interpretation.
   *
   * @generated from field: string target = 5;
   */
  target: string;

  /**
   * Structured context for templating + correlation (incl. correlation_id, C1).
   *
   * @generated from field: map<string, string> attributes = 6;
   */
  attributes: { [key: string]: string };
};

/**
 * Describes the message rat.notifications.v1.SendRequest.
 * Use `create(SendRequestSchema)` to create a new message.
 */
export const SendRequestSchema: GenMessage<SendRequest> = /*@__PURE__*/
  messageDesc(file_rat_notifications_v1_notifications, 0);

/**
 * @generated from message rat.notifications.v1.SendResponse
 */
export type SendResponse = Message<"rat.notifications.v1.SendResponse"> & {
  /**
   * @generated from field: bool delivered = 1;
   */
  delivered: boolean;

  /**
   * Provider message id, if any (for delivery tracking).
   *
   * @generated from field: string message_id = 2;
   */
  messageId: string;
};

/**
 * Describes the message rat.notifications.v1.SendResponse.
 * Use `create(SendResponseSchema)` to create a new message.
 */
export const SendResponseSchema: GenMessage<SendResponse> = /*@__PURE__*/
  messageDesc(file_rat_notifications_v1_notifications, 1);

/**
 * @generated from enum rat.notifications.v1.Severity
 */
export enum Severity {
  /**
   * @generated from enum value: SEVERITY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SEVERITY_INFO = 1;
   */
  INFO = 1,

  /**
   * @generated from enum value: SEVERITY_WARNING = 2;
   */
  WARNING = 2,

  /**
   * @generated from enum value: SEVERITY_ERROR = 3;
   */
  ERROR = 3,

  /**
   * @generated from enum value: SEVERITY_CRITICAL = 4;
   */
  CRITICAL = 4,
}

/**
 * Describes the enum rat.notifications.v1.Severity.
 */
export const SeveritySchema: GenEnum<Severity> = /*@__PURE__*/
  enumDesc(file_rat_notifications_v1_notifications, 0);

/**
 * @generated from service rat.notifications.v1.NotificationsService
 */
export const NotificationsService: GenService<{
  /**
   * rat://notifications/v1/send — deliver one notification.
   *
   * @generated from rpc rat.notifications.v1.NotificationsService.Send
   */
  send: {
    methodKind: "unary";
    input: typeof SendRequestSchema;
    output: typeof SendResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_rat_notifications_v1_notifications, 0);

