// Audit-log axis service contract. Status: v1 (frozen — rat/1.2; ADR-003: control-plane = one ref + conformance).
//
// A `kind: audit-log` plugin (file, syslog, SIEM, immutable object store) is a
// SINK for the core's audit stream.
//
// CRITICAL (reviews/04 I8 — mandatory audit trail): unlike most axes, audit
// emission is NOT optional. The core ALWAYS emits an append-only, tamper-evident
// record of security-relevant events (plugin installs, binding changes,
// credential vends, auth decisions) — even when NO audit-log plugin is installed
// (it falls back to a core-local append-only store). "audit-log: none" must NOT
// mean "no audit". This plugin axis decides WHERE the trail goes, never WHETHER
// it exists. That is why audit is in the core's enforcement layer
// (plugin-architecture.md cross-cutting concerns), and this axis is only the
// export sink.
//
// Capability mapping:
//   rat://auditlog/v1/append -> Append
//
// FREEZE-BLOCKER #4 (reviews/06 C-3 = SEC-5 ⊕ API-5). The earlier draft was
// "tamper-evident" in name only. Four fixes, all on the wire here:
//
//   1. CORE AUTHORS THE CHAIN, NOT THE SINK OR AN ARBITRARY CALLER. `id` and
//      `prev_hash` are assigned by the core, which serializes all audit events
//      into ONE linear chain. Append is CORE-ONLY: the capability is not
//      grantable to ordinary plugins, so no plugin can inject records or fork
//      the chain, and concurrent emitters can't race `prev_hash`.
//   2. EACH RECORD IS CORE-SIGNED (Ed25519 over the canonical serialization).
//      A third-party sink can VERIFY the chain but cannot FORGE or silently
//      rewrite/reorder/drop records without detection. "must not allow mutation"
//      is now cryptographically checkable, not a comment the sink may ignore.
//   3. CANONICAL SERIALIZATION IS PINNED (see AuditRecord) so every
//      implementation hashes+signs the same bytes — cross-impl verification is
//      well-defined. This is un-retrofittable once chains exist, hence pre-freeze.
//   4. THE RESPONSE REPORTS PER-RECORD STATUS, COMMIT IS PREFIX-ONLY. The old
//      `appended: int64` hid partial failure — committing records[0]+[2] while
//      rejecting [1] forks the chain. Now `AppendResponse.acks` is per-record and
//      commit is a contiguous PREFIX: a REJECTED entry means every later record
//      in the request is uncommitted. A chain-head watermark lets a reconnecting
//      emitter resume with no gap/fork.
//
// Two prose invariants the contract assumes:
//   - A REJECTED or DROPPED audit record is ITSELF an auditable event — the core
//     emits a meta-audit entry; "mandatory" means a record cannot be lost
//     silently.
//   - APPEND_STATUS_DUPLICATE is the idempotent-retry safety valve: the core-only
//     + signed model forces retry on transport failure, so re-appending an
//     already-stored record MUST NOT double-append or fork — the sink acks
//     DUPLICATE.

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file rat/auditlog/v1/auditlog.proto (package rat.auditlog.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { AuditRecord } from "../../common/v1/audit_pb";
import { file_rat_common_v1_audit } from "../../common/v1/audit_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file rat/auditlog/v1/auditlog.proto.
 */
export const file_rat_auditlog_v1_auditlog: GenFile = /*@__PURE__*/
  fileDesc("Ch5yYXQvYXVkaXRsb2cvdjEvYXVkaXRsb2cucHJvdG8SD3JhdC5hdWRpdGxvZy52MSJCCg1BcHBlbmRSZXF1ZXN0EisKB3JlY29yZHMYAiADKAsyGi5yYXQuY29tbW9uLnYxLkF1ZGl0UmVjb3JkSgQIARACIngKCVJlY29yZEFjaxIKCgJpZBgBIAEoCRItCgZzdGF0dXMYAiABKA4yHS5yYXQuYXVkaXRsb2cudjEuQXBwZW5kU3RhdHVzEjAKC3JlamVjdF9jb2RlGAMgASgOMhsucmF0LmF1ZGl0bG9nLnYxLlJlamVjdENvZGUicgoOQXBwZW5kUmVzcG9uc2USKAoEYWNrcxgBIAMoCzIaLnJhdC5hdWRpdGxvZy52MS5SZWNvcmRBY2sSGQoRbGFzdF9jb21taXR0ZWRfaWQYAiABKAkSGwoTbGFzdF9jb21taXR0ZWRfaGFzaBgDIAEoCSqDAQoMQXBwZW5kU3RhdHVzEh0KGUFQUEVORF9TVEFUVVNfVU5TUEVDSUZJRUQQABIbChdBUFBFTkRfU1RBVFVTX0NPTU1JVFRFRBABEhsKF0FQUEVORF9TVEFUVVNfRFVQTElDQVRFEAISGgoWQVBQRU5EX1NUQVRVU19SRUpFQ1RFRBADKoQBCgpSZWplY3RDb2RlEhsKF1JFSkVDVF9DT0RFX1VOU1BFQ0lGSUVEEAASHQoZUkVKRUNUX0NPREVfQkFEX1NJR05BVFVSRRABEhsKF1JFSkVDVF9DT0RFX0NIQUlOX0JSRUFLEAISHQoZUkVKRUNUX0NPREVfU1RPUkFHRV9FUlJPUhADMlwKD0F1ZGl0TG9nU2VydmljZRJJCgZBcHBlbmQSHi5yYXQuYXVkaXRsb2cudjEuQXBwZW5kUmVxdWVzdBofLnJhdC5hdWRpdGxvZy52MS5BcHBlbmRSZXNwb25zZUI3WjVnaXRodWIuY29tL3JhdC1kZXYvcmF0L2dlbi9yYXQvYXVkaXRsb2cvdjE7YXVkaXRsb2d2MWIGcHJvdG8z", [file_rat_common_v1_audit]);

/**
 * @generated from message rat.auditlog.v1.AppendRequest
 */
export type AppendRequest = Message<"rat.auditlog.v1.AppendRequest"> & {
  /**
   * Core-authored, core-signed records to append, in chain order.
   *
   * @generated from field: repeated rat.common.v1.AuditRecord records = 2;
   */
  records: AuditRecord[];
};

/**
 * Describes the message rat.auditlog.v1.AppendRequest.
 * Use `create(AppendRequestSchema)` to create a new message.
 */
export const AppendRequestSchema: GenMessage<AppendRequest> = /*@__PURE__*/
  messageDesc(file_rat_auditlog_v1_auditlog, 0);

/**
 * Ack for one record in the request; acks[i] corresponds to records[i].
 *
 * @generated from message rat.auditlog.v1.RecordAck
 */
export type RecordAck = Message<"rat.auditlog.v1.RecordAck"> & {
  /**
   * The core-assigned id this ack refers to (mirrors records[i].id).
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: rat.auditlog.v1.AppendStatus status = 2;
   */
  status: AppendStatus;

  /**
   * Set only when status == APPEND_STATUS_REJECTED.
   *
   * @generated from field: rat.auditlog.v1.RejectCode reject_code = 3;
   */
  rejectCode: RejectCode;
};

/**
 * Describes the message rat.auditlog.v1.RecordAck.
 * Use `create(RecordAckSchema)` to create a new message.
 */
export const RecordAckSchema: GenMessage<RecordAck> = /*@__PURE__*/
  messageDesc(file_rat_auditlog_v1_auditlog, 1);

/**
 * @generated from message rat.auditlog.v1.AppendResponse
 */
export type AppendResponse = Message<"rat.auditlog.v1.AppendResponse"> & {
  /**
   * Per-record acks in request order. COMMIT IS PREFIX-ONLY: once a record is
   * REJECTED, all later records in the request are uncommitted (never acked
   * COMMITTED), so the committed set is always a contiguous prefix — the chain
   * can't fork on partial failure.
   *
   * @generated from field: repeated rat.auditlog.v1.RecordAck acks = 1;
   */
  acks: RecordAck[];

  /**
   * Chain head after this append: the id + canonical-hash of the last durably
   * committed record. A reconnecting emitter resumes deterministically from here
   * with no gap/fork; also distinguishes "dropped" (absent from the chain) from
   * "in-flight".
   *
   * @generated from field: string last_committed_id = 2;
   */
  lastCommittedId: string;

  /**
   * @generated from field: string last_committed_hash = 3;
   */
  lastCommittedHash: string;
};

/**
 * Describes the message rat.auditlog.v1.AppendResponse.
 * Use `create(AppendResponseSchema)` to create a new message.
 */
export const AppendResponseSchema: GenMessage<AppendResponse> = /*@__PURE__*/
  messageDesc(file_rat_auditlog_v1_auditlog, 2);

/**
 * Per-record disposition of an Append.
 *
 * @generated from enum rat.auditlog.v1.AppendStatus
 */
export enum AppendStatus {
  /**
   * @generated from enum value: APPEND_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Durably stored and chain-linked.
   *
   * @generated from enum value: APPEND_STATUS_COMMITTED = 1;
   */
  COMMITTED = 1,

  /**
   * Already stored (idempotent retry) — NOT an error; the chain is intact.
   *
   * @generated from enum value: APPEND_STATUS_DUPLICATE = 2;
   */
  DUPLICATE = 2,

  /**
   * Not stored. See reject_code. Implies prefix-only: every later record in the
   * same request is also uncommitted.
   *
   * @generated from enum value: APPEND_STATUS_REJECTED = 3;
   */
  REJECTED = 3,
}

/**
 * Describes the enum rat.auditlog.v1.AppendStatus.
 */
export const AppendStatusSchema: GenEnum<AppendStatus> = /*@__PURE__*/
  enumDesc(file_rat_auditlog_v1_auditlog, 0);

/**
 * @generated from enum rat.auditlog.v1.RejectCode
 */
export enum RejectCode {
  /**
   * @generated from enum value: REJECT_CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Signature did not verify against the core's key.
   *
   * @generated from enum value: REJECT_CODE_BAD_SIGNATURE = 1;
   */
  BAD_SIGNATURE = 1,

  /**
   * prev_hash does not match the sink's current chain head (gap/fork attempt).
   *
   * @generated from enum value: REJECT_CODE_CHAIN_BREAK = 2;
   */
  CHAIN_BREAK = 2,

  /**
   * Sink-side durable-storage failure (retryable).
   *
   * @generated from enum value: REJECT_CODE_STORAGE_ERROR = 3;
   */
  STORAGE_ERROR = 3,
}

/**
 * Describes the enum rat.auditlog.v1.RejectCode.
 */
export const RejectCodeSchema: GenEnum<RejectCode> = /*@__PURE__*/
  enumDesc(file_rat_auditlog_v1_auditlog, 1);

/**
 * @generated from service rat.auditlog.v1.AuditLogService
 */
export const AuditLogService: GenService<{
  /**
   * rat://auditlog/v1/append — append core-authored, core-signed audit records
   * to the sink. CORE-ONLY: this capability is not grantable to ordinary
   * plugins. Records are also retained core-locally, so the sink is a fan-out,
   * not the only copy.
   *
   * @generated from rpc rat.auditlog.v1.AuditLogService.Append
   */
  append: {
    methodKind: "unary";
    input: typeof AppendRequestSchema;
    output: typeof AppendResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_rat_auditlog_v1_auditlog, 0);

