// Audit-log axis service contract. DRAFT — sub-phase 0b.
//
// A `kind: audit-log` plugin (file, syslog, SIEM, immutable object store) is a
// SINK for the core's audit stream.
//
// CRITICAL (reviews/04 I8 — mandatory audit trail): unlike most axes, audit
// emission is NOT optional. The core ALWAYS emits an append-only, tamper-evident
// record of security-relevant events (plugin installs, binding changes,
// credential vends, auth decisions) — even when NO audit-log plugin is installed
// (it falls back to a core-local append-only store). "audit-log: none" must NOT
// mean "no audit". This plugin axis decides WHERE the trail goes, never WHETHER
// it exists. That is why audit is in the core's enforcement layer
// (plugin-architecture.md cross-cutting concerns), and this axis is only the
// export sink.
//
// Capability mapping:
//   rat://auditlog/v1/append -> Append
//
// FREEZE-BLOCKER #4 (reviews/06 C-3 = SEC-5 ⊕ API-5). The earlier draft was
// "tamper-evident" in name only. Four fixes, all on the wire here:
//
//   1. CORE AUTHORS THE CHAIN, NOT THE SINK OR AN ARBITRARY CALLER. `id` and
//      `prev_hash` are assigned by the core, which serializes all audit events
//      into ONE linear chain. Append is CORE-ONLY: the capability is not
//      grantable to ordinary plugins, so no plugin can inject records or fork
//      the chain, and concurrent emitters can't race `prev_hash`.
//   2. EACH RECORD IS CORE-SIGNED (Ed25519 over the canonical serialization).
//      A third-party sink can VERIFY the chain but cannot FORGE or silently
//      rewrite/reorder/drop records without detection. "must not allow mutation"
//      is now cryptographically checkable, not a comment the sink may ignore.
//   3. CANONICAL SERIALIZATION IS PINNED (see AuditRecord) so every
//      implementation hashes+signs the same bytes — cross-impl verification is
//      well-defined. This is un-retrofittable once chains exist, hence pre-freeze.
//   4. THE RESPONSE REPORTS PER-RECORD STATUS, COMMIT IS PREFIX-ONLY. The old
//      `appended: int64` hid partial failure — committing records[0]+[2] while
//      rejecting [1] forks the chain. Now `AppendResponse.acks` is per-record and
//      commit is a contiguous PREFIX: a REJECTED entry means every later record
//      in the request is uncommitted. A chain-head watermark lets a reconnecting
//      emitter resume with no gap/fork.
//
// Two prose invariants the contract assumes:
//   - A REJECTED or DROPPED audit record is ITSELF an auditable event — the core
//     emits a meta-audit entry; "mandatory" means a record cannot be lost
//     silently.
//   - APPEND_STATUS_DUPLICATE is the idempotent-retry safety valve: the core-only
//     + signed model forces retry on transport failure, so re-appending an
//     already-stored record MUST NOT double-append or fork — the sink acks
//     DUPLICATE.

// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file rat/auditlog/v1/auditlog.proto (package rat.auditlog.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AppendRequest, AppendResponse } from "./auditlog_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service rat.auditlog.v1.AuditLogService
 */
export const AuditLogService = {
  typeName: "rat.auditlog.v1.AuditLogService",
  methods: {
    /**
     * rat://auditlog/v1/append — append core-authored, core-signed audit records
     * to the sink. CORE-ONLY: this capability is not grantable to ordinary
     * plugins. Records are also retained core-locally, so the sink is a fan-out,
     * not the only copy.
     *
     * @generated from rpc rat.auditlog.v1.AuditLogService.Append
     */
    append: {
      name: "Append",
      I: AppendRequest,
      O: AppendResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

