// Catalog axis service contract. Status: v1 (frozen — rat/1, ADR-009;
// RegisterTable + CommitTable added additively at rat/1.1, ADR-010).
//
// A `kind: catalog` plugin (Nessie, Unity, Lakekeeper, Glue, Polaris) owns
// table metadata + branch/version semantics. It is what makes "branch-isolated
// pipeline runs" (the v2 pipeline model we keep — overview.md) possible.
//
// Capability mapping:
//   rat://catalog/v1/get-table     -> GetTable
//   rat://catalog/v1/create-branch -> CreateBranch
//   rat://catalog/v1/merge-branch  -> MergeBranch
//   rat://catalog/v1/register-table-> RegisterTable  (ADR-010, additive)
//   rat://catalog/v1/commit-table  -> CommitTable    (ADR-010, additive)
//
// Not every catalog supports branching (Glue doesn't); those plugins simply do
// not `provide` the branch capabilities, and the registry won't wire a
// branch-requiring strategy to them. Capability negotiation, not feature flags.
//
// MERGE SAFETY (reviews/06 #8 = ARCH-4 / I-18): MergeBranch is the publish gate
// of the pipeline model and the reconciler RETRIES it, so it must be safe under
// retry AND concurrency. Two fields make it so:
//   - `expected_into_snapshot` — optimistic concurrency on the target. The merge
//     applies only if `into_branch` is still at this snapshot; otherwise it fails
//     (the caller re-reads + re-tests). Without it, two concurrent merges into
//     main silently lose one side's updates (lost-update).
//   - `idempotency_key` — a stable id for THIS logical merge (e.g. the run id).
//     A retry with the same key that already committed is a no-op that returns
//     the original result (MergeBranchResponse.already_applied = true), so a
//     reconciler retry can't double-apply.
// NOTE: this is the branch-MERGE linkage. The separate gap — how the catalog
// learns what format.Write put on a branch — is closed by the additive
// commit-linkage RPCs below (RegisterTable + CommitTable), added at rat/1.1 per
// ADR-010 (resolving ADR-009 residual R3 / reviews/08 B1). They are additive: the
// frozen GetTable/CreateBranch/MergeBranch shapes are unchanged.

// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file rat/catalog/v1/catalog.proto (package rat.catalog.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CommitTableRequest, CommitTableResponse, CreateBranchRequest, CreateBranchResponse, GetTableRequest, GetTableResponse, MergeBranchRequest, MergeBranchResponse, RegisterTableRequest, RegisterTableResponse } from "./catalog_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service rat.catalog.v1.CatalogService
 */
export const CatalogService = {
  typeName: "rat.catalog.v1.CatalogService",
  methods: {
    /**
     * rat://catalog/v1/get-table — resolve a table identifier to a TableRef
     * (physical location + current snapshot/branch).
     *
     * @generated from rpc rat.catalog.v1.CatalogService.GetTable
     */
    getTable: {
      name: "GetTable",
      I: GetTableRequest,
      O: GetTableResponse,
      kind: MethodKind.Unary,
    },
    /**
     * rat://catalog/v1/create-branch — open an isolated branch for a pipeline run.
     *
     * @generated from rpc rat.catalog.v1.CatalogService.CreateBranch
     */
    createBranch: {
      name: "CreateBranch",
      I: CreateBranchRequest,
      O: CreateBranchResponse,
      kind: MethodKind.Unary,
    },
    /**
     * rat://catalog/v1/merge-branch — merge a completed run's branch back to main,
     * after quality tests pass (the pre-merge gate of the v2 pipeline model).
     *
     * @generated from rpc rat.catalog.v1.CatalogService.MergeBranch
     */
    mergeBranch: {
      name: "MergeBranch",
      I: MergeBranchRequest,
      O: MergeBranchResponse,
      kind: MethodKind.Unary,
    },
    /**
     * rat://catalog/v1/register-table — register a NEW table so a pipeline can
     * create its own output (not only read pre-existing tables). Idempotent:
     * re-registering an existing identifier returns the existing ref (reconcile-safe,
     * no ALREADY_EXISTS). The "register" half of the create→write→register→merge loop
     * (ADR-010 / reviews/08 B1). Distinct capability from commit-table so creating a
     * new catalog entry is a separately-grantable privilege (C5 method-level authz).
     *
     * @generated from rpc rat.catalog.v1.CatalogService.RegisterTable
     */
    registerTable: {
      name: "RegisterTable",
      I: RegisterTableRequest,
      O: RegisterTableResponse,
      kind: MethodKind.Unary,
    },
    /**
     * rat://catalog/v1/commit-table — record the snapshot a format.Write produced
     * for a table on a branch (the value returned in WriteResult.snapshot_id). This
     * is the commit-LINKAGE: the catalog learns exactly what landed. Safe under
     * retry + concurrency via the SAME model as MergeBranch — `expected_snapshot`
     * optimistic-concurrency guard + `idempotency_key` (the write-leg idempotency the
     * reviews/08 B1 architect→sre cross-consult flagged). ADR-010.
     *
     * @generated from rpc rat.catalog.v1.CatalogService.CommitTable
     */
    commitTable: {
      name: "CommitTable",
      I: CommitTableRequest,
      O: CommitTableResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

