// Catalog axis service contract. DRAFT — sub-phase 0b.
//
// A `kind: catalog` plugin (Nessie, Unity, Lakekeeper, Glue, Polaris) owns
// table metadata + branch/version semantics. It is what makes "branch-isolated
// pipeline runs" (the v2 pipeline model we keep — overview.md) possible.
//
// Capability mapping:
//   rat://catalog/v1/get-table    -> GetTable
//   rat://catalog/v1/create-branch-> CreateBranch
//   rat://catalog/v1/merge-branch -> MergeBranch
//
// Not every catalog supports branching (Glue doesn't); those plugins simply do
// not `provide` the branch capabilities, and the registry won't wire a
// branch-requiring strategy to them. Capability negotiation, not feature flags.
//
// MERGE SAFETY (reviews/06 #8 = ARCH-4 / I-18): MergeBranch is the publish gate
// of the pipeline model and the reconciler RETRIES it, so it must be safe under
// retry AND concurrency. Two fields make it so:
//   - `expected_into_snapshot` — optimistic concurrency on the target. The merge
//     applies only if `into_branch` is still at this snapshot; otherwise it fails
//     (the caller re-reads + re-tests). Without it, two concurrent merges into
//     main silently lose one side's updates (lost-update).
//   - `idempotency_key` — a stable id for THIS logical merge (e.g. the run id).
//     A retry with the same key that already committed is a no-op that returns
//     the original result (MergeBranchResponse.already_applied = true), so a
//     reconciler retry can't double-apply.
// NOTE: this is the branch-MERGE linkage. The separate gap — how the catalog
// learns what format.Write put on a branch — is the additive commit-linkage RPC
// (reviews/06 I-18), GA-deferred; only the request-shape change here is
// freeze-gated.

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file rat/catalog/v1/catalog.proto (package rat.catalog.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { TableRef } from "../../common/v1/data_pb";
import { file_rat_common_v1_data } from "../../common/v1/data_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file rat/catalog/v1/catalog.proto.
 */
export const file_rat_catalog_v1_catalog: GenFile = /*@__PURE__*/
  fileDesc("ChxyYXQvY2F0YWxvZy92MS9jYXRhbG9nLnByb3RvEg5yYXQuY2F0YWxvZy52MSI7Cg9HZXRUYWJsZVJlcXVlc3QSEgoKaWRlbnRpZmllchgCIAEoCRIOCgZicmFuY2gYAyABKAlKBAgBEAIiOgoQR2V0VGFibGVSZXNwb25zZRImCgV0YWJsZRgBIAEoCzIXLnJhdC5jb21tb24udjEuVGFibGVSZWYiQAoTQ3JlYXRlQnJhbmNoUmVxdWVzdBIOCgZicmFuY2gYAiABKAkSEwoLZnJvbV9icmFuY2gYAyABKAlKBAgBEAIiJgoUQ3JlYXRlQnJhbmNoUmVzcG9uc2USDgoGYnJhbmNoGAEgASgJIngKEk1lcmdlQnJhbmNoUmVxdWVzdBIOCgZicmFuY2gYAiABKAkSEwoLaW50b19icmFuY2gYAyABKAkSHgoWZXhwZWN0ZWRfaW50b19zbmFwc2hvdBgEIAEoCRIXCg9pZGVtcG90ZW5jeV9rZXkYBSABKAlKBAgBEAIiQwoTTWVyZ2VCcmFuY2hSZXNwb25zZRITCgtzbmFwc2hvdF9pZBgBIAEoCRIXCg9hbHJlYWR5X2FwcGxpZWQYAiABKAgykgIKDkNhdGFsb2dTZXJ2aWNlEk0KCEdldFRhYmxlEh8ucmF0LmNhdGFsb2cudjEuR2V0VGFibGVSZXF1ZXN0GiAucmF0LmNhdGFsb2cudjEuR2V0VGFibGVSZXNwb25zZRJZCgxDcmVhdGVCcmFuY2gSIy5yYXQuY2F0YWxvZy52MS5DcmVhdGVCcmFuY2hSZXF1ZXN0GiQucmF0LmNhdGFsb2cudjEuQ3JlYXRlQnJhbmNoUmVzcG9uc2USVgoLTWVyZ2VCcmFuY2gSIi5yYXQuY2F0YWxvZy52MS5NZXJnZUJyYW5jaFJlcXVlc3QaIy5yYXQuY2F0YWxvZy52MS5NZXJnZUJyYW5jaFJlc3BvbnNlQjVaM2dpdGh1Yi5jb20vcmF0LWRldi9yYXQvZ2VuL3JhdC9jYXRhbG9nL3YxO2NhdGFsb2d2MWIGcHJvdG8z", [file_rat_common_v1_data]);

/**
 * @generated from message rat.catalog.v1.GetTableRequest
 */
export type GetTableRequest = Message<"rat.catalog.v1.GetTableRequest"> & {
  /**
   * @generated from field: string identifier = 2;
   */
  identifier: string;

  /**
   * Optional branch to read from (empty == main).
   *
   * @generated from field: string branch = 3;
   */
  branch: string;
};

/**
 * Describes the message rat.catalog.v1.GetTableRequest.
 * Use `create(GetTableRequestSchema)` to create a new message.
 */
export const GetTableRequestSchema: GenMessage<GetTableRequest> = /*@__PURE__*/
  messageDesc(file_rat_catalog_v1_catalog, 0);

/**
 * @generated from message rat.catalog.v1.GetTableResponse
 */
export type GetTableResponse = Message<"rat.catalog.v1.GetTableResponse"> & {
  /**
   * @generated from field: rat.common.v1.TableRef table = 1;
   */
  table?: TableRef | undefined;
};

/**
 * Describes the message rat.catalog.v1.GetTableResponse.
 * Use `create(GetTableResponseSchema)` to create a new message.
 */
export const GetTableResponseSchema: GenMessage<GetTableResponse> = /*@__PURE__*/
  messageDesc(file_rat_catalog_v1_catalog, 1);

/**
 * @generated from message rat.catalog.v1.CreateBranchRequest
 */
export type CreateBranchRequest = Message<"rat.catalog.v1.CreateBranchRequest"> & {
  /**
   * Branch name to create (e.g. a run id).
   *
   * @generated from field: string branch = 2;
   */
  branch: string;

  /**
   * Branch point (empty == tip of main).
   *
   * @generated from field: string from_branch = 3;
   */
  fromBranch: string;
};

/**
 * Describes the message rat.catalog.v1.CreateBranchRequest.
 * Use `create(CreateBranchRequestSchema)` to create a new message.
 */
export const CreateBranchRequestSchema: GenMessage<CreateBranchRequest> = /*@__PURE__*/
  messageDesc(file_rat_catalog_v1_catalog, 2);

/**
 * @generated from message rat.catalog.v1.CreateBranchResponse
 */
export type CreateBranchResponse = Message<"rat.catalog.v1.CreateBranchResponse"> & {
  /**
   * @generated from field: string branch = 1;
   */
  branch: string;
};

/**
 * Describes the message rat.catalog.v1.CreateBranchResponse.
 * Use `create(CreateBranchResponseSchema)` to create a new message.
 */
export const CreateBranchResponseSchema: GenMessage<CreateBranchResponse> = /*@__PURE__*/
  messageDesc(file_rat_catalog_v1_catalog, 3);

/**
 * @generated from message rat.catalog.v1.MergeBranchRequest
 */
export type MergeBranchRequest = Message<"rat.catalog.v1.MergeBranchRequest"> & {
  /**
   * @generated from field: string branch = 2;
   */
  branch: string;

  /**
   * @generated from field: string into_branch = 3;
   */
  intoBranch: string;

  /**
   * Optimistic-concurrency guard: the snapshot `into_branch` is expected to be at
   * for this merge to apply. Empty == unconditional (no concurrency guard — only
   * safe when the caller knows it's the sole writer). See MERGE SAFETY above.
   *
   * @generated from field: string expected_into_snapshot = 4;
   */
  expectedIntoSnapshot: string;

  /**
   * Stable id for this logical merge (e.g. the pipeline run id). Makes MergeBranch
   * idempotent under reconciler retry: re-submitting a key that already committed
   * is a no-op returning the original result. Empty == not idempotent (each call
   * is a fresh merge attempt).
   *
   * @generated from field: string idempotency_key = 5;
   */
  idempotencyKey: string;
};

/**
 * Describes the message rat.catalog.v1.MergeBranchRequest.
 * Use `create(MergeBranchRequestSchema)` to create a new message.
 */
export const MergeBranchRequestSchema: GenMessage<MergeBranchRequest> = /*@__PURE__*/
  messageDesc(file_rat_catalog_v1_catalog, 4);

/**
 * @generated from message rat.catalog.v1.MergeBranchResponse
 */
export type MergeBranchResponse = Message<"rat.catalog.v1.MergeBranchResponse"> & {
  /**
   * Resulting snapshot id on the target branch.
   *
   * @generated from field: string snapshot_id = 1;
   */
  snapshotId: string;

  /**
   * True if this response reflects a previously-committed merge with the same
   * idempotency_key (the retry was a no-op), rather than a merge applied now.
   *
   * @generated from field: bool already_applied = 2;
   */
  alreadyApplied: boolean;
};

/**
 * Describes the message rat.catalog.v1.MergeBranchResponse.
 * Use `create(MergeBranchResponseSchema)` to create a new message.
 */
export const MergeBranchResponseSchema: GenMessage<MergeBranchResponse> = /*@__PURE__*/
  messageDesc(file_rat_catalog_v1_catalog, 5);

/**
 * @generated from service rat.catalog.v1.CatalogService
 */
export const CatalogService: GenService<{
  /**
   * rat://catalog/v1/get-table — resolve a table identifier to a TableRef
   * (physical location + current snapshot/branch).
   *
   * @generated from rpc rat.catalog.v1.CatalogService.GetTable
   */
  getTable: {
    methodKind: "unary";
    input: typeof GetTableRequestSchema;
    output: typeof GetTableResponseSchema;
  },
  /**
   * rat://catalog/v1/create-branch — open an isolated branch for a pipeline run.
   *
   * @generated from rpc rat.catalog.v1.CatalogService.CreateBranch
   */
  createBranch: {
    methodKind: "unary";
    input: typeof CreateBranchRequestSchema;
    output: typeof CreateBranchResponseSchema;
  },
  /**
   * rat://catalog/v1/merge-branch — merge a completed run's branch back to main,
   * after quality tests pass (the pre-merge gate of the v2 pipeline model).
   *
   * @generated from rpc rat.catalog.v1.CatalogService.MergeBranch
   */
  mergeBranch: {
    methodKind: "unary";
    input: typeof MergeBranchRequestSchema;
    output: typeof MergeBranchResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_rat_catalog_v1_catalog, 0);

