// Catalog axis service contract. DRAFT — sub-phase 0b.
//
// A `kind: catalog` plugin (Nessie, Unity, Lakekeeper, Glue, Polaris) owns
// table metadata + branch/version semantics. It is what makes "branch-isolated
// pipeline runs" (the v2 pipeline model we keep — overview.md) possible.
//
// Capability mapping:
//   rat://catalog/v1/get-table    -> GetTable
//   rat://catalog/v1/create-branch-> CreateBranch
//   rat://catalog/v1/merge-branch -> MergeBranch
//
// Not every catalog supports branching (Glue doesn't); those plugins simply do
// not `provide` the branch capabilities, and the registry won't wire a
// branch-requiring strategy to them. Capability negotiation, not feature flags.
//
// MERGE SAFETY (reviews/06 #8 = ARCH-4 / I-18): MergeBranch is the publish gate
// of the pipeline model and the reconciler RETRIES it, so it must be safe under
// retry AND concurrency. Two fields make it so:
//   - `expected_into_snapshot` — optimistic concurrency on the target. The merge
//     applies only if `into_branch` is still at this snapshot; otherwise it fails
//     (the caller re-reads + re-tests). Without it, two concurrent merges into
//     main silently lose one side's updates (lost-update).
//   - `idempotency_key` — a stable id for THIS logical merge (e.g. the run id).
//     A retry with the same key that already committed is a no-op that returns
//     the original result (MergeBranchResponse.already_applied = true), so a
//     reconciler retry can't double-apply.
// NOTE: this is the branch-MERGE linkage. The separate gap — how the catalog
// learns what format.Write put on a branch — is the additive commit-linkage RPC
// (reviews/06 I-18), GA-deferred; only the request-shape change here is
// freeze-gated.

// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file rat/catalog/v1/catalog.proto (package rat.catalog.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateBranchRequest, CreateBranchResponse, GetTableRequest, GetTableResponse, MergeBranchRequest, MergeBranchResponse } from "./catalog_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service rat.catalog.v1.CatalogService
 */
export const CatalogService = {
  typeName: "rat.catalog.v1.CatalogService",
  methods: {
    /**
     * rat://catalog/v1/get-table — resolve a table identifier to a TableRef
     * (physical location + current snapshot/branch).
     *
     * @generated from rpc rat.catalog.v1.CatalogService.GetTable
     */
    getTable: {
      name: "GetTable",
      I: GetTableRequest,
      O: GetTableResponse,
      kind: MethodKind.Unary,
    },
    /**
     * rat://catalog/v1/create-branch — open an isolated branch for a pipeline run.
     *
     * @generated from rpc rat.catalog.v1.CatalogService.CreateBranch
     */
    createBranch: {
      name: "CreateBranch",
      I: CreateBranchRequest,
      O: CreateBranchResponse,
      kind: MethodKind.Unary,
    },
    /**
     * rat://catalog/v1/merge-branch — merge a completed run's branch back to main,
     * after quality tests pass (the pre-merge gate of the v2 pipeline model).
     *
     * @generated from rpc rat.catalog.v1.CatalogService.MergeBranch
     */
    mergeBranch: {
      name: "MergeBranch",
      I: MergeBranchRequest,
      O: MergeBranchResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

