// Catalog axis service contract. Status: v1 (frozen — rat/1, ADR-009;
// RegisterTable + CommitTable added additively at rat/1.5, ADR-010).
//
// A `kind: catalog` plugin (Nessie, Unity, Lakekeeper, Glue, Polaris) owns
// table metadata + branch/version semantics. It is what makes "branch-isolated
// pipeline runs" (the v2 pipeline model we keep — overview.md) possible.
//
// Capability mapping:
//   rat://catalog/v1/get-table     -> GetTable
//   rat://catalog/v1/create-branch -> CreateBranch
//   rat://catalog/v1/merge-branch  -> MergeBranch
//   rat://catalog/v1/register-table-> RegisterTable  (ADR-010, additive)
//   rat://catalog/v1/commit-table  -> CommitTable    (ADR-010, additive)
//
// Not every catalog supports branching (Glue doesn't); those plugins simply do
// not `provide` the branch capabilities, and the registry won't wire a
// branch-requiring strategy to them. Capability negotiation, not feature flags.
//
// MERGE SAFETY (reviews/06 #8 = ARCH-4 / I-18): MergeBranch is the publish gate
// of the pipeline model and the reconciler RETRIES it, so it must be safe under
// retry AND concurrency. Two fields make it so:
//   - `expected_into_snapshot` — optimistic concurrency on the target. The merge
//     applies only if `into_branch` is still at this snapshot; otherwise it fails
//     (the caller re-reads + re-tests). Without it, two concurrent merges into
//     main silently lose one side's updates (lost-update).
//   - `idempotency_key` — a stable id for THIS logical merge (e.g. the run id).
//     A retry with the same key that already committed is a no-op that returns
//     the original result (MergeBranchResponse.already_applied = true), so a
//     reconciler retry can't double-apply.
// NOTE: this is the branch-MERGE linkage. The separate gap — how the catalog
// learns what format.Write put on a branch — is closed by the additive
// commit-linkage RPCs below (RegisterTable + CommitTable), added at rat/1.5 per
// ADR-010 (resolving ADR-009 residual R3 / reviews/08 B1). They are additive: the
// frozen GetTable/CreateBranch/MergeBranch shapes are unchanged.

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file rat/catalog/v1/catalog.proto (package rat.catalog.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_rat_common_v1_annotations } from "../../common/v1/annotations_pb";
import type { TableRef } from "../../common/v1/data_pb";
import { file_rat_common_v1_data } from "../../common/v1/data_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file rat/catalog/v1/catalog.proto.
 */
export const file_rat_catalog_v1_catalog: GenFile = /*@__PURE__*/
  fileDesc("ChxyYXQvY2F0YWxvZy92MS9jYXRhbG9nLnByb3RvEg5yYXQuY2F0YWxvZy52MSI7Cg9HZXRUYWJsZVJlcXVlc3QSEgoKaWRlbnRpZmllchgCIAEoCRIOCgZicmFuY2gYAyABKAlKBAgBEAIiOgoQR2V0VGFibGVSZXNwb25zZRImCgV0YWJsZRgBIAEoCzIXLnJhdC5jb21tb24udjEuVGFibGVSZWYiQAoTQ3JlYXRlQnJhbmNoUmVxdWVzdBIOCgZicmFuY2gYAiABKAkSEwoLZnJvbV9icmFuY2gYAyABKAlKBAgBEAIiJgoUQ3JlYXRlQnJhbmNoUmVzcG9uc2USDgoGYnJhbmNoGAEgASgJIngKEk1lcmdlQnJhbmNoUmVxdWVzdBIOCgZicmFuY2gYAiABKAkSEwoLaW50b19icmFuY2gYAyABKAkSHgoWZXhwZWN0ZWRfaW50b19zbmFwc2hvdBgEIAEoCRIXCg9pZGVtcG90ZW5jeV9rZXkYBSABKAlKBAgBEAIiQwoTTWVyZ2VCcmFuY2hSZXNwb25zZRITCgtzbmFwc2hvdF9pZBgBIAEoCRIXCg9hbHJlYWR5X2FwcGxpZWQYAiABKAgiTQoUUmVnaXN0ZXJUYWJsZVJlcXVlc3QSEgoKaWRlbnRpZmllchgCIAEoCRILCgN1cmkYAyABKAkSDgoGYnJhbmNoGAQgASgJSgQIARACIj8KFVJlZ2lzdGVyVGFibGVSZXNwb25zZRImCgV0YWJsZRgBIAEoCzIXLnJhdC5jb21tb24udjEuVGFibGVSZWYihwEKEkNvbW1pdFRhYmxlUmVxdWVzdBISCgppZGVudGlmaWVyGAIgASgJEg4KBmJyYW5jaBgDIAEoCRITCgtzbmFwc2hvdF9pZBgEIAEoCRIZChFleHBlY3RlZF9zbmFwc2hvdBgFIAEoCRIXCg9pZGVtcG90ZW5jeV9rZXkYBiABKAlKBAgBEAIiQwoTQ29tbWl0VGFibGVSZXNwb25zZRITCgtzbmFwc2hvdF9pZBgBIAEoCRIXCg9hbHJlYWR5X2FwcGxpZWQYAiABKAgy+AQKDkNhdGFsb2dTZXJ2aWNlEm0KCEdldFRhYmxlEh8ucmF0LmNhdGFsb2cudjEuR2V0VGFibGVSZXF1ZXN0GiAucmF0LmNhdGFsb2cudjEuR2V0VGFibGVSZXNwb25zZSIeipciGnJhdDovL2NhdGFsb2cvdjEvZ2V0LXRhYmxlEn0KDENyZWF0ZUJyYW5jaBIjLnJhdC5jYXRhbG9nLnYxLkNyZWF0ZUJyYW5jaFJlcXVlc3QaJC5yYXQuY2F0YWxvZy52MS5DcmVhdGVCcmFuY2hSZXNwb25zZSIiipciHnJhdDovL2NhdGFsb2cvdjEvY3JlYXRlLWJyYW5jaBJ5CgtNZXJnZUJyYW5jaBIiLnJhdC5jYXRhbG9nLnYxLk1lcmdlQnJhbmNoUmVxdWVzdBojLnJhdC5jYXRhbG9nLnYxLk1lcmdlQnJhbmNoUmVzcG9uc2UiIYqXIh1yYXQ6Ly9jYXRhbG9nL3YxL21lcmdlLWJyYW5jaBKBAQoNUmVnaXN0ZXJUYWJsZRIkLnJhdC5jYXRhbG9nLnYxLlJlZ2lzdGVyVGFibGVSZXF1ZXN0GiUucmF0LmNhdGFsb2cudjEuUmVnaXN0ZXJUYWJsZVJlc3BvbnNlIiOKlyIfcmF0Oi8vY2F0YWxvZy92MS9yZWdpc3Rlci10YWJsZRJ5CgtDb21taXRUYWJsZRIiLnJhdC5jYXRhbG9nLnYxLkNvbW1pdFRhYmxlUmVxdWVzdBojLnJhdC5jYXRhbG9nLnYxLkNvbW1pdFRhYmxlUmVzcG9uc2UiIYqXIh1yYXQ6Ly9jYXRhbG9nL3YxL2NvbW1pdC10YWJsZUI1WjNnaXRodWIuY29tL3JhdC1kZXYvcmF0L2dlbi9yYXQvY2F0YWxvZy92MTtjYXRhbG9ndjFiBnByb3RvMw", [file_rat_common_v1_annotations, file_rat_common_v1_data]);

/**
 * @generated from message rat.catalog.v1.GetTableRequest
 */
export type GetTableRequest = Message<"rat.catalog.v1.GetTableRequest"> & {
  /**
   * @generated from field: string identifier = 2;
   */
  identifier: string;

  /**
   * Optional branch to read from (empty == main).
   *
   * @generated from field: string branch = 3;
   */
  branch: string;
};

/**
 * Describes the message rat.catalog.v1.GetTableRequest.
 * Use `create(GetTableRequestSchema)` to create a new message.
 */
export const GetTableRequestSchema: GenMessage<GetTableRequest> = /*@__PURE__*/
  messageDesc(file_rat_catalog_v1_catalog, 0);

/**
 * @generated from message rat.catalog.v1.GetTableResponse
 */
export type GetTableResponse = Message<"rat.catalog.v1.GetTableResponse"> & {
  /**
   * NO `found` field BY DESIGN (error-model M2, common/v1/ERROR_MODEL.md): a
   * GetTable on a named table the caller asserts exists is not normal control flow
   * and is not enumeration-sensitive, so an unknown identifier is an ERROR —
   * `NOT_FOUND` status, not a `found=false` outcome. (Contrast state.Get /
   * secret.Resolve, which DO use a `found` bool — read-miss is normal there, and
   * secret additionally collapses forbidden into absent for anti-enumeration.)
   *
   * @generated from field: rat.common.v1.TableRef table = 1;
   */
  table?: TableRef | undefined;
};

/**
 * Describes the message rat.catalog.v1.GetTableResponse.
 * Use `create(GetTableResponseSchema)` to create a new message.
 */
export const GetTableResponseSchema: GenMessage<GetTableResponse> = /*@__PURE__*/
  messageDesc(file_rat_catalog_v1_catalog, 1);

/**
 * @generated from message rat.catalog.v1.CreateBranchRequest
 */
export type CreateBranchRequest = Message<"rat.catalog.v1.CreateBranchRequest"> & {
  /**
   * Branch name to create (e.g. a run id).
   *
   * @generated from field: string branch = 2;
   */
  branch: string;

  /**
   * Branch point (empty == tip of main).
   *
   * @generated from field: string from_branch = 3;
   */
  fromBranch: string;
};

/**
 * Describes the message rat.catalog.v1.CreateBranchRequest.
 * Use `create(CreateBranchRequestSchema)` to create a new message.
 */
export const CreateBranchRequestSchema: GenMessage<CreateBranchRequest> = /*@__PURE__*/
  messageDesc(file_rat_catalog_v1_catalog, 2);

/**
 * @generated from message rat.catalog.v1.CreateBranchResponse
 */
export type CreateBranchResponse = Message<"rat.catalog.v1.CreateBranchResponse"> & {
  /**
   * @generated from field: string branch = 1;
   */
  branch: string;
};

/**
 * Describes the message rat.catalog.v1.CreateBranchResponse.
 * Use `create(CreateBranchResponseSchema)` to create a new message.
 */
export const CreateBranchResponseSchema: GenMessage<CreateBranchResponse> = /*@__PURE__*/
  messageDesc(file_rat_catalog_v1_catalog, 3);

/**
 * @generated from message rat.catalog.v1.MergeBranchRequest
 */
export type MergeBranchRequest = Message<"rat.catalog.v1.MergeBranchRequest"> & {
  /**
   * @generated from field: string branch = 2;
   */
  branch: string;

  /**
   * @generated from field: string into_branch = 3;
   */
  intoBranch: string;

  /**
   * Optimistic-concurrency guard: the snapshot `into_branch` is expected to be at
   * for this merge to apply. Empty == unconditional (no concurrency guard — only
   * safe when the caller knows it's the sole writer). See MERGE SAFETY above.
   *
   * @generated from field: string expected_into_snapshot = 4;
   */
  expectedIntoSnapshot: string;

  /**
   * Stable id for this logical merge (e.g. the pipeline run id). Makes MergeBranch
   * idempotent under reconciler retry: re-submitting a key that already committed
   * is a no-op returning the original result. Empty == not idempotent (each call
   * is a fresh merge attempt).
   *
   * @generated from field: string idempotency_key = 5;
   */
  idempotencyKey: string;
};

/**
 * Describes the message rat.catalog.v1.MergeBranchRequest.
 * Use `create(MergeBranchRequestSchema)` to create a new message.
 */
export const MergeBranchRequestSchema: GenMessage<MergeBranchRequest> = /*@__PURE__*/
  messageDesc(file_rat_catalog_v1_catalog, 4);

/**
 * @generated from message rat.catalog.v1.MergeBranchResponse
 */
export type MergeBranchResponse = Message<"rat.catalog.v1.MergeBranchResponse"> & {
  /**
   * Resulting snapshot id on the target branch.
   *
   * @generated from field: string snapshot_id = 1;
   */
  snapshotId: string;

  /**
   * True if this response reflects a previously-committed merge with the same
   * idempotency_key (the retry was a no-op), rather than a merge applied now.
   *
   * @generated from field: bool already_applied = 2;
   */
  alreadyApplied: boolean;
};

/**
 * Describes the message rat.catalog.v1.MergeBranchResponse.
 * Use `create(MergeBranchResponseSchema)` to create a new message.
 */
export const MergeBranchResponseSchema: GenMessage<MergeBranchResponse> = /*@__PURE__*/
  messageDesc(file_rat_catalog_v1_catalog, 5);

/**
 * @generated from message rat.catalog.v1.RegisterTableRequest
 */
export type RegisterTableRequest = Message<"rat.catalog.v1.RegisterTableRequest"> & {
  /**
   * Identifier of the table to register, e.g. "warehouse.sales.summary".
   *
   * @generated from field: string identifier = 2;
   */
  identifier: string;

  /**
   * Optional storage/format URI hint for the new table (empty == the catalog
   * synthesizes one). Mirrors TableRef.uri.
   *
   * @generated from field: string uri = 3;
   */
  uri: string;

  /**
   * Optional branch the table is registered on (empty == main).
   *
   * @generated from field: string branch = 4;
   */
  branch: string;
};

/**
 * Describes the message rat.catalog.v1.RegisterTableRequest.
 * Use `create(RegisterTableRequestSchema)` to create a new message.
 */
export const RegisterTableRequestSchema: GenMessage<RegisterTableRequest> = /*@__PURE__*/
  messageDesc(file_rat_catalog_v1_catalog, 6);

/**
 * @generated from message rat.catalog.v1.RegisterTableResponse
 */
export type RegisterTableResponse = Message<"rat.catalog.v1.RegisterTableResponse"> & {
  /**
   * The registered table. Re-registering an existing identifier is idempotent and
   * returns the existing ref (no ALREADY_EXISTS — registration is reconcile-safe).
   *
   * @generated from field: rat.common.v1.TableRef table = 1;
   */
  table?: TableRef | undefined;
};

/**
 * Describes the message rat.catalog.v1.RegisterTableResponse.
 * Use `create(RegisterTableResponseSchema)` to create a new message.
 */
export const RegisterTableResponseSchema: GenMessage<RegisterTableResponse> = /*@__PURE__*/
  messageDesc(file_rat_catalog_v1_catalog, 7);

/**
 * @generated from message rat.catalog.v1.CommitTableRequest
 */
export type CommitTableRequest = Message<"rat.catalog.v1.CommitTableRequest"> & {
  /**
   * Table whose written snapshot is being recorded. MUST already be registered
   * (unknown table → NOT_FOUND).
   *
   * @generated from field: string identifier = 2;
   */
  identifier: string;

  /**
   * Branch the commit lands on (empty == main).
   *
   * @generated from field: string branch = 3;
   */
  branch: string;

  /**
   * The snapshot id the write produced — the value the format returned in
   * WriteResult.snapshot_id. This is the commit-LINKAGE: the catalog records
   * exactly what format.Write landed. REQUIRED (empty == INVALID_ARGUMENT); an
   * unversioned format that cannot report a snapshot simply does not commit-link.
   *
   * @generated from field: string snapshot_id = 4;
   */
  snapshotId: string;

  /**
   * Optimistic-concurrency guard: the snapshot the table is expected to be at on
   * `branch` for this commit to apply. Empty == unconditional (only safe when the
   * caller knows it's the sole writer). Mismatch → FAILED_PRECONDITION. The twin of
   * MergeBranch.expected_into_snapshot.
   *
   * @generated from field: string expected_snapshot = 5;
   */
  expectedSnapshot: string;

  /**
   * Stable id for THIS logical commit (e.g. the pipeline run id). Makes CommitTable
   * idempotent under at-least-once/reconciler retry: re-submitting a key that
   * already committed is a no-op returning the original result. Empty == not
   * idempotent. The twin of MergeBranch.idempotency_key — the write-leg idempotency
   * the reviews/08 B1 architect→sre cross-consult flagged as missing.
   *
   * @generated from field: string idempotency_key = 6;
   */
  idempotencyKey: string;
};

/**
 * Describes the message rat.catalog.v1.CommitTableRequest.
 * Use `create(CommitTableRequestSchema)` to create a new message.
 */
export const CommitTableRequestSchema: GenMessage<CommitTableRequest> = /*@__PURE__*/
  messageDesc(file_rat_catalog_v1_catalog, 8);

/**
 * @generated from message rat.catalog.v1.CommitTableResponse
 */
export type CommitTableResponse = Message<"rat.catalog.v1.CommitTableResponse"> & {
  /**
   * The snapshot now recorded for the table on the branch (the committed value).
   *
   * @generated from field: string snapshot_id = 1;
   */
  snapshotId: string;

  /**
   * True if this response reflects a previously-committed CommitTable with the same
   * idempotency_key (the retry was a no-op), rather than a commit applied now.
   *
   * @generated from field: bool already_applied = 2;
   */
  alreadyApplied: boolean;
};

/**
 * Describes the message rat.catalog.v1.CommitTableResponse.
 * Use `create(CommitTableResponseSchema)` to create a new message.
 */
export const CommitTableResponseSchema: GenMessage<CommitTableResponse> = /*@__PURE__*/
  messageDesc(file_rat_catalog_v1_catalog, 9);

/**
 * @generated from service rat.catalog.v1.CatalogService
 */
export const CatalogService: GenService<{
  /**
   * rat://catalog/v1/get-table — resolve a table identifier to a TableRef
   * (physical location + current snapshot/branch).
   *
   * @generated from rpc rat.catalog.v1.CatalogService.GetTable
   */
  getTable: {
    methodKind: "unary";
    input: typeof GetTableRequestSchema;
    output: typeof GetTableResponseSchema;
  },
  /**
   * rat://catalog/v1/create-branch — open an isolated branch for a pipeline run.
   *
   * @generated from rpc rat.catalog.v1.CatalogService.CreateBranch
   */
  createBranch: {
    methodKind: "unary";
    input: typeof CreateBranchRequestSchema;
    output: typeof CreateBranchResponseSchema;
  },
  /**
   * rat://catalog/v1/merge-branch — merge a completed run's branch back to main,
   * after quality tests pass (the pre-merge gate of the v2 pipeline model).
   *
   * @generated from rpc rat.catalog.v1.CatalogService.MergeBranch
   */
  mergeBranch: {
    methodKind: "unary";
    input: typeof MergeBranchRequestSchema;
    output: typeof MergeBranchResponseSchema;
  },
  /**
   * rat://catalog/v1/register-table — register a NEW table so a pipeline can
   * create its own output (not only read pre-existing tables). Idempotent:
   * re-registering an existing identifier returns the existing ref (reconcile-safe,
   * no ALREADY_EXISTS). The "register" half of the create→write→register→merge loop
   * (ADR-010 / reviews/08 B1). Distinct capability from commit-table so creating a
   * new catalog entry is a separately-grantable privilege (C5 method-level authz).
   *
   * @generated from rpc rat.catalog.v1.CatalogService.RegisterTable
   */
  registerTable: {
    methodKind: "unary";
    input: typeof RegisterTableRequestSchema;
    output: typeof RegisterTableResponseSchema;
  },
  /**
   * rat://catalog/v1/commit-table — record the snapshot a format.Write produced
   * for a table on a branch (the value returned in WriteResult.snapshot_id). This
   * is the commit-LINKAGE: the catalog learns exactly what landed. Safe under
   * retry + concurrency via the SAME model as MergeBranch — `expected_snapshot`
   * optimistic-concurrency guard + `idempotency_key` (the write-leg idempotency the
   * reviews/08 B1 architect→sre cross-consult flagged). ADR-010.
   *
   * @generated from rpc rat.catalog.v1.CatalogService.CommitTable
   */
  commitTable: {
    methodKind: "unary";
    input: typeof CommitTableRequestSchema;
    output: typeof CommitTableResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_rat_catalog_v1_catalog, 0);

