// Strategy axis service contract. Status: v1 (frozen — rat/1.1, ADR-009 trigger:
// two strategy references — fullrefresh-py + scd2-py — validate the contract).
//
// A `kind: strategy` plugin (scd2, soft-delete, full-refresh, …) encodes HOW
// data is transformed/loaded. It is the cleanest expression of the capability
// model: a strategy `requires` format-capabilities (scan/merge/append) +
// a runtime, and works across EVERY format that provides them without naming any
// (reviews/02: "the cleanest idea in the whole design").
//
// Capability mapping:
//   rat://strategy/v1/apply -> Apply

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rat/strategy/v1/strategy.proto

package strategyv1

import (
	v1 "github.com/rat-dev/rat/gen/rat/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source dataset to read from.
	Source *v1.TableRef `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// Target dataset to write into.
	Target *v1.TableRef `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	// Strategy-specific options. ENCODING PINNED (reviews/06 API-12): these bytes
	// are UTF-8 JSON, validated against the plugin's own metadata_schema (manifest).
	// Opaque to the core (it does not parse them); the strategy decodes per its
	// declared schema. Pinned at freeze so the bytes field's meaning can't shift.
	Options       []byte `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_rat_strategy_v1_strategy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rat_strategy_v1_strategy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_rat_strategy_v1_strategy_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyRequest) GetSource() *v1.TableRef {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ApplyRequest) GetTarget() *v1.TableRef {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ApplyRequest) GetOptions() []byte {
	if x != nil {
		return x.Options
	}
	return nil
}

type ApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *v1.WriteResult        `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_rat_strategy_v1_strategy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rat_strategy_v1_strategy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_rat_strategy_v1_strategy_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyResponse) GetResult() *v1.WriteResult {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_rat_strategy_v1_strategy_proto protoreflect.FileDescriptor

const file_rat_strategy_v1_strategy_proto_rawDesc = "" +
	"\n" +
	"\x1erat/strategy/v1/strategy.proto\x12\x0frat.strategy.v1\x1a\x1frat/common/v1/annotations.proto\x1a\x18rat/common/v1/data.proto\"\x90\x01\n" +
	"\fApplyRequest\x12/\n" +
	"\x06source\x18\x02 \x01(\v2\x17.rat.common.v1.TableRefR\x06source\x12/\n" +
	"\x06target\x18\x03 \x01(\v2\x17.rat.common.v1.TableRefR\x06target\x12\x18\n" +
	"\aoptions\x18\x04 \x01(\fR\aoptionsJ\x04\b\x01\x10\x02\"C\n" +
	"\rApplyResponse\x122\n" +
	"\x06result\x18\x01 \x01(\v2\x1a.rat.common.v1.WriteResultR\x06result2v\n" +
	"\x0fStrategyService\x12c\n" +
	"\x05Apply\x12\x1d.rat.strategy.v1.ApplyRequest\x1a\x1e.rat.strategy.v1.ApplyResponse\"\x1b\x8a\x97\"\x17rat://strategy/v1/applyB7Z5github.com/rat-dev/rat/gen/rat/strategy/v1;strategyv1b\x06proto3"

var (
	file_rat_strategy_v1_strategy_proto_rawDescOnce sync.Once
	file_rat_strategy_v1_strategy_proto_rawDescData []byte
)

func file_rat_strategy_v1_strategy_proto_rawDescGZIP() []byte {
	file_rat_strategy_v1_strategy_proto_rawDescOnce.Do(func() {
		file_rat_strategy_v1_strategy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rat_strategy_v1_strategy_proto_rawDesc), len(file_rat_strategy_v1_strategy_proto_rawDesc)))
	})
	return file_rat_strategy_v1_strategy_proto_rawDescData
}

var file_rat_strategy_v1_strategy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rat_strategy_v1_strategy_proto_goTypes = []any{
	(*ApplyRequest)(nil),   // 0: rat.strategy.v1.ApplyRequest
	(*ApplyResponse)(nil),  // 1: rat.strategy.v1.ApplyResponse
	(*v1.TableRef)(nil),    // 2: rat.common.v1.TableRef
	(*v1.WriteResult)(nil), // 3: rat.common.v1.WriteResult
}
var file_rat_strategy_v1_strategy_proto_depIdxs = []int32{
	2, // 0: rat.strategy.v1.ApplyRequest.source:type_name -> rat.common.v1.TableRef
	2, // 1: rat.strategy.v1.ApplyRequest.target:type_name -> rat.common.v1.TableRef
	3, // 2: rat.strategy.v1.ApplyResponse.result:type_name -> rat.common.v1.WriteResult
	0, // 3: rat.strategy.v1.StrategyService.Apply:input_type -> rat.strategy.v1.ApplyRequest
	1, // 4: rat.strategy.v1.StrategyService.Apply:output_type -> rat.strategy.v1.ApplyResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rat_strategy_v1_strategy_proto_init() }
func file_rat_strategy_v1_strategy_proto_init() {
	if File_rat_strategy_v1_strategy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rat_strategy_v1_strategy_proto_rawDesc), len(file_rat_strategy_v1_strategy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rat_strategy_v1_strategy_proto_goTypes,
		DependencyIndexes: file_rat_strategy_v1_strategy_proto_depIdxs,
		MessageInfos:      file_rat_strategy_v1_strategy_proto_msgTypes,
	}.Build()
	File_rat_strategy_v1_strategy_proto = out.File
	file_rat_strategy_v1_strategy_proto_goTypes = nil
	file_rat_strategy_v1_strategy_proto_depIdxs = nil
}
