// Observability axis service contract. Status: v1 (frozen — rat/1.2; ADR-003: control-plane = one ref + conformance).
//
// A `kind: observability` plugin (Prometheus, OTel collector, Datadog) RECEIVES
// telemetry the core + plugins emit and ships it onward.
//
// IMPORTANT (reviews/00 Theme 1 + reviews/03 I1): the core's OWN observability
// (its `/metrics`, its OTel spans, its reconcile-loop SLIs) is NATIVE — it does
// NOT depend on any observability plugin being installed. This axis is for
// EXPORT/fan-out + enriching with plugin-supplied telemetry, not for making the
// platform's own health opt-in. "observability: none" must still leave the core
// self-observable. This proto is therefore an export sink, not the source of
// truth for core health.
//
// Capability mapping:
//   rat://observability/v1/ingest -> Ingest (stream of telemetry points)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rat/observability/v1/observability.proto

package observabilityv1

import (
	_ "github.com/squat-collective/rat-v3/contracts/sdks/go/rat/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignalType int32

const (
	SignalType_SIGNAL_TYPE_UNSPECIFIED SignalType = 0
	SignalType_SIGNAL_TYPE_METRIC      SignalType = 1
	SignalType_SIGNAL_TYPE_SPAN        SignalType = 2
	SignalType_SIGNAL_TYPE_LOG         SignalType = 3
)

// Enum value maps for SignalType.
var (
	SignalType_name = map[int32]string{
		0: "SIGNAL_TYPE_UNSPECIFIED",
		1: "SIGNAL_TYPE_METRIC",
		2: "SIGNAL_TYPE_SPAN",
		3: "SIGNAL_TYPE_LOG",
	}
	SignalType_value = map[string]int32{
		"SIGNAL_TYPE_UNSPECIFIED": 0,
		"SIGNAL_TYPE_METRIC":      1,
		"SIGNAL_TYPE_SPAN":        2,
		"SIGNAL_TYPE_LOG":         3,
	}
)

func (x SignalType) Enum() *SignalType {
	p := new(SignalType)
	*p = x
	return p
}

func (x SignalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalType) Descriptor() protoreflect.EnumDescriptor {
	return file_rat_observability_v1_observability_proto_enumTypes[0].Descriptor()
}

func (SignalType) Type() protoreflect.EnumType {
	return &file_rat_observability_v1_observability_proto_enumTypes[0]
}

func (x SignalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalType.Descriptor instead.
func (SignalType) EnumDescriptor() ([]byte, []int) {
	return file_rat_observability_v1_observability_proto_rawDescGZIP(), []int{0}
}

type TelemetryPoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  SignalType             `protobuf:"varint,1,opt,name=type,proto3,enum=rat.observability.v1.SignalType" json:"type,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Numeric value for metrics; ignored for spans/logs.
	Value float64 `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	// Structured attributes (incl. trace_id/run_id for correlation — C1).
	Attributes      map[string]string `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimestampUnixMs int64             `protobuf:"varint,5,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TelemetryPoint) Reset() {
	*x = TelemetryPoint{}
	mi := &file_rat_observability_v1_observability_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryPoint) ProtoMessage() {}

func (x *TelemetryPoint) ProtoReflect() protoreflect.Message {
	mi := &file_rat_observability_v1_observability_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryPoint.ProtoReflect.Descriptor instead.
func (*TelemetryPoint) Descriptor() ([]byte, []int) {
	return file_rat_observability_v1_observability_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryPoint) GetType() SignalType {
	if x != nil {
		return x.Type
	}
	return SignalType_SIGNAL_TYPE_UNSPECIFIED
}

func (x *TelemetryPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TelemetryPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TelemetryPoint) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *TelemetryPoint) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

type IngestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*TelemetryPoint      `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_rat_observability_v1_observability_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rat_observability_v1_observability_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_rat_observability_v1_observability_proto_rawDescGZIP(), []int{1}
}

func (x *IngestRequest) GetPoints() []*TelemetryPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

// Acknowledgement for the batches received so far on this bidi stream. The sink
// emits one per inbound batch (or periodically); counts are cumulative for the
// stream so the emitter can track progress and apply backpressure.
type IngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      int64                  `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Rejected      int64                  `protobuf:"varint,2,opt,name=rejected,proto3" json:"rejected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_rat_observability_v1_observability_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rat_observability_v1_observability_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_rat_observability_v1_observability_proto_rawDescGZIP(), []int{2}
}

func (x *IngestResponse) GetAccepted() int64 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *IngestResponse) GetRejected() int64 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

var File_rat_observability_v1_observability_proto protoreflect.FileDescriptor

const file_rat_observability_v1_observability_proto_rawDesc = "" +
	"\n" +
	"(rat/observability/v1/observability.proto\x12\x14rat.observability.v1\x1a\x1frat/common/v1/annotations.proto\"\xb1\x02\n" +
	"\x0eTelemetryPoint\x124\n" +
	"\x04type\x18\x01 \x01(\x0e2 .rat.observability.v1.SignalTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12T\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v24.rat.observability.v1.TelemetryPoint.AttributesEntryR\n" +
	"attributes\x12*\n" +
	"\x11timestamp_unix_ms\x18\x05 \x01(\x03R\x0ftimestampUnixMs\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"S\n" +
	"\rIngestRequest\x12<\n" +
	"\x06points\x18\x02 \x03(\v2$.rat.observability.v1.TelemetryPointR\x06pointsJ\x04\b\x01\x10\x02\"H\n" +
	"\x0eIngestResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x03R\baccepted\x12\x1a\n" +
	"\brejected\x18\x02 \x01(\x03R\brejected*l\n" +
	"\n" +
	"SignalType\x12\x1b\n" +
	"\x17SIGNAL_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SIGNAL_TYPE_METRIC\x10\x01\x12\x14\n" +
	"\x10SIGNAL_TYPE_SPAN\x10\x02\x12\x13\n" +
	"\x0fSIGNAL_TYPE_LOG\x10\x032\x92\x01\n" +
	"\x14ObservabilityService\x12z\n" +
	"\x06Ingest\x12#.rat.observability.v1.IngestRequest\x1a$.rat.observability.v1.IngestResponse\"!\x8a\x97\"\x1drat://observability/v1/ingest(\x010\x01B[ZYgithub.com/squat-collective/rat-v3/contracts/sdks/go/rat/observability/v1;observabilityv1b\x06proto3"

var (
	file_rat_observability_v1_observability_proto_rawDescOnce sync.Once
	file_rat_observability_v1_observability_proto_rawDescData []byte
)

func file_rat_observability_v1_observability_proto_rawDescGZIP() []byte {
	file_rat_observability_v1_observability_proto_rawDescOnce.Do(func() {
		file_rat_observability_v1_observability_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rat_observability_v1_observability_proto_rawDesc), len(file_rat_observability_v1_observability_proto_rawDesc)))
	})
	return file_rat_observability_v1_observability_proto_rawDescData
}

var file_rat_observability_v1_observability_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rat_observability_v1_observability_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rat_observability_v1_observability_proto_goTypes = []any{
	(SignalType)(0),        // 0: rat.observability.v1.SignalType
	(*TelemetryPoint)(nil), // 1: rat.observability.v1.TelemetryPoint
	(*IngestRequest)(nil),  // 2: rat.observability.v1.IngestRequest
	(*IngestResponse)(nil), // 3: rat.observability.v1.IngestResponse
	nil,                    // 4: rat.observability.v1.TelemetryPoint.AttributesEntry
}
var file_rat_observability_v1_observability_proto_depIdxs = []int32{
	0, // 0: rat.observability.v1.TelemetryPoint.type:type_name -> rat.observability.v1.SignalType
	4, // 1: rat.observability.v1.TelemetryPoint.attributes:type_name -> rat.observability.v1.TelemetryPoint.AttributesEntry
	1, // 2: rat.observability.v1.IngestRequest.points:type_name -> rat.observability.v1.TelemetryPoint
	2, // 3: rat.observability.v1.ObservabilityService.Ingest:input_type -> rat.observability.v1.IngestRequest
	3, // 4: rat.observability.v1.ObservabilityService.Ingest:output_type -> rat.observability.v1.IngestResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rat_observability_v1_observability_proto_init() }
func file_rat_observability_v1_observability_proto_init() {
	if File_rat_observability_v1_observability_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rat_observability_v1_observability_proto_rawDesc), len(file_rat_observability_v1_observability_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rat_observability_v1_observability_proto_goTypes,
		DependencyIndexes: file_rat_observability_v1_observability_proto_depIdxs,
		EnumInfos:         file_rat_observability_v1_observability_proto_enumTypes,
		MessageInfos:      file_rat_observability_v1_observability_proto_msgTypes,
	}.Build()
	File_rat_observability_v1_observability_proto = out.File
	file_rat_observability_v1_observability_proto_goTypes = nil
	file_rat_observability_v1_observability_proto_depIdxs = nil
}
