// Observability axis service contract. DRAFT — sub-phase 0b.
//
// A `kind: observability` plugin (Prometheus, OTel collector, Datadog) RECEIVES
// telemetry the core + plugins emit and ships it onward.
//
// IMPORTANT (reviews/00 Theme 1 + reviews/03 I1): the core's OWN observability
// (its `/metrics`, its OTel spans, its reconcile-loop SLIs) is NATIVE — it does
// NOT depend on any observability plugin being installed. This axis is for
// EXPORT/fan-out + enriching with plugin-supplied telemetry, not for making the
// platform's own health opt-in. "observability: none" must still leave the core
// self-observable. This proto is therefore an export sink, not the source of
// truth for core health.
//
// Capability mapping:
//   rat://observability/v1/ingest -> Ingest (stream of telemetry points)

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: rat/observability/v1/observability.proto

package observabilityv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ObservabilityService_Ingest_FullMethodName = "/rat.observability.v1.ObservabilityService/Ingest"
)

// ObservabilityServiceClient is the client API for ObservabilityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ObservabilityServiceClient interface {
	// rat://observability/v1/ingest — stream telemetry into the sink.
	//
	// BIDI-STREAMING (reviews/06 API-4 / freeze-blocker #9): the old shape was
	// client-streaming with a SINGLE terminal ack — for a process-lifetime
	// telemetry stream the sink would ack only at stream close (≈never), giving no
	// backpressure and no partial-failure feedback. Bidi lets the sink return an
	// IngestResponse per batch (or periodically), so the emitter sees accepted /
	// rejected counts incrementally and can flow-control. Streaming-shape changes
	// are wire-breaking, hence pre-freeze.
	Ingest(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[IngestRequest, IngestResponse], error)
}

type observabilityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewObservabilityServiceClient(cc grpc.ClientConnInterface) ObservabilityServiceClient {
	return &observabilityServiceClient{cc}
}

func (c *observabilityServiceClient) Ingest(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[IngestRequest, IngestResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ObservabilityService_ServiceDesc.Streams[0], ObservabilityService_Ingest_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IngestRequest, IngestResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ObservabilityService_IngestClient = grpc.BidiStreamingClient[IngestRequest, IngestResponse]

// ObservabilityServiceServer is the server API for ObservabilityService service.
// All implementations must embed UnimplementedObservabilityServiceServer
// for forward compatibility.
type ObservabilityServiceServer interface {
	// rat://observability/v1/ingest — stream telemetry into the sink.
	//
	// BIDI-STREAMING (reviews/06 API-4 / freeze-blocker #9): the old shape was
	// client-streaming with a SINGLE terminal ack — for a process-lifetime
	// telemetry stream the sink would ack only at stream close (≈never), giving no
	// backpressure and no partial-failure feedback. Bidi lets the sink return an
	// IngestResponse per batch (or periodically), so the emitter sees accepted /
	// rejected counts incrementally and can flow-control. Streaming-shape changes
	// are wire-breaking, hence pre-freeze.
	Ingest(grpc.BidiStreamingServer[IngestRequest, IngestResponse]) error
	mustEmbedUnimplementedObservabilityServiceServer()
}

// UnimplementedObservabilityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedObservabilityServiceServer struct{}

func (UnimplementedObservabilityServiceServer) Ingest(grpc.BidiStreamingServer[IngestRequest, IngestResponse]) error {
	return status.Error(codes.Unimplemented, "method Ingest not implemented")
}
func (UnimplementedObservabilityServiceServer) mustEmbedUnimplementedObservabilityServiceServer() {}
func (UnimplementedObservabilityServiceServer) testEmbeddedByValue()                              {}

// UnsafeObservabilityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ObservabilityServiceServer will
// result in compilation errors.
type UnsafeObservabilityServiceServer interface {
	mustEmbedUnimplementedObservabilityServiceServer()
}

func RegisterObservabilityServiceServer(s grpc.ServiceRegistrar, srv ObservabilityServiceServer) {
	// If the following call panics, it indicates UnimplementedObservabilityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ObservabilityService_ServiceDesc, srv)
}

func _ObservabilityService_Ingest_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ObservabilityServiceServer).Ingest(&grpc.GenericServerStream[IngestRequest, IngestResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ObservabilityService_IngestServer = grpc.BidiStreamingServer[IngestRequest, IngestResponse]

// ObservabilityService_ServiceDesc is the grpc.ServiceDesc for ObservabilityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ObservabilityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rat.observability.v1.ObservabilityService",
	HandlerType: (*ObservabilityServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Ingest",
			Handler:       _ObservabilityService_Ingest_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "rat/observability/v1/observability.proto",
}
