// State-backend axis service contract. Status: v1 (frozen — rat/1, ADR-009).
//
// A `kind: state-backend` plugin (sqlite, postgres, etcd, …) backs the core's
// State Gateway (one of the six core things). This is a TIER-0 plugin
// (bootstrap-critical, selected at boot — plugin-architecture.md): the core
// cannot start without it.
//
// Capability mapping:
//   rat://state/v1/get   -> Get
//   rat://state/v1/put   -> Put
//   rat://state/v1/list   -> List
//   rat://state/v1/delete -> Delete   (ADR-035; additive, optional per backend)
//   rat://state/v1/watch  -> Watch
//
// C3 — STATE-GATEWAY ISOLATION: every key is namespaced per-plugin and
// per-tenant. The gateway derives the effective namespace from
// RequestContext.identity.caller_plugin (the immediate calling plugin,
// server-derived per hop — keystone, context.proto) + RequestContext.identity.tenant
// and PREFIXES it onto `key` server-side; a plugin physically cannot address
// another plugin's or another tenant's keys. Cross-plugin access is
// deny-by-default. The `key`/`prefix` fields below are plugin-relative, NOT global.
//
// KEY GRAMMAR (reviews/06 SEC-2, freeze-blocker #3): `key`/`prefix` are
// constrained so namespace prefixing is a real boundary, not naive string concat
// a crafted value can escape. A conformant gateway MUST reject any key/prefix
// that:
//   - is empty (key; prefix MAY be empty == "all of my namespace"),
//   - exceeds 512 bytes,
//   - is not valid UTF-8,
//   - contains a NUL byte (\x00) or any ASCII control char (< 0x20),
//   - contains a path-traversal segment: a "." or ".." path component, or the
//     sequence "../" / "..\\" anywhere.
// Allowed: printable UTF-8 with `/` as a logical separator (the gateway's own
// namespace prefix is applied server-side and is NOT part of this grammar — the
// plugin never writes the namespace). Rejection surfaces as INVALID_ARGUMENT.
// This grammar is a CONFORMANCE obligation (see below), not just prose.
//
// C5 / CAS — the Put compare-and-set primitive is what the reconciler's
// leader-election lease (ADR-002 D5) is built on. CONFORMANCE OBLIGATION
// (reviews/06 C-4 / ARCH-3): a state-backend MUST provide single-key
// LINEARIZABLE compare-and-set and ORDERED Watch to be eligible as the lease
// backend of a multi-replica deployment, and the axis conformance suite
// (sub-phase 0f) gates on it with golden vectors — it is NOT an honor-system
// comment. A backend that can only offer eventually-consistent reads (e.g.
// DynamoDB in its default read mode) MUST either run in a strongly-consistent
// mode or declare itself solo-only; it MUST NOT silently back a multi-replica
// lease, because two stale CAS reads → two leaders → split-brain reconcile.
// DynamoDB is therefore NOT in the advertised multi-replica state-backend set
// unless configured for strongly-consistent reads (overview.md topology note).

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file rat/state/v1/state.proto (package rat.state.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_rat_common_v1_annotations } from "../../common/v1/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file rat/state/v1/state.proto.
 */
export const file_rat_state_v1_state: GenFile = /*@__PURE__*/
  fileDesc("ChhyYXQvc3RhdGUvdjEvc3RhdGUucHJvdG8SDHJhdC5zdGF0ZS52MSIfCgpHZXRSZXF1ZXN0EgsKA2tleRgCIAEoCUoECAEQAiI9CgtHZXRSZXNwb25zZRINCgVmb3VuZBgBIAEoCBINCgV2YWx1ZRgCIAEoDBIQCghyZXZpc2lvbhgDIAEoAyJDCgpQdXRSZXF1ZXN0EgsKA2tleRgCIAEoCRINCgV2YWx1ZRgDIAEoDBITCgtpZl9yZXZpc2lvbhgEIAEoA0oECAEQAiJKCgtQdXRSZXNwb25zZRIpCgdvdXRjb21lGAEgASgOMhgucmF0LnN0YXRlLnYxLlB1dE91dGNvbWUSEAoIcmV2aXNpb24YAiABKAMiIwoLTGlzdFJlcXVlc3QSDgoGcHJlZml4GAIgASgJSgQIARACIhwKDExpc3RSZXNwb25zZRIMCgRrZXlzGAEgAygJIjcKDURlbGV0ZVJlcXVlc3QSCwoDa2V5GAIgASgJEhMKC2lmX3JldmlzaW9uGAMgASgDSgQIARACIh8KDkRlbGV0ZVJlc3BvbnNlEg0KBWZvdW5kGAEgASgIIjsKDFdhdGNoUmVxdWVzdBIOCgZwcmVmaXgYAiABKAkSFQoNZnJvbV9yZXZpc2lvbhgDIAEoA0oECAEQAiKqAQoNV2F0Y2hSZXNwb25zZRIuCgR0eXBlGAEgASgOMiAucmF0LnN0YXRlLnYxLldhdGNoUmVzcG9uc2UuVHlwZRILCgNrZXkYAiABKAkSDQoFdmFsdWUYAyABKAwSEAoIcmV2aXNpb24YBCABKAMiOwoEVHlwZRIUChBUWVBFX1VOU1BFQ0lGSUVEEAASDAoIVFlQRV9QVVQQARIPCgtUWVBFX0RFTEVURRACKncKClB1dE91dGNvbWUSGwoXUFVUX09VVENPTUVfVU5TUEVDSUZJRUQQABIZChVQVVRfT1VUQ09NRV9DT01NSVRURUQQARIYChRQVVRfT1VUQ09NRV9DT05GTElDVBACEhcKE1BVVF9PVVRDT01FX1VOS05PV04QAzLMAwoMU3RhdGVTZXJ2aWNlElIKA0dldBIYLnJhdC5zdGF0ZS52MS5HZXRSZXF1ZXN0GhkucmF0LnN0YXRlLnYxLkdldFJlc3BvbnNlIhaKlyIScmF0Oi8vc3RhdGUvdjEvZ2V0ElIKA1B1dBIYLnJhdC5zdGF0ZS52MS5QdXRSZXF1ZXN0GhkucmF0LnN0YXRlLnYxLlB1dFJlc3BvbnNlIhaKlyIScmF0Oi8vc3RhdGUvdjEvcHV0ElYKBExpc3QSGS5yYXQuc3RhdGUudjEuTGlzdFJlcXVlc3QaGi5yYXQuc3RhdGUudjEuTGlzdFJlc3BvbnNlIheKlyITcmF0Oi8vc3RhdGUvdjEvbGlzdBJeCgZEZWxldGUSGy5yYXQuc3RhdGUudjEuRGVsZXRlUmVxdWVzdBocLnJhdC5zdGF0ZS52MS5EZWxldGVSZXNwb25zZSIZipciFXJhdDovL3N0YXRlL3YxL2RlbGV0ZRJcCgVXYXRjaBIaLnJhdC5zdGF0ZS52MS5XYXRjaFJlcXVlc3QaGy5yYXQuc3RhdGUudjEuV2F0Y2hSZXNwb25zZSIYipciFHJhdDovL3N0YXRlL3YxL3dhdGNoMAFCMVovZ2l0aHViLmNvbS9yYXQtZGV2L3JhdC9nZW4vcmF0L3N0YXRlL3YxO3N0YXRldjFiBnByb3RvMw", [file_rat_common_v1_annotations]);

/**
 * @generated from message rat.state.v1.GetRequest
 */
export type GetRequest = Message<"rat.state.v1.GetRequest"> & {
  /**
   * Plugin-relative key; subject to KEY GRAMMAR (file header). Non-empty.
   *
   * @generated from field: string key = 2;
   */
  key: string;
};

/**
 * Describes the message rat.state.v1.GetRequest.
 * Use `create(GetRequestSchema)` to create a new message.
 */
export const GetRequestSchema: GenMessage<GetRequest> = /*@__PURE__*/
  messageDesc(file_rat_state_v1_state, 0);

/**
 * @generated from message rat.state.v1.GetResponse
 */
export type GetResponse = Message<"rat.state.v1.GetResponse"> & {
  /**
   * @generated from field: bool found = 1;
   */
  found: boolean;

  /**
   * @generated from field: bytes value = 2;
   */
  value: Uint8Array;

  /**
   * Monotonic revision for CAS / optimistic concurrency.
   *
   * @generated from field: int64 revision = 3;
   */
  revision: bigint;
};

/**
 * Describes the message rat.state.v1.GetResponse.
 * Use `create(GetResponseSchema)` to create a new message.
 */
export const GetResponseSchema: GenMessage<GetResponse> = /*@__PURE__*/
  messageDesc(file_rat_state_v1_state, 1);

/**
 * @generated from message rat.state.v1.PutRequest
 */
export type PutRequest = Message<"rat.state.v1.PutRequest"> & {
  /**
   * Plugin-relative key; subject to KEY GRAMMAR (file header). Non-empty.
   *
   * @generated from field: string key = 2;
   */
  key: string;

  /**
   * @generated from field: bytes value = 3;
   */
  value: Uint8Array;

  /**
   * CAS: if > 0, the put succeeds only if the current revision matches.
   * 0 == unconditional write. This backs leader-election leases (ADR-002 D5).
   *
   * @generated from field: int64 if_revision = 4;
   */
  ifRevision: bigint;
};

/**
 * Describes the message rat.state.v1.PutRequest.
 * Use `create(PutRequestSchema)` to create a new message.
 */
export const PutRequestSchema: GenMessage<PutRequest> = /*@__PURE__*/
  messageDesc(file_rat_state_v1_state, 2);

/**
 * @generated from message rat.state.v1.PutResponse
 */
export type PutResponse = Message<"rat.state.v1.PutResponse"> & {
  /**
   * @generated from field: rat.state.v1.PutOutcome outcome = 1;
   */
  outcome: PutOutcome;

  /**
   * New revision on COMMITTED; the current conflicting revision on CONFLICT;
   * unspecified (0) on UNKNOWN.
   *
   * @generated from field: int64 revision = 2;
   */
  revision: bigint;
};

/**
 * Describes the message rat.state.v1.PutResponse.
 * Use `create(PutResponseSchema)` to create a new message.
 */
export const PutResponseSchema: GenMessage<PutResponse> = /*@__PURE__*/
  messageDesc(file_rat_state_v1_state, 3);

/**
 * @generated from message rat.state.v1.ListRequest
 */
export type ListRequest = Message<"rat.state.v1.ListRequest"> & {
  /**
   * Plugin-relative prefix; subject to KEY GRAMMAR (file header). MAY be empty
   * (== list all of this plugin+tenant namespace).
   *
   * @generated from field: string prefix = 2;
   */
  prefix: string;
};

/**
 * Describes the message rat.state.v1.ListRequest.
 * Use `create(ListRequestSchema)` to create a new message.
 */
export const ListRequestSchema: GenMessage<ListRequest> = /*@__PURE__*/
  messageDesc(file_rat_state_v1_state, 4);

/**
 * @generated from message rat.state.v1.ListResponse
 */
export type ListResponse = Message<"rat.state.v1.ListResponse"> & {
  /**
   * @generated from field: repeated string keys = 1;
   */
  keys: string[];
};

/**
 * Describes the message rat.state.v1.ListResponse.
 * Use `create(ListResponseSchema)` to create a new message.
 */
export const ListResponseSchema: GenMessage<ListResponse> = /*@__PURE__*/
  messageDesc(file_rat_state_v1_state, 5);

/**
 * ADR-035 — additive Delete. Optional per backend (UNIMPLEMENTED allowed).
 *
 * @generated from message rat.state.v1.DeleteRequest
 */
export type DeleteRequest = Message<"rat.state.v1.DeleteRequest"> & {
  /**
   * Plugin-relative key; subject to KEY GRAMMAR (file header). Non-empty.
   *
   * @generated from field: string key = 2;
   */
  key: string;

  /**
   * CAS: if > 0, delete only if the current revision matches (FAILED_PRECONDITION on mismatch).
   * 0 == unconditional delete. Releasing a lease key is a Delete — same fencing rigor as Put-CAS.
   *
   * @generated from field: int64 if_revision = 3;
   */
  ifRevision: bigint;
};

/**
 * Describes the message rat.state.v1.DeleteRequest.
 * Use `create(DeleteRequestSchema)` to create a new message.
 */
export const DeleteRequestSchema: GenMessage<DeleteRequest> = /*@__PURE__*/
  messageDesc(file_rat_state_v1_state, 6);

/**
 * @generated from message rat.state.v1.DeleteResponse
 */
export type DeleteResponse = Message<"rat.state.v1.DeleteResponse"> & {
  /**
   * true if the key existed and was removed; false if it was already absent (delete is idempotent).
   *
   * @generated from field: bool found = 1;
   */
  found: boolean;
};

/**
 * Describes the message rat.state.v1.DeleteResponse.
 * Use `create(DeleteResponseSchema)` to create a new message.
 */
export const DeleteResponseSchema: GenMessage<DeleteResponse> = /*@__PURE__*/
  messageDesc(file_rat_state_v1_state, 7);

/**
 * @generated from message rat.state.v1.WatchRequest
 */
export type WatchRequest = Message<"rat.state.v1.WatchRequest"> & {
  /**
   * Plugin-relative prefix; subject to KEY GRAMMAR (file header). MAY be empty.
   *
   * @generated from field: string prefix = 2;
   */
  prefix: string;

  /**
   * Resume from this revision (0 == from now).
   *
   * @generated from field: int64 from_revision = 3;
   */
  fromRevision: bigint;
};

/**
 * Describes the message rat.state.v1.WatchRequest.
 * Use `create(WatchRequestSchema)` to create a new message.
 */
export const WatchRequestSchema: GenMessage<WatchRequest> = /*@__PURE__*/
  messageDesc(file_rat_state_v1_state, 8);

/**
 * @generated from message rat.state.v1.WatchResponse
 */
export type WatchResponse = Message<"rat.state.v1.WatchResponse"> & {
  /**
   * @generated from field: rat.state.v1.WatchResponse.Type type = 1;
   */
  type: WatchResponse_Type;

  /**
   * @generated from field: string key = 2;
   */
  key: string;

  /**
   * @generated from field: bytes value = 3;
   */
  value: Uint8Array;

  /**
   * @generated from field: int64 revision = 4;
   */
  revision: bigint;
};

/**
 * Describes the message rat.state.v1.WatchResponse.
 * Use `create(WatchResponseSchema)` to create a new message.
 */
export const WatchResponseSchema: GenMessage<WatchResponse> = /*@__PURE__*/
  messageDesc(file_rat_state_v1_state, 9);

/**
 * @generated from enum rat.state.v1.WatchResponse.Type
 */
export enum WatchResponse_Type {
  /**
   * @generated from enum value: TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: TYPE_PUT = 1;
   */
  PUT = 1,

  /**
   * @generated from enum value: TYPE_DELETE = 2;
   */
  DELETE = 2,
}

/**
 * Describes the enum rat.state.v1.WatchResponse.Type.
 */
export const WatchResponse_TypeSchema: GenEnum<WatchResponse_Type> = /*@__PURE__*/
  enumDesc(file_rat_state_v1_state, 9, 0);

/**
 * The outcome of a Put. The old `committed: bool` could not distinguish a lost
 * CAS race from an unavailable backend from a maybe-committed timeout — fatal for
 * lease fencing (reviews/06 C-4 / API-1 reconciler axis). PutOutcome makes the
 * three cases explicit on the wire.
 *
 * @generated from enum rat.state.v1.PutOutcome
 */
export enum PutOutcome {
  /**
   * @generated from enum value: PUT_OUTCOME_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The write was durably committed. `revision` is the new revision.
   *
   * @generated from enum value: PUT_OUTCOME_COMMITTED = 1;
   */
  COMMITTED = 1,

  /**
   * CAS precondition failed: current revision != if_revision. Deterministic —
   * the caller should re-read and decide (a leader that loses this steps down).
   * The write did NOT happen. `revision` carries the current (conflicting) rev.
   *
   * @generated from enum value: PUT_OUTCOME_CONFLICT = 2;
   */
  CONFLICT = 2,

  /**
   * The backend could not confirm the result (timeout, partition, dropped
   * response): the write may or may not have committed. The caller MUST treat
   * its state as unknown — a lease renewal that returns UNKNOWN cannot be relied
   * on for fencing and the holder must assume it may have lost the lease. NOT
   * safe to blindly retry a CAS on this without re-reading the revision first.
   *
   * @generated from enum value: PUT_OUTCOME_UNKNOWN = 3;
   */
  UNKNOWN = 3,
}

/**
 * Describes the enum rat.state.v1.PutOutcome.
 */
export const PutOutcomeSchema: GenEnum<PutOutcome> = /*@__PURE__*/
  enumDesc(file_rat_state_v1_state, 0);

/**
 * @generated from service rat.state.v1.StateService
 */
export const StateService: GenService<{
  /**
   * rat://state/v1/get — read one key (plugin+tenant relative).
   *
   * @generated from rpc rat.state.v1.StateService.Get
   */
  get: {
    methodKind: "unary";
    input: typeof GetRequestSchema;
    output: typeof GetResponseSchema;
  },
  /**
   * rat://state/v1/put — write one key, optionally compare-and-set on revision.
   *
   * @generated from rpc rat.state.v1.StateService.Put
   */
  put: {
    methodKind: "unary";
    input: typeof PutRequestSchema;
    output: typeof PutResponseSchema;
  },
  /**
   * rat://state/v1/list — list keys under a plugin+tenant-relative prefix.
   *
   * @generated from rpc rat.state.v1.StateService.List
   */
  list: {
    methodKind: "unary";
    input: typeof ListRequestSchema;
    output: typeof ListResponseSchema;
  },
  /**
   * rat://state/v1/delete — remove one key (plugin+tenant relative), optionally compare-and-set.
   * ADDITIVE amendment (ADR-035): a state-backend MAY return UNIMPLEMENTED — Delete is optional;
   * a backend declares this capability in `provides` only if it supports it, and consumers MUST
   * handle UNIMPLEMENTED. Idempotent (absent key -> found=false, not an error). CAS via if_revision
   * with the same fencing rigor as Put (deleting a lease key releases the lease).
   *
   * @generated from rpc rat.state.v1.StateService.Delete
   */
  delete: {
    methodKind: "unary";
    input: typeof DeleteRequestSchema;
    output: typeof DeleteResponseSchema;
  },
  /**
   * rat://state/v1/watch — stream changes under a prefix (reconciler/event use).
   * Each streamed message is a WatchResponse — named per the *Response convention
   * buf STANDARD requires, even for streaming RPCs. Mediated via core
   * InvokeServerStream (ADR-008).
   *
   * @generated from rpc rat.state.v1.StateService.Watch
   */
  watch: {
    methodKind: "server_streaming";
    input: typeof WatchRequestSchema;
    output: typeof WatchResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_rat_state_v1_state, 0);

