// State-backend axis service contract. DRAFT — sub-phase 0b.
//
// A `kind: state-backend` plugin (sqlite, postgres, etcd, …) backs the core's
// State Gateway (one of the six core things). This is a TIER-0 plugin
// (bootstrap-critical, selected at boot — plugin-architecture.md): the core
// cannot start without it.
//
// Capability mapping:
//   rat://state/v1/get   -> Get
//   rat://state/v1/put   -> Put
//   rat://state/v1/list  -> List
//   rat://state/v1/watch -> Watch
//
// C3 — STATE-GATEWAY ISOLATION: every key is namespaced per-plugin and
// per-tenant. The gateway derives the effective namespace from
// RequestContext.identity.caller_plugin (the immediate calling plugin,
// server-derived per hop — keystone, context.proto) + RequestContext.identity.tenant
// and PREFIXES it onto `key` server-side; a plugin physically cannot address
// another plugin's or another tenant's keys. Cross-plugin access is
// deny-by-default. The `key`/`prefix` fields below are plugin-relative, NOT global.
//
// KEY GRAMMAR (reviews/06 SEC-2, freeze-blocker #3): `key`/`prefix` are
// constrained so namespace prefixing is a real boundary, not naive string concat
// a crafted value can escape. A conformant gateway MUST reject any key/prefix
// that:
//   - is empty (key; prefix MAY be empty == "all of my namespace"),
//   - exceeds 512 bytes,
//   - is not valid UTF-8,
//   - contains a NUL byte (\x00) or any ASCII control char (< 0x20),
//   - contains a path-traversal segment: a "." or ".." path component, or the
//     sequence "../" / "..\\" anywhere.
// Allowed: printable UTF-8 with `/` as a logical separator (the gateway's own
// namespace prefix is applied server-side and is NOT part of this grammar — the
// plugin never writes the namespace). Rejection surfaces as INVALID_ARGUMENT.
// This grammar is a CONFORMANCE obligation (see below), not just prose.
//
// C5 / CAS — the Put compare-and-set primitive is what the reconciler's
// leader-election lease (ADR-002 D5) is built on. CONFORMANCE OBLIGATION
// (reviews/06 C-4 / ARCH-3): a state-backend MUST provide single-key
// LINEARIZABLE compare-and-set and ORDERED Watch to be eligible as the lease
// backend of a multi-replica deployment, and the axis conformance suite
// (sub-phase 0f) gates on it with golden vectors — it is NOT an honor-system
// comment. A backend that can only offer eventually-consistent reads (e.g.
// DynamoDB in its default read mode) MUST either run in a strongly-consistent
// mode or declare itself solo-only; it MUST NOT silently back a multi-replica
// lease, because two stale CAS reads → two leaders → split-brain reconcile.
// DynamoDB is therefore NOT in the advertised multi-replica state-backend set
// unless configured for strongly-consistent reads (overview.md topology note).

// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file rat/state/v1/state.proto (package rat.state.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetRequest, GetResponse, ListRequest, ListResponse, PutRequest, PutResponse, WatchRequest, WatchResponse } from "./state_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service rat.state.v1.StateService
 */
export const StateService = {
  typeName: "rat.state.v1.StateService",
  methods: {
    /**
     * rat://state/v1/get — read one key (plugin+tenant relative).
     *
     * @generated from rpc rat.state.v1.StateService.Get
     */
    get: {
      name: "Get",
      I: GetRequest,
      O: GetResponse,
      kind: MethodKind.Unary,
    },
    /**
     * rat://state/v1/put — write one key, optionally compare-and-set on revision.
     *
     * @generated from rpc rat.state.v1.StateService.Put
     */
    put: {
      name: "Put",
      I: PutRequest,
      O: PutResponse,
      kind: MethodKind.Unary,
    },
    /**
     * rat://state/v1/list — list keys under a plugin+tenant-relative prefix.
     *
     * @generated from rpc rat.state.v1.StateService.List
     */
    list: {
      name: "List",
      I: ListRequest,
      O: ListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * rat://state/v1/watch — stream changes under a prefix (reconciler/event use).
     * Each streamed message is a WatchResponse — named per the *Response convention
     * buf STANDARD requires, even for streaming RPCs. Mediated via core
     * InvokeServerStream (ADR-008).
     *
     * @generated from rpc rat.state.v1.StateService.Watch
     */
    watch: {
      name: "Watch",
      I: WatchRequest,
      O: WatchResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

