// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuthenticateRequest {
    /// Opaque credential (bearer token, client-cert chain, etc.). Never logged;
    /// `debug_redact` makes that structural (reviews/06 SEC-8).
    #[prost(bytes="vec", tag="2")]
    pub credential: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuthenticateResponse {
    #[prost(bool, tag="1")]
    pub authenticated: bool,
    /// The resolved subject to stamp onto downstream RequestContext.subject.
    #[prost(string, tag="2")]
    pub subject: ::prost::alloc::string::String,
    /// The tenant this subject belongs to (stamped onto RequestContext.tenant).
    #[prost(string, tag="3")]
    pub tenant: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuthorizeRequest {
    /// Action being attempted, e.g. "pipeline.run", "plane.create".
    #[prost(string, tag="2")]
    pub action: ::prost::alloc::string::String,
    /// Optional resource the action targets.
    #[prost(string, tag="3")]
    pub resource: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuthorizeResponse {
    #[prost(bool, tag="1")]
    pub allowed: bool,
    /// Machine-readable deny reason when allowed=false. UNSPECIFIED when allowed.
    #[prost(enumeration="DenyCode", tag="2")]
    pub deny_code: i32,
    /// Human-readable reason — LOG/AUDIT-ONLY, never returned to drive caller logic
    /// (enumeration-oracle risk). Callers branch on deny_code.
    #[prost(string, tag="3")]
    pub reason: ::prost::alloc::string::String,
}
/// Machine-readable deny reason for Authorize. Callers branch on this, never on
/// the free-text reason (anti-enumeration-oracle; see ERROR MODEL above).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DenyCode {
    /// not a deny (allowed=true) OR reason not supplied
    Unspecified = 0,
    /// no/invalid subject established
    NotAuthenticated = 1,
    /// authenticated but lacks the required role
    InsufficientRole = 2,
    /// the action is denied for this subject
    ActionForbidden = 3,
    /// the specific resource is denied
    ResourceForbidden = 4,
}
impl DenyCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DENY_CODE_UNSPECIFIED",
            Self::NotAuthenticated => "DENY_CODE_NOT_AUTHENTICATED",
            Self::InsufficientRole => "DENY_CODE_INSUFFICIENT_ROLE",
            Self::ActionForbidden => "DENY_CODE_ACTION_FORBIDDEN",
            Self::ResourceForbidden => "DENY_CODE_RESOURCE_FORBIDDEN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DENY_CODE_UNSPECIFIED" => Some(Self::Unspecified),
            "DENY_CODE_NOT_AUTHENTICATED" => Some(Self::NotAuthenticated),
            "DENY_CODE_INSUFFICIENT_ROLE" => Some(Self::InsufficientRole),
            "DENY_CODE_ACTION_FORBIDDEN" => Some(Self::ActionForbidden),
            "DENY_CODE_RESOURCE_FORBIDDEN" => Some(Self::ResourceForbidden),
            _ => None,
        }
    }
}
include!("rat.identity.v1.tonic.rs");
// @@protoc_insertion_point(module)