// Storage axis service contract. Status: v1 (frozen — rat/1, ADR-009).
//
// A `kind: storage` plugin (S3, GCS, Azure Blob, local-fs) owns byte storage +
// credential vending. The control plane NEVER sees bytes (overview.md "data
// plane bypasses core"); it only asks storage to vend short-TTL scoped creds, and
// the engine/format then talk to object storage directly.
//
// Capability mapping:
//   rat://storage/v1/vend-credentials -> VendCredentials
//   rat://storage/v1/read  -> (declared capability; satisfied by vended creds)
//   rat://storage/v1/write -> (declared capability; satisfied by vended creds)
//
// SECURITY (reviews/01 Finding 3 + reviews/04): credential vending is the one
// place a mis-scoped grant defeats an otherwise-correct tenancy boundary. Creds
// MUST be scoped to the RequestContext.identity.tenant + the requested prefix, and
// short-TTL. This is a C7 (tenancy-structural) enforcement point — the proto
// carries tenant via context so the storage plugin cannot vend cross-tenant.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: rat/storage/v1/storage.proto

package storagev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StorageService_VendCredentials_FullMethodName = "/rat.storage.v1.StorageService/VendCredentials"
)

// StorageServiceClient is the client API for StorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageServiceClient interface {
	// rat://storage/v1/vend-credentials — issue short-TTL, prefix-scoped,
	// tenant-scoped credentials the data plane uses to read/write bytes directly.
	VendCredentials(ctx context.Context, in *VendCredentialsRequest, opts ...grpc.CallOption) (*VendCredentialsResponse, error)
}

type storageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageServiceClient(cc grpc.ClientConnInterface) StorageServiceClient {
	return &storageServiceClient{cc}
}

func (c *storageServiceClient) VendCredentials(ctx context.Context, in *VendCredentialsRequest, opts ...grpc.CallOption) (*VendCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VendCredentialsResponse)
	err := c.cc.Invoke(ctx, StorageService_VendCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServiceServer is the server API for StorageService service.
// All implementations must embed UnimplementedStorageServiceServer
// for forward compatibility.
type StorageServiceServer interface {
	// rat://storage/v1/vend-credentials — issue short-TTL, prefix-scoped,
	// tenant-scoped credentials the data plane uses to read/write bytes directly.
	VendCredentials(context.Context, *VendCredentialsRequest) (*VendCredentialsResponse, error)
	mustEmbedUnimplementedStorageServiceServer()
}

// UnimplementedStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageServiceServer struct{}

func (UnimplementedStorageServiceServer) VendCredentials(context.Context, *VendCredentialsRequest) (*VendCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VendCredentials not implemented")
}
func (UnimplementedStorageServiceServer) mustEmbedUnimplementedStorageServiceServer() {}
func (UnimplementedStorageServiceServer) testEmbeddedByValue()                        {}

// UnsafeStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServiceServer will
// result in compilation errors.
type UnsafeStorageServiceServer interface {
	mustEmbedUnimplementedStorageServiceServer()
}

func RegisterStorageServiceServer(s grpc.ServiceRegistrar, srv StorageServiceServer) {
	// If the following call panics, it indicates UnimplementedStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageService_ServiceDesc, srv)
}

func _StorageService_VendCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VendCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).VendCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_VendCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).VendCredentials(ctx, req.(*VendCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageService_ServiceDesc is the grpc.ServiceDesc for StorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rat.storage.v1.StorageService",
	HandlerType: (*StorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VendCredentials",
			Handler:    _StorageService_VendCredentials_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rat/storage/v1/storage.proto",
}
