// Cross-cutting audit envelope — the C8 (mandatory audit) wire type.
//
// AuditRecord is CORE-AUTHORED, CORE-SIGNED, and emitted on every security-relevant
// event (plugin installs, binding changes, credential vends, auth decisions) EVEN
// WHEN NO audit-log plugin is installed — the core falls back to a core-local
// append-only store. "audit-log: none" must NOT mean "no audit". It is therefore a
// CROSS-CUTTING type, not an axis type: the core's enforcement layer constructs +
// signs it; the `kind: audit-log` axis (auditlog.proto) is only the export SINK and
// IMPORTS this record. Keeping it here (common/v1), not in the axis proto, stops the
// core's C8 emission from depending on an axis contract — the layering the synthesis
// cross-cutting rule requires (reviews/00 C1–C10; plugin-architecture.md).
//
// AUDIT-ON-DENY IS MANDATORY (S3, reviews/07 — a C8 conformance obligation, not a
// best-effort): the gateway emits EXACTLY ONE AuditRecord per enforcement decision,
// INCLUDING denials — a DENIED outcome (AUDIT_OUTCOME_DENIED) on a failed C2/C5/C7
// check MUST still produce a record, never a silent drop. (A gateway that audits
// only the allow-path lets denied access go unrecorded — the exact gap a freeze
// review flagged in the throwaway stub.) For streams: one record at open (ADR-008).
//
// Moved here from rat.auditlog.v1 in sub-phase 0c (finalize cross-cutting protos).
// WIRE-COMPATIBLE: field numbers are unchanged, so the canonical serialization +
// signatures + hash chain are byte-identical; only the proto package (and the
// generated type name) moves rat.auditlog.v1 → rat.common.v1.
//
// Status: v1 (frozen — rat/1, ADR-009).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rat/common/v1/audit.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditOutcome int32

const (
	AuditOutcome_AUDIT_OUTCOME_UNSPECIFIED AuditOutcome = 0
	AuditOutcome_AUDIT_OUTCOME_SUCCESS     AuditOutcome = 1
	AuditOutcome_AUDIT_OUTCOME_DENIED      AuditOutcome = 2
	AuditOutcome_AUDIT_OUTCOME_ERROR       AuditOutcome = 3
)

// Enum value maps for AuditOutcome.
var (
	AuditOutcome_name = map[int32]string{
		0: "AUDIT_OUTCOME_UNSPECIFIED",
		1: "AUDIT_OUTCOME_SUCCESS",
		2: "AUDIT_OUTCOME_DENIED",
		3: "AUDIT_OUTCOME_ERROR",
	}
	AuditOutcome_value = map[string]int32{
		"AUDIT_OUTCOME_UNSPECIFIED": 0,
		"AUDIT_OUTCOME_SUCCESS":     1,
		"AUDIT_OUTCOME_DENIED":      2,
		"AUDIT_OUTCOME_ERROR":       3,
	}
)

func (x AuditOutcome) Enum() *AuditOutcome {
	p := new(AuditOutcome)
	*p = x
	return p
}

func (x AuditOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuditOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_rat_common_v1_audit_proto_enumTypes[0].Descriptor()
}

func (AuditOutcome) Type() protoreflect.EnumType {
	return &file_rat_common_v1_audit_proto_enumTypes[0]
}

func (x AuditOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuditOutcome.Descriptor instead.
func (AuditOutcome) EnumDescriptor() ([]byte, []int) {
	return file_rat_common_v1_audit_proto_rawDescGZIP(), []int{0}
}

// One audit record. Append-only; tamper-evidence is enforced by the core signature +
// hash chain, not by trusting the sink. Authored by the CORE (the audit-log axis is
// only the export sink).
//
// CANONICAL SERIALIZATION (pinned — the bytes `signature` covers and `prev_hash` of
// the NEXT record chains over): the proto3 wire encoding of all fields EXCEPT
// `signature` (field 10), emitted in ascending field-number order, each field
// present exactly once, no unknown fields, varints in minimal form, default-valued
// fields omitted. This deterministic form is the canonical record bytes; the core
// hashes/signs exactly these bytes and verifiers recompute them identically.
// `key_id` (field 11) is INCLUDED in these signed bytes — the signature commits to
// which key it claims to be from, defeating key-substitution.
type AuditRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Core-assigned chain position id (monotonic). Set by the CORE, never the caller.
	// With prev_hash this forms the linear hash chain.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Core-computed hash of the previous record's canonical bytes (chain link). Empty
	// for the first record in the chain.
	PrevHash        string `protobuf:"bytes,2,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	TimestampUnixMs int64  `protobuf:"varint,3,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	// Who (subject) did what (action) to which (resource), and the result.
	Subject  string       `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Tenant   string       `protobuf:"bytes,5,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Action   string       `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"`
	Resource string       `protobuf:"bytes,7,opt,name=resource,proto3" json:"resource,omitempty"`
	Outcome  AuditOutcome `protobuf:"varint,8,opt,name=outcome,proto3,enum=rat.common.v1.AuditOutcome" json:"outcome,omitempty"`
	// Correlation back to the operation (C1).
	CorrelationId string `protobuf:"bytes,9,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// Core's signature over this record's canonical serialization (all fields above
	// PLUS key_id; this field itself is excluded from the signed bytes). The authority
	// of the record — a sink verifies against the core's published key and rejects any
	// record whose signature does not verify.
	Signature []byte `protobuf:"bytes,10,opt,name=signature,proto3" json:"signature,omitempty"`
	// Identifier of the core verification key that signed this record (M3,
	// reviews/07). Resolves, in the core's PUBLISHED keyring, to {public key,
	// signature algorithm} — so a verifier picks the right key without out-of-band
	// agreement, key ROTATION is a new key_id on new records (old records still verify
	// against the retired key, which the keyring retains), and algorithm AGILITY is a
	// new key_id bound to a new algorithm (no separate on-wire `alg` field needed).
	// Empty is permitted ONLY for a single-key deployment that never rotates.
	KeyId         string `protobuf:"bytes,11,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRecord) Reset() {
	*x = AuditRecord{}
	mi := &file_rat_common_v1_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRecord) ProtoMessage() {}

func (x *AuditRecord) ProtoReflect() protoreflect.Message {
	mi := &file_rat_common_v1_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRecord.ProtoReflect.Descriptor instead.
func (*AuditRecord) Descriptor() ([]byte, []int) {
	return file_rat_common_v1_audit_proto_rawDescGZIP(), []int{0}
}

func (x *AuditRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditRecord) GetPrevHash() string {
	if x != nil {
		return x.PrevHash
	}
	return ""
}

func (x *AuditRecord) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *AuditRecord) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *AuditRecord) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *AuditRecord) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditRecord) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AuditRecord) GetOutcome() AuditOutcome {
	if x != nil {
		return x.Outcome
	}
	return AuditOutcome_AUDIT_OUTCOME_UNSPECIFIED
}

func (x *AuditRecord) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AuditRecord) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AuditRecord) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

var File_rat_common_v1_audit_proto protoreflect.FileDescriptor

const file_rat_common_v1_audit_proto_rawDesc = "" +
	"\n" +
	"\x19rat/common/v1/audit.proto\x12\rrat.common.v1\"\xdf\x02\n" +
	"\vAuditRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tprev_hash\x18\x02 \x01(\tR\bprevHash\x12*\n" +
	"\x11timestamp_unix_ms\x18\x03 \x01(\x03R\x0ftimestampUnixMs\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x16\n" +
	"\x06tenant\x18\x05 \x01(\tR\x06tenant\x12\x16\n" +
	"\x06action\x18\x06 \x01(\tR\x06action\x12\x1a\n" +
	"\bresource\x18\a \x01(\tR\bresource\x125\n" +
	"\aoutcome\x18\b \x01(\x0e2\x1b.rat.common.v1.AuditOutcomeR\aoutcome\x12%\n" +
	"\x0ecorrelation_id\x18\t \x01(\tR\rcorrelationId\x12\x1c\n" +
	"\tsignature\x18\n" +
	" \x01(\fR\tsignature\x12\x15\n" +
	"\x06key_id\x18\v \x01(\tR\x05keyId*{\n" +
	"\fAuditOutcome\x12\x1d\n" +
	"\x19AUDIT_OUTCOME_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15AUDIT_OUTCOME_SUCCESS\x10\x01\x12\x18\n" +
	"\x14AUDIT_OUTCOME_DENIED\x10\x02\x12\x17\n" +
	"\x13AUDIT_OUTCOME_ERROR\x10\x03B3Z1github.com/rat-dev/rat/gen/rat/common/v1;commonv1b\x06proto3"

var (
	file_rat_common_v1_audit_proto_rawDescOnce sync.Once
	file_rat_common_v1_audit_proto_rawDescData []byte
)

func file_rat_common_v1_audit_proto_rawDescGZIP() []byte {
	file_rat_common_v1_audit_proto_rawDescOnce.Do(func() {
		file_rat_common_v1_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rat_common_v1_audit_proto_rawDesc), len(file_rat_common_v1_audit_proto_rawDesc)))
	})
	return file_rat_common_v1_audit_proto_rawDescData
}

var file_rat_common_v1_audit_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rat_common_v1_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rat_common_v1_audit_proto_goTypes = []any{
	(AuditOutcome)(0),   // 0: rat.common.v1.AuditOutcome
	(*AuditRecord)(nil), // 1: rat.common.v1.AuditRecord
}
var file_rat_common_v1_audit_proto_depIdxs = []int32{
	0, // 0: rat.common.v1.AuditRecord.outcome:type_name -> rat.common.v1.AuditOutcome
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rat_common_v1_audit_proto_init() }
func file_rat_common_v1_audit_proto_init() {
	if File_rat_common_v1_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rat_common_v1_audit_proto_rawDesc), len(file_rat_common_v1_audit_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rat_common_v1_audit_proto_goTypes,
		DependencyIndexes: file_rat_common_v1_audit_proto_depIdxs,
		EnumInfos:         file_rat_common_v1_audit_proto_enumTypes,
		MessageInfos:      file_rat_common_v1_audit_proto_msgTypes,
	}.Build()
	File_rat_common_v1_audit_proto = out.File
	file_rat_common_v1_audit_proto_goTypes = nil
	file_rat_common_v1_audit_proto_depIdxs = nil
}
