// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ApplyRequest {
    /// Source dataset to read from.
    #[prost(message, optional, tag="2")]
    pub source: ::core::option::Option<super::super::common::v1::TableRef>,
    /// Target dataset to write into.
    #[prost(message, optional, tag="3")]
    pub target: ::core::option::Option<super::super::common::v1::TableRef>,
    /// Strategy-specific options. ENCODING PINNED (reviews/06 API-12): these bytes
    /// are UTF-8 JSON, validated against the plugin's own metadata_schema (manifest).
    /// Opaque to the core (it does not parse them); the strategy decodes per its
    /// declared schema. Pinned at freeze so the bytes field's meaning can't shift.
    #[prost(bytes="vec", tag="4")]
    pub options: ::prost::alloc::vec::Vec<u8>,
    /// Stable id for THIS logical run (e.g. the run id). The strategy threads it down to
    /// its format writes (format.*Request.idempotency_key) so a re-applied run is
    /// idempotent END-TO-END under an at-least-once scheduler (C1, ADR-012). Empty == not
    /// idempotent.
    #[prost(string, tag="5")]
    pub idempotency_key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ApplyResponse {
    #[prost(message, optional, tag="1")]
    pub result: ::core::option::Option<super::super::common::v1::WriteResult>,
}
include!("rat.strategy.v1.tonic.rs");
// @@protoc_insertion_point(module)