// @generated
// This file is @generated by prost-build.
/// One audit record. Append-only; tamper-evidence is enforced by the core
/// signature + hash chain, not by trusting the sink.
///
/// CANONICAL SERIALIZATION (pinned — the bytes `signature` covers and `prev_hash`
/// of the NEXT record chains over): the proto3 wire encoding of all fields EXCEPT
/// `signature` (field 10), emitted in ascending field-number order, each field
/// present exactly once, no unknown fields, varints in minimal form, default-valued
/// fields omitted. This deterministic form is the canonical record bytes; the
/// core hashes/signs exactly these bytes and verifiers recompute them identically.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuditRecord {
    /// Core-assigned chain position id (monotonic). Set by the CORE, never the
    /// caller. With prev_hash this forms the linear hash chain.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// Core-computed hash of the previous record's canonical bytes (chain link).
    /// Empty for the first record in the chain.
    #[prost(string, tag="2")]
    pub prev_hash: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub timestamp_unix_ms: i64,
    /// Who (subject) did what (action) to which (resource), and the result.
    #[prost(string, tag="4")]
    pub subject: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub tenant: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub action: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub resource: ::prost::alloc::string::String,
    #[prost(enumeration="AuditOutcome", tag="8")]
    pub outcome: i32,
    /// Correlation back to the operation (C1).
    #[prost(string, tag="9")]
    pub correlation_id: ::prost::alloc::string::String,
    /// Core's Ed25519 signature over this record's canonical serialization (all
    /// fields above; this field itself is excluded from the signed bytes). The
    /// authority of the record — a sink verifies against the core's published key
    /// and rejects any record whose signature does not verify.
    #[prost(bytes="vec", tag="10")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AppendRequest {
    #[prost(message, optional, tag="1")]
    pub context: ::core::option::Option<super::super::common::v1::RequestContext>,
    /// Core-authored, core-signed records to append, in chain order.
    #[prost(message, repeated, tag="2")]
    pub records: ::prost::alloc::vec::Vec<AuditRecord>,
}
/// Ack for one record in the request; acks\[i\] corresponds to records\[i\].
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecordAck {
    /// The core-assigned id this ack refers to (mirrors records\[i\].id).
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(enumeration="AppendStatus", tag="2")]
    pub status: i32,
    /// Set only when status == APPEND_STATUS_REJECTED.
    #[prost(enumeration="RejectCode", tag="3")]
    pub reject_code: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AppendResponse {
    /// Per-record acks in request order. COMMIT IS PREFIX-ONLY: once a record is
    /// REJECTED, all later records in the request are uncommitted (never acked
    /// COMMITTED), so the committed set is always a contiguous prefix — the chain
    /// can't fork on partial failure.
    #[prost(message, repeated, tag="1")]
    pub acks: ::prost::alloc::vec::Vec<RecordAck>,
    /// Chain head after this append: the id + canonical-hash of the last durably
    /// committed record. A reconnecting emitter resumes deterministically from here
    /// with no gap/fork; also distinguishes "dropped" (absent from the chain) from
    /// "in-flight".
    #[prost(string, tag="2")]
    pub last_committed_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub last_committed_hash: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AuditOutcome {
    Unspecified = 0,
    Success = 1,
    Denied = 2,
    Error = 3,
}
impl AuditOutcome {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "AUDIT_OUTCOME_UNSPECIFIED",
            Self::Success => "AUDIT_OUTCOME_SUCCESS",
            Self::Denied => "AUDIT_OUTCOME_DENIED",
            Self::Error => "AUDIT_OUTCOME_ERROR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AUDIT_OUTCOME_UNSPECIFIED" => Some(Self::Unspecified),
            "AUDIT_OUTCOME_SUCCESS" => Some(Self::Success),
            "AUDIT_OUTCOME_DENIED" => Some(Self::Denied),
            "AUDIT_OUTCOME_ERROR" => Some(Self::Error),
            _ => None,
        }
    }
}
/// Per-record disposition of an Append.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AppendStatus {
    Unspecified = 0,
    /// Durably stored and chain-linked.
    Committed = 1,
    /// Already stored (idempotent retry) — NOT an error; the chain is intact.
    Duplicate = 2,
    /// Not stored. See reject_code. Implies prefix-only: every later record in the
    /// same request is also uncommitted.
    Rejected = 3,
}
impl AppendStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "APPEND_STATUS_UNSPECIFIED",
            Self::Committed => "APPEND_STATUS_COMMITTED",
            Self::Duplicate => "APPEND_STATUS_DUPLICATE",
            Self::Rejected => "APPEND_STATUS_REJECTED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "APPEND_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "APPEND_STATUS_COMMITTED" => Some(Self::Committed),
            "APPEND_STATUS_DUPLICATE" => Some(Self::Duplicate),
            "APPEND_STATUS_REJECTED" => Some(Self::Rejected),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RejectCode {
    Unspecified = 0,
    /// Signature did not verify against the core's key.
    BadSignature = 1,
    /// prev_hash does not match the sink's current chain head (gap/fork attempt).
    ChainBreak = 2,
    /// Sink-side durable-storage failure (retryable).
    StorageError = 3,
}
impl RejectCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "REJECT_CODE_UNSPECIFIED",
            Self::BadSignature => "REJECT_CODE_BAD_SIGNATURE",
            Self::ChainBreak => "REJECT_CODE_CHAIN_BREAK",
            Self::StorageError => "REJECT_CODE_STORAGE_ERROR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "REJECT_CODE_UNSPECIFIED" => Some(Self::Unspecified),
            "REJECT_CODE_BAD_SIGNATURE" => Some(Self::BadSignature),
            "REJECT_CODE_CHAIN_BREAK" => Some(Self::ChainBreak),
            "REJECT_CODE_STORAGE_ERROR" => Some(Self::StorageError),
            _ => None,
        }
    }
}
include!("rat.auditlog.v1.tonic.rs");
// @@protoc_insertion_point(module)