# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rat.runtime.v1 import runtime_pb2 as rat_dot_runtime_dot_v1_dot_runtime__pb2


class RuntimeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_stream(
                '/rat.runtime.v1.RuntimeService/Execute',
                request_serializer=rat_dot_runtime_dot_v1_dot_runtime__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=rat_dot_runtime_dot_v1_dot_runtime__pb2.ExecuteResponse.FromString,
                _registered_method=True)


class RuntimeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Execute(self, request, context):
        """rat://runtime/v1/execute — run a unit of work. Streams progress so the
        reconciler/UI can show liveness on long tasks; terminal message carries the
        outcome. Each streamed message is an ExecuteResponse (a progress-or-completed
        oneof) — named per the *Response convention buf STANDARD requires, even for
        streaming RPCs. Mediated via core InvokeServerStream (ADR-008).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_stream_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=rat_dot_runtime_dot_v1_dot_runtime__pb2.ExecuteRequest.FromString,
                    response_serializer=rat_dot_runtime_dot_v1_dot_runtime__pb2.ExecuteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rat.runtime.v1.RuntimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rat.runtime.v1.RuntimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RuntimeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rat.runtime.v1.RuntimeService/Execute',
            rat_dot_runtime_dot_v1_dot_runtime__pb2.ExecuteRequest.SerializeToString,
            rat_dot_runtime_dot_v1_dot_runtime__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
