// Runtime axis service contract. DRAFT — sub-phase 0b.
//
// A `kind: runtime` plugin (pyarrow, a container exec runtime, a WASM host, …)
// executes a unit of work on behalf of a strategy/engine. It is the "where does
// the code run" axis — distinct from `deployment-runtime` (where PLUGINS run).
//
// Capability mapping:
//   rat://runtime/v1/execute -> Execute

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file rat/runtime/v1/runtime.proto (package rat.runtime.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { RequestContext } from "../../common/v1/context_pb";
import { file_rat_common_v1_context } from "../../common/v1/context_pb";
import type { ArrowStream, WriteResult } from "../../common/v1/data_pb";
import { file_rat_common_v1_data } from "../../common/v1/data_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file rat/runtime/v1/runtime.proto.
 */
export const file_rat_runtime_v1_runtime: GenFile = /*@__PURE__*/
  fileDesc("ChxyYXQvcnVudGltZS92MS9ydW50aW1lLnByb3RvEg5yYXQucnVudGltZS52MSJ/Cg5FeGVjdXRlUmVxdWVzdBIuCgdjb250ZXh0GAEgASgLMh0ucmF0LmNvbW1vbi52MS5SZXF1ZXN0Q29udGV4dBIRCgl3b3JrX3NwZWMYAiABKAwSKgoGaW5wdXRzGAMgAygLMhoucmF0LmNvbW1vbi52MS5BcnJvd1N0cmVhbSJGCg9FeGVjdXRlUHJvZ3Jlc3MSFQoIZnJhY3Rpb24YASABKAFIAIgBARIPCgdtZXNzYWdlGAIgASgJQgsKCV9mcmFjdGlvbiJeChBFeGVjdXRlQ29tcGxldGVkEg8KB3N1Y2Nlc3MYASABKAgSDQoFZXJyb3IYAiABKAkSKgoGcmVzdWx0GAMgASgLMhoucmF0LmNvbW1vbi52MS5Xcml0ZVJlc3VsdCKGAQoPRXhlY3V0ZVJlc3BvbnNlEjMKCHByb2dyZXNzGAEgASgLMh8ucmF0LnJ1bnRpbWUudjEuRXhlY3V0ZVByb2dyZXNzSAASNQoJY29tcGxldGVkGAIgASgLMiAucmF0LnJ1bnRpbWUudjEuRXhlY3V0ZUNvbXBsZXRlZEgAQgcKBWV2ZW50Ml4KDlJ1bnRpbWVTZXJ2aWNlEkwKB0V4ZWN1dGUSHi5yYXQucnVudGltZS52MS5FeGVjdXRlUmVxdWVzdBofLnJhdC5ydW50aW1lLnYxLkV4ZWN1dGVSZXNwb25zZTABQjVaM2dpdGh1Yi5jb20vcmF0LWRldi9yYXQvZ2VuL3JhdC9ydW50aW1lL3YxO3J1bnRpbWV2MWIGcHJvdG8z", [file_rat_common_v1_context, file_rat_common_v1_data]);

/**
 * @generated from message rat.runtime.v1.ExecuteRequest
 */
export type ExecuteRequest = Message<"rat.runtime.v1.ExecuteRequest"> & {
  /**
   * @generated from field: rat.common.v1.RequestContext context = 1;
   */
  context?: RequestContext | undefined;

  /**
   * Opaque work spec the runtime knows how to run (e.g. a serialized plan, a
   * script ref, a container entrypoint). The control plane does not interpret.
   *
   * @generated from field: bytes work_spec = 2;
   */
  workSpec: Uint8Array;

  /**
   * Optional input data streams the work consumes.
   *
   * @generated from field: repeated rat.common.v1.ArrowStream inputs = 3;
   */
  inputs: ArrowStream[];
};

/**
 * Describes the message rat.runtime.v1.ExecuteRequest.
 * Use `create(ExecuteRequestSchema)` to create a new message.
 */
export const ExecuteRequestSchema: GenMessage<ExecuteRequest> = /*@__PURE__*/
  messageDesc(file_rat_runtime_v1_runtime, 0);

/**
 * Streamed liveness update during Execute.
 *
 * @generated from message rat.runtime.v1.ExecuteProgress
 */
export type ExecuteProgress = Message<"rat.runtime.v1.ExecuteProgress"> & {
  /**
   * Completion fraction 0.0–1.0. proto3 `optional` for explicit presence: ABSENT
   * == indeterminate progress (replaces the old negative sentinel — reviews/06
   * API-13).
   *
   * @generated from field: optional double fraction = 1;
   */
  fraction?: number | undefined;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message rat.runtime.v1.ExecuteProgress.
 * Use `create(ExecuteProgressSchema)` to create a new message.
 */
export const ExecuteProgressSchema: GenMessage<ExecuteProgress> = /*@__PURE__*/
  messageDesc(file_rat_runtime_v1_runtime, 1);

/**
 * Terminal event of an Execute stream.
 *
 * @generated from message rat.runtime.v1.ExecuteCompleted
 */
export type ExecuteCompleted = Message<"rat.runtime.v1.ExecuteCompleted"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * Populated on failure.
   *
   * @generated from field: string error = 2;
   */
  error: string;

  /**
   * @generated from field: rat.common.v1.WriteResult result = 3;
   */
  result?: WriteResult | undefined;
};

/**
 * Describes the message rat.runtime.v1.ExecuteCompleted.
 * Use `create(ExecuteCompletedSchema)` to create a new message.
 */
export const ExecuteCompletedSchema: GenMessage<ExecuteCompleted> = /*@__PURE__*/
  messageDesc(file_rat_runtime_v1_runtime, 2);

/**
 * One message in the Execute stream: either an interim progress update or the
 * terminal completion.
 *
 * @generated from message rat.runtime.v1.ExecuteResponse
 */
export type ExecuteResponse = Message<"rat.runtime.v1.ExecuteResponse"> & {
  /**
   * @generated from oneof rat.runtime.v1.ExecuteResponse.event
   */
  event: {
    /**
     * @generated from field: rat.runtime.v1.ExecuteProgress progress = 1;
     */
    value: ExecuteProgress;
    case: "progress";
  } | {
    /**
     * @generated from field: rat.runtime.v1.ExecuteCompleted completed = 2;
     */
    value: ExecuteCompleted;
    case: "completed";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message rat.runtime.v1.ExecuteResponse.
 * Use `create(ExecuteResponseSchema)` to create a new message.
 */
export const ExecuteResponseSchema: GenMessage<ExecuteResponse> = /*@__PURE__*/
  messageDesc(file_rat_runtime_v1_runtime, 3);

/**
 * @generated from service rat.runtime.v1.RuntimeService
 */
export const RuntimeService: GenService<{
  /**
   * rat://runtime/v1/execute — run a unit of work. Streams progress so the
   * reconciler/UI can show liveness on long tasks; terminal message carries the
   * outcome. Each streamed message is an ExecuteResponse (a progress-or-completed
   * oneof) — named per the *Response convention buf STANDARD requires, even for
   * streaming RPCs.
   *
   * @generated from rpc rat.runtime.v1.RuntimeService.Execute
   */
  execute: {
    methodKind: "server_streaming";
    input: typeof ExecuteRequestSchema;
    output: typeof ExecuteResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_rat_runtime_v1_runtime, 0);

