// Runtime axis service contract. DRAFT — sub-phase 0b.
//
// A `kind: runtime` plugin (pyarrow, a container exec runtime, a WASM host, …)
// executes a unit of work on behalf of a strategy/engine. It is the "where does
// the code run" axis — distinct from `deployment-runtime` (where PLUGINS run).
//
// Capability mapping:
//   rat://runtime/v1/execute -> Execute

// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file rat/runtime/v1/runtime.proto (package rat.runtime.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ExecuteRequest, ExecuteResponse } from "./runtime_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service rat.runtime.v1.RuntimeService
 */
export const RuntimeService = {
  typeName: "rat.runtime.v1.RuntimeService",
  methods: {
    /**
     * rat://runtime/v1/execute — run a unit of work. Streams progress so the
     * reconciler/UI can show liveness on long tasks; terminal message carries the
     * outcome. Each streamed message is an ExecuteResponse (a progress-or-completed
     * oneof) — named per the *Response convention buf STANDARD requires, even for
     * streaming RPCs. Mediated via core InvokeServerStream (ADR-008).
     *
     * @generated from rpc rat.runtime.v1.RuntimeService.Execute
     */
    execute: {
      name: "Execute",
      I: ExecuteRequest,
      O: ExecuteResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

