# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rat.tenancy.v1 import tenancy_pb2 as rat_dot_tenancy_dot_v1_dot_tenancy__pb2


class TenancyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Decide = channel.unary_unary(
                '/rat.tenancy.v1.TenancyService/Decide',
                request_serializer=rat_dot_tenancy_dot_v1_dot_tenancy__pb2.DecideRequest.SerializeToString,
                response_deserializer=rat_dot_tenancy_dot_v1_dot_tenancy__pb2.DecideResponse.FromString,
                _registered_method=True)


class TenancyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Decide(self, request, context):
        """rat://tenancy/v1/decide — answer a policy decision the core poses at a hook
        point. The core enforces the verdict; the plugin only computes it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TenancyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Decide': grpc.unary_unary_rpc_method_handler(
                    servicer.Decide,
                    request_deserializer=rat_dot_tenancy_dot_v1_dot_tenancy__pb2.DecideRequest.FromString,
                    response_serializer=rat_dot_tenancy_dot_v1_dot_tenancy__pb2.DecideResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rat.tenancy.v1.TenancyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rat.tenancy.v1.TenancyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TenancyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Decide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rat.tenancy.v1.TenancyService/Decide',
            rat_dot_tenancy_dot_v1_dot_tenancy__pb2.DecideRequest.SerializeToString,
            rat_dot_tenancy_dot_v1_dot_tenancy__pb2.DecideResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
