// Scheduler-backend axis service contract. DRAFT — sub-phase 0b.
//
// A `kind: scheduler-backend` plugin (in-process timer, cron, Temporal,
// cloud scheduler) owns "fire this at this time / on this interval". The
// reconciler asks it WHEN; the reconciler still decides WHAT (overview.md
// reconciliation model — the scheduler is a clock, not an orchestrator).
//
// Capability mapping:
//   rat://scheduler/v1/schedule   -> Schedule
//   rat://scheduler/v1/cancel     -> Cancel
//   rat://scheduler/v1/watch-due  -> WatchDue (stream of fired triggers)

// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file rat/scheduler/v1/scheduler.proto (package rat.scheduler.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CancelRequest, CancelResponse, ScheduleRequest, ScheduleResponse, WatchDueRequest, WatchDueResponse } from "./scheduler_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service rat.scheduler.v1.SchedulerService
 */
export const SchedulerService = {
  typeName: "rat.scheduler.v1.SchedulerService",
  methods: {
    /**
     * rat://scheduler/v1/schedule — register a trigger (cron expr or one-shot).
     *
     * @generated from rpc rat.scheduler.v1.SchedulerService.Schedule
     */
    schedule: {
      name: "Schedule",
      I: ScheduleRequest,
      O: ScheduleResponse,
      kind: MethodKind.Unary,
    },
    /**
     * rat://scheduler/v1/cancel — remove a previously-registered trigger.
     *
     * @generated from rpc rat.scheduler.v1.SchedulerService.Cancel
     */
    cancel: {
      name: "Cancel",
      I: CancelRequest,
      O: CancelResponse,
      kind: MethodKind.Unary,
    },
    /**
     * rat://scheduler/v1/watch-due — stream of triggers as they fire. The
     * reconciler consumes this to know a pipeline is due.
     *
     * DELIVERY SEMANTICS (reviews/06 API-11, pinned at freeze): AT-LEAST-ONCE. A
     * fired trigger MAY be redelivered (e.g. if the consumer reconnects), so the
     * reconciler MUST treat WatchDue delivery as idempotent — it keys actions by
     * (trigger_id, fired_at_unix_ms) and ignores a duplicate. The scheduler does
     * NOT guarantee a trigger is delivered exactly once or that a missed delivery
     * is dropped; a consumer that was disconnected when a trigger fired re-derives
     * due-ness from declared schedule state on reconnect (the reconciler already
     * re-evaluates schedules each loop). A richer ack/lease mechanism is additive
     * (GA); the at-least-once guarantee is what's pinned now.
     *
     * @generated from rpc rat.scheduler.v1.SchedulerService.WatchDue
     */
    watchDue: {
      name: "WatchDue",
      I: WatchDueRequest,
      O: WatchDueResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

