// Scheduler-backend axis service contract. DRAFT — sub-phase 0b.
//
// A `kind: scheduler-backend` plugin (in-process timer, cron, Temporal,
// cloud scheduler) owns "fire this at this time / on this interval". The
// reconciler asks it WHEN; the reconciler still decides WHAT (overview.md
// reconciliation model — the scheduler is a clock, not an orchestrator).
//
// Capability mapping:
//   rat://scheduler/v1/schedule   -> Schedule
//   rat://scheduler/v1/cancel     -> Cancel
//   rat://scheduler/v1/watch-due  -> WatchDue (stream of fired triggers)

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file rat/scheduler/v1/scheduler.proto (package rat.scheduler.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { RequestContext } from "../../common/v1/context_pb";
import { file_rat_common_v1_context } from "../../common/v1/context_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file rat/scheduler/v1/scheduler.proto.
 */
export const file_rat_scheduler_v1_scheduler: GenFile = /*@__PURE__*/
  fileDesc("CiByYXQvc2NoZWR1bGVyL3YxL3NjaGVkdWxlci5wcm90bxIQcmF0LnNjaGVkdWxlci52MSJ3Cg9TY2hlZHVsZVJlcXVlc3QSLgoHY29udGV4dBgBIAEoCzIdLnJhdC5jb21tb24udjEuUmVxdWVzdENvbnRleHQSEgoKdHJpZ2dlcl9pZBgCIAEoCRIMCgRjcm9uGAMgASgJEhIKCmF0X3VuaXhfbXMYBCABKAMiJgoQU2NoZWR1bGVSZXNwb25zZRISCgp0cmlnZ2VyX2lkGAEgASgJIlMKDUNhbmNlbFJlcXVlc3QSLgoHY29udGV4dBgBIAEoCzIdLnJhdC5jb21tb24udjEuUmVxdWVzdENvbnRleHQSEgoKdHJpZ2dlcl9pZBgCIAEoCSIjCg5DYW5jZWxSZXNwb25zZRIRCgljYW5jZWxsZWQYASABKAgiQQoPV2F0Y2hEdWVSZXF1ZXN0Ei4KB2NvbnRleHQYASABKAsyHS5yYXQuY29tbW9uLnYxLlJlcXVlc3RDb250ZXh0IkAKEFdhdGNoRHVlUmVzcG9uc2USEgoKdHJpZ2dlcl9pZBgBIAEoCRIYChBmaXJlZF9hdF91bml4X21zGAIgASgDMocCChBTY2hlZHVsZXJTZXJ2aWNlElEKCFNjaGVkdWxlEiEucmF0LnNjaGVkdWxlci52MS5TY2hlZHVsZVJlcXVlc3QaIi5yYXQuc2NoZWR1bGVyLnYxLlNjaGVkdWxlUmVzcG9uc2USSwoGQ2FuY2VsEh8ucmF0LnNjaGVkdWxlci52MS5DYW5jZWxSZXF1ZXN0GiAucmF0LnNjaGVkdWxlci52MS5DYW5jZWxSZXNwb25zZRJTCghXYXRjaER1ZRIhLnJhdC5zY2hlZHVsZXIudjEuV2F0Y2hEdWVSZXF1ZXN0GiIucmF0LnNjaGVkdWxlci52MS5XYXRjaER1ZVJlc3BvbnNlMAFCOVo3Z2l0aHViLmNvbS9yYXQtZGV2L3JhdC9nZW4vcmF0L3NjaGVkdWxlci92MTtzY2hlZHVsZXJ2MWIGcHJvdG8z", [file_rat_common_v1_context]);

/**
 * @generated from message rat.scheduler.v1.ScheduleRequest
 */
export type ScheduleRequest = Message<"rat.scheduler.v1.ScheduleRequest"> & {
  /**
   * @generated from field: rat.common.v1.RequestContext context = 1;
   */
  context?: RequestContext | undefined;

  /**
   * Caller-chosen id, used to cancel + to correlate fired triggers.
   *
   * @generated from field: string trigger_id = 2;
   */
  triggerId: string;

  /**
   * Cron expression; if empty, `at_unix_ms` is used for a one-shot.
   *
   * @generated from field: string cron = 3;
   */
  cron: string;

  /**
   * @generated from field: int64 at_unix_ms = 4;
   */
  atUnixMs: bigint;
};

/**
 * Describes the message rat.scheduler.v1.ScheduleRequest.
 * Use `create(ScheduleRequestSchema)` to create a new message.
 */
export const ScheduleRequestSchema: GenMessage<ScheduleRequest> = /*@__PURE__*/
  messageDesc(file_rat_scheduler_v1_scheduler, 0);

/**
 * @generated from message rat.scheduler.v1.ScheduleResponse
 */
export type ScheduleResponse = Message<"rat.scheduler.v1.ScheduleResponse"> & {
  /**
   * @generated from field: string trigger_id = 1;
   */
  triggerId: string;
};

/**
 * Describes the message rat.scheduler.v1.ScheduleResponse.
 * Use `create(ScheduleResponseSchema)` to create a new message.
 */
export const ScheduleResponseSchema: GenMessage<ScheduleResponse> = /*@__PURE__*/
  messageDesc(file_rat_scheduler_v1_scheduler, 1);

/**
 * @generated from message rat.scheduler.v1.CancelRequest
 */
export type CancelRequest = Message<"rat.scheduler.v1.CancelRequest"> & {
  /**
   * @generated from field: rat.common.v1.RequestContext context = 1;
   */
  context?: RequestContext | undefined;

  /**
   * @generated from field: string trigger_id = 2;
   */
  triggerId: string;
};

/**
 * Describes the message rat.scheduler.v1.CancelRequest.
 * Use `create(CancelRequestSchema)` to create a new message.
 */
export const CancelRequestSchema: GenMessage<CancelRequest> = /*@__PURE__*/
  messageDesc(file_rat_scheduler_v1_scheduler, 2);

/**
 * @generated from message rat.scheduler.v1.CancelResponse
 */
export type CancelResponse = Message<"rat.scheduler.v1.CancelResponse"> & {
  /**
   * @generated from field: bool cancelled = 1;
   */
  cancelled: boolean;
};

/**
 * Describes the message rat.scheduler.v1.CancelResponse.
 * Use `create(CancelResponseSchema)` to create a new message.
 */
export const CancelResponseSchema: GenMessage<CancelResponse> = /*@__PURE__*/
  messageDesc(file_rat_scheduler_v1_scheduler, 3);

/**
 * @generated from message rat.scheduler.v1.WatchDueRequest
 */
export type WatchDueRequest = Message<"rat.scheduler.v1.WatchDueRequest"> & {
  /**
   * @generated from field: rat.common.v1.RequestContext context = 1;
   */
  context?: RequestContext | undefined;
};

/**
 * Describes the message rat.scheduler.v1.WatchDueRequest.
 * Use `create(WatchDueRequestSchema)` to create a new message.
 */
export const WatchDueRequestSchema: GenMessage<WatchDueRequest> = /*@__PURE__*/
  messageDesc(file_rat_scheduler_v1_scheduler, 4);

/**
 * One fired trigger.
 *
 * @generated from message rat.scheduler.v1.WatchDueResponse
 */
export type WatchDueResponse = Message<"rat.scheduler.v1.WatchDueResponse"> & {
  /**
   * @generated from field: string trigger_id = 1;
   */
  triggerId: string;

  /**
   * @generated from field: int64 fired_at_unix_ms = 2;
   */
  firedAtUnixMs: bigint;
};

/**
 * Describes the message rat.scheduler.v1.WatchDueResponse.
 * Use `create(WatchDueResponseSchema)` to create a new message.
 */
export const WatchDueResponseSchema: GenMessage<WatchDueResponse> = /*@__PURE__*/
  messageDesc(file_rat_scheduler_v1_scheduler, 5);

/**
 * @generated from service rat.scheduler.v1.SchedulerService
 */
export const SchedulerService: GenService<{
  /**
   * rat://scheduler/v1/schedule — register a trigger (cron expr or one-shot).
   *
   * @generated from rpc rat.scheduler.v1.SchedulerService.Schedule
   */
  schedule: {
    methodKind: "unary";
    input: typeof ScheduleRequestSchema;
    output: typeof ScheduleResponseSchema;
  },
  /**
   * rat://scheduler/v1/cancel — remove a previously-registered trigger.
   *
   * @generated from rpc rat.scheduler.v1.SchedulerService.Cancel
   */
  cancel: {
    methodKind: "unary";
    input: typeof CancelRequestSchema;
    output: typeof CancelResponseSchema;
  },
  /**
   * rat://scheduler/v1/watch-due — stream of triggers as they fire. The
   * reconciler consumes this to know a pipeline is due.
   *
   * DELIVERY SEMANTICS (reviews/06 API-11, pinned at freeze): AT-LEAST-ONCE. A
   * fired trigger MAY be redelivered (e.g. if the consumer reconnects), so the
   * reconciler MUST treat WatchDue delivery as idempotent — it keys actions by
   * (trigger_id, fired_at_unix_ms) and ignores a duplicate. The scheduler does
   * NOT guarantee a trigger is delivered exactly once or that a missed delivery
   * is dropped; a consumer that was disconnected when a trigger fired re-derives
   * due-ness from declared schedule state on reconnect (the reconciler already
   * re-evaluates schedules each loop). A richer ack/lease mechanism is additive
   * (GA); the at-least-once guarantee is what's pinned now.
   *
   * @generated from rpc rat.scheduler.v1.SchedulerService.WatchDue
   */
  watchDue: {
    methodKind: "server_streaming";
    input: typeof WatchDueRequestSchema;
    output: typeof WatchDueResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_rat_scheduler_v1_scheduler, 0);

