# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from rat.core.v1 import control_pb2 as rat_dot_core_dot_v1_dot_control__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rat/core/v1/control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControlServiceStub(object):
    """ControlService is served on the daemon's CONTROL listener alongside
    CapabilityInvokeService. rat.toml stays the source of truth; these RPCs only apply a
    diff to the running daemon (the CLI writes the file first, then materializes).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterPlugin = channel.unary_unary(
                '/rat.core.v1.ControlService/RegisterPlugin',
                request_serializer=rat_dot_core_dot_v1_dot_control__pb2.RegisterPluginRequest.SerializeToString,
                response_deserializer=rat_dot_core_dot_v1_dot_control__pb2.RegisterPluginResponse.FromString,
                _registered_method=True)
        self.DeregisterPlugin = channel.unary_unary(
                '/rat.core.v1.ControlService/DeregisterPlugin',
                request_serializer=rat_dot_core_dot_v1_dot_control__pb2.DeregisterPluginRequest.SerializeToString,
                response_deserializer=rat_dot_core_dot_v1_dot_control__pb2.DeregisterPluginResponse.FromString,
                _registered_method=True)
        self.ListPlugins = channel.unary_unary(
                '/rat.core.v1.ControlService/ListPlugins',
                request_serializer=rat_dot_core_dot_v1_dot_control__pb2.ListPluginsRequest.SerializeToString,
                response_deserializer=rat_dot_core_dot_v1_dot_control__pb2.ListPluginsResponse.FromString,
                _registered_method=True)


class ControlServiceServicer(object):
    """ControlService is served on the daemon's CONTROL listener alongside
    CapabilityInvokeService. rat.toml stays the source of truth; these RPCs only apply a
    diff to the running daemon (the CLI writes the file first, then materializes).
    """

    def RegisterPlugin(self, request, context):
        """Add a plugin to the running plane: validate its manifest, register it (so C5
        authorization now knows it), add it to the reconciler's desired set (launch +
        wire), and wait — bounded — for it to become Healthy. Idempotent: re-registering
        a present plugin refreshes its spec. On a launch/readiness failure the daemon
        rolls the desired entry back so a failed live-add leaves no partial state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeregisterPlugin(self, request, context):
        """Remove a plugin from the running plane: drop it from the desired set (terminate
        the instance), unbind it from the gateway, and deregister it from the registry.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPlugins(self, request, context):
        """The live plane as the daemon sees it — distinct from `rat status`, which reads
        rat.toml. Reports each plugin's name, kind, reconcile state, endpoint, provides.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterPlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterPlugin,
                    request_deserializer=rat_dot_core_dot_v1_dot_control__pb2.RegisterPluginRequest.FromString,
                    response_serializer=rat_dot_core_dot_v1_dot_control__pb2.RegisterPluginResponse.SerializeToString,
            ),
            'DeregisterPlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.DeregisterPlugin,
                    request_deserializer=rat_dot_core_dot_v1_dot_control__pb2.DeregisterPluginRequest.FromString,
                    response_serializer=rat_dot_core_dot_v1_dot_control__pb2.DeregisterPluginResponse.SerializeToString,
            ),
            'ListPlugins': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlugins,
                    request_deserializer=rat_dot_core_dot_v1_dot_control__pb2.ListPluginsRequest.FromString,
                    response_serializer=rat_dot_core_dot_v1_dot_control__pb2.ListPluginsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rat.core.v1.ControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rat.core.v1.ControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlService(object):
    """ControlService is served on the daemon's CONTROL listener alongside
    CapabilityInvokeService. rat.toml stays the source of truth; these RPCs only apply a
    diff to the running daemon (the CLI writes the file first, then materializes).
    """

    @staticmethod
    def RegisterPlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rat.core.v1.ControlService/RegisterPlugin',
            rat_dot_core_dot_v1_dot_control__pb2.RegisterPluginRequest.SerializeToString,
            rat_dot_core_dot_v1_dot_control__pb2.RegisterPluginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeregisterPlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rat.core.v1.ControlService/DeregisterPlugin',
            rat_dot_core_dot_v1_dot_control__pb2.DeregisterPluginRequest.SerializeToString,
            rat_dot_core_dot_v1_dot_control__pb2.DeregisterPluginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPlugins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rat.core.v1.ControlService/ListPlugins',
            rat_dot_core_dot_v1_dot_control__pb2.ListPluginsRequest.SerializeToString,
            rat_dot_core_dot_v1_dot_control__pb2.ListPluginsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
