# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rat.core.v1 import invoke_pb2 as rat_dot_core_dot_v1_dot_invoke__pb2


class CapabilityInvokeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Invoke = channel.unary_unary(
                '/rat.core.v1.CapabilityInvokeService/Invoke',
                request_serializer=rat_dot_core_dot_v1_dot_invoke__pb2.InvokeRequest.SerializeToString,
                response_deserializer=rat_dot_core_dot_v1_dot_invoke__pb2.InvokeResponse.FromString,
                _registered_method=True)


class CapabilityInvokeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Invoke(self, request, context):
        """Invoke one capability on its resolved provider, mediated + enforced by the
        core. Unary control call; bulk data (if any) flows out-of-band via the
        ArrowStream descriptors inside the relayed payload/result.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CapabilityInvokeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Invoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Invoke,
                    request_deserializer=rat_dot_core_dot_v1_dot_invoke__pb2.InvokeRequest.FromString,
                    response_serializer=rat_dot_core_dot_v1_dot_invoke__pb2.InvokeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rat.core.v1.CapabilityInvokeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rat.core.v1.CapabilityInvokeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CapabilityInvokeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Invoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rat.core.v1.CapabilityInvokeService/Invoke',
            rat_dot_core_dot_v1_dot_invoke__pb2.InvokeRequest.SerializeToString,
            rat_dot_core_dot_v1_dot_invoke__pb2.InvokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
