// Identity axis service contract. Status: v1 (frozen — rat/1.2; ADR-003: control-plane = one ref + conformance).
//
// A `kind: identity` plugin (static-token, OIDC, mTLS) backs the core's Identity
// Gateway (one of the six core things). Every request the API gateway accepts is
// authenticated here before routing.
//
// Capability mapping:
//   rat://identity/v1/authenticate -> Authenticate (credential -> subject)
//   rat://identity/v1/authorize    -> Authorize    (subject + action -> allow?)
//
// C2 — PLUGIN-TO-CORE AUTH: this axis also resolves the plugin's OWN identity.
// Per reviews/00 Theme 3, v2 already solved this (ADR-020: per-startup platform
// token, constant-time compare). v3 inherits it as a CONTRACT: the default
// identity plugin issues a per-plugin token at registration; Authenticate
// constant-time-compares it. The default is NOT anonymous-root (reviews/04).
//
// NOTE: authz here is COARSE (is this subject allowed this action at all). The
// per-capability call authorization (C5) is enforced by the API gateway against
// the manifest `provides`/`requires`, not re-litigated per identity plugin.
//
// ERROR MODEL (reviews/06 C-5 / freeze-blocker #9), pinned at freeze so authors
// build ONE model:
//   - TRANSPORT/operational failures (backend down, malformed request) -> gRPC
//     canonical status codes.
//   - DECISION outcomes on a SUCCESSFUL rpc (a deny is a successful Authorize, so
//     a status code can't carry it) -> in-band `allowed` bool + enumerated
//     `deny_code`. Free-text `reason` is LOG/AUDIT-ONLY and MUST NOT drive caller
//     logic (returning rich reasons to an untrusted caller is an enumeration
//     oracle, reviews/04). Callers branch on `deny_code`, not `reason`.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rat/identity/v1/identity.proto

package identityv1

import (
	_ "github.com/squat-collective/rat-v3/gen/rat/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Machine-readable deny reason for Authorize. Callers branch on this, never on
// the free-text reason (anti-enumeration-oracle; see ERROR MODEL above).
type DenyCode int32

const (
	DenyCode_DENY_CODE_UNSPECIFIED        DenyCode = 0 // not a deny (allowed=true) OR reason not supplied
	DenyCode_DENY_CODE_NOT_AUTHENTICATED  DenyCode = 1 // no/invalid subject established
	DenyCode_DENY_CODE_INSUFFICIENT_ROLE  DenyCode = 2 // authenticated but lacks the required role
	DenyCode_DENY_CODE_ACTION_FORBIDDEN   DenyCode = 3 // the action is denied for this subject
	DenyCode_DENY_CODE_RESOURCE_FORBIDDEN DenyCode = 4 // the specific resource is denied
)

// Enum value maps for DenyCode.
var (
	DenyCode_name = map[int32]string{
		0: "DENY_CODE_UNSPECIFIED",
		1: "DENY_CODE_NOT_AUTHENTICATED",
		2: "DENY_CODE_INSUFFICIENT_ROLE",
		3: "DENY_CODE_ACTION_FORBIDDEN",
		4: "DENY_CODE_RESOURCE_FORBIDDEN",
	}
	DenyCode_value = map[string]int32{
		"DENY_CODE_UNSPECIFIED":        0,
		"DENY_CODE_NOT_AUTHENTICATED":  1,
		"DENY_CODE_INSUFFICIENT_ROLE":  2,
		"DENY_CODE_ACTION_FORBIDDEN":   3,
		"DENY_CODE_RESOURCE_FORBIDDEN": 4,
	}
)

func (x DenyCode) Enum() *DenyCode {
	p := new(DenyCode)
	*p = x
	return p
}

func (x DenyCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DenyCode) Descriptor() protoreflect.EnumDescriptor {
	return file_rat_identity_v1_identity_proto_enumTypes[0].Descriptor()
}

func (DenyCode) Type() protoreflect.EnumType {
	return &file_rat_identity_v1_identity_proto_enumTypes[0]
}

func (x DenyCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DenyCode.Descriptor instead.
func (DenyCode) EnumDescriptor() ([]byte, []int) {
	return file_rat_identity_v1_identity_proto_rawDescGZIP(), []int{0}
}

type AuthenticateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque credential (bearer token, client-cert chain, etc.). Never logged;
	// `debug_redact` makes that structural (reviews/06 SEC-8).
	Credential    []byte `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_rat_identity_v1_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rat_identity_v1_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_rat_identity_v1_identity_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateRequest) GetCredential() []byte {
	if x != nil {
		return x.Credential
	}
	return nil
}

type AuthenticateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authenticated bool                   `protobuf:"varint,1,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	// The resolved subject to stamp onto downstream RequestContext.subject.
	Subject string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	// The tenant this subject belongs to (stamped onto RequestContext.tenant).
	Tenant        string `protobuf:"bytes,3,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_rat_identity_v1_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rat_identity_v1_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_rat_identity_v1_identity_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticateResponse) GetAuthenticated() bool {
	if x != nil {
		return x.Authenticated
	}
	return false
}

func (x *AuthenticateResponse) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *AuthenticateResponse) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

type AuthorizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Action being attempted, e.g. "pipeline.run", "plane.create".
	Action string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	// Optional resource the action targets.
	Resource      string `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_rat_identity_v1_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rat_identity_v1_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_rat_identity_v1_identity_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorizeRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuthorizeRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

type AuthorizeResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Allowed bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	// Machine-readable deny reason when allowed=false. UNSPECIFIED when allowed.
	DenyCode DenyCode `protobuf:"varint,2,opt,name=deny_code,json=denyCode,proto3,enum=rat.identity.v1.DenyCode" json:"deny_code,omitempty"`
	// Human-readable reason — LOG/AUDIT-ONLY, never returned to drive caller logic
	// (enumeration-oracle risk). Callers branch on deny_code.
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_rat_identity_v1_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rat_identity_v1_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_rat_identity_v1_identity_proto_rawDescGZIP(), []int{3}
}

func (x *AuthorizeResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *AuthorizeResponse) GetDenyCode() DenyCode {
	if x != nil {
		return x.DenyCode
	}
	return DenyCode_DENY_CODE_UNSPECIFIED
}

func (x *AuthorizeResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_rat_identity_v1_identity_proto protoreflect.FileDescriptor

const file_rat_identity_v1_identity_proto_rawDesc = "" +
	"\n" +
	"\x1erat/identity/v1/identity.proto\x12\x0frat.identity.v1\x1a\x1frat/common/v1/annotations.proto\"@\n" +
	"\x13AuthenticateRequest\x12#\n" +
	"\n" +
	"credential\x18\x02 \x01(\fB\x03\x80\x01\x01R\n" +
	"credentialJ\x04\b\x01\x10\x02\"n\n" +
	"\x14AuthenticateResponse\x12$\n" +
	"\rauthenticated\x18\x01 \x01(\bR\rauthenticated\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x16\n" +
	"\x06tenant\x18\x03 \x01(\tR\x06tenant\"L\n" +
	"\x10AuthorizeRequest\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresourceJ\x04\b\x01\x10\x02\"}\n" +
	"\x11AuthorizeResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x126\n" +
	"\tdeny_code\x18\x02 \x01(\x0e2\x19.rat.identity.v1.DenyCodeR\bdenyCode\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason*\xa9\x01\n" +
	"\bDenyCode\x12\x19\n" +
	"\x15DENY_CODE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bDENY_CODE_NOT_AUTHENTICATED\x10\x01\x12\x1f\n" +
	"\x1bDENY_CODE_INSUFFICIENT_ROLE\x10\x02\x12\x1e\n" +
	"\x1aDENY_CODE_ACTION_FORBIDDEN\x10\x03\x12 \n" +
	"\x1cDENY_CODE_RESOURCE_FORBIDDEN\x10\x042\x87\x02\n" +
	"\x0fIdentityService\x12\x7f\n" +
	"\fAuthenticate\x12$.rat.identity.v1.AuthenticateRequest\x1a%.rat.identity.v1.AuthenticateResponse\"\"\x8a\x97\"\x1erat://identity/v1/authenticate\x12s\n" +
	"\tAuthorize\x12!.rat.identity.v1.AuthorizeRequest\x1a\".rat.identity.v1.AuthorizeResponse\"\x1f\x8a\x97\"\x1brat://identity/v1/authorizeBCZAgithub.com/squat-collective/rat-v3/gen/rat/identity/v1;identityv1b\x06proto3"

var (
	file_rat_identity_v1_identity_proto_rawDescOnce sync.Once
	file_rat_identity_v1_identity_proto_rawDescData []byte
)

func file_rat_identity_v1_identity_proto_rawDescGZIP() []byte {
	file_rat_identity_v1_identity_proto_rawDescOnce.Do(func() {
		file_rat_identity_v1_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rat_identity_v1_identity_proto_rawDesc), len(file_rat_identity_v1_identity_proto_rawDesc)))
	})
	return file_rat_identity_v1_identity_proto_rawDescData
}

var file_rat_identity_v1_identity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rat_identity_v1_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rat_identity_v1_identity_proto_goTypes = []any{
	(DenyCode)(0),                // 0: rat.identity.v1.DenyCode
	(*AuthenticateRequest)(nil),  // 1: rat.identity.v1.AuthenticateRequest
	(*AuthenticateResponse)(nil), // 2: rat.identity.v1.AuthenticateResponse
	(*AuthorizeRequest)(nil),     // 3: rat.identity.v1.AuthorizeRequest
	(*AuthorizeResponse)(nil),    // 4: rat.identity.v1.AuthorizeResponse
}
var file_rat_identity_v1_identity_proto_depIdxs = []int32{
	0, // 0: rat.identity.v1.AuthorizeResponse.deny_code:type_name -> rat.identity.v1.DenyCode
	1, // 1: rat.identity.v1.IdentityService.Authenticate:input_type -> rat.identity.v1.AuthenticateRequest
	3, // 2: rat.identity.v1.IdentityService.Authorize:input_type -> rat.identity.v1.AuthorizeRequest
	2, // 3: rat.identity.v1.IdentityService.Authenticate:output_type -> rat.identity.v1.AuthenticateResponse
	4, // 4: rat.identity.v1.IdentityService.Authorize:output_type -> rat.identity.v1.AuthorizeResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rat_identity_v1_identity_proto_init() }
func file_rat_identity_v1_identity_proto_init() {
	if File_rat_identity_v1_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rat_identity_v1_identity_proto_rawDesc), len(file_rat_identity_v1_identity_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rat_identity_v1_identity_proto_goTypes,
		DependencyIndexes: file_rat_identity_v1_identity_proto_depIdxs,
		EnumInfos:         file_rat_identity_v1_identity_proto_enumTypes,
		MessageInfos:      file_rat_identity_v1_identity_proto_msgTypes,
	}.Build()
	File_rat_identity_v1_identity_proto = out.File
	file_rat_identity_v1_identity_proto_goTypes = nil
	file_rat_identity_v1_identity_proto_depIdxs = nil
}
