// Catalog axis service contract. DRAFT — sub-phase 0b.
//
// A `kind: catalog` plugin (Nessie, Unity, Lakekeeper, Glue, Polaris) owns
// table metadata + branch/version semantics. It is what makes "branch-isolated
// pipeline runs" (the v2 pipeline model we keep — overview.md) possible.
//
// Capability mapping:
//   rat://catalog/v1/get-table    -> GetTable
//   rat://catalog/v1/create-branch-> CreateBranch
//   rat://catalog/v1/merge-branch -> MergeBranch
//
// Not every catalog supports branching (Glue doesn't); those plugins simply do
// not `provide` the branch capabilities, and the registry won't wire a
// branch-requiring strategy to them. Capability negotiation, not feature flags.
//
// MERGE SAFETY (reviews/06 #8 = ARCH-4 / I-18): MergeBranch is the publish gate
// of the pipeline model and the reconciler RETRIES it, so it must be safe under
// retry AND concurrency. Two fields make it so:
//   - `expected_into_snapshot` — optimistic concurrency on the target. The merge
//     applies only if `into_branch` is still at this snapshot; otherwise it fails
//     (the caller re-reads + re-tests). Without it, two concurrent merges into
//     main silently lose one side's updates (lost-update).
//   - `idempotency_key` — a stable id for THIS logical merge (e.g. the run id).
//     A retry with the same key that already committed is a no-op that returns
//     the original result (MergeBranchResponse.already_applied = true), so a
//     reconciler retry can't double-apply.
// NOTE: this is the branch-MERGE linkage. The separate gap — how the catalog
// learns what format.Write put on a branch — is the additive commit-linkage RPC
// (reviews/06 I-18), GA-deferred; only the request-shape change here is
// freeze-gated.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rat/catalog/v1/catalog.proto

package catalogv1

import (
	v1 "github.com/rat-dev/rat/gen/rat/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTableRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Identifier string                 `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// Optional branch to read from (empty == main).
	Branch        string `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTableRequest) Reset() {
	*x = GetTableRequest{}
	mi := &file_rat_catalog_v1_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTableRequest) ProtoMessage() {}

func (x *GetTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rat_catalog_v1_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTableRequest.ProtoReflect.Descriptor instead.
func (*GetTableRequest) Descriptor() ([]byte, []int) {
	return file_rat_catalog_v1_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *GetTableRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *GetTableRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

type GetTableResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// NO `found` field BY DESIGN (error-model M2, common/v1/ERROR_MODEL.md): a
	// GetTable on a named table the caller asserts exists is not normal control flow
	// and is not enumeration-sensitive, so an unknown identifier is an ERROR —
	// `NOT_FOUND` status, not a `found=false` outcome. (Contrast state.Get /
	// secret.Resolve, which DO use a `found` bool — read-miss is normal there, and
	// secret additionally collapses forbidden into absent for anti-enumeration.)
	Table         *v1.TableRef `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTableResponse) Reset() {
	*x = GetTableResponse{}
	mi := &file_rat_catalog_v1_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTableResponse) ProtoMessage() {}

func (x *GetTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rat_catalog_v1_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTableResponse.ProtoReflect.Descriptor instead.
func (*GetTableResponse) Descriptor() ([]byte, []int) {
	return file_rat_catalog_v1_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *GetTableResponse) GetTable() *v1.TableRef {
	if x != nil {
		return x.Table
	}
	return nil
}

type CreateBranchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Branch name to create (e.g. a run id).
	Branch string `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	// Branch point (empty == tip of main).
	FromBranch    string `protobuf:"bytes,3,opt,name=from_branch,json=fromBranch,proto3" json:"from_branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBranchRequest) Reset() {
	*x = CreateBranchRequest{}
	mi := &file_rat_catalog_v1_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBranchRequest) ProtoMessage() {}

func (x *CreateBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rat_catalog_v1_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBranchRequest.ProtoReflect.Descriptor instead.
func (*CreateBranchRequest) Descriptor() ([]byte, []int) {
	return file_rat_catalog_v1_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBranchRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *CreateBranchRequest) GetFromBranch() string {
	if x != nil {
		return x.FromBranch
	}
	return ""
}

type CreateBranchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branch        string                 `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBranchResponse) Reset() {
	*x = CreateBranchResponse{}
	mi := &file_rat_catalog_v1_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBranchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBranchResponse) ProtoMessage() {}

func (x *CreateBranchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rat_catalog_v1_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBranchResponse.ProtoReflect.Descriptor instead.
func (*CreateBranchResponse) Descriptor() ([]byte, []int) {
	return file_rat_catalog_v1_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBranchResponse) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

type MergeBranchRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Branch     string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	IntoBranch string                 `protobuf:"bytes,3,opt,name=into_branch,json=intoBranch,proto3" json:"into_branch,omitempty"`
	// Optimistic-concurrency guard: the snapshot `into_branch` is expected to be at
	// for this merge to apply. Empty == unconditional (no concurrency guard — only
	// safe when the caller knows it's the sole writer). See MERGE SAFETY above.
	ExpectedIntoSnapshot string `protobuf:"bytes,4,opt,name=expected_into_snapshot,json=expectedIntoSnapshot,proto3" json:"expected_into_snapshot,omitempty"`
	// Stable id for this logical merge (e.g. the pipeline run id). Makes MergeBranch
	// idempotent under reconciler retry: re-submitting a key that already committed
	// is a no-op returning the original result. Empty == not idempotent (each call
	// is a fresh merge attempt).
	IdempotencyKey string `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MergeBranchRequest) Reset() {
	*x = MergeBranchRequest{}
	mi := &file_rat_catalog_v1_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeBranchRequest) ProtoMessage() {}

func (x *MergeBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rat_catalog_v1_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeBranchRequest.ProtoReflect.Descriptor instead.
func (*MergeBranchRequest) Descriptor() ([]byte, []int) {
	return file_rat_catalog_v1_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *MergeBranchRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *MergeBranchRequest) GetIntoBranch() string {
	if x != nil {
		return x.IntoBranch
	}
	return ""
}

func (x *MergeBranchRequest) GetExpectedIntoSnapshot() string {
	if x != nil {
		return x.ExpectedIntoSnapshot
	}
	return ""
}

func (x *MergeBranchRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type MergeBranchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resulting snapshot id on the target branch.
	SnapshotId string `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	// True if this response reflects a previously-committed merge with the same
	// idempotency_key (the retry was a no-op), rather than a merge applied now.
	AlreadyApplied bool `protobuf:"varint,2,opt,name=already_applied,json=alreadyApplied,proto3" json:"already_applied,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MergeBranchResponse) Reset() {
	*x = MergeBranchResponse{}
	mi := &file_rat_catalog_v1_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeBranchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeBranchResponse) ProtoMessage() {}

func (x *MergeBranchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rat_catalog_v1_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeBranchResponse.ProtoReflect.Descriptor instead.
func (*MergeBranchResponse) Descriptor() ([]byte, []int) {
	return file_rat_catalog_v1_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *MergeBranchResponse) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *MergeBranchResponse) GetAlreadyApplied() bool {
	if x != nil {
		return x.AlreadyApplied
	}
	return false
}

var File_rat_catalog_v1_catalog_proto protoreflect.FileDescriptor

const file_rat_catalog_v1_catalog_proto_rawDesc = "" +
	"\n" +
	"\x1crat/catalog/v1/catalog.proto\x12\x0erat.catalog.v1\x1a\x1frat/common/v1/annotations.proto\x1a\x18rat/common/v1/data.proto\"O\n" +
	"\x0fGetTableRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branchJ\x04\b\x01\x10\x02\"A\n" +
	"\x10GetTableResponse\x12-\n" +
	"\x05table\x18\x01 \x01(\v2\x17.rat.common.v1.TableRefR\x05table\"T\n" +
	"\x13CreateBranchRequest\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12\x1f\n" +
	"\vfrom_branch\x18\x03 \x01(\tR\n" +
	"fromBranchJ\x04\b\x01\x10\x02\".\n" +
	"\x14CreateBranchResponse\x12\x16\n" +
	"\x06branch\x18\x01 \x01(\tR\x06branch\"\xb2\x01\n" +
	"\x12MergeBranchRequest\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12\x1f\n" +
	"\vinto_branch\x18\x03 \x01(\tR\n" +
	"intoBranch\x124\n" +
	"\x16expected_into_snapshot\x18\x04 \x01(\tR\x14expectedIntoSnapshot\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKeyJ\x04\b\x01\x10\x02\"_\n" +
	"\x13MergeBranchResponse\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12'\n" +
	"\x0falready_applied\x18\x02 \x01(\bR\x0ealreadyApplied2\xf9\x02\n" +
	"\x0eCatalogService\x12m\n" +
	"\bGetTable\x12\x1f.rat.catalog.v1.GetTableRequest\x1a .rat.catalog.v1.GetTableResponse\"\x1e\x8a\x97\"\x1arat://catalog/v1/get-table\x12}\n" +
	"\fCreateBranch\x12#.rat.catalog.v1.CreateBranchRequest\x1a$.rat.catalog.v1.CreateBranchResponse\"\"\x8a\x97\"\x1erat://catalog/v1/create-branch\x12y\n" +
	"\vMergeBranch\x12\".rat.catalog.v1.MergeBranchRequest\x1a#.rat.catalog.v1.MergeBranchResponse\"!\x8a\x97\"\x1drat://catalog/v1/merge-branchB5Z3github.com/rat-dev/rat/gen/rat/catalog/v1;catalogv1b\x06proto3"

var (
	file_rat_catalog_v1_catalog_proto_rawDescOnce sync.Once
	file_rat_catalog_v1_catalog_proto_rawDescData []byte
)

func file_rat_catalog_v1_catalog_proto_rawDescGZIP() []byte {
	file_rat_catalog_v1_catalog_proto_rawDescOnce.Do(func() {
		file_rat_catalog_v1_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rat_catalog_v1_catalog_proto_rawDesc), len(file_rat_catalog_v1_catalog_proto_rawDesc)))
	})
	return file_rat_catalog_v1_catalog_proto_rawDescData
}

var file_rat_catalog_v1_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rat_catalog_v1_catalog_proto_goTypes = []any{
	(*GetTableRequest)(nil),      // 0: rat.catalog.v1.GetTableRequest
	(*GetTableResponse)(nil),     // 1: rat.catalog.v1.GetTableResponse
	(*CreateBranchRequest)(nil),  // 2: rat.catalog.v1.CreateBranchRequest
	(*CreateBranchResponse)(nil), // 3: rat.catalog.v1.CreateBranchResponse
	(*MergeBranchRequest)(nil),   // 4: rat.catalog.v1.MergeBranchRequest
	(*MergeBranchResponse)(nil),  // 5: rat.catalog.v1.MergeBranchResponse
	(*v1.TableRef)(nil),          // 6: rat.common.v1.TableRef
}
var file_rat_catalog_v1_catalog_proto_depIdxs = []int32{
	6, // 0: rat.catalog.v1.GetTableResponse.table:type_name -> rat.common.v1.TableRef
	0, // 1: rat.catalog.v1.CatalogService.GetTable:input_type -> rat.catalog.v1.GetTableRequest
	2, // 2: rat.catalog.v1.CatalogService.CreateBranch:input_type -> rat.catalog.v1.CreateBranchRequest
	4, // 3: rat.catalog.v1.CatalogService.MergeBranch:input_type -> rat.catalog.v1.MergeBranchRequest
	1, // 4: rat.catalog.v1.CatalogService.GetTable:output_type -> rat.catalog.v1.GetTableResponse
	3, // 5: rat.catalog.v1.CatalogService.CreateBranch:output_type -> rat.catalog.v1.CreateBranchResponse
	5, // 6: rat.catalog.v1.CatalogService.MergeBranch:output_type -> rat.catalog.v1.MergeBranchResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rat_catalog_v1_catalog_proto_init() }
func file_rat_catalog_v1_catalog_proto_init() {
	if File_rat_catalog_v1_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rat_catalog_v1_catalog_proto_rawDesc), len(file_rat_catalog_v1_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rat_catalog_v1_catalog_proto_goTypes,
		DependencyIndexes: file_rat_catalog_v1_catalog_proto_depIdxs,
		MessageInfos:      file_rat_catalog_v1_catalog_proto_msgTypes,
	}.Build()
	File_rat_catalog_v1_catalog_proto = out.File
	file_rat_catalog_v1_catalog_proto_goTypes = nil
	file_rat_catalog_v1_catalog_proto_depIdxs = nil
}
