// Catalog axis service contract. Status: v1 (frozen — rat/1, ADR-009;
// RegisterTable + CommitTable added additively at rat/1.5, ADR-010).
//
// A `kind: catalog` plugin (Nessie, Unity, Lakekeeper, Glue, Polaris) owns
// table metadata + branch/version semantics. It is what makes "branch-isolated
// pipeline runs" (the v2 pipeline model we keep — overview.md) possible.
//
// Capability mapping:
//   rat://catalog/v1/get-table     -> GetTable
//   rat://catalog/v1/create-branch -> CreateBranch
//   rat://catalog/v1/merge-branch  -> MergeBranch
//   rat://catalog/v1/register-table-> RegisterTable  (ADR-010, additive)
//   rat://catalog/v1/commit-table  -> CommitTable    (ADR-010, additive)
//
// Not every catalog supports branching (Glue doesn't); those plugins simply do
// not `provide` the branch capabilities, and the registry won't wire a
// branch-requiring strategy to them. Capability negotiation, not feature flags.
//
// MERGE SAFETY (reviews/06 #8 = ARCH-4 / I-18): MergeBranch is the publish gate
// of the pipeline model and the reconciler RETRIES it, so it must be safe under
// retry AND concurrency. Two fields make it so:
//   - `expected_into_snapshot` — optimistic concurrency on the target. The merge
//     applies only if `into_branch` is still at this snapshot; otherwise it fails
//     (the caller re-reads + re-tests). Without it, two concurrent merges into
//     main silently lose one side's updates (lost-update).
//   - `idempotency_key` — a stable id for THIS logical merge (e.g. the run id).
//     A retry with the same key that already committed is a no-op that returns
//     the original result (MergeBranchResponse.already_applied = true), so a
//     reconciler retry can't double-apply.
// NOTE: this is the branch-MERGE linkage. The separate gap — how the catalog
// learns what format.Write put on a branch — is closed by the additive
// commit-linkage RPCs below (RegisterTable + CommitTable), added at rat/1.5 per
// ADR-010 (resolving ADR-009 residual R3 / reviews/08 B1). They are additive: the
// frozen GetTable/CreateBranch/MergeBranch shapes are unchanged.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: rat/catalog/v1/catalog.proto

package catalogv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatalogService_GetTable_FullMethodName      = "/rat.catalog.v1.CatalogService/GetTable"
	CatalogService_CreateBranch_FullMethodName  = "/rat.catalog.v1.CatalogService/CreateBranch"
	CatalogService_MergeBranch_FullMethodName   = "/rat.catalog.v1.CatalogService/MergeBranch"
	CatalogService_RegisterTable_FullMethodName = "/rat.catalog.v1.CatalogService/RegisterTable"
	CatalogService_CommitTable_FullMethodName   = "/rat.catalog.v1.CatalogService/CommitTable"
)

// CatalogServiceClient is the client API for CatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogServiceClient interface {
	// rat://catalog/v1/get-table — resolve a table identifier to a TableRef
	// (physical location + current snapshot/branch).
	GetTable(ctx context.Context, in *GetTableRequest, opts ...grpc.CallOption) (*GetTableResponse, error)
	// rat://catalog/v1/create-branch — open an isolated branch for a pipeline run.
	CreateBranch(ctx context.Context, in *CreateBranchRequest, opts ...grpc.CallOption) (*CreateBranchResponse, error)
	// rat://catalog/v1/merge-branch — merge a completed run's branch back to main,
	// after quality tests pass (the pre-merge gate of the v2 pipeline model).
	MergeBranch(ctx context.Context, in *MergeBranchRequest, opts ...grpc.CallOption) (*MergeBranchResponse, error)
	// rat://catalog/v1/register-table — register a NEW table so a pipeline can
	// create its own output (not only read pre-existing tables). Idempotent:
	// re-registering an existing identifier returns the existing ref (reconcile-safe,
	// no ALREADY_EXISTS). The "register" half of the create→write→register→merge loop
	// (ADR-010 / reviews/08 B1). Distinct capability from commit-table so creating a
	// new catalog entry is a separately-grantable privilege (C5 method-level authz).
	RegisterTable(ctx context.Context, in *RegisterTableRequest, opts ...grpc.CallOption) (*RegisterTableResponse, error)
	// rat://catalog/v1/commit-table — record the snapshot a format.Write produced
	// for a table on a branch (the value returned in WriteResult.snapshot_id). This
	// is the commit-LINKAGE: the catalog learns exactly what landed. Safe under
	// retry + concurrency via the SAME model as MergeBranch — `expected_snapshot`
	// optimistic-concurrency guard + `idempotency_key` (the write-leg idempotency the
	// reviews/08 B1 architect→sre cross-consult flagged). ADR-010.
	CommitTable(ctx context.Context, in *CommitTableRequest, opts ...grpc.CallOption) (*CommitTableResponse, error)
}

type catalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogServiceClient(cc grpc.ClientConnInterface) CatalogServiceClient {
	return &catalogServiceClient{cc}
}

func (c *catalogServiceClient) GetTable(ctx context.Context, in *GetTableRequest, opts ...grpc.CallOption) (*GetTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTableResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) CreateBranch(ctx context.Context, in *CreateBranchRequest, opts ...grpc.CallOption) (*CreateBranchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBranchResponse)
	err := c.cc.Invoke(ctx, CatalogService_CreateBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) MergeBranch(ctx context.Context, in *MergeBranchRequest, opts ...grpc.CallOption) (*MergeBranchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MergeBranchResponse)
	err := c.cc.Invoke(ctx, CatalogService_MergeBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) RegisterTable(ctx context.Context, in *RegisterTableRequest, opts ...grpc.CallOption) (*RegisterTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterTableResponse)
	err := c.cc.Invoke(ctx, CatalogService_RegisterTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) CommitTable(ctx context.Context, in *CommitTableRequest, opts ...grpc.CallOption) (*CommitTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitTableResponse)
	err := c.cc.Invoke(ctx, CatalogService_CommitTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServiceServer is the server API for CatalogService service.
// All implementations must embed UnimplementedCatalogServiceServer
// for forward compatibility.
type CatalogServiceServer interface {
	// rat://catalog/v1/get-table — resolve a table identifier to a TableRef
	// (physical location + current snapshot/branch).
	GetTable(context.Context, *GetTableRequest) (*GetTableResponse, error)
	// rat://catalog/v1/create-branch — open an isolated branch for a pipeline run.
	CreateBranch(context.Context, *CreateBranchRequest) (*CreateBranchResponse, error)
	// rat://catalog/v1/merge-branch — merge a completed run's branch back to main,
	// after quality tests pass (the pre-merge gate of the v2 pipeline model).
	MergeBranch(context.Context, *MergeBranchRequest) (*MergeBranchResponse, error)
	// rat://catalog/v1/register-table — register a NEW table so a pipeline can
	// create its own output (not only read pre-existing tables). Idempotent:
	// re-registering an existing identifier returns the existing ref (reconcile-safe,
	// no ALREADY_EXISTS). The "register" half of the create→write→register→merge loop
	// (ADR-010 / reviews/08 B1). Distinct capability from commit-table so creating a
	// new catalog entry is a separately-grantable privilege (C5 method-level authz).
	RegisterTable(context.Context, *RegisterTableRequest) (*RegisterTableResponse, error)
	// rat://catalog/v1/commit-table — record the snapshot a format.Write produced
	// for a table on a branch (the value returned in WriteResult.snapshot_id). This
	// is the commit-LINKAGE: the catalog learns exactly what landed. Safe under
	// retry + concurrency via the SAME model as MergeBranch — `expected_snapshot`
	// optimistic-concurrency guard + `idempotency_key` (the write-leg idempotency the
	// reviews/08 B1 architect→sre cross-consult flagged). ADR-010.
	CommitTable(context.Context, *CommitTableRequest) (*CommitTableResponse, error)
	mustEmbedUnimplementedCatalogServiceServer()
}

// UnimplementedCatalogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogServiceServer struct{}

func (UnimplementedCatalogServiceServer) GetTable(context.Context, *GetTableRequest) (*GetTableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTable not implemented")
}
func (UnimplementedCatalogServiceServer) CreateBranch(context.Context, *CreateBranchRequest) (*CreateBranchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBranch not implemented")
}
func (UnimplementedCatalogServiceServer) MergeBranch(context.Context, *MergeBranchRequest) (*MergeBranchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MergeBranch not implemented")
}
func (UnimplementedCatalogServiceServer) RegisterTable(context.Context, *RegisterTableRequest) (*RegisterTableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterTable not implemented")
}
func (UnimplementedCatalogServiceServer) CommitTable(context.Context, *CommitTableRequest) (*CommitTableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitTable not implemented")
}
func (UnimplementedCatalogServiceServer) mustEmbedUnimplementedCatalogServiceServer() {}
func (UnimplementedCatalogServiceServer) testEmbeddedByValue()                        {}

// UnsafeCatalogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogServiceServer will
// result in compilation errors.
type UnsafeCatalogServiceServer interface {
	mustEmbedUnimplementedCatalogServiceServer()
}

func RegisterCatalogServiceServer(s grpc.ServiceRegistrar, srv CatalogServiceServer) {
	// If the following call panics, it indicates UnimplementedCatalogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatalogService_ServiceDesc, srv)
}

func _CatalogService_GetTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetTable(ctx, req.(*GetTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_CreateBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).CreateBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_CreateBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).CreateBranch(ctx, req.(*CreateBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_MergeBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MergeBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).MergeBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_MergeBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).MergeBranch(ctx, req.(*MergeBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_RegisterTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).RegisterTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_RegisterTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).RegisterTable(ctx, req.(*RegisterTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_CommitTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).CommitTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_CommitTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).CommitTable(ctx, req.(*CommitTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogService_ServiceDesc is the grpc.ServiceDesc for CatalogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rat.catalog.v1.CatalogService",
	HandlerType: (*CatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTable",
			Handler:    _CatalogService_GetTable_Handler,
		},
		{
			MethodName: "CreateBranch",
			Handler:    _CatalogService_CreateBranch_Handler,
		},
		{
			MethodName: "MergeBranch",
			Handler:    _CatalogService_MergeBranch_Handler,
		},
		{
			MethodName: "RegisterTable",
			Handler:    _CatalogService_RegisterTable_Handler,
		},
		{
			MethodName: "CommitTable",
			Handler:    _CatalogService_CommitTable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rat/catalog/v1/catalog.proto",
}
