// UI (experience) axis service contract. Status: v1 (frozen — rat/1.4; ADR-003: experience = one ref + conformance).
//
// A `kind: ui` plugin (web-portal, CLI, Slack bot, VS Code extension) is an
// experience surface. The platform's multi-UI story (overview.md / Phase 5) is
// "each UI is a separate ui plugin" — so this contract is deliberately thin: a
// UI plugin mostly CONSUMES the API gateway like any other client. What the core
// needs from it is (a) discovery of what surfaces/slots it exposes, and (b) the
// ability to render contributions other plugins declare via `contributes.slots`
// in their manifest (the portal-slot mechanism — overview.md contract triple).
//
// Capability mapping:
//   rat://ui/v1/describe -> Describe (what this UI exposes + which slots it hosts)
//   rat://ui/v1/render-slot -> RenderSlot (resolve a contributed slot to render info)
//
// Slot targets are capability-shaped URIs (e.g. rat://ui/v1/pipeline-detail), the
// same ones plugins name in `contributes.slots[].target` in plugin.v1.json.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rat/ui/v1/ui.proto

package uiv1

import (
	_ "github.com/squat-collective/rat-v3/gen/rat/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_rat_ui_v1_ui_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rat_ui_v1_ui_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_rat_ui_v1_ui_proto_rawDescGZIP(), []int{0}
}

// A slot this UI can host plugin-contributed components into.
type HostedSlot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Capability-shaped slot id, e.g. "rat://ui/v1/pipeline-detail".
	Slot          string `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Description   string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostedSlot) Reset() {
	*x = HostedSlot{}
	mi := &file_rat_ui_v1_ui_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostedSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostedSlot) ProtoMessage() {}

func (x *HostedSlot) ProtoReflect() protoreflect.Message {
	mi := &file_rat_ui_v1_ui_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostedSlot.ProtoReflect.Descriptor instead.
func (*HostedSlot) Descriptor() ([]byte, []int) {
	return file_rat_ui_v1_ui_proto_rawDescGZIP(), []int{1}
}

func (x *HostedSlot) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

func (x *HostedSlot) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DescribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human label for this UI surface (e.g. "Web Portal").
	DisplayName   string        `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Slots         []*HostedSlot `protobuf:"bytes,2,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_rat_ui_v1_ui_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rat_ui_v1_ui_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_rat_ui_v1_ui_proto_rawDescGZIP(), []int{2}
}

func (x *DescribeResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *DescribeResponse) GetSlots() []*HostedSlot {
	if x != nil {
		return x.Slots
	}
	return nil
}

type RenderSlotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Slot  string                 `protobuf:"bytes,2,opt,name=slot,proto3" json:"slot,omitempty"`
	// The contributing component name (from another plugin's contributes.slots).
	Component     string `protobuf:"bytes,3,opt,name=component,proto3" json:"component,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderSlotRequest) Reset() {
	*x = RenderSlotRequest{}
	mi := &file_rat_ui_v1_ui_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderSlotRequest) ProtoMessage() {}

func (x *RenderSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rat_ui_v1_ui_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderSlotRequest.ProtoReflect.Descriptor instead.
func (*RenderSlotRequest) Descriptor() ([]byte, []int) {
	return file_rat_ui_v1_ui_proto_rawDescGZIP(), []int{3}
}

func (x *RenderSlotRequest) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

func (x *RenderSlotRequest) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

type RenderSlotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Asset reference the UI loads (e.g. a JS bundle URL or an OCI asset ref).
	AssetRef string `protobuf:"bytes,1,opt,name=asset_ref,json=assetRef,proto3" json:"asset_ref,omitempty"`
	// JSON Schema (serialized) describing the props the component accepts.
	PropsSchema   []byte `protobuf:"bytes,2,opt,name=props_schema,json=propsSchema,proto3" json:"props_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderSlotResponse) Reset() {
	*x = RenderSlotResponse{}
	mi := &file_rat_ui_v1_ui_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderSlotResponse) ProtoMessage() {}

func (x *RenderSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rat_ui_v1_ui_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderSlotResponse.ProtoReflect.Descriptor instead.
func (*RenderSlotResponse) Descriptor() ([]byte, []int) {
	return file_rat_ui_v1_ui_proto_rawDescGZIP(), []int{4}
}

func (x *RenderSlotResponse) GetAssetRef() string {
	if x != nil {
		return x.AssetRef
	}
	return ""
}

func (x *RenderSlotResponse) GetPropsSchema() []byte {
	if x != nil {
		return x.PropsSchema
	}
	return nil
}

var File_rat_ui_v1_ui_proto protoreflect.FileDescriptor

const file_rat_ui_v1_ui_proto_rawDesc = "" +
	"\n" +
	"\x12rat/ui/v1/ui.proto\x12\trat.ui.v1\x1a\x1frat/common/v1/annotations.proto\"\x17\n" +
	"\x0fDescribeRequestJ\x04\b\x01\x10\x02\"B\n" +
	"\n" +
	"HostedSlot\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\tR\x04slot\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"b\n" +
	"\x10DescribeResponse\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12+\n" +
	"\x05slots\x18\x02 \x03(\v2\x15.rat.ui.v1.HostedSlotR\x05slots\"K\n" +
	"\x11RenderSlotRequest\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\tR\x04slot\x12\x1c\n" +
	"\tcomponent\x18\x03 \x01(\tR\tcomponentJ\x04\b\x01\x10\x02\"T\n" +
	"\x12RenderSlotResponse\x12\x1b\n" +
	"\tasset_ref\x18\x01 \x01(\tR\bassetRef\x12!\n" +
	"\fprops_schema\x18\x02 \x01(\fR\vpropsSchema2\xd2\x01\n" +
	"\tUiService\x12]\n" +
	"\bDescribe\x12\x1a.rat.ui.v1.DescribeRequest\x1a\x1b.rat.ui.v1.DescribeResponse\"\x18\x8a\x97\"\x14rat://ui/v1/describe\x12f\n" +
	"\n" +
	"RenderSlot\x12\x1c.rat.ui.v1.RenderSlotRequest\x1a\x1d.rat.ui.v1.RenderSlotResponse\"\x1b\x8a\x97\"\x17rat://ui/v1/render-slotB7Z5github.com/squat-collective/rat-v3/gen/rat/ui/v1;uiv1b\x06proto3"

var (
	file_rat_ui_v1_ui_proto_rawDescOnce sync.Once
	file_rat_ui_v1_ui_proto_rawDescData []byte
)

func file_rat_ui_v1_ui_proto_rawDescGZIP() []byte {
	file_rat_ui_v1_ui_proto_rawDescOnce.Do(func() {
		file_rat_ui_v1_ui_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rat_ui_v1_ui_proto_rawDesc), len(file_rat_ui_v1_ui_proto_rawDesc)))
	})
	return file_rat_ui_v1_ui_proto_rawDescData
}

var file_rat_ui_v1_ui_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_rat_ui_v1_ui_proto_goTypes = []any{
	(*DescribeRequest)(nil),    // 0: rat.ui.v1.DescribeRequest
	(*HostedSlot)(nil),         // 1: rat.ui.v1.HostedSlot
	(*DescribeResponse)(nil),   // 2: rat.ui.v1.DescribeResponse
	(*RenderSlotRequest)(nil),  // 3: rat.ui.v1.RenderSlotRequest
	(*RenderSlotResponse)(nil), // 4: rat.ui.v1.RenderSlotResponse
}
var file_rat_ui_v1_ui_proto_depIdxs = []int32{
	1, // 0: rat.ui.v1.DescribeResponse.slots:type_name -> rat.ui.v1.HostedSlot
	0, // 1: rat.ui.v1.UiService.Describe:input_type -> rat.ui.v1.DescribeRequest
	3, // 2: rat.ui.v1.UiService.RenderSlot:input_type -> rat.ui.v1.RenderSlotRequest
	2, // 3: rat.ui.v1.UiService.Describe:output_type -> rat.ui.v1.DescribeResponse
	4, // 4: rat.ui.v1.UiService.RenderSlot:output_type -> rat.ui.v1.RenderSlotResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rat_ui_v1_ui_proto_init() }
func file_rat_ui_v1_ui_proto_init() {
	if File_rat_ui_v1_ui_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rat_ui_v1_ui_proto_rawDesc), len(file_rat_ui_v1_ui_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rat_ui_v1_ui_proto_goTypes,
		DependencyIndexes: file_rat_ui_v1_ui_proto_depIdxs,
		MessageInfos:      file_rat_ui_v1_ui_proto_msgTypes,
	}.Build()
	File_rat_ui_v1_ui_proto = out.File
	file_rat_ui_v1_ui_proto_goTypes = nil
	file_rat_ui_v1_ui_proto_depIdxs = nil
}
