// UI (experience) axis service contract. Status: v1 (frozen — rat/1.4; ADR-003: experience = one ref + conformance).
//
// A `kind: ui` plugin (web-portal, CLI, Slack bot, VS Code extension) is an
// experience surface. The platform's multi-UI story (overview.md / Phase 5) is
// "each UI is a separate ui plugin" — so this contract is deliberately thin: a
// UI plugin mostly CONSUMES the API gateway like any other client. What the core
// needs from it is (a) discovery of what surfaces/slots it exposes, and (b) the
// ability to render contributions other plugins declare via `contributes.slots`
// in their manifest (the portal-slot mechanism — overview.md contract triple).
//
// Capability mapping:
//   rat://ui/v1/describe -> Describe (what this UI exposes + which slots it hosts)
//   rat://ui/v1/render-slot -> RenderSlot (resolve a contributed slot to render info)
//
// Slot targets are capability-shaped URIs (e.g. rat://ui/v1/pipeline-detail), the
// same ones plugins name in `contributes.slots[].target` in plugin.v1.json.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: rat/ui/v1/ui.proto

package uiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UiService_Describe_FullMethodName   = "/rat.ui.v1.UiService/Describe"
	UiService_RenderSlot_FullMethodName = "/rat.ui.v1.UiService/RenderSlot"
)

// UiServiceClient is the client API for UiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UiServiceClient interface {
	// rat://ui/v1/describe — enumerate the surfaces this UI exposes and the slots
	// it can host contributions into.
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error)
	// rat://ui/v1/render-slot — given a slot + the contributing component, return
	// what the UI needs to render it (asset ref, props schema).
	RenderSlot(ctx context.Context, in *RenderSlotRequest, opts ...grpc.CallOption) (*RenderSlotResponse, error)
}

type uiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUiServiceClient(cc grpc.ClientConnInterface) UiServiceClient {
	return &uiServiceClient{cc}
}

func (c *uiServiceClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeResponse)
	err := c.cc.Invoke(ctx, UiService_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uiServiceClient) RenderSlot(ctx context.Context, in *RenderSlotRequest, opts ...grpc.CallOption) (*RenderSlotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderSlotResponse)
	err := c.cc.Invoke(ctx, UiService_RenderSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UiServiceServer is the server API for UiService service.
// All implementations must embed UnimplementedUiServiceServer
// for forward compatibility.
type UiServiceServer interface {
	// rat://ui/v1/describe — enumerate the surfaces this UI exposes and the slots
	// it can host contributions into.
	Describe(context.Context, *DescribeRequest) (*DescribeResponse, error)
	// rat://ui/v1/render-slot — given a slot + the contributing component, return
	// what the UI needs to render it (asset ref, props schema).
	RenderSlot(context.Context, *RenderSlotRequest) (*RenderSlotResponse, error)
	mustEmbedUnimplementedUiServiceServer()
}

// UnimplementedUiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUiServiceServer struct{}

func (UnimplementedUiServiceServer) Describe(context.Context, *DescribeRequest) (*DescribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedUiServiceServer) RenderSlot(context.Context, *RenderSlotRequest) (*RenderSlotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenderSlot not implemented")
}
func (UnimplementedUiServiceServer) mustEmbedUnimplementedUiServiceServer() {}
func (UnimplementedUiServiceServer) testEmbeddedByValue()                   {}

// UnsafeUiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UiServiceServer will
// result in compilation errors.
type UnsafeUiServiceServer interface {
	mustEmbedUnimplementedUiServiceServer()
}

func RegisterUiServiceServer(s grpc.ServiceRegistrar, srv UiServiceServer) {
	// If the following call panics, it indicates UnimplementedUiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UiService_ServiceDesc, srv)
}

func _UiService_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UiServiceServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UiService_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UiServiceServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UiService_RenderSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UiServiceServer).RenderSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UiService_RenderSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UiServiceServer).RenderSlot(ctx, req.(*RenderSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UiService_ServiceDesc is the grpc.ServiceDesc for UiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rat.ui.v1.UiService",
	HandlerType: (*UiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _UiService_Describe_Handler,
		},
		{
			MethodName: "RenderSlot",
			Handler:    _UiService_RenderSlot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rat/ui/v1/ui.proto",
}
