// Core daemon control service (ADR-027). The daemon's ADMIN face: it mutates the
// RUNNING plane — add/remove a plugin without a restart — and reports the live set.
//
// This is the operator counterpart to CapabilityInvokeService (invoke.proto): that
// service is the DATA plane (a plugin calls a capability it `requires`, C5-gated);
// this is the CONTROL plane (an operator adds/removes plugins). They are deliberately
// SEPARATE services with different authorization: capability-invocation is authorized
// from the caller's manifest `requires` (C5), whereas control is an OPERATOR action —
// `rat add` is a CLI, not a plugin with a manifest — so it does not flow through C5.
// In v1 the control listener's REACHABILITY is the authorization: a per-project unix
// socket (.rat/daemon.sock, ADR-023) means filesystem permissions gate who may
// register, exactly as they gate `rat down`. Operator identity + mTLS for a networked
// (TCP) control endpoint is deferred (ADR-027 Q01).
//
// This stays within the six-thing core: it mutates the Registry and exposes an admin
// RPC on the API gateway — two EXISTING responsibilities — and reuses the reconciler's
// unchanged convergence (it only makes the desired SET mutable). No 7th core thing.
//
// Status: v1 additive (ADR-027; bound by the ADR-017 pre-unfreeze gate). Core↔operator,
// not a plugin contract.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rat/core/v1/control.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LaunchSpec is how a plugin is launched (the subset rat.toml carries). An empty image
// means a REGISTER-ONLY driver (an operator identity that dials the gateway but is not
// itself launched), mirroring a rat.toml [[plugin]] with no image.
type LaunchSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OCI image ref. Empty = a register-only driver (no launch).
	Image string `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	// Isolation profile shorthand (e.g. "i9"); the daemon maps it to a full profile, the
	// same mapping rat.toml uses. Empty defaults to the hardened profile.
	Isolation string `protobuf:"bytes,2,opt,name=isolation,proto3" json:"isolation,omitempty"`
	// Launch environment. NEVER secrets — only opaque refs (the *_REF convention); the
	// secret-backend resolves them at first use (ADR-022).
	Env           map[string]string `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchSpec) Reset() {
	*x = LaunchSpec{}
	mi := &file_rat_core_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchSpec) ProtoMessage() {}

func (x *LaunchSpec) ProtoReflect() protoreflect.Message {
	mi := &file_rat_core_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchSpec.ProtoReflect.Descriptor instead.
func (*LaunchSpec) Descriptor() ([]byte, []int) {
	return file_rat_core_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *LaunchSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *LaunchSpec) GetIsolation() string {
	if x != nil {
		return x.Isolation
	}
	return ""
}

func (x *LaunchSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

// RegisterPluginRequest adds one plugin to the running plane.
type RegisterPluginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The plugin's instance name in this plane (the key `rat remove` / Deregister uses).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The plugin's manifest as raw YAML (the frozen plugin.v1 shape). The daemon parses +
	// validates it; its kind + provides/requires are what the registry authorizes from.
	// Carried as bytes so the manifest stays YAML end to end (no proto schema dup).
	ManifestYaml []byte `protobuf:"bytes,2,opt,name=manifest_yaml,json=manifestYaml,proto3" json:"manifest_yaml,omitempty"`
	// How to launch it. Absent (or empty image) = a register-only driver.
	Launch        *LaunchSpec `protobuf:"bytes,3,opt,name=launch,proto3" json:"launch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPluginRequest) Reset() {
	*x = RegisterPluginRequest{}
	mi := &file_rat_core_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPluginRequest) ProtoMessage() {}

func (x *RegisterPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rat_core_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPluginRequest.ProtoReflect.Descriptor instead.
func (*RegisterPluginRequest) Descriptor() ([]byte, []int) {
	return file_rat_core_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterPluginRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterPluginRequest) GetManifestYaml() []byte {
	if x != nil {
		return x.ManifestYaml
	}
	return nil
}

func (x *RegisterPluginRequest) GetLaunch() *LaunchSpec {
	if x != nil {
		return x.Launch
	}
	return nil
}

// RegisterPluginResponse reports the plugin's live state after the daemon materialized it.
type RegisterPluginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The plugin name, echoed.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The reconcile state after materialize (e.g. "Healthy"). A driver with no launch is
	// reported as registered without a health probe.
	State string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// Where the gateway bound the plugin (its routable endpoint); empty for a driver.
	Endpoint      string `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPluginResponse) Reset() {
	*x = RegisterPluginResponse{}
	mi := &file_rat_core_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPluginResponse) ProtoMessage() {}

func (x *RegisterPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rat_core_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPluginResponse.ProtoReflect.Descriptor instead.
func (*RegisterPluginResponse) Descriptor() ([]byte, []int) {
	return file_rat_core_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterPluginResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterPluginResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *RegisterPluginResponse) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

// DeregisterPluginRequest removes one plugin from the running plane by name.
type DeregisterPluginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The plugin instance name to remove.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterPluginRequest) Reset() {
	*x = DeregisterPluginRequest{}
	mi := &file_rat_core_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterPluginRequest) ProtoMessage() {}

func (x *DeregisterPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rat_core_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterPluginRequest.ProtoReflect.Descriptor instead.
func (*DeregisterPluginRequest) Descriptor() ([]byte, []int) {
	return file_rat_core_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *DeregisterPluginRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// DeregisterPluginResponse confirms the removal.
type DeregisterPluginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The plugin name, echoed.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Whether the plugin was actually present in the running plane (false = no-op).
	WasPresent    bool `protobuf:"varint,2,opt,name=was_present,json=wasPresent,proto3" json:"was_present,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterPluginResponse) Reset() {
	*x = DeregisterPluginResponse{}
	mi := &file_rat_core_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterPluginResponse) ProtoMessage() {}

func (x *DeregisterPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rat_core_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterPluginResponse.ProtoReflect.Descriptor instead.
func (*DeregisterPluginResponse) Descriptor() ([]byte, []int) {
	return file_rat_core_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *DeregisterPluginResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeregisterPluginResponse) GetWasPresent() bool {
	if x != nil {
		return x.WasPresent
	}
	return false
}

// ListPluginsRequest asks for the live plane (no parameters in v1).
type ListPluginsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsRequest) Reset() {
	*x = ListPluginsRequest{}
	mi := &file_rat_core_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsRequest) ProtoMessage() {}

func (x *ListPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rat_core_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsRequest.ProtoReflect.Descriptor instead.
func (*ListPluginsRequest) Descriptor() ([]byte, []int) {
	return file_rat_core_v1_control_proto_rawDescGZIP(), []int{5}
}

// ListPluginsResponse is the live plane as the daemon sees it.
type ListPluginsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One entry per plugin currently known to the running daemon.
	Plugins       []*PluginStatus `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsResponse) Reset() {
	*x = ListPluginsResponse{}
	mi := &file_rat_core_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsResponse) ProtoMessage() {}

func (x *ListPluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rat_core_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsResponse.ProtoReflect.Descriptor instead.
func (*ListPluginsResponse) Descriptor() ([]byte, []int) {
	return file_rat_core_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *ListPluginsResponse) GetPlugins() []*PluginStatus {
	if x != nil {
		return x.Plugins
	}
	return nil
}

// PluginStatus is one plugin's live state in the running plane.
type PluginStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The plugin instance name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The plugin's manifest kind (the axis it implements).
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// The reconcile state (e.g. "Healthy", "Launching", "Degraded"); "registered" for a
	// register-only driver with no health probe.
	State string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	// The plugin's routable endpoint, if bound; empty for a driver or a not-yet-Healthy
	// plugin.
	Endpoint string `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// The capability URIs this plugin provides (from its manifest).
	Provides      []string `protobuf:"bytes,5,rep,name=provides,proto3" json:"provides,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginStatus) Reset() {
	*x = PluginStatus{}
	mi := &file_rat_core_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginStatus) ProtoMessage() {}

func (x *PluginStatus) ProtoReflect() protoreflect.Message {
	mi := &file_rat_core_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginStatus.ProtoReflect.Descriptor instead.
func (*PluginStatus) Descriptor() ([]byte, []int) {
	return file_rat_core_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *PluginStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginStatus) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PluginStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *PluginStatus) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *PluginStatus) GetProvides() []string {
	if x != nil {
		return x.Provides
	}
	return nil
}

var File_rat_core_v1_control_proto protoreflect.FileDescriptor

const file_rat_core_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x19rat/core/v1/control.proto\x12\vrat.core.v1\"\xac\x01\n" +
	"\n" +
	"LaunchSpec\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x1c\n" +
	"\tisolation\x18\x02 \x01(\tR\tisolation\x122\n" +
	"\x03env\x18\x03 \x03(\v2 .rat.core.v1.LaunchSpec.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x01\n" +
	"\x15RegisterPluginRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rmanifest_yaml\x18\x02 \x01(\fR\fmanifestYaml\x12/\n" +
	"\x06launch\x18\x03 \x01(\v2\x17.rat.core.v1.LaunchSpecR\x06launch\"^\n" +
	"\x16RegisterPluginResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\"-\n" +
	"\x17DeregisterPluginRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"O\n" +
	"\x18DeregisterPluginResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vwas_present\x18\x02 \x01(\bR\n" +
	"wasPresent\"\x14\n" +
	"\x12ListPluginsRequest\"J\n" +
	"\x13ListPluginsResponse\x123\n" +
	"\aplugins\x18\x01 \x03(\v2\x19.rat.core.v1.PluginStatusR\aplugins\"\x84\x01\n" +
	"\fPluginStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\x12\x1a\n" +
	"\bprovides\x18\x05 \x03(\tR\bprovides2\x9e\x02\n" +
	"\x0eControlService\x12Y\n" +
	"\x0eRegisterPlugin\x12\".rat.core.v1.RegisterPluginRequest\x1a#.rat.core.v1.RegisterPluginResponse\x12_\n" +
	"\x10DeregisterPlugin\x12$.rat.core.v1.DeregisterPluginRequest\x1a%.rat.core.v1.DeregisterPluginResponse\x12P\n" +
	"\vListPlugins\x12\x1f.rat.core.v1.ListPluginsRequest\x1a .rat.core.v1.ListPluginsResponseB0Z.github.com/le-squat/rat/gen/rat/core/v1;corev1b\x06proto3"

var (
	file_rat_core_v1_control_proto_rawDescOnce sync.Once
	file_rat_core_v1_control_proto_rawDescData []byte
)

func file_rat_core_v1_control_proto_rawDescGZIP() []byte {
	file_rat_core_v1_control_proto_rawDescOnce.Do(func() {
		file_rat_core_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rat_core_v1_control_proto_rawDesc), len(file_rat_core_v1_control_proto_rawDesc)))
	})
	return file_rat_core_v1_control_proto_rawDescData
}

var file_rat_core_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_rat_core_v1_control_proto_goTypes = []any{
	(*LaunchSpec)(nil),               // 0: rat.core.v1.LaunchSpec
	(*RegisterPluginRequest)(nil),    // 1: rat.core.v1.RegisterPluginRequest
	(*RegisterPluginResponse)(nil),   // 2: rat.core.v1.RegisterPluginResponse
	(*DeregisterPluginRequest)(nil),  // 3: rat.core.v1.DeregisterPluginRequest
	(*DeregisterPluginResponse)(nil), // 4: rat.core.v1.DeregisterPluginResponse
	(*ListPluginsRequest)(nil),       // 5: rat.core.v1.ListPluginsRequest
	(*ListPluginsResponse)(nil),      // 6: rat.core.v1.ListPluginsResponse
	(*PluginStatus)(nil),             // 7: rat.core.v1.PluginStatus
	nil,                              // 8: rat.core.v1.LaunchSpec.EnvEntry
}
var file_rat_core_v1_control_proto_depIdxs = []int32{
	8, // 0: rat.core.v1.LaunchSpec.env:type_name -> rat.core.v1.LaunchSpec.EnvEntry
	0, // 1: rat.core.v1.RegisterPluginRequest.launch:type_name -> rat.core.v1.LaunchSpec
	7, // 2: rat.core.v1.ListPluginsResponse.plugins:type_name -> rat.core.v1.PluginStatus
	1, // 3: rat.core.v1.ControlService.RegisterPlugin:input_type -> rat.core.v1.RegisterPluginRequest
	3, // 4: rat.core.v1.ControlService.DeregisterPlugin:input_type -> rat.core.v1.DeregisterPluginRequest
	5, // 5: rat.core.v1.ControlService.ListPlugins:input_type -> rat.core.v1.ListPluginsRequest
	2, // 6: rat.core.v1.ControlService.RegisterPlugin:output_type -> rat.core.v1.RegisterPluginResponse
	4, // 7: rat.core.v1.ControlService.DeregisterPlugin:output_type -> rat.core.v1.DeregisterPluginResponse
	6, // 8: rat.core.v1.ControlService.ListPlugins:output_type -> rat.core.v1.ListPluginsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rat_core_v1_control_proto_init() }
func file_rat_core_v1_control_proto_init() {
	if File_rat_core_v1_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rat_core_v1_control_proto_rawDesc), len(file_rat_core_v1_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rat_core_v1_control_proto_goTypes,
		DependencyIndexes: file_rat_core_v1_control_proto_depIdxs,
		MessageInfos:      file_rat_core_v1_control_proto_msgTypes,
	}.Build()
	File_rat_core_v1_control_proto = out.File
	file_rat_core_v1_control_proto_goTypes = nil
	file_rat_core_v1_control_proto_depIdxs = nil
}
