// Core capability-invoke service. DRAFT — freeze-blocker #6.
//
// This is the wire artifact ADR-005 requires and reviews/06 C-6 (AUTH-2 ⊕
// ARCH-2) flagged as missing: the mechanism by which a plugin actually CALLS a
// capability it `requires`. Before this, "the core wires providers in via the
// registry" was asserted in comments with no wire mechanism — the headline
// call-by-capability feature was unbuildable.
//
// MODEL — CORE-MEDIATED (ADR-005). A plugin does NOT dial providers directly.
// It calls Invoke on the core's API gateway with a capability URI + the
// already-serialized request for the target axis method. The core:
//   1. resolves the capability URI -> concrete provider via the registry,
//   2. enforces the cross-cutting properties on this hop — C2 (caller
//      authenticated), C5 (caller's manifest `requires` this capability AND the
//      provider `provides` it; the capability⇄method binding comes from the
//      (rat.common.v1.capability) method option, freeze-blocker #5),
//      C7 (tenant scoping), C3 (state-namespace derivation),
//   3. stamps/propagates C1 trace + re-derives identity.caller_plugin for the
//      downstream hop (keystone, context.proto), and emits the C8 audit record,
//   4. proxies `payload` to the provider's method and relays its response.
//
// GENERIC PROXY: the gateway routes by `capability` and forwards `payload`
// WITHOUT interpreting it — it gains no per-axis knowledge, so the six-thing core
// stays minimal (no 7th thing; this is the API gateway + registry doing their
// existing jobs). `payload` is the serialized axis request message (e.g. a
// rat.format.v1.MergeRequest); `result` is the serialized axis response.
//
// NOT here: the bulk-data path. Per "data plane bypasses core for bytes"
// (overview.md), Arrow byte transfer still flows plugin-to-plugin via
// common/v1/data.proto ArrowStream and never traverses this service — Invoke
// carries only control RPCs (refs, metadata, stream descriptors).
//
// Status: DRAFT (pre-freeze). Must exist in the frozen rat/1 surface.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rat/core/v1/invoke.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvokeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The capability being invoked, e.g. "rat://format/v1/merge". MUST match the
	// rat://<axis>/v<major>/<capability> grammar. The core resolves this to a
	// concrete provider + method via the registry + the (rat.common.v1.capability)
	// method annotation, and checks the caller's manifest `requires` it.
	Capability string `protobuf:"bytes,2,opt,name=capability,proto3" json:"capability,omitempty"`
	// The serialized request message for the target axis method (e.g. an encoded
	// rat.format.v1.MergeRequest). Opaque to the core — routed, not interpreted.
	// The target method is determined by `capability`, so the message type is
	// implied by the capability, not carried here.
	Payload       []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_rat_core_v1_invoke_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rat_core_v1_invoke_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_rat_core_v1_invoke_proto_rawDescGZIP(), []int{0}
}

func (x *InvokeRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *InvokeRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type InvokeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The serialized response message from the provider's method (e.g. an encoded
	// rat.format.v1.MergeResponse). Opaque to the core.
	//
	// Note: this contract returns the provider's success payload; failures surface
	// via gRPC status (transport/enforcement) per the error-model convention
	// (reviews/06 C-5, freeze-blocker #9). Capability-not-found, caller-not-
	// -authorized, and provider-unavailable are core-side enforcement failures
	// returned as gRPC status codes, not as a field here.
	Result        []byte `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_rat_core_v1_invoke_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rat_core_v1_invoke_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_rat_core_v1_invoke_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_rat_core_v1_invoke_proto protoreflect.FileDescriptor

const file_rat_core_v1_invoke_proto_rawDesc = "" +
	"\n" +
	"\x18rat/core/v1/invoke.proto\x12\vrat.core.v1\"O\n" +
	"\rInvokeRequest\x12\x1e\n" +
	"\n" +
	"capability\x18\x02 \x01(\tR\n" +
	"capability\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayloadJ\x04\b\x01\x10\x02\"(\n" +
	"\x0eInvokeResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result2\\\n" +
	"\x17CapabilityInvokeService\x12A\n" +
	"\x06Invoke\x12\x1a.rat.core.v1.InvokeRequest\x1a\x1b.rat.core.v1.InvokeResponseB/Z-github.com/rat-dev/rat/gen/rat/core/v1;corev1b\x06proto3"

var (
	file_rat_core_v1_invoke_proto_rawDescOnce sync.Once
	file_rat_core_v1_invoke_proto_rawDescData []byte
)

func file_rat_core_v1_invoke_proto_rawDescGZIP() []byte {
	file_rat_core_v1_invoke_proto_rawDescOnce.Do(func() {
		file_rat_core_v1_invoke_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rat_core_v1_invoke_proto_rawDesc), len(file_rat_core_v1_invoke_proto_rawDesc)))
	})
	return file_rat_core_v1_invoke_proto_rawDescData
}

var file_rat_core_v1_invoke_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rat_core_v1_invoke_proto_goTypes = []any{
	(*InvokeRequest)(nil),  // 0: rat.core.v1.InvokeRequest
	(*InvokeResponse)(nil), // 1: rat.core.v1.InvokeResponse
}
var file_rat_core_v1_invoke_proto_depIdxs = []int32{
	0, // 0: rat.core.v1.CapabilityInvokeService.Invoke:input_type -> rat.core.v1.InvokeRequest
	1, // 1: rat.core.v1.CapabilityInvokeService.Invoke:output_type -> rat.core.v1.InvokeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rat_core_v1_invoke_proto_init() }
func file_rat_core_v1_invoke_proto_init() {
	if File_rat_core_v1_invoke_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rat_core_v1_invoke_proto_rawDesc), len(file_rat_core_v1_invoke_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rat_core_v1_invoke_proto_goTypes,
		DependencyIndexes: file_rat_core_v1_invoke_proto_depIdxs,
		MessageInfos:      file_rat_core_v1_invoke_proto_msgTypes,
	}.Build()
	File_rat_core_v1_invoke_proto = out.File
	file_rat_core_v1_invoke_proto_goTypes = nil
	file_rat_core_v1_invoke_proto_depIdxs = nil
}
