// Core capability-invoke service. Status: v1 (frozen — rat/1, ADR-009).
//
// This is the wire artifact ADR-005 requires and reviews/06 C-6 (AUTH-2 ⊕
// ARCH-2) flagged as missing: the mechanism by which a plugin actually CALLS a
// capability it `requires`. Before this, "the core wires providers in via the
// registry" was asserted in comments with no wire mechanism — the headline
// call-by-capability feature was unbuildable.
//
// MODEL — CORE-MEDIATED (ADR-005). A plugin does NOT dial providers directly.
// It calls Invoke on the core's API gateway with a capability URI + the
// already-serialized request for the target axis method. The core:
//   1. resolves the capability URI -> concrete provider via the registry,
//   2. enforces the cross-cutting properties on this hop — C2 (caller
//      authenticated), C5 (caller's manifest `requires` this capability AND the
//      provider `provides` it; the capability⇄method binding comes from the
//      (rat.common.v1.capability) method option, freeze-blocker #5),
//      C7 (tenant scoping), C3 (state-namespace derivation),
//   3. stamps/propagates C1 trace + re-derives identity.caller_plugin for the
//      downstream hop (keystone, context.proto), and emits the C8 audit record,
//   4. proxies `payload` to the provider's method and relays its response.
//
// GENERIC PROXY: the gateway routes by `capability` and forwards `payload`
// WITHOUT interpreting it — it gains no per-axis knowledge, so the six-thing core
// stays minimal (no 7th thing; this is the API gateway + registry doing their
// existing jobs). `payload` is the serialized axis request message (e.g. a
// rat.format.v1.MergeRequest); `result` is the serialized axis response.
//
// NOT here: the bulk-data path. Per "data plane bypasses core for bytes"
// (overview.md), Arrow byte transfer still flows plugin-to-plugin via
// common/v1/data.proto ArrowStream and never traverses this service — Invoke
// carries only control RPCs (refs, metadata, stream descriptors).
//
// Status: v1 (frozen — rat/1, ADR-009). The frozen capability-invoke surface.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rat/core/v1/invoke.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvokeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The capability being invoked, e.g. "rat://format/v1/merge". MUST match the
	// rat://<axis>/v<major>/<capability> grammar. The core resolves this to a
	// concrete provider + method via the registry + the (rat.common.v1.capability)
	// method annotation, and checks the caller's manifest `requires` it.
	Capability string `protobuf:"bytes,2,opt,name=capability,proto3" json:"capability,omitempty"`
	// The serialized request message for the target axis method (e.g. an encoded
	// rat.format.v1.MergeRequest). Opaque to the core — routed, not interpreted.
	// The target method is determined by `capability`, so the message type is
	// implied by the capability, not carried here.
	Payload       []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_rat_core_v1_invoke_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rat_core_v1_invoke_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_rat_core_v1_invoke_proto_rawDescGZIP(), []int{0}
}

func (x *InvokeRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *InvokeRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type InvokeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The serialized response message from the provider's method (e.g. an encoded
	// rat.format.v1.MergeResponse). Opaque to the core.
	//
	// Note: this contract returns the provider's success payload; failures surface
	// via gRPC status (transport/enforcement) per the canonical error model
	// ([common/v1/ERROR_MODEL.md], pinned at rat/1). Capability-not-authorized
	// (PERMISSION_DENIED), provider-unavailable (UNAVAILABLE), and unauthenticated
	// caller (UNAUTHENTICATED) are core-side enforcement failures returned as those
	// gRPC status codes, not as a field here.
	Result        []byte `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_rat_core_v1_invoke_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rat_core_v1_invoke_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_rat_core_v1_invoke_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type InvokeServerStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The capability being invoked; same grammar + resolution as InvokeRequest. Must
	// resolve to a server-streaming provider method.
	Capability string `protobuf:"bytes,2,opt,name=capability,proto3" json:"capability,omitempty"`
	// The serialized request message for the target method (e.g. an encoded
	// rat.runtime.v1.ExecuteRequest). Opaque to the core.
	Payload       []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeServerStreamRequest) Reset() {
	*x = InvokeServerStreamRequest{}
	mi := &file_rat_core_v1_invoke_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeServerStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeServerStreamRequest) ProtoMessage() {}

func (x *InvokeServerStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rat_core_v1_invoke_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeServerStreamRequest.ProtoReflect.Descriptor instead.
func (*InvokeServerStreamRequest) Descriptor() ([]byte, []int) {
	return file_rat_core_v1_invoke_proto_rawDescGZIP(), []int{2}
}

func (x *InvokeServerStreamRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *InvokeServerStreamRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type InvokeServerStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One serialized axis response frame (e.g. an encoded
	// rat.runtime.v1.ExecuteResponse). Opaque to the core; relayed verbatim.
	// Failures surface via gRPC status, not a field here.
	Result        []byte `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeServerStreamResponse) Reset() {
	*x = InvokeServerStreamResponse{}
	mi := &file_rat_core_v1_invoke_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeServerStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeServerStreamResponse) ProtoMessage() {}

func (x *InvokeServerStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rat_core_v1_invoke_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeServerStreamResponse.ProtoReflect.Descriptor instead.
func (*InvokeServerStreamResponse) Descriptor() ([]byte, []int) {
	return file_rat_core_v1_invoke_proto_rawDescGZIP(), []int{3}
}

func (x *InvokeServerStreamResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type InvokeBidiStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Set on the FIRST frame only to establish + authorize the call; MUST be empty
	// on subsequent frames. A non-empty `capability` on a non-first frame is a
	// protocol violation — the core ABORTS the stream with INVALID_ARGUMENT (S2,
	// reviews/07: "ignored" would let a client attempt a silent mid-stream capability
	// switch; reject it, never tolerate it).
	Capability string `protobuf:"bytes,2,opt,name=capability,proto3" json:"capability,omitempty"`
	// One serialized axis request frame. Opaque to the core.
	Payload       []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeBidiStreamRequest) Reset() {
	*x = InvokeBidiStreamRequest{}
	mi := &file_rat_core_v1_invoke_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeBidiStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeBidiStreamRequest) ProtoMessage() {}

func (x *InvokeBidiStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rat_core_v1_invoke_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeBidiStreamRequest.ProtoReflect.Descriptor instead.
func (*InvokeBidiStreamRequest) Descriptor() ([]byte, []int) {
	return file_rat_core_v1_invoke_proto_rawDescGZIP(), []int{4}
}

func (x *InvokeBidiStreamRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *InvokeBidiStreamRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type InvokeBidiStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One serialized axis response frame. Opaque to the core; relayed verbatim.
	Result        []byte `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeBidiStreamResponse) Reset() {
	*x = InvokeBidiStreamResponse{}
	mi := &file_rat_core_v1_invoke_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeBidiStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeBidiStreamResponse) ProtoMessage() {}

func (x *InvokeBidiStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rat_core_v1_invoke_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeBidiStreamResponse.ProtoReflect.Descriptor instead.
func (*InvokeBidiStreamResponse) Descriptor() ([]byte, []int) {
	return file_rat_core_v1_invoke_proto_rawDescGZIP(), []int{5}
}

func (x *InvokeBidiStreamResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_rat_core_v1_invoke_proto protoreflect.FileDescriptor

const file_rat_core_v1_invoke_proto_rawDesc = "" +
	"\n" +
	"\x18rat/core/v1/invoke.proto\x12\vrat.core.v1\"O\n" +
	"\rInvokeRequest\x12\x1e\n" +
	"\n" +
	"capability\x18\x02 \x01(\tR\n" +
	"capability\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayloadJ\x04\b\x01\x10\x02\"(\n" +
	"\x0eInvokeResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\"[\n" +
	"\x19InvokeServerStreamRequest\x12\x1e\n" +
	"\n" +
	"capability\x18\x02 \x01(\tR\n" +
	"capability\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayloadJ\x04\b\x01\x10\x02\"4\n" +
	"\x1aInvokeServerStreamResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\"Y\n" +
	"\x17InvokeBidiStreamRequest\x12\x1e\n" +
	"\n" +
	"capability\x18\x02 \x01(\tR\n" +
	"capability\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayloadJ\x04\b\x01\x10\x02\"2\n" +
	"\x18InvokeBidiStreamResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result2\xaa\x02\n" +
	"\x17CapabilityInvokeService\x12A\n" +
	"\x06Invoke\x12\x1a.rat.core.v1.InvokeRequest\x1a\x1b.rat.core.v1.InvokeResponse\x12g\n" +
	"\x12InvokeServerStream\x12&.rat.core.v1.InvokeServerStreamRequest\x1a'.rat.core.v1.InvokeServerStreamResponse0\x01\x12c\n" +
	"\x10InvokeBidiStream\x12$.rat.core.v1.InvokeBidiStreamRequest\x1a%.rat.core.v1.InvokeBidiStreamResponse(\x010\x01B;Z9github.com/squat-collective/rat-v3/gen/rat/core/v1;corev1b\x06proto3"

var (
	file_rat_core_v1_invoke_proto_rawDescOnce sync.Once
	file_rat_core_v1_invoke_proto_rawDescData []byte
)

func file_rat_core_v1_invoke_proto_rawDescGZIP() []byte {
	file_rat_core_v1_invoke_proto_rawDescOnce.Do(func() {
		file_rat_core_v1_invoke_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rat_core_v1_invoke_proto_rawDesc), len(file_rat_core_v1_invoke_proto_rawDesc)))
	})
	return file_rat_core_v1_invoke_proto_rawDescData
}

var file_rat_core_v1_invoke_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rat_core_v1_invoke_proto_goTypes = []any{
	(*InvokeRequest)(nil),              // 0: rat.core.v1.InvokeRequest
	(*InvokeResponse)(nil),             // 1: rat.core.v1.InvokeResponse
	(*InvokeServerStreamRequest)(nil),  // 2: rat.core.v1.InvokeServerStreamRequest
	(*InvokeServerStreamResponse)(nil), // 3: rat.core.v1.InvokeServerStreamResponse
	(*InvokeBidiStreamRequest)(nil),    // 4: rat.core.v1.InvokeBidiStreamRequest
	(*InvokeBidiStreamResponse)(nil),   // 5: rat.core.v1.InvokeBidiStreamResponse
}
var file_rat_core_v1_invoke_proto_depIdxs = []int32{
	0, // 0: rat.core.v1.CapabilityInvokeService.Invoke:input_type -> rat.core.v1.InvokeRequest
	2, // 1: rat.core.v1.CapabilityInvokeService.InvokeServerStream:input_type -> rat.core.v1.InvokeServerStreamRequest
	4, // 2: rat.core.v1.CapabilityInvokeService.InvokeBidiStream:input_type -> rat.core.v1.InvokeBidiStreamRequest
	1, // 3: rat.core.v1.CapabilityInvokeService.Invoke:output_type -> rat.core.v1.InvokeResponse
	3, // 4: rat.core.v1.CapabilityInvokeService.InvokeServerStream:output_type -> rat.core.v1.InvokeServerStreamResponse
	5, // 5: rat.core.v1.CapabilityInvokeService.InvokeBidiStream:output_type -> rat.core.v1.InvokeBidiStreamResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rat_core_v1_invoke_proto_init() }
func file_rat_core_v1_invoke_proto_init() {
	if File_rat_core_v1_invoke_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rat_core_v1_invoke_proto_rawDesc), len(file_rat_core_v1_invoke_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rat_core_v1_invoke_proto_goTypes,
		DependencyIndexes: file_rat_core_v1_invoke_proto_depIdxs,
		MessageInfos:      file_rat_core_v1_invoke_proto_msgTypes,
	}.Build()
	File_rat_core_v1_invoke_proto = out.File
	file_rat_core_v1_invoke_proto_goTypes = nil
	file_rat_core_v1_invoke_proto_depIdxs = nil
}
