// Deployment-runtime axis service contract. DRAFT — sub-phase 0b.
//
// A `kind: deployment-runtime` plugin (local-process, docker, podman, k8s,
// nomad, lambda, fargate) is WHERE PLUGINS RUN. Distinct from `runtime` (where
// data-plane WORK runs). This is a TIER-0 plugin (bootstrap-critical, selected
// at boot — plugin-architecture.md): the core needs one to launch any other
// out-of-process plugin.
//
// Capability mapping:
//   rat://deployment-runtime/v1/launch    -> Launch
//   rat://deployment-runtime/v1/terminate -> Terminate
//   rat://deployment-runtime/v1/healthcheck -> Healthcheck
//
// SECURITY (reviews/04 I9 — minimum isolation profile): a deployment-runtime
// MUST honor the IsolationProfile (non-root, cap_drop ALL, no-new-privileges,
// read-only FS, blocked metadata egress). The profile is part of the LaunchSpec
// so it is contract, not convention — a runtime that ignores it fails conformance.
// This is the trust boundary the whole "install many 3rd-party plugins" bet leans
// on (reviews/01), so it is wire-level, not a deployment nicety.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rat/deploymentruntime/v1/deployment_runtime.proto

package deploymentruntimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_HEALTH_STATUS_HEALTHY     HealthStatus = 1
	HealthStatus_HEALTH_STATUS_UNHEALTHY   HealthStatus = 2
	HealthStatus_HEALTH_STATUS_UNKNOWN     HealthStatus = 3
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_HEALTHY",
		2: "HEALTH_STATUS_UNHEALTHY",
		3: "HEALTH_STATUS_UNKNOWN",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_HEALTHY":     1,
		"HEALTH_STATUS_UNHEALTHY":   2,
		"HEALTH_STATUS_UNKNOWN":     3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rat_deploymentruntime_v1_deployment_runtime_proto_enumTypes[0].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_rat_deploymentruntime_v1_deployment_runtime_proto_enumTypes[0]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_rat_deploymentruntime_v1_deployment_runtime_proto_rawDescGZIP(), []int{0}
}

// K8s-shaped resource asks, mirroring the manifest `resources` block (C4).
type ResourceQuantities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           string                 `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`       // e.g. "500m"
	Memory        string                 `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"` // e.g. "512Mi"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceQuantities) Reset() {
	*x = ResourceQuantities{}
	mi := &file_rat_deploymentruntime_v1_deployment_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceQuantities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceQuantities) ProtoMessage() {}

func (x *ResourceQuantities) ProtoReflect() protoreflect.Message {
	mi := &file_rat_deploymentruntime_v1_deployment_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceQuantities.ProtoReflect.Descriptor instead.
func (*ResourceQuantities) Descriptor() ([]byte, []int) {
	return file_rat_deploymentruntime_v1_deployment_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceQuantities) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *ResourceQuantities) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

// I9 minimum isolation profile — contract, not convention.
type IsolationProfile struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RunAsNonRoot        bool                   `protobuf:"varint,1,opt,name=run_as_non_root,json=runAsNonRoot,proto3" json:"run_as_non_root,omitempty"`
	DropAllCapabilities bool                   `protobuf:"varint,2,opt,name=drop_all_capabilities,json=dropAllCapabilities,proto3" json:"drop_all_capabilities,omitempty"`
	NoNewPrivileges     bool                   `protobuf:"varint,3,opt,name=no_new_privileges,json=noNewPrivileges,proto3" json:"no_new_privileges,omitempty"`
	ReadOnlyRootFs      bool                   `protobuf:"varint,4,opt,name=read_only_root_fs,json=readOnlyRootFs,proto3" json:"read_only_root_fs,omitempty"`
	// Block egress to cloud metadata endpoints (e.g. 169.254.169.254).
	BlockMetadataEgress bool `protobuf:"varint,5,opt,name=block_metadata_egress,json=blockMetadataEgress,proto3" json:"block_metadata_egress,omitempty"`
	// Optional seccomp profile name (empty == runtime default, which must be at
	// least "RuntimeDefault"-equivalent).
	SeccompProfile string `protobuf:"bytes,6,opt,name=seccomp_profile,json=seccompProfile,proto3" json:"seccomp_profile,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IsolationProfile) Reset() {
	*x = IsolationProfile{}
	mi := &file_rat_deploymentruntime_v1_deployment_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsolationProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsolationProfile) ProtoMessage() {}

func (x *IsolationProfile) ProtoReflect() protoreflect.Message {
	mi := &file_rat_deploymentruntime_v1_deployment_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsolationProfile.ProtoReflect.Descriptor instead.
func (*IsolationProfile) Descriptor() ([]byte, []int) {
	return file_rat_deploymentruntime_v1_deployment_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *IsolationProfile) GetRunAsNonRoot() bool {
	if x != nil {
		return x.RunAsNonRoot
	}
	return false
}

func (x *IsolationProfile) GetDropAllCapabilities() bool {
	if x != nil {
		return x.DropAllCapabilities
	}
	return false
}

func (x *IsolationProfile) GetNoNewPrivileges() bool {
	if x != nil {
		return x.NoNewPrivileges
	}
	return false
}

func (x *IsolationProfile) GetReadOnlyRootFs() bool {
	if x != nil {
		return x.ReadOnlyRootFs
	}
	return false
}

func (x *IsolationProfile) GetBlockMetadataEgress() bool {
	if x != nil {
		return x.BlockMetadataEgress
	}
	return false
}

func (x *IsolationProfile) GetSeccompProfile() string {
	if x != nil {
		return x.SeccompProfile
	}
	return ""
}

type LaunchSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OCI image reference for the plugin.
	Image     string              `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Requests  *ResourceQuantities `protobuf:"bytes,2,opt,name=requests,proto3" json:"requests,omitempty"`
	Limits    *ResourceQuantities `protobuf:"bytes,3,opt,name=limits,proto3" json:"limits,omitempty"`
	Isolation *IsolationProfile   `protobuf:"bytes,4,opt,name=isolation,proto3" json:"isolation,omitempty"`
	// Environment the plugin needs (NEVER secrets — those come via secret-backend).
	Env           map[string]string `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchSpec) Reset() {
	*x = LaunchSpec{}
	mi := &file_rat_deploymentruntime_v1_deployment_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchSpec) ProtoMessage() {}

func (x *LaunchSpec) ProtoReflect() protoreflect.Message {
	mi := &file_rat_deploymentruntime_v1_deployment_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchSpec.ProtoReflect.Descriptor instead.
func (*LaunchSpec) Descriptor() ([]byte, []int) {
	return file_rat_deploymentruntime_v1_deployment_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *LaunchSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *LaunchSpec) GetRequests() *ResourceQuantities {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *LaunchSpec) GetLimits() *ResourceQuantities {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *LaunchSpec) GetIsolation() *IsolationProfile {
	if x != nil {
		return x.Isolation
	}
	return nil
}

func (x *LaunchSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type LaunchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Logical plugin id this instance serves (for healthcheck/terminate).
	PluginId      string      `protobuf:"bytes,2,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Spec          *LaunchSpec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchRequest) Reset() {
	*x = LaunchRequest{}
	mi := &file_rat_deploymentruntime_v1_deployment_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchRequest) ProtoMessage() {}

func (x *LaunchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rat_deploymentruntime_v1_deployment_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchRequest.ProtoReflect.Descriptor instead.
func (*LaunchRequest) Descriptor() ([]byte, []int) {
	return file_rat_deploymentruntime_v1_deployment_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *LaunchRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *LaunchRequest) GetSpec() *LaunchSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type LaunchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque handle the runtime uses to identify this instance later.
	InstanceId string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// Address the core/API gateway dials to reach the launched plugin.
	Endpoint      string `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchResponse) Reset() {
	*x = LaunchResponse{}
	mi := &file_rat_deploymentruntime_v1_deployment_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchResponse) ProtoMessage() {}

func (x *LaunchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rat_deploymentruntime_v1_deployment_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchResponse.ProtoReflect.Descriptor instead.
func (*LaunchResponse) Descriptor() ([]byte, []int) {
	return file_rat_deploymentruntime_v1_deployment_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *LaunchResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *LaunchResponse) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type TerminateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateRequest) Reset() {
	*x = TerminateRequest{}
	mi := &file_rat_deploymentruntime_v1_deployment_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateRequest) ProtoMessage() {}

func (x *TerminateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rat_deploymentruntime_v1_deployment_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateRequest.ProtoReflect.Descriptor instead.
func (*TerminateRequest) Descriptor() ([]byte, []int) {
	return file_rat_deploymentruntime_v1_deployment_runtime_proto_rawDescGZIP(), []int{5}
}

func (x *TerminateRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type TerminateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Terminated    bool                   `protobuf:"varint,1,opt,name=terminated,proto3" json:"terminated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateResponse) Reset() {
	*x = TerminateResponse{}
	mi := &file_rat_deploymentruntime_v1_deployment_runtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateResponse) ProtoMessage() {}

func (x *TerminateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rat_deploymentruntime_v1_deployment_runtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateResponse.ProtoReflect.Descriptor instead.
func (*TerminateResponse) Descriptor() ([]byte, []int) {
	return file_rat_deploymentruntime_v1_deployment_runtime_proto_rawDescGZIP(), []int{6}
}

func (x *TerminateResponse) GetTerminated() bool {
	if x != nil {
		return x.Terminated
	}
	return false
}

type HealthcheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthcheckRequest) Reset() {
	*x = HealthcheckRequest{}
	mi := &file_rat_deploymentruntime_v1_deployment_runtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthcheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthcheckRequest) ProtoMessage() {}

func (x *HealthcheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rat_deploymentruntime_v1_deployment_runtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthcheckRequest.ProtoReflect.Descriptor instead.
func (*HealthcheckRequest) Descriptor() ([]byte, []int) {
	return file_rat_deploymentruntime_v1_deployment_runtime_proto_rawDescGZIP(), []int{7}
}

func (x *HealthcheckRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type HealthcheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=rat.deploymentruntime.v1.HealthStatus" json:"status,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthcheckResponse) Reset() {
	*x = HealthcheckResponse{}
	mi := &file_rat_deploymentruntime_v1_deployment_runtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthcheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthcheckResponse) ProtoMessage() {}

func (x *HealthcheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rat_deploymentruntime_v1_deployment_runtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthcheckResponse.ProtoReflect.Descriptor instead.
func (*HealthcheckResponse) Descriptor() ([]byte, []int) {
	return file_rat_deploymentruntime_v1_deployment_runtime_proto_rawDescGZIP(), []int{8}
}

func (x *HealthcheckResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *HealthcheckResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_rat_deploymentruntime_v1_deployment_runtime_proto protoreflect.FileDescriptor

const file_rat_deploymentruntime_v1_deployment_runtime_proto_rawDesc = "" +
	"\n" +
	"1rat/deploymentruntime/v1/deployment_runtime.proto\x12\x18rat.deploymentruntime.v1\">\n" +
	"\x12ResourceQuantities\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\tR\x06memory\"\xa1\x02\n" +
	"\x10IsolationProfile\x12%\n" +
	"\x0frun_as_non_root\x18\x01 \x01(\bR\frunAsNonRoot\x122\n" +
	"\x15drop_all_capabilities\x18\x02 \x01(\bR\x13dropAllCapabilities\x12*\n" +
	"\x11no_new_privileges\x18\x03 \x01(\bR\x0fnoNewPrivileges\x12)\n" +
	"\x11read_only_root_fs\x18\x04 \x01(\bR\x0ereadOnlyRootFs\x122\n" +
	"\x15block_metadata_egress\x18\x05 \x01(\bR\x13blockMetadataEgress\x12'\n" +
	"\x0fseccomp_profile\x18\x06 \x01(\tR\x0eseccompProfile\"\xf5\x02\n" +
	"\n" +
	"LaunchSpec\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12H\n" +
	"\brequests\x18\x02 \x01(\v2,.rat.deploymentruntime.v1.ResourceQuantitiesR\brequests\x12D\n" +
	"\x06limits\x18\x03 \x01(\v2,.rat.deploymentruntime.v1.ResourceQuantitiesR\x06limits\x12H\n" +
	"\tisolation\x18\x04 \x01(\v2*.rat.deploymentruntime.v1.IsolationProfileR\tisolation\x12?\n" +
	"\x03env\x18\x05 \x03(\v2-.rat.deploymentruntime.v1.LaunchSpec.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"l\n" +
	"\rLaunchRequest\x12\x1b\n" +
	"\tplugin_id\x18\x02 \x01(\tR\bpluginId\x128\n" +
	"\x04spec\x18\x03 \x01(\v2$.rat.deploymentruntime.v1.LaunchSpecR\x04specJ\x04\b\x01\x10\x02\"M\n" +
	"\x0eLaunchResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\"9\n" +
	"\x10TerminateRequest\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceIdJ\x04\b\x01\x10\x02\"3\n" +
	"\x11TerminateResponse\x12\x1e\n" +
	"\n" +
	"terminated\x18\x01 \x01(\bR\n" +
	"terminated\";\n" +
	"\x12HealthcheckRequest\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceIdJ\x04\b\x01\x10\x02\"m\n" +
	"\x13HealthcheckResponse\x12>\n" +
	"\x06status\x18\x01 \x01(\x0e2&.rat.deploymentruntime.v1.HealthStatusR\x06status\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail*\x80\x01\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_HEALTHY\x10\x01\x12\x1b\n" +
	"\x17HEALTH_STATUS_UNHEALTHY\x10\x02\x12\x19\n" +
	"\x15HEALTH_STATUS_UNKNOWN\x10\x032\xc9\x02\n" +
	"\x18DeploymentRuntimeService\x12[\n" +
	"\x06Launch\x12'.rat.deploymentruntime.v1.LaunchRequest\x1a(.rat.deploymentruntime.v1.LaunchResponse\x12d\n" +
	"\tTerminate\x12*.rat.deploymentruntime.v1.TerminateRequest\x1a+.rat.deploymentruntime.v1.TerminateResponse\x12j\n" +
	"\vHealthcheck\x12,.rat.deploymentruntime.v1.HealthcheckRequest\x1a-.rat.deploymentruntime.v1.HealthcheckResponseBIZGgithub.com/rat-dev/rat/gen/rat/deploymentruntime/v1;deploymentruntimev1b\x06proto3"

var (
	file_rat_deploymentruntime_v1_deployment_runtime_proto_rawDescOnce sync.Once
	file_rat_deploymentruntime_v1_deployment_runtime_proto_rawDescData []byte
)

func file_rat_deploymentruntime_v1_deployment_runtime_proto_rawDescGZIP() []byte {
	file_rat_deploymentruntime_v1_deployment_runtime_proto_rawDescOnce.Do(func() {
		file_rat_deploymentruntime_v1_deployment_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rat_deploymentruntime_v1_deployment_runtime_proto_rawDesc), len(file_rat_deploymentruntime_v1_deployment_runtime_proto_rawDesc)))
	})
	return file_rat_deploymentruntime_v1_deployment_runtime_proto_rawDescData
}

var file_rat_deploymentruntime_v1_deployment_runtime_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rat_deploymentruntime_v1_deployment_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rat_deploymentruntime_v1_deployment_runtime_proto_goTypes = []any{
	(HealthStatus)(0),           // 0: rat.deploymentruntime.v1.HealthStatus
	(*ResourceQuantities)(nil),  // 1: rat.deploymentruntime.v1.ResourceQuantities
	(*IsolationProfile)(nil),    // 2: rat.deploymentruntime.v1.IsolationProfile
	(*LaunchSpec)(nil),          // 3: rat.deploymentruntime.v1.LaunchSpec
	(*LaunchRequest)(nil),       // 4: rat.deploymentruntime.v1.LaunchRequest
	(*LaunchResponse)(nil),      // 5: rat.deploymentruntime.v1.LaunchResponse
	(*TerminateRequest)(nil),    // 6: rat.deploymentruntime.v1.TerminateRequest
	(*TerminateResponse)(nil),   // 7: rat.deploymentruntime.v1.TerminateResponse
	(*HealthcheckRequest)(nil),  // 8: rat.deploymentruntime.v1.HealthcheckRequest
	(*HealthcheckResponse)(nil), // 9: rat.deploymentruntime.v1.HealthcheckResponse
	nil,                         // 10: rat.deploymentruntime.v1.LaunchSpec.EnvEntry
}
var file_rat_deploymentruntime_v1_deployment_runtime_proto_depIdxs = []int32{
	1,  // 0: rat.deploymentruntime.v1.LaunchSpec.requests:type_name -> rat.deploymentruntime.v1.ResourceQuantities
	1,  // 1: rat.deploymentruntime.v1.LaunchSpec.limits:type_name -> rat.deploymentruntime.v1.ResourceQuantities
	2,  // 2: rat.deploymentruntime.v1.LaunchSpec.isolation:type_name -> rat.deploymentruntime.v1.IsolationProfile
	10, // 3: rat.deploymentruntime.v1.LaunchSpec.env:type_name -> rat.deploymentruntime.v1.LaunchSpec.EnvEntry
	3,  // 4: rat.deploymentruntime.v1.LaunchRequest.spec:type_name -> rat.deploymentruntime.v1.LaunchSpec
	0,  // 5: rat.deploymentruntime.v1.HealthcheckResponse.status:type_name -> rat.deploymentruntime.v1.HealthStatus
	4,  // 6: rat.deploymentruntime.v1.DeploymentRuntimeService.Launch:input_type -> rat.deploymentruntime.v1.LaunchRequest
	6,  // 7: rat.deploymentruntime.v1.DeploymentRuntimeService.Terminate:input_type -> rat.deploymentruntime.v1.TerminateRequest
	8,  // 8: rat.deploymentruntime.v1.DeploymentRuntimeService.Healthcheck:input_type -> rat.deploymentruntime.v1.HealthcheckRequest
	5,  // 9: rat.deploymentruntime.v1.DeploymentRuntimeService.Launch:output_type -> rat.deploymentruntime.v1.LaunchResponse
	7,  // 10: rat.deploymentruntime.v1.DeploymentRuntimeService.Terminate:output_type -> rat.deploymentruntime.v1.TerminateResponse
	9,  // 11: rat.deploymentruntime.v1.DeploymentRuntimeService.Healthcheck:output_type -> rat.deploymentruntime.v1.HealthcheckResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_rat_deploymentruntime_v1_deployment_runtime_proto_init() }
func file_rat_deploymentruntime_v1_deployment_runtime_proto_init() {
	if File_rat_deploymentruntime_v1_deployment_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rat_deploymentruntime_v1_deployment_runtime_proto_rawDesc), len(file_rat_deploymentruntime_v1_deployment_runtime_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rat_deploymentruntime_v1_deployment_runtime_proto_goTypes,
		DependencyIndexes: file_rat_deploymentruntime_v1_deployment_runtime_proto_depIdxs,
		EnumInfos:         file_rat_deploymentruntime_v1_deployment_runtime_proto_enumTypes,
		MessageInfos:      file_rat_deploymentruntime_v1_deployment_runtime_proto_msgTypes,
	}.Build()
	File_rat_deploymentruntime_v1_deployment_runtime_proto = out.File
	file_rat_deploymentruntime_v1_deployment_runtime_proto_goTypes = nil
	file_rat_deploymentruntime_v1_deployment_runtime_proto_depIdxs = nil
}
