// Storage axis service contract. Status: v1 (frozen — rat/1, ADR-009).
//
// A `kind: storage` plugin (S3, GCS, Azure Blob, local-fs) owns byte storage +
// credential vending. The control plane NEVER sees bytes (overview.md "data
// plane bypasses core"); it only asks storage to vend short-TTL scoped creds, and
// the engine/format then talk to object storage directly.
//
// Capability mapping:
//   rat://storage/v1/vend-credentials       -> VendCredentials       (mode in request; broad grant)
//   rat://storage/v1/vend-credentials-read  -> VendReadCredentials   (Q02 5c; READ-only, C5-authorizable)
//   rat://storage/v1/vend-credentials-write -> VendWriteCredentials  (Q02 5c; WRITE, C5-authorizable)
//   rat://storage/v1/read  -> (declared capability; satisfied by vended creds)
//   rat://storage/v1/write -> (declared capability; satisfied by vended creds)
//
// SECURITY (reviews/01 Finding 3 + reviews/04): credential vending is the one
// place a mis-scoped grant defeats an otherwise-correct tenancy boundary. Creds
// MUST be scoped to the RequestContext.identity.tenant + the requested prefix, and
// short-TTL. This is a C7 (tenancy-structural) enforcement point — the proto
// carries tenant via context so the storage plugin cannot vend cross-tenant.
//
// LEAST-PRIVILEGE VENDING (Q02 5c, ADR-017 — security F6): VendCredentials takes the
// access mode as a REQUEST field, but C5 authorizes the CAPABILITY, not request
// contents — so it cannot distinguish vend-for-read from vend-for-write, and a
// read-only-intended grant of `vend-credentials` can still request WRITE creds. The two
// mode-scoped RPCs below make the mode C5-authorizable: a plugin that only reads
// `requires` rat://storage/v1/vend-credentials-read, and the gateway denies any attempt
// to obtain write creds. VendReadCredentials MUST vend READ-only creds and
// VendWriteCredentials write-capable creds regardless of any mode in the request;
// VendCredentials remains for the broad / back-compatible grant.

// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file rat/storage/v1/storage.proto (package rat.storage.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { VendCredentialsRequest, VendCredentialsResponse, VendReadCredentialsRequest, VendReadCredentialsResponse, VendWriteCredentialsRequest, VendWriteCredentialsResponse } from "./storage_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service rat.storage.v1.StorageService
 */
export const StorageService = {
  typeName: "rat.storage.v1.StorageService",
  methods: {
    /**
     * rat://storage/v1/vend-credentials — issue short-TTL, prefix-scoped,
     * tenant-scoped credentials the data plane uses to read/write bytes directly.
     * The mode is taken from the request; broad / back-compatible grant.
     *
     * @generated from rpc rat.storage.v1.StorageService.VendCredentials
     */
    vendCredentials: {
      name: "VendCredentials",
      I: VendCredentialsRequest,
      O: VendCredentialsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * rat://storage/v1/vend-credentials-read — vend READ-only creds (Q02 5c). The mode is
     * FIXED by the method (not the request), so C5 authorizes read-vending distinctly and
     * a least-privilege grant can give read without write.
     *
     * @generated from rpc rat.storage.v1.StorageService.VendReadCredentials
     */
    vendReadCredentials: {
      name: "VendReadCredentials",
      I: VendReadCredentialsRequest,
      O: VendReadCredentialsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * rat://storage/v1/vend-credentials-write — vend WRITE-capable creds (Q02 5c). The
     * mode is FIXED by the method so a read-only grant can withhold write-vending.
     *
     * @generated from rpc rat.storage.v1.StorageService.VendWriteCredentials
     */
    vendWriteCredentials: {
      name: "VendWriteCredentials",
      I: VendWriteCredentialsRequest,
      O: VendWriteCredentialsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

