// Storage axis service contract. DRAFT — sub-phase 0b.
//
// A `kind: storage` plugin (S3, GCS, Azure Blob, local-fs) owns byte storage +
// credential vending. The control plane NEVER sees bytes (overview.md "data
// plane bypasses core"); it only asks storage to vend short-TTL scoped creds, and
// the engine/format then talk to object storage directly.
//
// Capability mapping:
//   rat://storage/v1/vend-credentials -> VendCredentials
//   rat://storage/v1/read  -> (declared capability; satisfied by vended creds)
//   rat://storage/v1/write -> (declared capability; satisfied by vended creds)
//
// SECURITY (reviews/01 Finding 3 + reviews/04): credential vending is the one
// place a mis-scoped grant defeats an otherwise-correct tenancy boundary. Creds
// MUST be scoped to the RequestContext.identity.tenant + the requested prefix, and
// short-TTL. This is a C7 (tenancy-structural) enforcement point — the proto
// carries tenant via context so the storage plugin cannot vend cross-tenant.

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file rat/storage/v1/storage.proto (package rat.storage.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { RequestContext } from "../../common/v1/context_pb";
import { file_rat_common_v1_context } from "../../common/v1/context_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file rat/storage/v1/storage.proto.
 */
export const file_rat_storage_v1_storage: GenFile = /*@__PURE__*/
  fileDesc("ChxyYXQvc3RvcmFnZS92MS9zdG9yYWdlLnByb3RvEg5yYXQuc3RvcmFnZS52MSKCAQoWVmVuZENyZWRlbnRpYWxzUmVxdWVzdBIuCgdjb250ZXh0GAEgASgLMh0ucmF0LmNvbW1vbi52MS5SZXF1ZXN0Q29udGV4dBIOCgZwcmVmaXgYAiABKAkSKAoEbW9kZRgDIAEoDjIaLnJhdC5zdG9yYWdlLnYxLkFjY2Vzc01vZGUiTAoXVmVuZENyZWRlbnRpYWxzUmVzcG9uc2USGAoLY3JlZGVudGlhbHMYASABKAxCA4ABARIXCg9leHBpcmVzX3VuaXhfbXMYAiABKAMqcgoKQWNjZXNzTW9kZRIbChdBQ0NFU1NfTU9ERV9VTlNQRUNJRklFRBAAEhQKEEFDQ0VTU19NT0RFX1JFQUQQARIVChFBQ0NFU1NfTU9ERV9XUklURRACEhoKFkFDQ0VTU19NT0RFX1JFQURfV1JJVEUQAzJ0Cg5TdG9yYWdlU2VydmljZRJiCg9WZW5kQ3JlZGVudGlhbHMSJi5yYXQuc3RvcmFnZS52MS5WZW5kQ3JlZGVudGlhbHNSZXF1ZXN0GicucmF0LnN0b3JhZ2UudjEuVmVuZENyZWRlbnRpYWxzUmVzcG9uc2VCNVozZ2l0aHViLmNvbS9yYXQtZGV2L3JhdC9nZW4vcmF0L3N0b3JhZ2UvdjE7c3RvcmFnZXYxYgZwcm90bzM", [file_rat_common_v1_context]);

/**
 * @generated from message rat.storage.v1.VendCredentialsRequest
 */
export type VendCredentialsRequest = Message<"rat.storage.v1.VendCredentialsRequest"> & {
  /**
   * @generated from field: rat.common.v1.RequestContext context = 1;
   */
  context?: RequestContext | undefined;

  /**
   * Storage prefix the creds are scoped to (e.g. "s3://bucket/warehouse/orders").
   * The plugin MUST further constrain by context.identity.tenant.
   *
   * @generated from field: string prefix = 2;
   */
  prefix: string;

  /**
   * @generated from field: rat.storage.v1.AccessMode mode = 3;
   */
  mode: AccessMode;
};

/**
 * Describes the message rat.storage.v1.VendCredentialsRequest.
 * Use `create(VendCredentialsRequestSchema)` to create a new message.
 */
export const VendCredentialsRequestSchema: GenMessage<VendCredentialsRequest> = /*@__PURE__*/
  messageDesc(file_rat_storage_v1_storage, 0);

/**
 * @generated from message rat.storage.v1.VendCredentialsResponse
 */
export type VendCredentialsResponse = Message<"rat.storage.v1.VendCredentialsResponse"> & {
  /**
   * Opaque, provider-specific credential blob (e.g. STS token set). Never logged;
   * `debug_redact` makes that structural (reviews/06 SEC-8).
   *
   * @generated from field: bytes credentials = 1;
   */
  credentials: Uint8Array;

  /**
   * Expiry (unix epoch millis). Callers must re-vend after this.
   *
   * @generated from field: int64 expires_unix_ms = 2;
   */
  expiresUnixMs: bigint;
};

/**
 * Describes the message rat.storage.v1.VendCredentialsResponse.
 * Use `create(VendCredentialsResponseSchema)` to create a new message.
 */
export const VendCredentialsResponseSchema: GenMessage<VendCredentialsResponse> = /*@__PURE__*/
  messageDesc(file_rat_storage_v1_storage, 1);

/**
 * @generated from enum rat.storage.v1.AccessMode
 */
export enum AccessMode {
  /**
   * @generated from enum value: ACCESS_MODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ACCESS_MODE_READ = 1;
   */
  READ = 1,

  /**
   * @generated from enum value: ACCESS_MODE_WRITE = 2;
   */
  WRITE = 2,

  /**
   * @generated from enum value: ACCESS_MODE_READ_WRITE = 3;
   */
  READ_WRITE = 3,
}

/**
 * Describes the enum rat.storage.v1.AccessMode.
 */
export const AccessModeSchema: GenEnum<AccessMode> = /*@__PURE__*/
  enumDesc(file_rat_storage_v1_storage, 0);

/**
 * @generated from service rat.storage.v1.StorageService
 */
export const StorageService: GenService<{
  /**
   * rat://storage/v1/vend-credentials — issue short-TTL, prefix-scoped,
   * tenant-scoped credentials the data plane uses to read/write bytes directly.
   *
   * @generated from rpc rat.storage.v1.StorageService.VendCredentials
   */
  vendCredentials: {
    methodKind: "unary";
    input: typeof VendCredentialsRequestSchema;
    output: typeof VendCredentialsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_rat_storage_v1_storage, 0);

