// Storage axis service contract. Status: v1 (frozen — rat/1, ADR-009).
//
// A `kind: storage` plugin (S3, GCS, Azure Blob, local-fs) owns byte storage +
// credential vending. The control plane NEVER sees bytes (overview.md "data
// plane bypasses core"); it only asks storage to vend short-TTL scoped creds, and
// the engine/format then talk to object storage directly.
//
// Capability mapping:
//   rat://storage/v1/vend-credentials       -> VendCredentials       (mode in request; broad grant)
//   rat://storage/v1/vend-credentials-read  -> VendReadCredentials   (Q02 5c; READ-only, C5-authorizable)
//   rat://storage/v1/vend-credentials-write -> VendWriteCredentials  (Q02 5c; WRITE, C5-authorizable)
//   rat://storage/v1/read  -> (declared capability; satisfied by vended creds)
//   rat://storage/v1/write -> (declared capability; satisfied by vended creds)
//
// SECURITY (reviews/01 Finding 3 + reviews/04): credential vending is the one
// place a mis-scoped grant defeats an otherwise-correct tenancy boundary. Creds
// MUST be scoped to the RequestContext.identity.tenant + the requested prefix, and
// short-TTL. This is a C7 (tenancy-structural) enforcement point — the proto
// carries tenant via context so the storage plugin cannot vend cross-tenant.
//
// LEAST-PRIVILEGE VENDING (Q02 5c, ADR-017 — security F6): VendCredentials takes the
// access mode as a REQUEST field, but C5 authorizes the CAPABILITY, not request
// contents — so it cannot distinguish vend-for-read from vend-for-write, and a
// read-only-intended grant of `vend-credentials` can still request WRITE creds. The two
// mode-scoped RPCs below make the mode C5-authorizable: a plugin that only reads
// `requires` rat://storage/v1/vend-credentials-read, and the gateway denies any attempt
// to obtain write creds. VendReadCredentials MUST vend READ-only creds and
// VendWriteCredentials write-capable creds regardless of any mode in the request;
// VendCredentials remains for the broad / back-compatible grant.

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file rat/storage/v1/storage.proto (package rat.storage.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_rat_common_v1_annotations } from "../../common/v1/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file rat/storage/v1/storage.proto.
 */
export const file_rat_storage_v1_storage: GenFile = /*@__PURE__*/
  fileDesc("ChxyYXQvc3RvcmFnZS92MS9zdG9yYWdlLnByb3RvEg5yYXQuc3RvcmFnZS52MSJYChZWZW5kQ3JlZGVudGlhbHNSZXF1ZXN0Eg4KBnByZWZpeBgCIAEoCRIoCgRtb2RlGAMgASgOMhoucmF0LnN0b3JhZ2UudjEuQWNjZXNzTW9kZUoECAEQAiJMChdWZW5kQ3JlZGVudGlhbHNSZXNwb25zZRIYCgtjcmVkZW50aWFscxgBIAEoDEIDgAEBEhcKD2V4cGlyZXNfdW5peF9tcxgCIAEoAyIyChpWZW5kUmVhZENyZWRlbnRpYWxzUmVxdWVzdBIOCgZwcmVmaXgYAiABKAlKBAgBEAIiUAobVmVuZFJlYWRDcmVkZW50aWFsc1Jlc3BvbnNlEhgKC2NyZWRlbnRpYWxzGAEgASgMQgOAAQESFwoPZXhwaXJlc191bml4X21zGAIgASgDIjMKG1ZlbmRXcml0ZUNyZWRlbnRpYWxzUmVxdWVzdBIOCgZwcmVmaXgYAiABKAlKBAgBEAIiUQocVmVuZFdyaXRlQ3JlZGVudGlhbHNSZXNwb25zZRIYCgtjcmVkZW50aWFscxgBIAEoDEIDgAEBEhcKD2V4cGlyZXNfdW5peF9tcxgCIAEoAypyCgpBY2Nlc3NNb2RlEhsKF0FDQ0VTU19NT0RFX1VOU1BFQ0lGSUVEEAASFAoQQUNDRVNTX01PREVfUkVBRBABEhUKEUFDQ0VTU19NT0RFX1dSSVRFEAISGgoWQUNDRVNTX01PREVfUkVBRF9XUklURRADMtoDCg5TdG9yYWdlU2VydmljZRKJAQoPVmVuZENyZWRlbnRpYWxzEiYucmF0LnN0b3JhZ2UudjEuVmVuZENyZWRlbnRpYWxzUmVxdWVzdBonLnJhdC5zdG9yYWdlLnYxLlZlbmRDcmVkZW50aWFsc1Jlc3BvbnNlIiWKlyIhcmF0Oi8vc3RvcmFnZS92MS92ZW5kLWNyZWRlbnRpYWxzEpoBChNWZW5kUmVhZENyZWRlbnRpYWxzEioucmF0LnN0b3JhZ2UudjEuVmVuZFJlYWRDcmVkZW50aWFsc1JlcXVlc3QaKy5yYXQuc3RvcmFnZS52MS5WZW5kUmVhZENyZWRlbnRpYWxzUmVzcG9uc2UiKoqXIiZyYXQ6Ly9zdG9yYWdlL3YxL3ZlbmQtY3JlZGVudGlhbHMtcmVhZBKeAQoUVmVuZFdyaXRlQ3JlZGVudGlhbHMSKy5yYXQuc3RvcmFnZS52MS5WZW5kV3JpdGVDcmVkZW50aWFsc1JlcXVlc3QaLC5yYXQuc3RvcmFnZS52MS5WZW5kV3JpdGVDcmVkZW50aWFsc1Jlc3BvbnNlIiuKlyIncmF0Oi8vc3RvcmFnZS92MS92ZW5kLWNyZWRlbnRpYWxzLXdyaXRlQjVaM2dpdGh1Yi5jb20vcmF0LWRldi9yYXQvZ2VuL3JhdC9zdG9yYWdlL3YxO3N0b3JhZ2V2MWIGcHJvdG8z", [file_rat_common_v1_annotations]);

/**
 * @generated from message rat.storage.v1.VendCredentialsRequest
 */
export type VendCredentialsRequest = Message<"rat.storage.v1.VendCredentialsRequest"> & {
  /**
   * Storage prefix the creds are scoped to (e.g. "s3://bucket/warehouse/orders").
   * The plugin MUST further constrain by context.identity.tenant.
   *
   * @generated from field: string prefix = 2;
   */
  prefix: string;

  /**
   * @generated from field: rat.storage.v1.AccessMode mode = 3;
   */
  mode: AccessMode;
};

/**
 * Describes the message rat.storage.v1.VendCredentialsRequest.
 * Use `create(VendCredentialsRequestSchema)` to create a new message.
 */
export const VendCredentialsRequestSchema: GenMessage<VendCredentialsRequest> = /*@__PURE__*/
  messageDesc(file_rat_storage_v1_storage, 0);

/**
 * @generated from message rat.storage.v1.VendCredentialsResponse
 */
export type VendCredentialsResponse = Message<"rat.storage.v1.VendCredentialsResponse"> & {
  /**
   * Opaque, provider-specific credential blob (e.g. STS token set). Never logged;
   * `debug_redact` makes that structural (reviews/06 SEC-8).
   *
   * @generated from field: bytes credentials = 1;
   */
  credentials: Uint8Array;

  /**
   * Expiry (unix epoch millis). Callers must re-vend after this.
   *
   * @generated from field: int64 expires_unix_ms = 2;
   */
  expiresUnixMs: bigint;
};

/**
 * Describes the message rat.storage.v1.VendCredentialsResponse.
 * Use `create(VendCredentialsResponseSchema)` to create a new message.
 */
export const VendCredentialsResponseSchema: GenMessage<VendCredentialsResponse> = /*@__PURE__*/
  messageDesc(file_rat_storage_v1_storage, 1);

/**
 * Q02 5c — request for the READ-scoped vend. No `mode` field: the method fixes the
 * mode to READ so it is authorized at the capability level (C5), not chosen by the
 * caller. Same prefix/tenant scoping rules as VendCredentials.
 *
 * @generated from message rat.storage.v1.VendReadCredentialsRequest
 */
export type VendReadCredentialsRequest = Message<"rat.storage.v1.VendReadCredentialsRequest"> & {
  /**
   * Storage prefix the creds are scoped to. The plugin MUST further constrain by
   * context.identity.tenant.
   *
   * @generated from field: string prefix = 2;
   */
  prefix: string;
};

/**
 * Describes the message rat.storage.v1.VendReadCredentialsRequest.
 * Use `create(VendReadCredentialsRequestSchema)` to create a new message.
 */
export const VendReadCredentialsRequestSchema: GenMessage<VendReadCredentialsRequest> = /*@__PURE__*/
  messageDesc(file_rat_storage_v1_storage, 2);

/**
 * @generated from message rat.storage.v1.VendReadCredentialsResponse
 */
export type VendReadCredentialsResponse = Message<"rat.storage.v1.VendReadCredentialsResponse"> & {
  /**
   * @generated from field: bytes credentials = 1;
   */
  credentials: Uint8Array;

  /**
   * @generated from field: int64 expires_unix_ms = 2;
   */
  expiresUnixMs: bigint;
};

/**
 * Describes the message rat.storage.v1.VendReadCredentialsResponse.
 * Use `create(VendReadCredentialsResponseSchema)` to create a new message.
 */
export const VendReadCredentialsResponseSchema: GenMessage<VendReadCredentialsResponse> = /*@__PURE__*/
  messageDesc(file_rat_storage_v1_storage, 3);

/**
 * Q02 5c — request for the WRITE-scoped vend. No `mode` field: the method fixes the
 * mode to write-capable so it is authorized at the capability level (C5).
 *
 * @generated from message rat.storage.v1.VendWriteCredentialsRequest
 */
export type VendWriteCredentialsRequest = Message<"rat.storage.v1.VendWriteCredentialsRequest"> & {
  /**
   * Storage prefix the creds are scoped to. The plugin MUST further constrain by
   * context.identity.tenant.
   *
   * @generated from field: string prefix = 2;
   */
  prefix: string;
};

/**
 * Describes the message rat.storage.v1.VendWriteCredentialsRequest.
 * Use `create(VendWriteCredentialsRequestSchema)` to create a new message.
 */
export const VendWriteCredentialsRequestSchema: GenMessage<VendWriteCredentialsRequest> = /*@__PURE__*/
  messageDesc(file_rat_storage_v1_storage, 4);

/**
 * @generated from message rat.storage.v1.VendWriteCredentialsResponse
 */
export type VendWriteCredentialsResponse = Message<"rat.storage.v1.VendWriteCredentialsResponse"> & {
  /**
   * @generated from field: bytes credentials = 1;
   */
  credentials: Uint8Array;

  /**
   * @generated from field: int64 expires_unix_ms = 2;
   */
  expiresUnixMs: bigint;
};

/**
 * Describes the message rat.storage.v1.VendWriteCredentialsResponse.
 * Use `create(VendWriteCredentialsResponseSchema)` to create a new message.
 */
export const VendWriteCredentialsResponseSchema: GenMessage<VendWriteCredentialsResponse> = /*@__PURE__*/
  messageDesc(file_rat_storage_v1_storage, 5);

/**
 * @generated from enum rat.storage.v1.AccessMode
 */
export enum AccessMode {
  /**
   * @generated from enum value: ACCESS_MODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ACCESS_MODE_READ = 1;
   */
  READ = 1,

  /**
   * @generated from enum value: ACCESS_MODE_WRITE = 2;
   */
  WRITE = 2,

  /**
   * @generated from enum value: ACCESS_MODE_READ_WRITE = 3;
   */
  READ_WRITE = 3,
}

/**
 * Describes the enum rat.storage.v1.AccessMode.
 */
export const AccessModeSchema: GenEnum<AccessMode> = /*@__PURE__*/
  enumDesc(file_rat_storage_v1_storage, 0);

/**
 * @generated from service rat.storage.v1.StorageService
 */
export const StorageService: GenService<{
  /**
   * rat://storage/v1/vend-credentials — issue short-TTL, prefix-scoped,
   * tenant-scoped credentials the data plane uses to read/write bytes directly.
   * The mode is taken from the request; broad / back-compatible grant.
   *
   * @generated from rpc rat.storage.v1.StorageService.VendCredentials
   */
  vendCredentials: {
    methodKind: "unary";
    input: typeof VendCredentialsRequestSchema;
    output: typeof VendCredentialsResponseSchema;
  },
  /**
   * rat://storage/v1/vend-credentials-read — vend READ-only creds (Q02 5c). The mode is
   * FIXED by the method (not the request), so C5 authorizes read-vending distinctly and
   * a least-privilege grant can give read without write.
   *
   * @generated from rpc rat.storage.v1.StorageService.VendReadCredentials
   */
  vendReadCredentials: {
    methodKind: "unary";
    input: typeof VendReadCredentialsRequestSchema;
    output: typeof VendReadCredentialsResponseSchema;
  },
  /**
   * rat://storage/v1/vend-credentials-write — vend WRITE-capable creds (Q02 5c). The
   * mode is FIXED by the method so a read-only grant can withhold write-vending.
   *
   * @generated from rpc rat.storage.v1.StorageService.VendWriteCredentials
   */
  vendWriteCredentials: {
    methodKind: "unary";
    input: typeof VendWriteCredentialsRequestSchema;
    output: typeof VendWriteCredentialsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_rat_storage_v1_storage, 0);

