// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendRequest {
    #[prost(enumeration="Severity", tag="2")]
    pub severity: i32,
    /// Short title + longer body. Plugins MUST NOT include secrets (I13); the core
    /// redacts, but emitters share the obligation.
    #[prost(string, tag="3")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub body: ::prost::alloc::string::String,
    /// Optional routing target (channel, address) — plugin-specific interpretation.
    #[prost(string, tag="5")]
    pub target: ::prost::alloc::string::String,
    /// Structured context for templating + correlation (incl. correlation_id, C1).
    #[prost(map="string, string", tag="6")]
    pub attributes: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SendResponse {
    #[prost(bool, tag="1")]
    pub delivered: bool,
    /// Provider message id, if any (for delivery tracking).
    #[prost(string, tag="2")]
    pub message_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Severity {
    Unspecified = 0,
    Info = 1,
    Warning = 2,
    Error = 3,
    Critical = 4,
}
impl Severity {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SEVERITY_UNSPECIFIED",
            Self::Info => "SEVERITY_INFO",
            Self::Warning => "SEVERITY_WARNING",
            Self::Error => "SEVERITY_ERROR",
            Self::Critical => "SEVERITY_CRITICAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SEVERITY_UNSPECIFIED" => Some(Self::Unspecified),
            "SEVERITY_INFO" => Some(Self::Info),
            "SEVERITY_WARNING" => Some(Self::Warning),
            "SEVERITY_ERROR" => Some(Self::Error),
            "SEVERITY_CRITICAL" => Some(Self::Critical),
            _ => None,
        }
    }
}
include!("rat.notifications.v1.tonic.rs");
// @@protoc_insertion_point(module)