// Notifications axis service contract. Status: v1 (frozen — rat/1.4; ADR-003: experience = one ref + conformance).
//
// A `kind: notifications` plugin (slack, email, webhook, PagerDuty) delivers
// messages triggered by platform events (pipeline failed, plane warmed, etc.).
// It is a delivery sink; WHAT to notify on is the operator's subscription config
// (overview.md reconciliation: subscriptions = [event, action]), not this plugin.
//
// Capability mapping:
//   rat://notifications/v1/send -> Send

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rat/notifications/v1/notifications.proto

package notificationsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_INFO        Severity = 1
	Severity_SEVERITY_WARNING     Severity = 2
	Severity_SEVERITY_ERROR       Severity = 3
	Severity_SEVERITY_CRITICAL    Severity = 4
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_INFO",
		2: "SEVERITY_WARNING",
		3: "SEVERITY_ERROR",
		4: "SEVERITY_CRITICAL",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_INFO":        1,
		"SEVERITY_WARNING":     2,
		"SEVERITY_ERROR":       3,
		"SEVERITY_CRITICAL":    4,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_rat_notifications_v1_notifications_proto_enumTypes[0].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_rat_notifications_v1_notifications_proto_enumTypes[0]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_rat_notifications_v1_notifications_proto_rawDescGZIP(), []int{0}
}

type SendRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Severity Severity               `protobuf:"varint,2,opt,name=severity,proto3,enum=rat.notifications.v1.Severity" json:"severity,omitempty"`
	// Short title + longer body. Plugins MUST NOT include secrets (I13); the core
	// redacts, but emitters share the obligation.
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body  string `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	// Optional routing target (channel, address) — plugin-specific interpretation.
	Target string `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	// Structured context for templating + correlation (incl. correlation_id, C1).
	Attributes    map[string]string `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_rat_notifications_v1_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rat_notifications_v1_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_rat_notifications_v1_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *SendRequest) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *SendRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SendRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *SendRequest) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type SendResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Delivered bool                   `protobuf:"varint,1,opt,name=delivered,proto3" json:"delivered,omitempty"`
	// Provider message id, if any (for delivery tracking).
	MessageId     string `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_rat_notifications_v1_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rat_notifications_v1_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_rat_notifications_v1_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *SendResponse) GetDelivered() bool {
	if x != nil {
		return x.Delivered
	}
	return false
}

func (x *SendResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

var File_rat_notifications_v1_notifications_proto protoreflect.FileDescriptor

const file_rat_notifications_v1_notifications_proto_rawDesc = "" +
	"\n" +
	"(rat/notifications/v1/notifications.proto\x12\x14rat.notifications.v1\"\xa3\x02\n" +
	"\vSendRequest\x12:\n" +
	"\bseverity\x18\x02 \x01(\x0e2\x1e.rat.notifications.v1.SeverityR\bseverity\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x16\n" +
	"\x06target\x18\x05 \x01(\tR\x06target\x12Q\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v21.rat.notifications.v1.SendRequest.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x01\x10\x02\"K\n" +
	"\fSendResponse\x12\x1c\n" +
	"\tdelivered\x18\x01 \x01(\bR\tdelivered\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId*x\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSEVERITY_INFO\x10\x01\x12\x14\n" +
	"\x10SEVERITY_WARNING\x10\x02\x12\x12\n" +
	"\x0eSEVERITY_ERROR\x10\x03\x12\x15\n" +
	"\x11SEVERITY_CRITICAL\x10\x042e\n" +
	"\x14NotificationsService\x12M\n" +
	"\x04Send\x12!.rat.notifications.v1.SendRequest\x1a\".rat.notifications.v1.SendResponseBAZ?github.com/rat-dev/rat/gen/rat/notifications/v1;notificationsv1b\x06proto3"

var (
	file_rat_notifications_v1_notifications_proto_rawDescOnce sync.Once
	file_rat_notifications_v1_notifications_proto_rawDescData []byte
)

func file_rat_notifications_v1_notifications_proto_rawDescGZIP() []byte {
	file_rat_notifications_v1_notifications_proto_rawDescOnce.Do(func() {
		file_rat_notifications_v1_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rat_notifications_v1_notifications_proto_rawDesc), len(file_rat_notifications_v1_notifications_proto_rawDesc)))
	})
	return file_rat_notifications_v1_notifications_proto_rawDescData
}

var file_rat_notifications_v1_notifications_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rat_notifications_v1_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rat_notifications_v1_notifications_proto_goTypes = []any{
	(Severity)(0),        // 0: rat.notifications.v1.Severity
	(*SendRequest)(nil),  // 1: rat.notifications.v1.SendRequest
	(*SendResponse)(nil), // 2: rat.notifications.v1.SendResponse
	nil,                  // 3: rat.notifications.v1.SendRequest.AttributesEntry
}
var file_rat_notifications_v1_notifications_proto_depIdxs = []int32{
	0, // 0: rat.notifications.v1.SendRequest.severity:type_name -> rat.notifications.v1.Severity
	3, // 1: rat.notifications.v1.SendRequest.attributes:type_name -> rat.notifications.v1.SendRequest.AttributesEntry
	1, // 2: rat.notifications.v1.NotificationsService.Send:input_type -> rat.notifications.v1.SendRequest
	2, // 3: rat.notifications.v1.NotificationsService.Send:output_type -> rat.notifications.v1.SendResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rat_notifications_v1_notifications_proto_init() }
func file_rat_notifications_v1_notifications_proto_init() {
	if File_rat_notifications_v1_notifications_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rat_notifications_v1_notifications_proto_rawDesc), len(file_rat_notifications_v1_notifications_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rat_notifications_v1_notifications_proto_goTypes,
		DependencyIndexes: file_rat_notifications_v1_notifications_proto_depIdxs,
		EnumInfos:         file_rat_notifications_v1_notifications_proto_enumTypes,
		MessageInfos:      file_rat_notifications_v1_notifications_proto_msgTypes,
	}.Build()
	File_rat_notifications_v1_notifications_proto = out.File
	file_rat_notifications_v1_notifications_proto_goTypes = nil
	file_rat_notifications_v1_notifications_proto_depIdxs = nil
}
