// Format axis service contract. DRAFT — sub-phase 0b.
//
// A `kind: format` plugin (Iceberg, Delta, Hudi, …) implements table-format
// semantics: resolving refs to physical files, writing data, doing maintenance.
//
// Capability mapping (machine-readable via (rat.common.v1.capability) on each
// method — freeze-blocker #5 / reviews/06 I-3+I-4):
//   rat://format/v1/scan      -> Resolve
//   rat://format/v1/append    -> Append
//   rat://format/v1/merge     -> Merge
//   rat://format/v1/overwrite -> Overwrite
//   rat://format/v1/maintain  -> Maintain
//
// WHY Append/Merge/Overwrite are SEPARATE RPCs (reviews/06 I-3 / AUTH-8): the
// earlier draft had one `Write` RPC keyed by a `WriteMode` enum, so a plugin that
// `provides` only `append` could not be enforced at the method level — the C5
// gateway would have to inspect the payload's mode field to deny a MERGE
// (payload-level authz). Splitting per mode makes each capability a distinct
// method, so capability-enforcement is method-level and the manifest `provides`
// set maps 1:1 to callable methods. It also gives WRITE_MODE_OVERWRITE the
// capability URI it previously lacked (it was unreachable).
//
// C6: each capability above has a golden-data conformance vector. A plugin that
// lists `merge` in its manifest but fails the merge vector is NOT a valid format
// plugin. "Capability declared" is meaningless without "capability conformed" —
// that is what stops capability negotiation from being a lie (reviews/02 Stage5).

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file rat/format/v1/format.proto (package rat.format.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_rat_common_v1_annotations } from "../../common/v1/annotations_pb";
import type { ArrowStream, TableRef, WriteResult } from "../../common/v1/data_pb";
import { file_rat_common_v1_data } from "../../common/v1/data_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file rat/format/v1/format.proto.
 */
export const file_rat_format_v1_format: GenFile = /*@__PURE__*/
  fileDesc("ChpyYXQvZm9ybWF0L3YxL2Zvcm1hdC5wcm90bxINcmF0LmZvcm1hdC52MSJiCg5SZXNvbHZlUmVxdWVzdBImCgV0YWJsZRgCIAEoCzIXLnJhdC5jb21tb24udjEuVGFibGVSZWYSDwoHY29sdW1ucxgDIAMoCRIRCglwcmVkaWNhdGUYBCABKAlKBAgBEAIiPQoPUmVzb2x2ZVJlc3BvbnNlEioKBnN0cmVhbRgBIAEoCzIaLnJhdC5jb21tb24udjEuQXJyb3dTdHJlYW0iaQoNQXBwZW5kUmVxdWVzdBImCgV0YWJsZRgCIAEoCzIXLnJhdC5jb21tb24udjEuVGFibGVSZWYSKgoGc291cmNlGAMgASgLMhoucmF0LmNvbW1vbi52MS5BcnJvd1N0cmVhbUoECAEQAiI8Cg5BcHBlbmRSZXNwb25zZRIqCgZyZXN1bHQYASABKAsyGi5yYXQuY29tbW9uLnYxLldyaXRlUmVzdWx0InwKDE1lcmdlUmVxdWVzdBImCgV0YWJsZRgCIAEoCzIXLnJhdC5jb21tb24udjEuVGFibGVSZWYSKgoGc291cmNlGAMgASgLMhoucmF0LmNvbW1vbi52MS5BcnJvd1N0cmVhbRISCgptZXJnZV9rZXlzGAQgAygJSgQIARACIjsKDU1lcmdlUmVzcG9uc2USKgoGcmVzdWx0GAEgASgLMhoucmF0LmNvbW1vbi52MS5Xcml0ZVJlc3VsdCJsChBPdmVyd3JpdGVSZXF1ZXN0EiYKBXRhYmxlGAIgASgLMhcucmF0LmNvbW1vbi52MS5UYWJsZVJlZhIqCgZzb3VyY2UYAyABKAsyGi5yYXQuY29tbW9uLnYxLkFycm93U3RyZWFtSgQIARACIj8KEU92ZXJ3cml0ZVJlc3BvbnNlEioKBnJlc3VsdBgBIAEoCzIaLnJhdC5jb21tb24udjEuV3JpdGVSZXN1bHQiPwoPTWFpbnRhaW5SZXF1ZXN0EiYKBXRhYmxlGAIgASgLMhcucmF0LmNvbW1vbi52MS5UYWJsZVJlZkoECAEQAiI+ChBNYWludGFpblJlc3BvbnNlEioKBnJlc3VsdBgBIAEoCzIaLnJhdC5jb21tb24udjEuV3JpdGVSZXN1bHQyjwQKDUZvcm1hdFNlcnZpY2USYgoHUmVzb2x2ZRIdLnJhdC5mb3JtYXQudjEuUmVzb2x2ZVJlcXVlc3QaHi5yYXQuZm9ybWF0LnYxLlJlc29sdmVSZXNwb25zZSIYipciFHJhdDovL2Zvcm1hdC92MS9zY2FuEmEKBkFwcGVuZBIcLnJhdC5mb3JtYXQudjEuQXBwZW5kUmVxdWVzdBodLnJhdC5mb3JtYXQudjEuQXBwZW5kUmVzcG9uc2UiGoqXIhZyYXQ6Ly9mb3JtYXQvdjEvYXBwZW5kEl0KBU1lcmdlEhsucmF0LmZvcm1hdC52MS5NZXJnZVJlcXVlc3QaHC5yYXQuZm9ybWF0LnYxLk1lcmdlUmVzcG9uc2UiGYqXIhVyYXQ6Ly9mb3JtYXQvdjEvbWVyZ2USbQoJT3ZlcndyaXRlEh8ucmF0LmZvcm1hdC52MS5PdmVyd3JpdGVSZXF1ZXN0GiAucmF0LmZvcm1hdC52MS5PdmVyd3JpdGVSZXNwb25zZSIdipciGXJhdDovL2Zvcm1hdC92MS9vdmVyd3JpdGUSaQoITWFpbnRhaW4SHi5yYXQuZm9ybWF0LnYxLk1haW50YWluUmVxdWVzdBofLnJhdC5mb3JtYXQudjEuTWFpbnRhaW5SZXNwb25zZSIcipciGHJhdDovL2Zvcm1hdC92MS9tYWludGFpbkIzWjFnaXRodWIuY29tL3JhdC1kZXYvcmF0L2dlbi9yYXQvZm9ybWF0L3YxO2Zvcm1hdHYxYgZwcm90bzM", [file_rat_common_v1_annotations, file_rat_common_v1_data]);

/**
 * @generated from message rat.format.v1.ResolveRequest
 */
export type ResolveRequest = Message<"rat.format.v1.ResolveRequest"> & {
  /**
   * @generated from field: rat.common.v1.TableRef table = 2;
   */
  table?: TableRef | undefined;

  /**
   * Optional column projection + predicate pushdown hints (opaque to core).
   *
   * @generated from field: repeated string columns = 3;
   */
  columns: string[];

  /**
   * @generated from field: string predicate = 4;
   */
  predicate: string;
};

/**
 * Describes the message rat.format.v1.ResolveRequest.
 * Use `create(ResolveRequestSchema)` to create a new message.
 */
export const ResolveRequestSchema: GenMessage<ResolveRequest> = /*@__PURE__*/
  messageDesc(file_rat_format_v1_format, 0);

/**
 * @generated from message rat.format.v1.ResolveResponse
 */
export type ResolveResponse = Message<"rat.format.v1.ResolveResponse"> & {
  /**
   * Out-of-band Arrow endpoint to pull matching record batches from.
   *
   * @generated from field: rat.common.v1.ArrowStream stream = 1;
   */
  stream?: ArrowStream | undefined;
};

/**
 * Describes the message rat.format.v1.ResolveResponse.
 * Use `create(ResolveResponseSchema)` to create a new message.
 */
export const ResolveResponseSchema: GenMessage<ResolveResponse> = /*@__PURE__*/
  messageDesc(file_rat_format_v1_format, 1);

/**
 * @generated from message rat.format.v1.AppendRequest
 */
export type AppendRequest = Message<"rat.format.v1.AppendRequest"> & {
  /**
   * @generated from field: rat.common.v1.TableRef table = 2;
   */
  table?: TableRef | undefined;

  /**
   * Source Arrow stream the format pulls rows from.
   *
   * @generated from field: rat.common.v1.ArrowStream source = 3;
   */
  source?: ArrowStream | undefined;
};

/**
 * Describes the message rat.format.v1.AppendRequest.
 * Use `create(AppendRequestSchema)` to create a new message.
 */
export const AppendRequestSchema: GenMessage<AppendRequest> = /*@__PURE__*/
  messageDesc(file_rat_format_v1_format, 2);

/**
 * @generated from message rat.format.v1.AppendResponse
 */
export type AppendResponse = Message<"rat.format.v1.AppendResponse"> & {
  /**
   * @generated from field: rat.common.v1.WriteResult result = 1;
   */
  result?: WriteResult | undefined;
};

/**
 * Describes the message rat.format.v1.AppendResponse.
 * Use `create(AppendResponseSchema)` to create a new message.
 */
export const AppendResponseSchema: GenMessage<AppendResponse> = /*@__PURE__*/
  messageDesc(file_rat_format_v1_format, 3);

/**
 * @generated from message rat.format.v1.MergeRequest
 */
export type MergeRequest = Message<"rat.format.v1.MergeRequest"> & {
  /**
   * @generated from field: rat.common.v1.TableRef table = 2;
   */
  table?: TableRef | undefined;

  /**
   * @generated from field: rat.common.v1.ArrowStream source = 3;
   */
  source?: ArrowStream | undefined;

  /**
   * The key columns to match existing rows on.
   *
   * @generated from field: repeated string merge_keys = 4;
   */
  mergeKeys: string[];
};

/**
 * Describes the message rat.format.v1.MergeRequest.
 * Use `create(MergeRequestSchema)` to create a new message.
 */
export const MergeRequestSchema: GenMessage<MergeRequest> = /*@__PURE__*/
  messageDesc(file_rat_format_v1_format, 4);

/**
 * @generated from message rat.format.v1.MergeResponse
 */
export type MergeResponse = Message<"rat.format.v1.MergeResponse"> & {
  /**
   * @generated from field: rat.common.v1.WriteResult result = 1;
   */
  result?: WriteResult | undefined;
};

/**
 * Describes the message rat.format.v1.MergeResponse.
 * Use `create(MergeResponseSchema)` to create a new message.
 */
export const MergeResponseSchema: GenMessage<MergeResponse> = /*@__PURE__*/
  messageDesc(file_rat_format_v1_format, 5);

/**
 * @generated from message rat.format.v1.OverwriteRequest
 */
export type OverwriteRequest = Message<"rat.format.v1.OverwriteRequest"> & {
  /**
   * @generated from field: rat.common.v1.TableRef table = 2;
   */
  table?: TableRef | undefined;

  /**
   * @generated from field: rat.common.v1.ArrowStream source = 3;
   */
  source?: ArrowStream | undefined;
};

/**
 * Describes the message rat.format.v1.OverwriteRequest.
 * Use `create(OverwriteRequestSchema)` to create a new message.
 */
export const OverwriteRequestSchema: GenMessage<OverwriteRequest> = /*@__PURE__*/
  messageDesc(file_rat_format_v1_format, 6);

/**
 * @generated from message rat.format.v1.OverwriteResponse
 */
export type OverwriteResponse = Message<"rat.format.v1.OverwriteResponse"> & {
  /**
   * @generated from field: rat.common.v1.WriteResult result = 1;
   */
  result?: WriteResult | undefined;
};

/**
 * Describes the message rat.format.v1.OverwriteResponse.
 * Use `create(OverwriteResponseSchema)` to create a new message.
 */
export const OverwriteResponseSchema: GenMessage<OverwriteResponse> = /*@__PURE__*/
  messageDesc(file_rat_format_v1_format, 7);

/**
 * @generated from message rat.format.v1.MaintainRequest
 */
export type MaintainRequest = Message<"rat.format.v1.MaintainRequest"> & {
  /**
   * @generated from field: rat.common.v1.TableRef table = 2;
   */
  table?: TableRef | undefined;
};

/**
 * Describes the message rat.format.v1.MaintainRequest.
 * Use `create(MaintainRequestSchema)` to create a new message.
 */
export const MaintainRequestSchema: GenMessage<MaintainRequest> = /*@__PURE__*/
  messageDesc(file_rat_format_v1_format, 8);

/**
 * @generated from message rat.format.v1.MaintainResponse
 */
export type MaintainResponse = Message<"rat.format.v1.MaintainResponse"> & {
  /**
   * @generated from field: rat.common.v1.WriteResult result = 1;
   */
  result?: WriteResult | undefined;
};

/**
 * Describes the message rat.format.v1.MaintainResponse.
 * Use `create(MaintainResponseSchema)` to create a new message.
 */
export const MaintainResponseSchema: GenMessage<MaintainResponse> = /*@__PURE__*/
  messageDesc(file_rat_format_v1_format, 9);

/**
 * @generated from service rat.format.v1.FormatService
 */
export const FormatService: GenService<{
  /**
   * Resolve a table ref to a readable Arrow stream descriptor. Bulk bytes flow
   * out-of-band via the returned ArrowStream.
   *
   * @generated from rpc rat.format.v1.FormatService.Resolve
   */
  resolve: {
    methodKind: "unary";
    input: typeof ResolveRequestSchema;
    output: typeof ResolveResponseSchema;
  },
  /**
   * Append rows (no key matching). Caller hands an ArrowStream to pull from.
   *
   * @generated from rpc rat.format.v1.FormatService.Append
   */
  append: {
    methodKind: "unary";
    input: typeof AppendRequestSchema;
    output: typeof AppendResponseSchema;
  },
  /**
   * Merge (upsert) rows matched on `merge_keys`.
   *
   * @generated from rpc rat.format.v1.FormatService.Merge
   */
  merge: {
    methodKind: "unary";
    input: typeof MergeRequestSchema;
    output: typeof MergeResponseSchema;
  },
  /**
   * Overwrite the target (replace existing data).
   *
   * @generated from rpc rat.format.v1.FormatService.Overwrite
   */
  overwrite: {
    methodKind: "unary";
    input: typeof OverwriteRequestSchema;
    output: typeof OverwriteResponseSchema;
  },
  /**
   * Format upkeep (compaction, snapshot expiry, manifest rewrite). Idempotent;
   * safe to retry.
   *
   * @generated from rpc rat.format.v1.FormatService.Maintain
   */
  maintain: {
    methodKind: "unary";
    input: typeof MaintainRequestSchema;
    output: typeof MaintainResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_rat_format_v1_format, 0);

