// Format axis service contract. Status: v1 (frozen — rat/1, ADR-009).
//
// A `kind: format` plugin (Iceberg, Delta, Hudi, …) implements table-format
// semantics: resolving refs to physical files, writing data, doing maintenance.
//
// Capability mapping (machine-readable via (rat.common.v1.capability) on each
// method — freeze-blocker #5 / reviews/06 I-3+I-4):
//   rat://format/v1/scan      -> Resolve
//   rat://format/v1/append    -> Append
//   rat://format/v1/merge     -> Merge
//   rat://format/v1/overwrite -> Overwrite
//   rat://format/v1/maintain  -> Maintain
//
// WHY Append/Merge/Overwrite are SEPARATE RPCs (reviews/06 I-3 / AUTH-8): the
// earlier draft had one `Write` RPC keyed by a `WriteMode` enum, so a plugin that
// `provides` only `append` could not be enforced at the method level — the C5
// gateway would have to inspect the payload's mode field to deny a MERGE
// (payload-level authz). Splitting per mode makes each capability a distinct
// method, so capability-enforcement is method-level and the manifest `provides`
// set maps 1:1 to callable methods. It also gives WRITE_MODE_OVERWRITE the
// capability URI it previously lacked (it was unreachable).
//
// C6: each capability above has a golden-data conformance vector. A plugin that
// lists `merge` in its manifest but fails the merge vector is NOT a valid format
// plugin. "Capability declared" is meaningless without "capability conformed" —
// that is what stops capability negotiation from being a lie (reviews/02 Stage5).

// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file rat/format/v1/format.proto (package rat.format.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AppendRequest, AppendResponse, MaintainRequest, MaintainResponse, MergeRequest, MergeResponse, OverwriteRequest, OverwriteResponse, ResolveRequest, ResolveResponse } from "./format_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service rat.format.v1.FormatService
 */
export const FormatService = {
  typeName: "rat.format.v1.FormatService",
  methods: {
    /**
     * Resolve a table ref to a readable Arrow stream descriptor. Bulk bytes flow
     * out-of-band via the returned ArrowStream.
     *
     * @generated from rpc rat.format.v1.FormatService.Resolve
     */
    resolve: {
      name: "Resolve",
      I: ResolveRequest,
      O: ResolveResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Append rows (no key matching). Caller hands an ArrowStream to pull from.
     *
     * @generated from rpc rat.format.v1.FormatService.Append
     */
    append: {
      name: "Append",
      I: AppendRequest,
      O: AppendResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Merge (upsert) rows matched on `merge_keys`.
     *
     * @generated from rpc rat.format.v1.FormatService.Merge
     */
    merge: {
      name: "Merge",
      I: MergeRequest,
      O: MergeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Overwrite the target (replace existing data).
     *
     * @generated from rpc rat.format.v1.FormatService.Overwrite
     */
    overwrite: {
      name: "Overwrite",
      I: OverwriteRequest,
      O: OverwriteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Format upkeep (compaction, snapshot expiry, manifest rewrite). Idempotent;
     * safe to retry.
     *
     * @generated from rpc rat.format.v1.FormatService.Maintain
     */
    maintain: {
      name: "Maintain",
      I: MaintainRequest,
      O: MaintainResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

