// @generated
// This file is @generated by prost-build.
/// LaunchSpec is how a plugin is launched (the subset rat.toml carries). An empty image
/// means a REGISTER-ONLY driver (an operator identity that dials the gateway but is not
/// itself launched), mirroring a rat.toml \[[plugin]\] with no image.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LaunchSpec {
    /// OCI image ref. Empty = a register-only driver (no launch).
    #[prost(string, tag = "1")]
    pub image: ::prost::alloc::string::String,
    /// Isolation profile shorthand (e.g. "i9"); the daemon maps it to a full profile, the
    /// same mapping rat.toml uses. Empty defaults to the hardened profile.
    #[prost(string, tag = "2")]
    pub isolation: ::prost::alloc::string::String,
    /// Launch environment. NEVER secrets — only opaque refs (the *_REF convention); the
    /// secret-backend resolves them at first use (ADR-022).
    #[prost(map = "string, string", tag = "3")]
    pub env: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
/// RegisterPluginRequest adds one plugin to the running plane.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterPluginRequest {
    /// The plugin's instance name in this plane (the key `rat remove` / Deregister uses).
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// The plugin's manifest as raw YAML (the frozen plugin.v1 shape). The daemon parses +
    /// validates it; its kind + provides/requires are what the registry authorizes from.
    /// Carried as bytes so the manifest stays YAML end to end (no proto schema dup).
    #[prost(bytes = "vec", tag = "2")]
    pub manifest_yaml: ::prost::alloc::vec::Vec<u8>,
    /// How to launch it. Absent (or empty image) = a register-only driver.
    #[prost(message, optional, tag = "3")]
    pub launch: ::core::option::Option<LaunchSpec>,
}
/// RegisterPluginResponse reports the plugin's live state after the daemon materialized it.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegisterPluginResponse {
    /// The plugin name, echoed.
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// The reconcile state after materialize (e.g. "Healthy"). A driver with no launch is
    /// reported as registered without a health probe.
    #[prost(string, tag = "2")]
    pub state: ::prost::alloc::string::String,
    /// Where the gateway bound the plugin (its routable endpoint); empty for a driver.
    #[prost(string, tag = "3")]
    pub endpoint: ::prost::alloc::string::String,
}
/// DeregisterPluginRequest removes one plugin from the running plane by name.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeregisterPluginRequest {
    /// The plugin instance name to remove.
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
}
/// DeregisterPluginResponse confirms the removal.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeregisterPluginResponse {
    /// The plugin name, echoed.
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Whether the plugin was actually present in the running plane (false = no-op).
    #[prost(bool, tag = "2")]
    pub was_present: bool,
}
/// ListPluginsRequest asks for the live plane (no parameters in v1).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListPluginsRequest {
}
/// ListPluginsResponse is the live plane as the daemon sees it.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListPluginsResponse {
    /// One entry per plugin currently known to the running daemon.
    #[prost(message, repeated, tag = "1")]
    pub plugins: ::prost::alloc::vec::Vec<PluginStatus>,
}
/// PluginStatus is one plugin's live state in the running plane.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PluginStatus {
    /// The plugin instance name.
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// The plugin's manifest kind (the axis it implements).
    #[prost(string, tag = "2")]
    pub kind: ::prost::alloc::string::String,
    /// The reconcile state (e.g. "Healthy", "Launching", "Degraded"); "registered" for a
    /// register-only driver with no health probe.
    #[prost(string, tag = "3")]
    pub state: ::prost::alloc::string::String,
    /// The plugin's routable endpoint, if bound; empty for a driver or a not-yet-Healthy
    /// plugin.
    #[prost(string, tag = "4")]
    pub endpoint: ::prost::alloc::string::String,
    /// The capability URIs this plugin provides (from its manifest).
    #[prost(string, repeated, tag = "5")]
    pub provides: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
// The three Invoke variants carry the SAME {capability, payload} → {result}
// envelope, but buf STANDARD (RPC_REQUEST_RESPONSE_UNIQUE) requires a distinct
// request/response per RPC — which also lets each cardinality evolve + document
// its own framing semantics independently (ADR-008). Context never rides in any of
// them; it is in the rat-callmeta-bin metadata header (ADR-007).

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InvokeRequest {
    /// The capability being invoked, e.g. "rat://format/v1/merge". MUST match the
    /// rat://<axis>/v<major>/<capability> grammar. The core resolves this to a
    /// concrete provider + method via the registry + the (rat.common.v1.capability)
    /// method annotation, and checks the caller's manifest `requires` it.
    #[prost(string, tag = "2")]
    pub capability: ::prost::alloc::string::String,
    /// The serialized request message for the target axis method (e.g. an encoded
    /// rat.format.v1.MergeRequest). Opaque to the core — routed, not interpreted.
    /// The target method is determined by `capability`, so the message type is
    /// implied by the capability, not carried here.
    #[prost(bytes = "vec", tag = "3")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InvokeResponse {
    /// The serialized response message from the provider's method (e.g. an encoded
    /// rat.format.v1.MergeResponse). Opaque to the core.
    ///
    /// Note: this contract returns the provider's success payload; failures surface
    /// via gRPC status (transport/enforcement) per the canonical error model
    /// (\[common/v1/ERROR_MODEL.md\], pinned at rat/1). Capability-not-authorized
    /// (PERMISSION_DENIED), provider-unavailable (UNAVAILABLE), and unauthenticated
    /// caller (UNAUTHENTICATED) are core-side enforcement failures returned as those
    /// gRPC status codes, not as a field here.
    #[prost(bytes = "vec", tag = "1")]
    pub result: ::prost::alloc::vec::Vec<u8>,
}
// --- server-streaming variant (ADR-008) ---

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InvokeServerStreamRequest {
    /// The capability being invoked; same grammar + resolution as InvokeRequest. Must
    /// resolve to a server-streaming provider method.
    #[prost(string, tag = "2")]
    pub capability: ::prost::alloc::string::String,
    /// The serialized request message for the target method (e.g. an encoded
    /// rat.runtime.v1.ExecuteRequest). Opaque to the core.
    #[prost(bytes = "vec", tag = "3")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InvokeServerStreamResponse {
    /// One serialized axis response frame (e.g. an encoded
    /// rat.runtime.v1.ExecuteResponse). Opaque to the core; relayed verbatim.
    /// Failures surface via gRPC status, not a field here.
    #[prost(bytes = "vec", tag = "1")]
    pub result: ::prost::alloc::vec::Vec<u8>,
}
// --- bidirectional variant (ADR-008; also serves client-streaming) ---

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InvokeBidiStreamRequest {
    /// Set on the FIRST frame only to establish + authorize the call; MUST be empty
    /// on subsequent frames. A non-empty `capability` on a non-first frame is a
    /// protocol violation — the core ABORTS the stream with INVALID_ARGUMENT (S2,
    /// reviews/07: "ignored" would let a client attempt a silent mid-stream capability
    /// switch; reject it, never tolerate it).
    #[prost(string, tag = "2")]
    pub capability: ::prost::alloc::string::String,
    /// One serialized axis request frame. Opaque to the core.
    #[prost(bytes = "vec", tag = "3")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InvokeBidiStreamResponse {
    /// One serialized axis response frame. Opaque to the core; relayed verbatim.
    #[prost(bytes = "vec", tag = "1")]
    pub result: ::prost::alloc::vec::Vec<u8>,
}
include!("rat.core.v1.tonic.rs");
// @@protoc_insertion_point(module)