# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rat/billing/v1/billing.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'rat/billing/v1/billing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1crat/billing/v1/billing.proto\x12\x0erat.billing.v1\"\xf5\x01\n\nUsageEvent\x12\x14\n\x05meter\x18\x01 \x01(\tR\x05meter\x12\x1a\n\x08quantity\x18\x02 \x01(\x01R\x08quantity\x12*\n\x11timestamp_unix_ms\x18\x03 \x01(\x03R\x0ftimestampUnixMs\x12J\n\ndimensions\x18\x04 \x03(\x0b\x32*.rat.billing.v1.UsageEvent.DimensionsEntryR\ndimensions\x1a=\n\x0f\x44imensionsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"I\n\rRecordRequest\x12\x32\n\x06\x65vents\x18\x02 \x03(\x0b\x32\x1a.rat.billing.v1.UsageEventR\x06\x65ventsJ\x04\x08\x01\x10\x02\",\n\x0eRecordResponse\x12\x1a\n\x08recorded\x18\x01 \x01(\x03R\x08recorded2Y\n\x0e\x42illingService\x12G\n\x06Record\x12\x1d.rat.billing.v1.RecordRequest\x1a\x1e.rat.billing.v1.RecordResponseB5Z3github.com/rat-dev/rat/gen/rat/billing/v1;billingv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rat.billing.v1.billing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3github.com/rat-dev/rat/gen/rat/billing/v1;billingv1'
  _globals['_USAGEEVENT_DIMENSIONSENTRY']._loaded_options = None
  _globals['_USAGEEVENT_DIMENSIONSENTRY']._serialized_options = b'8\001'
  _globals['_USAGEEVENT']._serialized_start=49
  _globals['_USAGEEVENT']._serialized_end=294
  _globals['_USAGEEVENT_DIMENSIONSENTRY']._serialized_start=233
  _globals['_USAGEEVENT_DIMENSIONSENTRY']._serialized_end=294
  _globals['_RECORDREQUEST']._serialized_start=296
  _globals['_RECORDREQUEST']._serialized_end=369
  _globals['_RECORDRESPONSE']._serialized_start=371
  _globals['_RECORDRESPONSE']._serialized_end=415
  _globals['_BILLINGSERVICE']._serialized_start=417
  _globals['_BILLINGSERVICE']._serialized_end=506
# @@protoc_insertion_point(module_scope)
