# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rat.billing.v1 import billing_pb2 as rat_dot_billing_dot_v1_dot_billing__pb2


class BillingServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Record = channel.unary_unary(
                '/rat.billing.v1.BillingService/Record',
                request_serializer=rat_dot_billing_dot_v1_dot_billing__pb2.RecordRequest.SerializeToString,
                response_deserializer=rat_dot_billing_dot_v1_dot_billing__pb2.RecordResponse.FromString,
                _registered_method=True)


class BillingServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Record(self, request, context):
        """rat://billing/v1/record — record one meterable usage event.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BillingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Record': grpc.unary_unary_rpc_method_handler(
                    servicer.Record,
                    request_deserializer=rat_dot_billing_dot_v1_dot_billing__pb2.RecordRequest.FromString,
                    response_serializer=rat_dot_billing_dot_v1_dot_billing__pb2.RecordResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rat.billing.v1.BillingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rat.billing.v1.BillingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BillingService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Record(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rat.billing.v1.BillingService/Record',
            rat_dot_billing_dot_v1_dot_billing__pb2.RecordRequest.SerializeToString,
            rat_dot_billing_dot_v1_dot_billing__pb2.RecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
