# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from rat.state.v1 import state_pb2 as rat_dot_state_dot_v1_dot_state__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rat/state/v1/state_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StateServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/rat.state.v1.StateService/Get',
                request_serializer=rat_dot_state_dot_v1_dot_state__pb2.GetRequest.SerializeToString,
                response_deserializer=rat_dot_state_dot_v1_dot_state__pb2.GetResponse.FromString,
                _registered_method=True)
        self.Put = channel.unary_unary(
                '/rat.state.v1.StateService/Put',
                request_serializer=rat_dot_state_dot_v1_dot_state__pb2.PutRequest.SerializeToString,
                response_deserializer=rat_dot_state_dot_v1_dot_state__pb2.PutResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/rat.state.v1.StateService/List',
                request_serializer=rat_dot_state_dot_v1_dot_state__pb2.ListRequest.SerializeToString,
                response_deserializer=rat_dot_state_dot_v1_dot_state__pb2.ListResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/rat.state.v1.StateService/Delete',
                request_serializer=rat_dot_state_dot_v1_dot_state__pb2.DeleteRequest.SerializeToString,
                response_deserializer=rat_dot_state_dot_v1_dot_state__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Watch = channel.unary_stream(
                '/rat.state.v1.StateService/Watch',
                request_serializer=rat_dot_state_dot_v1_dot_state__pb2.WatchRequest.SerializeToString,
                response_deserializer=rat_dot_state_dot_v1_dot_state__pb2.WatchResponse.FromString,
                _registered_method=True)


class StateServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """rat://state/v1/get — read one key (plugin+tenant relative).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Put(self, request, context):
        """rat://state/v1/put — write one key, optionally compare-and-set on revision.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """rat://state/v1/list — list keys under a plugin+tenant-relative prefix.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """rat://state/v1/delete — remove one key (plugin+tenant relative), optionally compare-and-set.
        ADDITIVE amendment (ADR-035): a state-backend MAY return UNIMPLEMENTED — Delete is optional;
        a backend declares this capability in `provides` only if it supports it, and consumers MUST
        handle UNIMPLEMENTED. Idempotent (absent key -> found=false, not an error). CAS via if_revision
        with the same fencing rigor as Put (deleting a lease key releases the lease).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Watch(self, request, context):
        """rat://state/v1/watch — stream changes under a prefix (reconciler/event use).
        Each streamed message is a WatchResponse — named per the *Response convention
        buf STANDARD requires, even for streaming RPCs. Mediated via core
        InvokeServerStream (ADR-008).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=rat_dot_state_dot_v1_dot_state__pb2.GetRequest.FromString,
                    response_serializer=rat_dot_state_dot_v1_dot_state__pb2.GetResponse.SerializeToString,
            ),
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=rat_dot_state_dot_v1_dot_state__pb2.PutRequest.FromString,
                    response_serializer=rat_dot_state_dot_v1_dot_state__pb2.PutResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=rat_dot_state_dot_v1_dot_state__pb2.ListRequest.FromString,
                    response_serializer=rat_dot_state_dot_v1_dot_state__pb2.ListResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=rat_dot_state_dot_v1_dot_state__pb2.DeleteRequest.FromString,
                    response_serializer=rat_dot_state_dot_v1_dot_state__pb2.DeleteResponse.SerializeToString,
            ),
            'Watch': grpc.unary_stream_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=rat_dot_state_dot_v1_dot_state__pb2.WatchRequest.FromString,
                    response_serializer=rat_dot_state_dot_v1_dot_state__pb2.WatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rat.state.v1.StateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rat.state.v1.StateService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StateService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rat.state.v1.StateService/Get',
            rat_dot_state_dot_v1_dot_state__pb2.GetRequest.SerializeToString,
            rat_dot_state_dot_v1_dot_state__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rat.state.v1.StateService/Put',
            rat_dot_state_dot_v1_dot_state__pb2.PutRequest.SerializeToString,
            rat_dot_state_dot_v1_dot_state__pb2.PutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rat.state.v1.StateService/List',
            rat_dot_state_dot_v1_dot_state__pb2.ListRequest.SerializeToString,
            rat_dot_state_dot_v1_dot_state__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rat.state.v1.StateService/Delete',
            rat_dot_state_dot_v1_dot_state__pb2.DeleteRequest.SerializeToString,
            rat_dot_state_dot_v1_dot_state__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rat.state.v1.StateService/Watch',
            rat_dot_state_dot_v1_dot_state__pb2.WatchRequest.SerializeToString,
            rat_dot_state_dot_v1_dot_state__pb2.WatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
