// Custom proto annotations for RAT contracts. Status: v1 (frozen — rat/1, ADR-009).
//
// This file defines the MACHINE-READABLE capability⇄method binding that
// reviews/06 I-4 (AUTH-9) requires. Before this, the mapping from a capability
// URI (rat://<axis>/v<major>/<capability>) to the concrete (service, method)
// lived only in proto COMMENTS — unreadable by the two components that need it:
//   - the C5 capability-enforcement gateway (ADR-005), which must check that a
//     caller's manifest `requires`/`provides` the capability a method serves;
//   - the C6 conformance harness, which must know which golden-data vectors apply
//     to which method.
//
// Every axis RPC carries `option (rat.common.v1.capability) = "rat://…";`. The
// gateway + harness read it from the method descriptor. This file MUST be part of
// the frozen `rat/1` surface (the option's existence is freeze-load-bearing);
// applying the option to additional methods later is additive/wire-compatible.

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file rat/common/v1/annotations.proto (package rat.common.v1, syntax proto3)
/* eslint-disable */

import type { GenExtension, GenFile } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";
import type { MethodOptions } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file rat/common/v1/annotations.proto.
 */
export const file_rat_common_v1_annotations: GenFile = /*@__PURE__*/
  fileDesc("Ch9yYXQvY29tbW9uL3YxL2Fubm90YXRpb25zLnByb3RvEg1yYXQuY29tbW9uLnYxOkAKCmNhcGFiaWxpdHkSHi5nb29nbGUucHJvdG9idWYuTWV0aG9kT3B0aW9ucxjxogQgASgJUgpjYXBhYmlsaXR5QjNaMWdpdGh1Yi5jb20vcmF0LWRldi9yYXQvZ2VuL3JhdC9jb21tb24vdjE7Y29tbW9udjFiBnByb3RvMw", [file_google_protobuf_descriptor]);

/**
 * @generated from extension: string capability = 70001;
 */
export const capability: GenExtension<MethodOptions, string> = /*@__PURE__*/
  extDesc(file_rat_common_v1_annotations, 0);

