// Async event-bus envelope. DRAFT — freeze-blocker #7.
//
// This is the wire contract for the ASYNC plane (reviews/06 ARCH-1). The event
// bus is one of the six core things (overview.md): the reconciler emits events
// (pipeline_run_requested, *_completed, *_failed, plugin_installed, …) and N
// plugins react without coupling — "the core never tells anyone to do anything."
//
// THE GAP THIS CLOSES: every SYNC rpc carries common.v1.RequestContext (trace +
// identity + tenant), but until now the async plane had NO envelope at all — so
// distributed tracing broke across the async boundary (the main coordination
// path), and multi-tenant event routing/isolation was undefined. An Event now
// carries the SAME RequestContext, so a `pipeline_run_failed` can be traced back
// through the `pipeline_run_requested` that caused it, across every reacting
// plugin, within one correlation_id — and the bus can route/filter by tenant.
//
// FREEZE NOTE: this envelope is part of the frozen rat/1 surface. Per ADR-002 D2
// the bus PROTOCOL is fixed (this message) while the TRANSPORT is pluggable
// (NATS JetStream default — ADR-002 D4 — / Kafka / Redis Streams); a
// `kind: <bus-transport>` plugin carries Events without interpreting `payload`.
//
// IDENTITY ON THE ASYNC HOP: `context.identity` is stamped by the CORE at emit
// time (the emitter is the core reconciler or a core-mediated plugin call), same
// non-forgeable rules as the keystone (context.proto). A subscriber READS it for
// its own logic + audit; it is not caller-asserted on the bus.
//
// Status: DRAFT (pre-freeze).

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file rat/common/v1/event.proto (package rat.common.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { RequestContext } from "./context_pb";
import { file_rat_common_v1_context } from "./context_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file rat/common/v1/event.proto.
 */
export const file_rat_common_v1_event: GenFile = /*@__PURE__*/
  fileDesc("ChlyYXQvY29tbW9uL3YxL2V2ZW50LnByb3RvEg1yYXQuY29tbW9uLnYxIqoBCgVFdmVudBIuCgdjb250ZXh0GAEgASgLMh0ucmF0LmNvbW1vbi52MS5SZXF1ZXN0Q29udGV4dBIQCghldmVudF9pZBgCIAEoCRIMCgR0eXBlGAMgASgJEhkKEXRpbWVzdGFtcF91bml4X21zGAQgASgDEg4KBnNvdXJjZRgFIAEoCRIPCgdwYXlsb2FkGAYgASgMEhUKDXBhcnRpdGlvbl9rZXkYByABKAlCM1oxZ2l0aHViLmNvbS9yYXQtZGV2L3JhdC9nZW4vcmF0L2NvbW1vbi92MTtjb21tb252MWIGcHJvdG8z", [file_rat_common_v1_context]);

/**
 * One event on the bus. Published by the core (or a core-mediated plugin),
 * delivered to every subscriber whose subscription matches `type`.
 *
 * @generated from message rat.common.v1.Event
 */
export type Event = Message<"rat.common.v1.Event"> & {
  /**
   * Trace + identity + tenant for this event — the SAME envelope (context.proto).
   * CARRIAGE: sync control RPCs carry it in the rat-callmeta-bin metadata header
   * (ADR-007); the async Event carries it IN-BODY here, by design — a published,
   * persisted, fan-out event has no per-hop metadata channel, and it is
   * core-stamped once at emit (not re-stamped per hop), so a body field is correct.
   * correlation_id chains the event to the operation that produced it;
   * identity.tenant scopes routing/isolation; traceparent continues the
   * distributed trace across the async hop.
   *
   * @generated from field: rat.common.v1.RequestContext context = 1;
   */
  context?: RequestContext | undefined;

  /**
   * Globally-unique id for THIS event instance. Used for idempotent delivery:
   * a subscriber that has already processed this event_id MUST treat redelivery
   * as a no-op (at-least-once transports redeliver). Distinct from
   * context.correlation_id (which is shared by all events of one operation).
   *
   * @generated from field: string event_id = 2;
   */
  eventId: string;

  /**
   * The event type, e.g. "pipeline_run_requested", "pipeline_run_completed",
   * "pipeline_run_failed", "plugin_installed", "plane_warmed". Subscriptions
   * match on this (overview.md reconciliation model: subscriptions = [event,
   * action]). Convention: lower_snake_case; the open-set is not enumerated
   * centrally (community event types are allowed, namespaced by emitter).
   *
   * @generated from field: string type = 3;
   */
  type: string;

  /**
   * When the event occurred (unix epoch millis). Consistent with the int64-ms
   * timestamp convention used across the contracts.
   *
   * @generated from field: int64 timestamp_unix_ms = 4;
   */
  timestampUnixMs: bigint;

  /**
   * The emitting component: the core reconciler ("rat-core") or the plugin id of
   * a core-mediated emitter. Set by the core; lets subscribers + audit attribute
   * the event. (Mirrors identity.caller_plugin semantics for the async path.)
   *
   * @generated from field: string source = 5;
   */
  source: string;

  /**
   * The event payload — a serialized, type-specific message whose schema is
   * implied by `type`. Opaque to the bus transport (which routes by `type` +
   * tenant without interpreting it), exactly as core/v1/invoke.proto's payload is
   * opaque to the gateway. Subscribers decode it per the documented type.
   *
   * @generated from field: bytes payload = 6;
   */
  payload: Uint8Array;

  /**
   * Optional ordering key. Events sharing a partition_key are delivered to a
   * subscriber in emit order (e.g. all events for one pipeline run, keyed by its
   * run id), where the transport supports partitioned/ordered delivery. Empty ==
   * no ordering guarantee beyond the transport's default.
   *
   * @generated from field: string partition_key = 7;
   */
  partitionKey: string;
};

/**
 * Describes the message rat.common.v1.Event.
 * Use `create(EventSchema)` to create a new message.
 */
export const EventSchema: GenMessage<Event> = /*@__PURE__*/
  messageDesc(file_rat_common_v1_event, 0);

