# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from rat.auditlog.v1 import auditlog_pb2 as rat_dot_auditlog_dot_v1_dot_auditlog__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rat/auditlog/v1/auditlog_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuditLogServiceStub(object):
    """NOTE (0c): the cross-cutting audit RECORD — common.v1.AuditRecord +
    common.v1.AuditOutcome — lives in common/v1/audit.proto, because the CORE authors
    + signs + emits it even when NO audit-log plugin is installed. This axis is only
    the export SINK; the messages below are its Append SERVICE wire shapes.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Append = channel.unary_unary(
                '/rat.auditlog.v1.AuditLogService/Append',
                request_serializer=rat_dot_auditlog_dot_v1_dot_auditlog__pb2.AppendRequest.SerializeToString,
                response_deserializer=rat_dot_auditlog_dot_v1_dot_auditlog__pb2.AppendResponse.FromString,
                _registered_method=True)


class AuditLogServiceServicer(object):
    """NOTE (0c): the cross-cutting audit RECORD — common.v1.AuditRecord +
    common.v1.AuditOutcome — lives in common/v1/audit.proto, because the CORE authors
    + signs + emits it even when NO audit-log plugin is installed. This axis is only
    the export SINK; the messages below are its Append SERVICE wire shapes.

    """

    def Append(self, request, context):
        """rat://auditlog/v1/append — append core-authored, core-signed audit records
        to the sink. CORE-ONLY: this capability is not grantable to ordinary
        plugins. Records are also retained core-locally, so the sink is a fan-out,
        not the only copy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuditLogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Append': grpc.unary_unary_rpc_method_handler(
                    servicer.Append,
                    request_deserializer=rat_dot_auditlog_dot_v1_dot_auditlog__pb2.AppendRequest.FromString,
                    response_serializer=rat_dot_auditlog_dot_v1_dot_auditlog__pb2.AppendResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rat.auditlog.v1.AuditLogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rat.auditlog.v1.AuditLogService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuditLogService(object):
    """NOTE (0c): the cross-cutting audit RECORD — common.v1.AuditRecord +
    common.v1.AuditOutcome — lives in common/v1/audit.proto, because the CORE authors
    + signs + emits it even when NO audit-log plugin is installed. This axis is only
    the export SINK; the messages below are its Append SERVICE wire shapes.

    """

    @staticmethod
    def Append(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rat.auditlog.v1.AuditLogService/Append',
            rat_dot_auditlog_dot_v1_dot_auditlog__pb2.AppendRequest.SerializeToString,
            rat_dot_auditlog_dot_v1_dot_auditlog__pb2.AppendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
