// UI (experience) axis service contract. DRAFT — sub-phase 0b.
//
// A `kind: ui` plugin (web-portal, CLI, Slack bot, VS Code extension) is an
// experience surface. The platform's multi-UI story (overview.md / Phase 5) is
// "each UI is a separate ui plugin" — so this contract is deliberately thin: a
// UI plugin mostly CONSUMES the API gateway like any other client. What the core
// needs from it is (a) discovery of what surfaces/slots it exposes, and (b) the
// ability to render contributions other plugins declare via `contributes.slots`
// in their manifest (the portal-slot mechanism — overview.md contract triple).
//
// Capability mapping:
//   rat://ui/v1/describe -> Describe (what this UI exposes + which slots it hosts)
//   rat://ui/v1/render-slot -> RenderSlot (resolve a contributed slot to render info)
//
// Slot targets are capability-shaped URIs (e.g. rat://ui/v1/pipeline-detail), the
// same ones plugins name in `contributes.slots[].target` in plugin.v1.json.

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file rat/ui/v1/ui.proto (package rat.ui.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { RequestContext } from "../../common/v1/context_pb";
import { file_rat_common_v1_context } from "../../common/v1/context_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file rat/ui/v1/ui.proto.
 */
export const file_rat_ui_v1_ui: GenFile = /*@__PURE__*/
  fileDesc("ChJyYXQvdWkvdjEvdWkucHJvdG8SCXJhdC51aS52MSJBCg9EZXNjcmliZVJlcXVlc3QSLgoHY29udGV4dBgBIAEoCzIdLnJhdC5jb21tb24udjEuUmVxdWVzdENvbnRleHQiLwoKSG9zdGVkU2xvdBIMCgRzbG90GAEgASgJEhMKC2Rlc2NyaXB0aW9uGAIgASgJIk4KEERlc2NyaWJlUmVzcG9uc2USFAoMZGlzcGxheV9uYW1lGAEgASgJEiQKBXNsb3RzGAIgAygLMhUucmF0LnVpLnYxLkhvc3RlZFNsb3QiZAoRUmVuZGVyU2xvdFJlcXVlc3QSLgoHY29udGV4dBgBIAEoCzIdLnJhdC5jb21tb24udjEuUmVxdWVzdENvbnRleHQSDAoEc2xvdBgCIAEoCRIRCgljb21wb25lbnQYAyABKAkiPQoSUmVuZGVyU2xvdFJlc3BvbnNlEhEKCWFzc2V0X3JlZhgBIAEoCRIUCgxwcm9wc19zY2hlbWEYAiABKAwymwEKCVVpU2VydmljZRJDCghEZXNjcmliZRIaLnJhdC51aS52MS5EZXNjcmliZVJlcXVlc3QaGy5yYXQudWkudjEuRGVzY3JpYmVSZXNwb25zZRJJCgpSZW5kZXJTbG90EhwucmF0LnVpLnYxLlJlbmRlclNsb3RSZXF1ZXN0Gh0ucmF0LnVpLnYxLlJlbmRlclNsb3RSZXNwb25zZUIrWilnaXRodWIuY29tL3JhdC1kZXYvcmF0L2dlbi9yYXQvdWkvdjE7dWl2MWIGcHJvdG8z", [file_rat_common_v1_context]);

/**
 * @generated from message rat.ui.v1.DescribeRequest
 */
export type DescribeRequest = Message<"rat.ui.v1.DescribeRequest"> & {
  /**
   * @generated from field: rat.common.v1.RequestContext context = 1;
   */
  context?: RequestContext | undefined;
};

/**
 * Describes the message rat.ui.v1.DescribeRequest.
 * Use `create(DescribeRequestSchema)` to create a new message.
 */
export const DescribeRequestSchema: GenMessage<DescribeRequest> = /*@__PURE__*/
  messageDesc(file_rat_ui_v1_ui, 0);

/**
 * A slot this UI can host plugin-contributed components into.
 *
 * @generated from message rat.ui.v1.HostedSlot
 */
export type HostedSlot = Message<"rat.ui.v1.HostedSlot"> & {
  /**
   * Capability-shaped slot id, e.g. "rat://ui/v1/pipeline-detail".
   *
   * @generated from field: string slot = 1;
   */
  slot: string;

  /**
   * @generated from field: string description = 2;
   */
  description: string;
};

/**
 * Describes the message rat.ui.v1.HostedSlot.
 * Use `create(HostedSlotSchema)` to create a new message.
 */
export const HostedSlotSchema: GenMessage<HostedSlot> = /*@__PURE__*/
  messageDesc(file_rat_ui_v1_ui, 1);

/**
 * @generated from message rat.ui.v1.DescribeResponse
 */
export type DescribeResponse = Message<"rat.ui.v1.DescribeResponse"> & {
  /**
   * Human label for this UI surface (e.g. "Web Portal").
   *
   * @generated from field: string display_name = 1;
   */
  displayName: string;

  /**
   * @generated from field: repeated rat.ui.v1.HostedSlot slots = 2;
   */
  slots: HostedSlot[];
};

/**
 * Describes the message rat.ui.v1.DescribeResponse.
 * Use `create(DescribeResponseSchema)` to create a new message.
 */
export const DescribeResponseSchema: GenMessage<DescribeResponse> = /*@__PURE__*/
  messageDesc(file_rat_ui_v1_ui, 2);

/**
 * @generated from message rat.ui.v1.RenderSlotRequest
 */
export type RenderSlotRequest = Message<"rat.ui.v1.RenderSlotRequest"> & {
  /**
   * @generated from field: rat.common.v1.RequestContext context = 1;
   */
  context?: RequestContext | undefined;

  /**
   * @generated from field: string slot = 2;
   */
  slot: string;

  /**
   * The contributing component name (from another plugin's contributes.slots).
   *
   * @generated from field: string component = 3;
   */
  component: string;
};

/**
 * Describes the message rat.ui.v1.RenderSlotRequest.
 * Use `create(RenderSlotRequestSchema)` to create a new message.
 */
export const RenderSlotRequestSchema: GenMessage<RenderSlotRequest> = /*@__PURE__*/
  messageDesc(file_rat_ui_v1_ui, 3);

/**
 * @generated from message rat.ui.v1.RenderSlotResponse
 */
export type RenderSlotResponse = Message<"rat.ui.v1.RenderSlotResponse"> & {
  /**
   * Asset reference the UI loads (e.g. a JS bundle URL or an OCI asset ref).
   *
   * @generated from field: string asset_ref = 1;
   */
  assetRef: string;

  /**
   * JSON Schema (serialized) describing the props the component accepts.
   *
   * @generated from field: bytes props_schema = 2;
   */
  propsSchema: Uint8Array;
};

/**
 * Describes the message rat.ui.v1.RenderSlotResponse.
 * Use `create(RenderSlotResponseSchema)` to create a new message.
 */
export const RenderSlotResponseSchema: GenMessage<RenderSlotResponse> = /*@__PURE__*/
  messageDesc(file_rat_ui_v1_ui, 4);

/**
 * @generated from service rat.ui.v1.UiService
 */
export const UiService: GenService<{
  /**
   * rat://ui/v1/describe — enumerate the surfaces this UI exposes and the slots
   * it can host contributions into.
   *
   * @generated from rpc rat.ui.v1.UiService.Describe
   */
  describe: {
    methodKind: "unary";
    input: typeof DescribeRequestSchema;
    output: typeof DescribeResponseSchema;
  },
  /**
   * rat://ui/v1/render-slot — given a slot + the contributing component, return
   * what the UI needs to render it (asset ref, props schema).
   *
   * @generated from rpc rat.ui.v1.UiService.RenderSlot
   */
  renderSlot: {
    methodKind: "unary";
    input: typeof RenderSlotRequestSchema;
    output: typeof RenderSlotResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_rat_ui_v1_ui, 0);

