// Identity axis service contract. Status: v1 (frozen — rat/1.2; ADR-003: control-plane = one ref + conformance).
//
// A `kind: identity` plugin (static-token, OIDC, mTLS) backs the core's Identity
// Gateway (one of the six core things). Every request the API gateway accepts is
// authenticated here before routing.
//
// Capability mapping:
//   rat://identity/v1/authenticate -> Authenticate (credential -> subject)
//   rat://identity/v1/authorize    -> Authorize    (subject + action -> allow?)
//
// C2 — PLUGIN-TO-CORE AUTH: this axis also resolves the plugin's OWN identity.
// Per reviews/00 Theme 3, v2 already solved this (ADR-020: per-startup platform
// token, constant-time compare). v3 inherits it as a CONTRACT: the default
// identity plugin issues a per-plugin token at registration; Authenticate
// constant-time-compares it. The default is NOT anonymous-root (reviews/04).
//
// NOTE: authz here is COARSE (is this subject allowed this action at all). The
// per-capability call authorization (C5) is enforced by the API gateway against
// the manifest `provides`/`requires`, not re-litigated per identity plugin.
//
// ERROR MODEL (reviews/06 C-5 / freeze-blocker #9), pinned at freeze so authors
// build ONE model:
//   - TRANSPORT/operational failures (backend down, malformed request) -> gRPC
//     canonical status codes.
//   - DECISION outcomes on a SUCCESSFUL rpc (a deny is a successful Authorize, so
//     a status code can't carry it) -> in-band `allowed` bool + enumerated
//     `deny_code`. Free-text `reason` is LOG/AUDIT-ONLY and MUST NOT drive caller
//     logic (returning rich reasons to an untrusted caller is an enumeration
//     oracle, reviews/04). Callers branch on `deny_code`, not `reason`.

// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file rat/identity/v1/identity.proto (package rat.identity.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AuthenticateRequest, AuthenticateResponse, AuthorizeRequest, AuthorizeResponse } from "./identity_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service rat.identity.v1.IdentityService
 */
export const IdentityService = {
  typeName: "rat.identity.v1.IdentityService",
  methods: {
    /**
     * rat://identity/v1/authenticate — validate a credential, resolve the subject.
     *
     * @generated from rpc rat.identity.v1.IdentityService.Authenticate
     */
    authenticate: {
      name: "Authenticate",
      I: AuthenticateRequest,
      O: AuthenticateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * rat://identity/v1/authorize — coarse allow/deny for a subject + action.
     *
     * @generated from rpc rat.identity.v1.IdentityService.Authorize
     */
    authorize: {
      name: "Authorize",
      I: AuthorizeRequest,
      O: AuthorizeResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

