// Identity axis service contract. Status: v1 (frozen — rat/1.2; ADR-003: control-plane = one ref + conformance).
//
// A `kind: identity` plugin (static-token, OIDC, mTLS) backs the core's Identity
// Gateway (one of the six core things). Every request the API gateway accepts is
// authenticated here before routing.
//
// Capability mapping:
//   rat://identity/v1/authenticate -> Authenticate (credential -> subject)
//   rat://identity/v1/authorize    -> Authorize    (subject + action -> allow?)
//
// C2 — PLUGIN-TO-CORE AUTH: this axis also resolves the plugin's OWN identity.
// Per reviews/00 Theme 3, v2 already solved this (ADR-020: per-startup platform
// token, constant-time compare). v3 inherits it as a CONTRACT: the default
// identity plugin issues a per-plugin token at registration; Authenticate
// constant-time-compares it. The default is NOT anonymous-root (reviews/04).
//
// NOTE: authz here is COARSE (is this subject allowed this action at all). The
// per-capability call authorization (C5) is enforced by the API gateway against
// the manifest `provides`/`requires`, not re-litigated per identity plugin.
//
// ERROR MODEL (reviews/06 C-5 / freeze-blocker #9), pinned at freeze so authors
// build ONE model:
//   - TRANSPORT/operational failures (backend down, malformed request) -> gRPC
//     canonical status codes.
//   - DECISION outcomes on a SUCCESSFUL rpc (a deny is a successful Authorize, so
//     a status code can't carry it) -> in-band `allowed` bool + enumerated
//     `deny_code`. Free-text `reason` is LOG/AUDIT-ONLY and MUST NOT drive caller
//     logic (returning rich reasons to an untrusted caller is an enumeration
//     oracle, reviews/04). Callers branch on `deny_code`, not `reason`.

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file rat/identity/v1/identity.proto (package rat.identity.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file rat/identity/v1/identity.proto.
 */
export const file_rat_identity_v1_identity: GenFile = /*@__PURE__*/
  fileDesc("Ch5yYXQvaWRlbnRpdHkvdjEvaWRlbnRpdHkucHJvdG8SD3JhdC5pZGVudGl0eS52MSI0ChNBdXRoZW50aWNhdGVSZXF1ZXN0EhcKCmNyZWRlbnRpYWwYAiABKAxCA4ABAUoECAEQAiJOChRBdXRoZW50aWNhdGVSZXNwb25zZRIVCg1hdXRoZW50aWNhdGVkGAEgASgIEg8KB3N1YmplY3QYAiABKAkSDgoGdGVuYW50GAMgASgJIjoKEEF1dGhvcml6ZVJlcXVlc3QSDgoGYWN0aW9uGAIgASgJEhAKCHJlc291cmNlGAMgASgJSgQIARACImIKEUF1dGhvcml6ZVJlc3BvbnNlEg8KB2FsbG93ZWQYASABKAgSLAoJZGVueV9jb2RlGAIgASgOMhkucmF0LmlkZW50aXR5LnYxLkRlbnlDb2RlEg4KBnJlYXNvbhgDIAEoCSqpAQoIRGVueUNvZGUSGQoVREVOWV9DT0RFX1VOU1BFQ0lGSUVEEAASHwobREVOWV9DT0RFX05PVF9BVVRIRU5USUNBVEVEEAESHwobREVOWV9DT0RFX0lOU1VGRklDSUVOVF9ST0xFEAISHgoaREVOWV9DT0RFX0FDVElPTl9GT1JCSURERU4QAxIgChxERU5ZX0NPREVfUkVTT1VSQ0VfRk9SQklEREVOEAQywgEKD0lkZW50aXR5U2VydmljZRJbCgxBdXRoZW50aWNhdGUSJC5yYXQuaWRlbnRpdHkudjEuQXV0aGVudGljYXRlUmVxdWVzdBolLnJhdC5pZGVudGl0eS52MS5BdXRoZW50aWNhdGVSZXNwb25zZRJSCglBdXRob3JpemUSIS5yYXQuaWRlbnRpdHkudjEuQXV0aG9yaXplUmVxdWVzdBoiLnJhdC5pZGVudGl0eS52MS5BdXRob3JpemVSZXNwb25zZUI3WjVnaXRodWIuY29tL3JhdC1kZXYvcmF0L2dlbi9yYXQvaWRlbnRpdHkvdjE7aWRlbnRpdHl2MWIGcHJvdG8z");

/**
 * @generated from message rat.identity.v1.AuthenticateRequest
 */
export type AuthenticateRequest = Message<"rat.identity.v1.AuthenticateRequest"> & {
  /**
   * Opaque credential (bearer token, client-cert chain, etc.). Never logged;
   * `debug_redact` makes that structural (reviews/06 SEC-8).
   *
   * @generated from field: bytes credential = 2;
   */
  credential: Uint8Array;
};

/**
 * Describes the message rat.identity.v1.AuthenticateRequest.
 * Use `create(AuthenticateRequestSchema)` to create a new message.
 */
export const AuthenticateRequestSchema: GenMessage<AuthenticateRequest> = /*@__PURE__*/
  messageDesc(file_rat_identity_v1_identity, 0);

/**
 * @generated from message rat.identity.v1.AuthenticateResponse
 */
export type AuthenticateResponse = Message<"rat.identity.v1.AuthenticateResponse"> & {
  /**
   * @generated from field: bool authenticated = 1;
   */
  authenticated: boolean;

  /**
   * The resolved subject to stamp onto downstream RequestContext.subject.
   *
   * @generated from field: string subject = 2;
   */
  subject: string;

  /**
   * The tenant this subject belongs to (stamped onto RequestContext.tenant).
   *
   * @generated from field: string tenant = 3;
   */
  tenant: string;
};

/**
 * Describes the message rat.identity.v1.AuthenticateResponse.
 * Use `create(AuthenticateResponseSchema)` to create a new message.
 */
export const AuthenticateResponseSchema: GenMessage<AuthenticateResponse> = /*@__PURE__*/
  messageDesc(file_rat_identity_v1_identity, 1);

/**
 * @generated from message rat.identity.v1.AuthorizeRequest
 */
export type AuthorizeRequest = Message<"rat.identity.v1.AuthorizeRequest"> & {
  /**
   * Action being attempted, e.g. "pipeline.run", "plane.create".
   *
   * @generated from field: string action = 2;
   */
  action: string;

  /**
   * Optional resource the action targets.
   *
   * @generated from field: string resource = 3;
   */
  resource: string;
};

/**
 * Describes the message rat.identity.v1.AuthorizeRequest.
 * Use `create(AuthorizeRequestSchema)` to create a new message.
 */
export const AuthorizeRequestSchema: GenMessage<AuthorizeRequest> = /*@__PURE__*/
  messageDesc(file_rat_identity_v1_identity, 2);

/**
 * @generated from message rat.identity.v1.AuthorizeResponse
 */
export type AuthorizeResponse = Message<"rat.identity.v1.AuthorizeResponse"> & {
  /**
   * @generated from field: bool allowed = 1;
   */
  allowed: boolean;

  /**
   * Machine-readable deny reason when allowed=false. UNSPECIFIED when allowed.
   *
   * @generated from field: rat.identity.v1.DenyCode deny_code = 2;
   */
  denyCode: DenyCode;

  /**
   * Human-readable reason — LOG/AUDIT-ONLY, never returned to drive caller logic
   * (enumeration-oracle risk). Callers branch on deny_code.
   *
   * @generated from field: string reason = 3;
   */
  reason: string;
};

/**
 * Describes the message rat.identity.v1.AuthorizeResponse.
 * Use `create(AuthorizeResponseSchema)` to create a new message.
 */
export const AuthorizeResponseSchema: GenMessage<AuthorizeResponse> = /*@__PURE__*/
  messageDesc(file_rat_identity_v1_identity, 3);

/**
 * Machine-readable deny reason for Authorize. Callers branch on this, never on
 * the free-text reason (anti-enumeration-oracle; see ERROR MODEL above).
 *
 * @generated from enum rat.identity.v1.DenyCode
 */
export enum DenyCode {
  /**
   * not a deny (allowed=true) OR reason not supplied
   *
   * @generated from enum value: DENY_CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * no/invalid subject established
   *
   * @generated from enum value: DENY_CODE_NOT_AUTHENTICATED = 1;
   */
  NOT_AUTHENTICATED = 1,

  /**
   * authenticated but lacks the required role
   *
   * @generated from enum value: DENY_CODE_INSUFFICIENT_ROLE = 2;
   */
  INSUFFICIENT_ROLE = 2,

  /**
   * the action is denied for this subject
   *
   * @generated from enum value: DENY_CODE_ACTION_FORBIDDEN = 3;
   */
  ACTION_FORBIDDEN = 3,

  /**
   * the specific resource is denied
   *
   * @generated from enum value: DENY_CODE_RESOURCE_FORBIDDEN = 4;
   */
  RESOURCE_FORBIDDEN = 4,
}

/**
 * Describes the enum rat.identity.v1.DenyCode.
 */
export const DenyCodeSchema: GenEnum<DenyCode> = /*@__PURE__*/
  enumDesc(file_rat_identity_v1_identity, 0);

/**
 * @generated from service rat.identity.v1.IdentityService
 */
export const IdentityService: GenService<{
  /**
   * rat://identity/v1/authenticate — validate a credential, resolve the subject.
   *
   * @generated from rpc rat.identity.v1.IdentityService.Authenticate
   */
  authenticate: {
    methodKind: "unary";
    input: typeof AuthenticateRequestSchema;
    output: typeof AuthenticateResponseSchema;
  },
  /**
   * rat://identity/v1/authorize — coarse allow/deny for a subject + action.
   *
   * @generated from rpc rat.identity.v1.IdentityService.Authorize
   */
  authorize: {
    methodKind: "unary";
    input: typeof AuthorizeRequestSchema;
    output: typeof AuthorizeResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_rat_identity_v1_identity, 0);

