// Core daemon control service (ADR-027). The daemon's ADMIN face: it mutates the
// RUNNING plane — add/remove a plugin without a restart — and reports the live set.
//
// This is the operator counterpart to CapabilityInvokeService (invoke.proto): that
// service is the DATA plane (a plugin calls a capability it `requires`, C5-gated);
// this is the CONTROL plane (an operator adds/removes plugins). They are deliberately
// SEPARATE services with different authorization: capability-invocation is authorized
// from the caller's manifest `requires` (C5), whereas control is an OPERATOR action —
// `rat add` is a CLI, not a plugin with a manifest — so it does not flow through C5.
// In v1 the control listener's REACHABILITY is the authorization: a per-project unix
// socket (.rat/daemon.sock, ADR-023) means filesystem permissions gate who may
// register, exactly as they gate `rat down`. Operator identity + mTLS for a networked
// (TCP) control endpoint is deferred (ADR-027 Q01).
//
// This stays within the six-thing core: it mutates the Registry and exposes an admin
// RPC on the API gateway — two EXISTING responsibilities — and reuses the reconciler's
// unchanged convergence (it only makes the desired SET mutable). No 7th core thing.
//
// Status: v1 additive (ADR-027; bound by the ADR-017 pre-unfreeze gate). Core↔operator,
// not a plugin contract.

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file rat/core/v1/control.proto (package rat.core.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file rat/core/v1/control.proto.
 */
export const file_rat_core_v1_control: GenFile = /*@__PURE__*/
  fileDesc("ChlyYXQvY29yZS92MS9jb250cm9sLnByb3RvEgtyYXQuY29yZS52MSKJAQoKTGF1bmNoU3BlYxINCgVpbWFnZRgBIAEoCRIRCglpc29sYXRpb24YAiABKAkSLQoDZW52GAMgAygLMiAucmF0LmNvcmUudjEuTGF1bmNoU3BlYy5FbnZFbnRyeRoqCghFbnZFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBImUKFVJlZ2lzdGVyUGx1Z2luUmVxdWVzdBIMCgRuYW1lGAEgASgJEhUKDW1hbmlmZXN0X3lhbWwYAiABKAwSJwoGbGF1bmNoGAMgASgLMhcucmF0LmNvcmUudjEuTGF1bmNoU3BlYyJHChZSZWdpc3RlclBsdWdpblJlc3BvbnNlEgwKBG5hbWUYASABKAkSDQoFc3RhdGUYAiABKAkSEAoIZW5kcG9pbnQYAyABKAkiJwoXRGVyZWdpc3RlclBsdWdpblJlcXVlc3QSDAoEbmFtZRgBIAEoCSI9ChhEZXJlZ2lzdGVyUGx1Z2luUmVzcG9uc2USDAoEbmFtZRgBIAEoCRITCgt3YXNfcHJlc2VudBgCIAEoCCIUChJMaXN0UGx1Z2luc1JlcXVlc3QiQQoTTGlzdFBsdWdpbnNSZXNwb25zZRIqCgdwbHVnaW5zGAEgAygLMhkucmF0LmNvcmUudjEuUGx1Z2luU3RhdHVzIl0KDFBsdWdpblN0YXR1cxIMCgRuYW1lGAEgASgJEgwKBGtpbmQYAiABKAkSDQoFc3RhdGUYAyABKAkSEAoIZW5kcG9pbnQYBCABKAkSEAoIcHJvdmlkZXMYBSADKAkyngIKDkNvbnRyb2xTZXJ2aWNlElkKDlJlZ2lzdGVyUGx1Z2luEiIucmF0LmNvcmUudjEuUmVnaXN0ZXJQbHVnaW5SZXF1ZXN0GiMucmF0LmNvcmUudjEuUmVnaXN0ZXJQbHVnaW5SZXNwb25zZRJfChBEZXJlZ2lzdGVyUGx1Z2luEiQucmF0LmNvcmUudjEuRGVyZWdpc3RlclBsdWdpblJlcXVlc3QaJS5yYXQuY29yZS52MS5EZXJlZ2lzdGVyUGx1Z2luUmVzcG9uc2USUAoLTGlzdFBsdWdpbnMSHy5yYXQuY29yZS52MS5MaXN0UGx1Z2luc1JlcXVlc3QaIC5yYXQuY29yZS52MS5MaXN0UGx1Z2luc1Jlc3BvbnNlQi9aLWdpdGh1Yi5jb20vcmF0LWRldi9yYXQvZ2VuL3JhdC9jb3JlL3YxO2NvcmV2MWIGcHJvdG8z");

/**
 * LaunchSpec is how a plugin is launched (the subset rat.toml carries). An empty image
 * means a REGISTER-ONLY driver (an operator identity that dials the gateway but is not
 * itself launched), mirroring a rat.toml [[plugin]] with no image.
 *
 * @generated from message rat.core.v1.LaunchSpec
 */
export type LaunchSpec = Message<"rat.core.v1.LaunchSpec"> & {
  /**
   * OCI image ref. Empty = a register-only driver (no launch).
   *
   * @generated from field: string image = 1;
   */
  image: string;

  /**
   * Isolation profile shorthand (e.g. "i9"); the daemon maps it to a full profile, the
   * same mapping rat.toml uses. Empty defaults to the hardened profile.
   *
   * @generated from field: string isolation = 2;
   */
  isolation: string;

  /**
   * Launch environment. NEVER secrets — only opaque refs (the *_REF convention); the
   * secret-backend resolves them at first use (ADR-022).
   *
   * @generated from field: map<string, string> env = 3;
   */
  env: { [key: string]: string };
};

/**
 * Describes the message rat.core.v1.LaunchSpec.
 * Use `create(LaunchSpecSchema)` to create a new message.
 */
export const LaunchSpecSchema: GenMessage<LaunchSpec> = /*@__PURE__*/
  messageDesc(file_rat_core_v1_control, 0);

/**
 * RegisterPluginRequest adds one plugin to the running plane.
 *
 * @generated from message rat.core.v1.RegisterPluginRequest
 */
export type RegisterPluginRequest = Message<"rat.core.v1.RegisterPluginRequest"> & {
  /**
   * The plugin's instance name in this plane (the key `rat remove` / Deregister uses).
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * The plugin's manifest as raw YAML (the frozen plugin.v1 shape). The daemon parses +
   * validates it; its kind + provides/requires are what the registry authorizes from.
   * Carried as bytes so the manifest stays YAML end to end (no proto schema dup).
   *
   * @generated from field: bytes manifest_yaml = 2;
   */
  manifestYaml: Uint8Array;

  /**
   * How to launch it. Absent (or empty image) = a register-only driver.
   *
   * @generated from field: rat.core.v1.LaunchSpec launch = 3;
   */
  launch?: LaunchSpec | undefined;
};

/**
 * Describes the message rat.core.v1.RegisterPluginRequest.
 * Use `create(RegisterPluginRequestSchema)` to create a new message.
 */
export const RegisterPluginRequestSchema: GenMessage<RegisterPluginRequest> = /*@__PURE__*/
  messageDesc(file_rat_core_v1_control, 1);

/**
 * RegisterPluginResponse reports the plugin's live state after the daemon materialized it.
 *
 * @generated from message rat.core.v1.RegisterPluginResponse
 */
export type RegisterPluginResponse = Message<"rat.core.v1.RegisterPluginResponse"> & {
  /**
   * The plugin name, echoed.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * The reconcile state after materialize (e.g. "Healthy"). A driver with no launch is
   * reported as registered without a health probe.
   *
   * @generated from field: string state = 2;
   */
  state: string;

  /**
   * Where the gateway bound the plugin (its routable endpoint); empty for a driver.
   *
   * @generated from field: string endpoint = 3;
   */
  endpoint: string;
};

/**
 * Describes the message rat.core.v1.RegisterPluginResponse.
 * Use `create(RegisterPluginResponseSchema)` to create a new message.
 */
export const RegisterPluginResponseSchema: GenMessage<RegisterPluginResponse> = /*@__PURE__*/
  messageDesc(file_rat_core_v1_control, 2);

/**
 * DeregisterPluginRequest removes one plugin from the running plane by name.
 *
 * @generated from message rat.core.v1.DeregisterPluginRequest
 */
export type DeregisterPluginRequest = Message<"rat.core.v1.DeregisterPluginRequest"> & {
  /**
   * The plugin instance name to remove.
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message rat.core.v1.DeregisterPluginRequest.
 * Use `create(DeregisterPluginRequestSchema)` to create a new message.
 */
export const DeregisterPluginRequestSchema: GenMessage<DeregisterPluginRequest> = /*@__PURE__*/
  messageDesc(file_rat_core_v1_control, 3);

/**
 * DeregisterPluginResponse confirms the removal.
 *
 * @generated from message rat.core.v1.DeregisterPluginResponse
 */
export type DeregisterPluginResponse = Message<"rat.core.v1.DeregisterPluginResponse"> & {
  /**
   * The plugin name, echoed.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Whether the plugin was actually present in the running plane (false = no-op).
   *
   * @generated from field: bool was_present = 2;
   */
  wasPresent: boolean;
};

/**
 * Describes the message rat.core.v1.DeregisterPluginResponse.
 * Use `create(DeregisterPluginResponseSchema)` to create a new message.
 */
export const DeregisterPluginResponseSchema: GenMessage<DeregisterPluginResponse> = /*@__PURE__*/
  messageDesc(file_rat_core_v1_control, 4);

/**
 * ListPluginsRequest asks for the live plane (no parameters in v1).
 *
 * @generated from message rat.core.v1.ListPluginsRequest
 */
export type ListPluginsRequest = Message<"rat.core.v1.ListPluginsRequest"> & {
};

/**
 * Describes the message rat.core.v1.ListPluginsRequest.
 * Use `create(ListPluginsRequestSchema)` to create a new message.
 */
export const ListPluginsRequestSchema: GenMessage<ListPluginsRequest> = /*@__PURE__*/
  messageDesc(file_rat_core_v1_control, 5);

/**
 * ListPluginsResponse is the live plane as the daemon sees it.
 *
 * @generated from message rat.core.v1.ListPluginsResponse
 */
export type ListPluginsResponse = Message<"rat.core.v1.ListPluginsResponse"> & {
  /**
   * One entry per plugin currently known to the running daemon.
   *
   * @generated from field: repeated rat.core.v1.PluginStatus plugins = 1;
   */
  plugins: PluginStatus[];
};

/**
 * Describes the message rat.core.v1.ListPluginsResponse.
 * Use `create(ListPluginsResponseSchema)` to create a new message.
 */
export const ListPluginsResponseSchema: GenMessage<ListPluginsResponse> = /*@__PURE__*/
  messageDesc(file_rat_core_v1_control, 6);

/**
 * PluginStatus is one plugin's live state in the running plane.
 *
 * @generated from message rat.core.v1.PluginStatus
 */
export type PluginStatus = Message<"rat.core.v1.PluginStatus"> & {
  /**
   * The plugin instance name.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * The plugin's manifest kind (the axis it implements).
   *
   * @generated from field: string kind = 2;
   */
  kind: string;

  /**
   * The reconcile state (e.g. "Healthy", "Launching", "Degraded"); "registered" for a
   * register-only driver with no health probe.
   *
   * @generated from field: string state = 3;
   */
  state: string;

  /**
   * The plugin's routable endpoint, if bound; empty for a driver or a not-yet-Healthy
   * plugin.
   *
   * @generated from field: string endpoint = 4;
   */
  endpoint: string;

  /**
   * The capability URIs this plugin provides (from its manifest).
   *
   * @generated from field: repeated string provides = 5;
   */
  provides: string[];
};

/**
 * Describes the message rat.core.v1.PluginStatus.
 * Use `create(PluginStatusSchema)` to create a new message.
 */
export const PluginStatusSchema: GenMessage<PluginStatus> = /*@__PURE__*/
  messageDesc(file_rat_core_v1_control, 7);

/**
 * ControlService is served on the daemon's CONTROL listener alongside
 * CapabilityInvokeService. rat.toml stays the source of truth; these RPCs only apply a
 * diff to the running daemon (the CLI writes the file first, then materializes).
 *
 * @generated from service rat.core.v1.ControlService
 */
export const ControlService: GenService<{
  /**
   * Add a plugin to the running plane: validate its manifest, register it (so C5
   * authorization now knows it), add it to the reconciler's desired set (launch +
   * wire), and wait — bounded — for it to become Healthy. Idempotent: re-registering
   * a present plugin refreshes its spec. On a launch/readiness failure the daemon
   * rolls the desired entry back so a failed live-add leaves no partial state.
   *
   * @generated from rpc rat.core.v1.ControlService.RegisterPlugin
   */
  registerPlugin: {
    methodKind: "unary";
    input: typeof RegisterPluginRequestSchema;
    output: typeof RegisterPluginResponseSchema;
  },
  /**
   * Remove a plugin from the running plane: drop it from the desired set (terminate
   * the instance), unbind it from the gateway, and deregister it from the registry.
   *
   * @generated from rpc rat.core.v1.ControlService.DeregisterPlugin
   */
  deregisterPlugin: {
    methodKind: "unary";
    input: typeof DeregisterPluginRequestSchema;
    output: typeof DeregisterPluginResponseSchema;
  },
  /**
   * The live plane as the daemon sees it — distinct from `rat status`, which reads
   * rat.toml. Reports each plugin's name, kind, reconcile state, endpoint, provides.
   *
   * @generated from rpc rat.core.v1.ControlService.ListPlugins
   */
  listPlugins: {
    methodKind: "unary";
    input: typeof ListPluginsRequestSchema;
    output: typeof ListPluginsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_rat_core_v1_control, 0);

