// Core capability-invoke service. Status: v1 (frozen — rat/1, ADR-009).
//
// This is the wire artifact ADR-005 requires and reviews/06 C-6 (AUTH-2 ⊕
// ARCH-2) flagged as missing: the mechanism by which a plugin actually CALLS a
// capability it `requires`. Before this, "the core wires providers in via the
// registry" was asserted in comments with no wire mechanism — the headline
// call-by-capability feature was unbuildable.
//
// MODEL — CORE-MEDIATED (ADR-005). A plugin does NOT dial providers directly.
// It calls Invoke on the core's API gateway with a capability URI + the
// already-serialized request for the target axis method. The core:
//   1. resolves the capability URI -> concrete provider via the registry,
//   2. enforces the cross-cutting properties on this hop — C2 (caller
//      authenticated), C5 (caller's manifest `requires` this capability AND the
//      provider `provides` it; the capability⇄method binding comes from the
//      (rat.common.v1.capability) method option, freeze-blocker #5),
//      C7 (tenant scoping), C3 (state-namespace derivation),
//   3. stamps/propagates C1 trace + re-derives identity.caller_plugin for the
//      downstream hop (keystone, context.proto), and emits the C8 audit record,
//   4. proxies `payload` to the provider's method and relays its response.
//
// GENERIC PROXY: the gateway routes by `capability` and forwards `payload`
// WITHOUT interpreting it — it gains no per-axis knowledge, so the six-thing core
// stays minimal (no 7th thing; this is the API gateway + registry doing their
// existing jobs). `payload` is the serialized axis request message (e.g. a
// rat.format.v1.MergeRequest); `result` is the serialized axis response.
//
// NOT here: the bulk-data path. Per "data plane bypasses core for bytes"
// (overview.md), Arrow byte transfer still flows plugin-to-plugin via
// common/v1/data.proto ArrowStream and never traverses this service — Invoke
// carries only control RPCs (refs, metadata, stream descriptors).
//
// Status: v1 (frozen — rat/1, ADR-009). The frozen capability-invoke surface.

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file rat/core/v1/invoke.proto (package rat.core.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file rat/core/v1/invoke.proto.
 */
export const file_rat_core_v1_invoke: GenFile = /*@__PURE__*/
  fileDesc("ChhyYXQvY29yZS92MS9pbnZva2UucHJvdG8SC3JhdC5jb3JlLnYxIjoKDUludm9rZVJlcXVlc3QSEgoKY2FwYWJpbGl0eRgCIAEoCRIPCgdwYXlsb2FkGAMgASgMSgQIARACIiAKDkludm9rZVJlc3BvbnNlEg4KBnJlc3VsdBgBIAEoDCJGChlJbnZva2VTZXJ2ZXJTdHJlYW1SZXF1ZXN0EhIKCmNhcGFiaWxpdHkYAiABKAkSDwoHcGF5bG9hZBgDIAEoDEoECAEQAiIsChpJbnZva2VTZXJ2ZXJTdHJlYW1SZXNwb25zZRIOCgZyZXN1bHQYASABKAwiRAoXSW52b2tlQmlkaVN0cmVhbVJlcXVlc3QSEgoKY2FwYWJpbGl0eRgCIAEoCRIPCgdwYXlsb2FkGAMgASgMSgQIARACIioKGEludm9rZUJpZGlTdHJlYW1SZXNwb25zZRIOCgZyZXN1bHQYASABKAwyqgIKF0NhcGFiaWxpdHlJbnZva2VTZXJ2aWNlEkEKBkludm9rZRIaLnJhdC5jb3JlLnYxLkludm9rZVJlcXVlc3QaGy5yYXQuY29yZS52MS5JbnZva2VSZXNwb25zZRJnChJJbnZva2VTZXJ2ZXJTdHJlYW0SJi5yYXQuY29yZS52MS5JbnZva2VTZXJ2ZXJTdHJlYW1SZXF1ZXN0GicucmF0LmNvcmUudjEuSW52b2tlU2VydmVyU3RyZWFtUmVzcG9uc2UwARJjChBJbnZva2VCaWRpU3RyZWFtEiQucmF0LmNvcmUudjEuSW52b2tlQmlkaVN0cmVhbVJlcXVlc3QaJS5yYXQuY29yZS52MS5JbnZva2VCaWRpU3RyZWFtUmVzcG9uc2UoATABQi9aLWdpdGh1Yi5jb20vcmF0LWRldi9yYXQvZ2VuL3JhdC9jb3JlL3YxO2NvcmV2MWIGcHJvdG8z");

/**
 * @generated from message rat.core.v1.InvokeRequest
 */
export type InvokeRequest = Message<"rat.core.v1.InvokeRequest"> & {
  /**
   * The capability being invoked, e.g. "rat://format/v1/merge". MUST match the
   * rat://<axis>/v<major>/<capability> grammar. The core resolves this to a
   * concrete provider + method via the registry + the (rat.common.v1.capability)
   * method annotation, and checks the caller's manifest `requires` it.
   *
   * @generated from field: string capability = 2;
   */
  capability: string;

  /**
   * The serialized request message for the target axis method (e.g. an encoded
   * rat.format.v1.MergeRequest). Opaque to the core — routed, not interpreted.
   * The target method is determined by `capability`, so the message type is
   * implied by the capability, not carried here.
   *
   * @generated from field: bytes payload = 3;
   */
  payload: Uint8Array;
};

/**
 * Describes the message rat.core.v1.InvokeRequest.
 * Use `create(InvokeRequestSchema)` to create a new message.
 */
export const InvokeRequestSchema: GenMessage<InvokeRequest> = /*@__PURE__*/
  messageDesc(file_rat_core_v1_invoke, 0);

/**
 * @generated from message rat.core.v1.InvokeResponse
 */
export type InvokeResponse = Message<"rat.core.v1.InvokeResponse"> & {
  /**
   * The serialized response message from the provider's method (e.g. an encoded
   * rat.format.v1.MergeResponse). Opaque to the core.
   *
   * Note: this contract returns the provider's success payload; failures surface
   * via gRPC status (transport/enforcement) per the canonical error model
   * ([common/v1/ERROR_MODEL.md], pinned at rat/1). Capability-not-authorized
   * (PERMISSION_DENIED), provider-unavailable (UNAVAILABLE), and unauthenticated
   * caller (UNAUTHENTICATED) are core-side enforcement failures returned as those
   * gRPC status codes, not as a field here.
   *
   * @generated from field: bytes result = 1;
   */
  result: Uint8Array;
};

/**
 * Describes the message rat.core.v1.InvokeResponse.
 * Use `create(InvokeResponseSchema)` to create a new message.
 */
export const InvokeResponseSchema: GenMessage<InvokeResponse> = /*@__PURE__*/
  messageDesc(file_rat_core_v1_invoke, 1);

/**
 * @generated from message rat.core.v1.InvokeServerStreamRequest
 */
export type InvokeServerStreamRequest = Message<"rat.core.v1.InvokeServerStreamRequest"> & {
  /**
   * The capability being invoked; same grammar + resolution as InvokeRequest. Must
   * resolve to a server-streaming provider method.
   *
   * @generated from field: string capability = 2;
   */
  capability: string;

  /**
   * The serialized request message for the target method (e.g. an encoded
   * rat.runtime.v1.ExecuteRequest). Opaque to the core.
   *
   * @generated from field: bytes payload = 3;
   */
  payload: Uint8Array;
};

/**
 * Describes the message rat.core.v1.InvokeServerStreamRequest.
 * Use `create(InvokeServerStreamRequestSchema)` to create a new message.
 */
export const InvokeServerStreamRequestSchema: GenMessage<InvokeServerStreamRequest> = /*@__PURE__*/
  messageDesc(file_rat_core_v1_invoke, 2);

/**
 * @generated from message rat.core.v1.InvokeServerStreamResponse
 */
export type InvokeServerStreamResponse = Message<"rat.core.v1.InvokeServerStreamResponse"> & {
  /**
   * One serialized axis response frame (e.g. an encoded
   * rat.runtime.v1.ExecuteResponse). Opaque to the core; relayed verbatim.
   * Failures surface via gRPC status, not a field here.
   *
   * @generated from field: bytes result = 1;
   */
  result: Uint8Array;
};

/**
 * Describes the message rat.core.v1.InvokeServerStreamResponse.
 * Use `create(InvokeServerStreamResponseSchema)` to create a new message.
 */
export const InvokeServerStreamResponseSchema: GenMessage<InvokeServerStreamResponse> = /*@__PURE__*/
  messageDesc(file_rat_core_v1_invoke, 3);

/**
 * @generated from message rat.core.v1.InvokeBidiStreamRequest
 */
export type InvokeBidiStreamRequest = Message<"rat.core.v1.InvokeBidiStreamRequest"> & {
  /**
   * Set on the FIRST frame only to establish + authorize the call; MUST be empty
   * on subsequent frames. A non-empty `capability` on a non-first frame is a
   * protocol violation — the core ABORTS the stream with INVALID_ARGUMENT (S2,
   * reviews/07: "ignored" would let a client attempt a silent mid-stream capability
   * switch; reject it, never tolerate it).
   *
   * @generated from field: string capability = 2;
   */
  capability: string;

  /**
   * One serialized axis request frame. Opaque to the core.
   *
   * @generated from field: bytes payload = 3;
   */
  payload: Uint8Array;
};

/**
 * Describes the message rat.core.v1.InvokeBidiStreamRequest.
 * Use `create(InvokeBidiStreamRequestSchema)` to create a new message.
 */
export const InvokeBidiStreamRequestSchema: GenMessage<InvokeBidiStreamRequest> = /*@__PURE__*/
  messageDesc(file_rat_core_v1_invoke, 4);

/**
 * @generated from message rat.core.v1.InvokeBidiStreamResponse
 */
export type InvokeBidiStreamResponse = Message<"rat.core.v1.InvokeBidiStreamResponse"> & {
  /**
   * One serialized axis response frame. Opaque to the core; relayed verbatim.
   *
   * @generated from field: bytes result = 1;
   */
  result: Uint8Array;
};

/**
 * Describes the message rat.core.v1.InvokeBidiStreamResponse.
 * Use `create(InvokeBidiStreamResponseSchema)` to create a new message.
 */
export const InvokeBidiStreamResponseSchema: GenMessage<InvokeBidiStreamResponse> = /*@__PURE__*/
  messageDesc(file_rat_core_v1_invoke, 5);

/**
 * CapabilityInvokeService has one Invoke variant per RPC cardinality (ADR-008).
 * All three are GENERIC byte-relays: the core enforces C2/C5/C7/C8 + traceparent
 * and stamps the downstream rat-callmeta-bin envelope (ADR-007) ONCE at the call
 * (for streams: once at stream-open), then relays opaque payload/result frames
 * without deserializing them. The caller's SDK picks the variant from the target
 * capability's cardinality. Bulk data (if any) still flows out-of-band via the
 * ArrowStream descriptors inside the relayed frames — never through this service.
 *
 * @generated from service rat.core.v1.CapabilityInvokeService
 */
export const CapabilityInvokeService: GenService<{
  /**
   * Unary→unary capabilities. One request, one response.
   *
   * @generated from rpc rat.core.v1.CapabilityInvokeService.Invoke
   */
  invoke: {
    methodKind: "unary";
    input: typeof InvokeRequestSchema;
    output: typeof InvokeResponseSchema;
  },
  /**
   * Server-streaming capabilities (e.g. runtime.Execute, state.Watch,
   * scheduler.WatchDue). One request opens the call; the core relays a stream of
   * responses, each `result` being one serialized axis response frame. Enforcement
   * + identity-stamp happen once at open; one C8 audit record per stream.
   *
   * @generated from rpc rat.core.v1.CapabilityInvokeService.InvokeServerStream
   */
  invokeServerStream: {
    methodKind: "server_streaming";
    input: typeof InvokeServerStreamRequestSchema;
    output: typeof InvokeServerStreamResponseSchema;
  },
  /**
   * Bidirectional capabilities (e.g. observability.Ingest) — and pure
   * client-streaming (the provider returns a single response frame). The FIRST
   * request frame establishes `capability` (and triggers enforcement); subsequent
   * request frames carry only `payload` and MUST leave `capability` empty.
   *
   * @generated from rpc rat.core.v1.CapabilityInvokeService.InvokeBidiStream
   */
  invokeBidiStream: {
    methodKind: "bidi_streaming";
    input: typeof InvokeBidiStreamRequestSchema;
    output: typeof InvokeBidiStreamResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_rat_core_v1_invoke, 0);

