// Core capability-invoke service. Status: v1 (frozen — rat/1, ADR-009).
//
// This is the wire artifact ADR-005 requires and reviews/06 C-6 (AUTH-2 ⊕
// ARCH-2) flagged as missing: the mechanism by which a plugin actually CALLS a
// capability it `requires`. Before this, "the core wires providers in via the
// registry" was asserted in comments with no wire mechanism — the headline
// call-by-capability feature was unbuildable.
//
// MODEL — CORE-MEDIATED (ADR-005). A plugin does NOT dial providers directly.
// It calls Invoke on the core's API gateway with a capability URI + the
// already-serialized request for the target axis method. The core:
//   1. resolves the capability URI -> concrete provider via the registry,
//   2. enforces the cross-cutting properties on this hop — C2 (caller
//      authenticated), C5 (caller's manifest `requires` this capability AND the
//      provider `provides` it; the capability⇄method binding comes from the
//      (rat.common.v1.capability) method option, freeze-blocker #5),
//      C7 (tenant scoping), C3 (state-namespace derivation),
//   3. stamps/propagates C1 trace + re-derives identity.caller_plugin for the
//      downstream hop (keystone, context.proto), and emits the C8 audit record,
//   4. proxies `payload` to the provider's method and relays its response.
//
// GENERIC PROXY: the gateway routes by `capability` and forwards `payload`
// WITHOUT interpreting it — it gains no per-axis knowledge, so the six-thing core
// stays minimal (no 7th thing; this is the API gateway + registry doing their
// existing jobs). `payload` is the serialized axis request message (e.g. a
// rat.format.v1.MergeRequest); `result` is the serialized axis response.
//
// NOT here: the bulk-data path. Per "data plane bypasses core for bytes"
// (overview.md), Arrow byte transfer still flows plugin-to-plugin via
// common/v1/data.proto ArrowStream and never traverses this service — Invoke
// carries only control RPCs (refs, metadata, stream descriptors).
//
// Status: v1 (frozen — rat/1, ADR-009). The frozen capability-invoke surface.

// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file rat/core/v1/invoke.proto (package rat.core.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { InvokeBidiStreamRequest, InvokeBidiStreamResponse, InvokeRequest, InvokeResponse, InvokeServerStreamRequest, InvokeServerStreamResponse } from "./invoke_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * CapabilityInvokeService has one Invoke variant per RPC cardinality (ADR-008).
 * All three are GENERIC byte-relays: the core enforces C2/C5/C7/C8 + traceparent
 * and stamps the downstream rat-callmeta-bin envelope (ADR-007) ONCE at the call
 * (for streams: once at stream-open), then relays opaque payload/result frames
 * without deserializing them. The caller's SDK picks the variant from the target
 * capability's cardinality. Bulk data (if any) still flows out-of-band via the
 * ArrowStream descriptors inside the relayed frames — never through this service.
 *
 * @generated from service rat.core.v1.CapabilityInvokeService
 */
export const CapabilityInvokeService = {
  typeName: "rat.core.v1.CapabilityInvokeService",
  methods: {
    /**
     * Unary→unary capabilities. One request, one response.
     *
     * @generated from rpc rat.core.v1.CapabilityInvokeService.Invoke
     */
    invoke: {
      name: "Invoke",
      I: InvokeRequest,
      O: InvokeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Server-streaming capabilities (e.g. runtime.Execute, state.Watch,
     * scheduler.WatchDue). One request opens the call; the core relays a stream of
     * responses, each `result` being one serialized axis response frame. Enforcement
     * + identity-stamp happen once at open; one C8 audit record per stream.
     *
     * @generated from rpc rat.core.v1.CapabilityInvokeService.InvokeServerStream
     */
    invokeServerStream: {
      name: "InvokeServerStream",
      I: InvokeServerStreamRequest,
      O: InvokeServerStreamResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * Bidirectional capabilities (e.g. observability.Ingest) — and pure
     * client-streaming (the provider returns a single response frame). The FIRST
     * request frame establishes `capability` (and triggers enforcement); subsequent
     * request frames carry only `payload` and MUST leave `capability` empty.
     *
     * @generated from rpc rat.core.v1.CapabilityInvokeService.InvokeBidiStream
     */
    invokeBidiStream: {
      name: "InvokeBidiStream",
      I: InvokeBidiStreamRequest,
      O: InvokeBidiStreamResponse,
      kind: MethodKind.BiDiStreaming,
    },
  }
} as const;

