// Strategy axis service contract. Status: v1 (frozen — rat/1.1, ADR-009 trigger:
// two strategy references — fullrefresh-py + scd2-py — validate the contract).
//
// A `kind: strategy` plugin (scd2, soft-delete, full-refresh, …) encodes HOW
// data is transformed/loaded. It is the cleanest expression of the capability
// model: a strategy `requires` format-capabilities (scan/merge/append) +
// a runtime, and works across EVERY format that provides them without naming any
// (reviews/02: "the cleanest idea in the whole design").
//
// Capability mapping:
//   rat://strategy/v1/apply -> Apply

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file rat/strategy/v1/strategy.proto (package rat.strategy.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { TableRef, WriteResult } from "../../common/v1/data_pb";
import { file_rat_common_v1_data } from "../../common/v1/data_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file rat/strategy/v1/strategy.proto.
 */
export const file_rat_strategy_v1_strategy: GenFile = /*@__PURE__*/
  fileDesc("Ch5yYXQvc3RyYXRlZ3kvdjEvc3RyYXRlZ3kucHJvdG8SD3JhdC5zdHJhdGVneS52MSJ3CgxBcHBseVJlcXVlc3QSJwoGc291cmNlGAIgASgLMhcucmF0LmNvbW1vbi52MS5UYWJsZVJlZhInCgZ0YXJnZXQYAyABKAsyFy5yYXQuY29tbW9uLnYxLlRhYmxlUmVmEg8KB29wdGlvbnMYBCABKAxKBAgBEAIiOwoNQXBwbHlSZXNwb25zZRIqCgZyZXN1bHQYASABKAsyGi5yYXQuY29tbW9uLnYxLldyaXRlUmVzdWx0MlkKD1N0cmF0ZWd5U2VydmljZRJGCgVBcHBseRIdLnJhdC5zdHJhdGVneS52MS5BcHBseVJlcXVlc3QaHi5yYXQuc3RyYXRlZ3kudjEuQXBwbHlSZXNwb25zZUI3WjVnaXRodWIuY29tL3JhdC1kZXYvcmF0L2dlbi9yYXQvc3RyYXRlZ3kvdjE7c3RyYXRlZ3l2MWIGcHJvdG8z", [file_rat_common_v1_data]);

/**
 * @generated from message rat.strategy.v1.ApplyRequest
 */
export type ApplyRequest = Message<"rat.strategy.v1.ApplyRequest"> & {
  /**
   * Source dataset to read from.
   *
   * @generated from field: rat.common.v1.TableRef source = 2;
   */
  source?: TableRef | undefined;

  /**
   * Target dataset to write into.
   *
   * @generated from field: rat.common.v1.TableRef target = 3;
   */
  target?: TableRef | undefined;

  /**
   * Strategy-specific options. ENCODING PINNED (reviews/06 API-12): these bytes
   * are UTF-8 JSON, validated against the plugin's own metadata_schema (manifest).
   * Opaque to the core (it does not parse them); the strategy decodes per its
   * declared schema. Pinned at freeze so the bytes field's meaning can't shift.
   *
   * @generated from field: bytes options = 4;
   */
  options: Uint8Array;
};

/**
 * Describes the message rat.strategy.v1.ApplyRequest.
 * Use `create(ApplyRequestSchema)` to create a new message.
 */
export const ApplyRequestSchema: GenMessage<ApplyRequest> = /*@__PURE__*/
  messageDesc(file_rat_strategy_v1_strategy, 0);

/**
 * @generated from message rat.strategy.v1.ApplyResponse
 */
export type ApplyResponse = Message<"rat.strategy.v1.ApplyResponse"> & {
  /**
   * @generated from field: rat.common.v1.WriteResult result = 1;
   */
  result?: WriteResult | undefined;
};

/**
 * Describes the message rat.strategy.v1.ApplyResponse.
 * Use `create(ApplyResponseSchema)` to create a new message.
 */
export const ApplyResponseSchema: GenMessage<ApplyResponse> = /*@__PURE__*/
  messageDesc(file_rat_strategy_v1_strategy, 1);

/**
 * @generated from service rat.strategy.v1.StrategyService
 */
export const StrategyService: GenService<{
  /**
   * rat://strategy/v1/apply — apply the strategy for one pipeline run. The
   * strategy orchestrates its required capabilities (e.g. Resolve source via a
   * a format capability, transform via a runtime, Write back via a
   * format capability) — but it does so by capability, never by plugin name.
   * The strategy reaches those providers through the core capability-invoke
   * gateway (core/v1 Invoke, ADR-005), which resolves each capability URI to a
   * concrete provider via the registry and mediates the call.
   *
   * @generated from rpc rat.strategy.v1.StrategyService.Apply
   */
  apply: {
    methodKind: "unary";
    input: typeof ApplyRequestSchema;
    output: typeof ApplyResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_rat_strategy_v1_strategy, 0);

