#!/usr/bin/env bash
# Regenerate the per-language plugin SDKs from contracts/proto (ADR-006 D3).
#
# Source of truth: contracts/proto/**. Output: contracts/sdks/<lang>/ (committed,
# never hand-edited). Runs buf in a container per the project's container-only
# rule (root CLAUDE.md) — nothing is installed on the host.
#
# CODEGEN TOOLCHAIN (ADR-018 — connectionless): a language that has a
# contracts/codegen/Dockerfile.<lang> is generated by a LOCAL-plugin image
# (rat-codegen-<lang>: buf + the pinned protoc plugins) — NO BSR call at gen time
# (the cause of the ADR-017 rate-limit friction). A language without one falls back
# to the stock buf image + its remote: plugins (pre-ADR-018; rate-limited). Local
# images are built on demand (cached after the first build; `make gen-images`
# pre-builds them).
#
# Usage:
#   scripts/gen-sdks.sh           # regenerate all wired languages
#   scripts/gen-sdks.sh --check   # regenerate to a temp dir + fail if it differs
#                                  # from the committed sdks/ (CI freshness gate)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONTRACTS="$REPO_ROOT/contracts"
CODEGEN_DIR="$CONTRACTS/codegen"
BUF_IMAGE="${BUF_IMAGE:-docker.io/bufbuild/buf:1.47.2}"

# Container runtime: podman preferred (root CLAUDE.md), docker fallback.
if command -v podman >/dev/null 2>&1; then
  RUNTIME=podman
  RUNTIME_FLAGS=(--userns=keep-id)
elif command -v docker >/dev/null 2>&1; then
  RUNTIME=docker
  RUNTIME_FLAGS=()
else
  echo "error: need podman or docker (container-only project, nothing installed on host)" >&2
  exit 1
fi

# Languages wired today -> their buf.gen template + output subdir.
LANGS=(go python typescript rust)

# runner_image LANG -> the image that runs `buf generate` for LANG, on stdout.
# A local toolchain image (ADR-018) if contracts/codegen/Dockerfile.<lang> exists
# (built on demand, cached); otherwise the stock buf image (remote plugins). Build
# noise goes to stderr so stdout is just the image ref.
runner_image() {
  local lang="$1" df="$CODEGEN_DIR/Dockerfile.$1" img="rat-codegen-$1"
  if [[ -f "$df" ]]; then
    if ! "$RUNTIME" image inspect "$img" >/dev/null 2>&1; then
      echo ">> building $img (one-time; compiles the local plugins)" >&2
      "$RUNTIME" build -t "$img" -f "$df" "$CODEGEN_DIR" >&2
    fi
    echo "$img"
  else
    echo "$BUF_IMAGE"
  fi
}

run_buf_generate() {
  # $1 = workspace dir to mount as /workspace (templates write relative to it)
  local ws="$1" lang tmpl img
  for lang in "${LANGS[@]}"; do
    # Python (ADR-018 protoc-35 hybrid): there is no standalone protoc-gen-python binary
    # (it's a protoc builtin), so when a local toolchain is present python is generated by
    # rat-codegen-python's own ENTRYPOINT — standalone protoc 35 for the messages (matching
    # buf's protocolbuffers/python 7.35.0) + grpcio-tools for the grpc stubs. No buf, no BSR.
    if [[ "$lang" == "python" && -f "$CODEGEN_DIR/Dockerfile.python" ]]; then
      if ! "$RUNTIME" image inspect rat-codegen-python >/dev/null 2>&1; then
        echo ">> building rat-codegen-python (one-time)" >&2
        "$RUNTIME" build -t rat-codegen-python -f "$CODEGEN_DIR/Dockerfile.python" "$CODEGEN_DIR" >&2
      fi
      echo ">> generating python SDK (protoc-35 hybrid) [rat-codegen-python]"
      "$RUNTIME" run --rm "${RUNTIME_FLAGS[@]}" -e HOME=/tmp \
        -v "${ws}:/workspace:Z" -w /workspace rat-codegen-python
      continue
    fi
    tmpl="buf.gen.${lang}.yaml"
    img="$(runner_image "$lang")"
    echo ">> generating ${lang} SDK (${tmpl}) [${img##*/}]"
    "$RUNTIME" run --rm "${RUNTIME_FLAGS[@]}" \
      -e HOME=/tmp -e XDG_CACHE_HOME=/tmp/.cache \
      -v "${ws}:/workspace:Z" -w /workspace \
      "$img" generate --template "$tmpl"
  done
}

if [[ "${1:-}" == "--check" ]]; then
  # Freshness gate: regenerate into a throwaway copy of contracts/ and diff the
  # produced sdks/ against the committed one. Non-empty diff => protos changed but
  # sdks/ wasn't regenerated. Used by CI + (optionally) a pre-commit check.
  TMP="$(mktemp -d)"
  trap 'rm -rf "$TMP"' EXIT
  cp -r "$CONTRACTS/." "$TMP/"
  rm -rf "$TMP"/sdks
  run_buf_generate "$TMP"
  for lang in "${LANGS[@]}"; do
    # Ignore hand-added, non-generated module files (e.g. sdks/go/go.mod) — they
    # are not produced by buf and would otherwise read as a spurious diff.
    if ! diff -r \
        --exclude=go.mod --exclude=go.sum \
        "$CONTRACTS/sdks/$lang" "$TMP/sdks/$lang" >/dev/null 2>&1; then
      echo "error: contracts/sdks/$lang is stale — run 'make gen-sdks' and commit." >&2
      exit 1
    fi
  done
  echo "OK: all committed SDKs are up to date with contracts/proto."
else
  run_buf_generate "$CONTRACTS"
  echo "OK: regenerated SDKs into contracts/sdks/."
fi
