# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rat.format.v1 import format_pb2 as rat_dot_format_dot_v1_dot_format__pb2


class FormatServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Resolve = channel.unary_unary(
                '/rat.format.v1.FormatService/Resolve',
                request_serializer=rat_dot_format_dot_v1_dot_format__pb2.ResolveRequest.SerializeToString,
                response_deserializer=rat_dot_format_dot_v1_dot_format__pb2.ResolveResponse.FromString,
                _registered_method=True)
        self.Append = channel.unary_unary(
                '/rat.format.v1.FormatService/Append',
                request_serializer=rat_dot_format_dot_v1_dot_format__pb2.AppendRequest.SerializeToString,
                response_deserializer=rat_dot_format_dot_v1_dot_format__pb2.AppendResponse.FromString,
                _registered_method=True)
        self.Merge = channel.unary_unary(
                '/rat.format.v1.FormatService/Merge',
                request_serializer=rat_dot_format_dot_v1_dot_format__pb2.MergeRequest.SerializeToString,
                response_deserializer=rat_dot_format_dot_v1_dot_format__pb2.MergeResponse.FromString,
                _registered_method=True)
        self.Overwrite = channel.unary_unary(
                '/rat.format.v1.FormatService/Overwrite',
                request_serializer=rat_dot_format_dot_v1_dot_format__pb2.OverwriteRequest.SerializeToString,
                response_deserializer=rat_dot_format_dot_v1_dot_format__pb2.OverwriteResponse.FromString,
                _registered_method=True)
        self.Maintain = channel.unary_unary(
                '/rat.format.v1.FormatService/Maintain',
                request_serializer=rat_dot_format_dot_v1_dot_format__pb2.MaintainRequest.SerializeToString,
                response_deserializer=rat_dot_format_dot_v1_dot_format__pb2.MaintainResponse.FromString,
                _registered_method=True)


class FormatServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Resolve(self, request, context):
        """Resolve a table ref to a readable Arrow stream descriptor. Bulk bytes flow
        out-of-band via the returned ArrowStream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Append(self, request, context):
        """Append rows (no key matching). Caller hands an ArrowStream to pull from.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Merge(self, request, context):
        """Merge (upsert) rows matched on `merge_keys`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Overwrite(self, request, context):
        """Overwrite the target (replace existing data).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Maintain(self, request, context):
        """Format upkeep (compaction, snapshot expiry, manifest rewrite). Idempotent;
        safe to retry.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FormatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Resolve': grpc.unary_unary_rpc_method_handler(
                    servicer.Resolve,
                    request_deserializer=rat_dot_format_dot_v1_dot_format__pb2.ResolveRequest.FromString,
                    response_serializer=rat_dot_format_dot_v1_dot_format__pb2.ResolveResponse.SerializeToString,
            ),
            'Append': grpc.unary_unary_rpc_method_handler(
                    servicer.Append,
                    request_deserializer=rat_dot_format_dot_v1_dot_format__pb2.AppendRequest.FromString,
                    response_serializer=rat_dot_format_dot_v1_dot_format__pb2.AppendResponse.SerializeToString,
            ),
            'Merge': grpc.unary_unary_rpc_method_handler(
                    servicer.Merge,
                    request_deserializer=rat_dot_format_dot_v1_dot_format__pb2.MergeRequest.FromString,
                    response_serializer=rat_dot_format_dot_v1_dot_format__pb2.MergeResponse.SerializeToString,
            ),
            'Overwrite': grpc.unary_unary_rpc_method_handler(
                    servicer.Overwrite,
                    request_deserializer=rat_dot_format_dot_v1_dot_format__pb2.OverwriteRequest.FromString,
                    response_serializer=rat_dot_format_dot_v1_dot_format__pb2.OverwriteResponse.SerializeToString,
            ),
            'Maintain': grpc.unary_unary_rpc_method_handler(
                    servicer.Maintain,
                    request_deserializer=rat_dot_format_dot_v1_dot_format__pb2.MaintainRequest.FromString,
                    response_serializer=rat_dot_format_dot_v1_dot_format__pb2.MaintainResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rat.format.v1.FormatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rat.format.v1.FormatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FormatService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Resolve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rat.format.v1.FormatService/Resolve',
            rat_dot_format_dot_v1_dot_format__pb2.ResolveRequest.SerializeToString,
            rat_dot_format_dot_v1_dot_format__pb2.ResolveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Append(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rat.format.v1.FormatService/Append',
            rat_dot_format_dot_v1_dot_format__pb2.AppendRequest.SerializeToString,
            rat_dot_format_dot_v1_dot_format__pb2.AppendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Merge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rat.format.v1.FormatService/Merge',
            rat_dot_format_dot_v1_dot_format__pb2.MergeRequest.SerializeToString,
            rat_dot_format_dot_v1_dot_format__pb2.MergeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Overwrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rat.format.v1.FormatService/Overwrite',
            rat_dot_format_dot_v1_dot_format__pb2.OverwriteRequest.SerializeToString,
            rat_dot_format_dot_v1_dot_format__pb2.OverwriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Maintain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rat.format.v1.FormatService/Maintain',
            rat_dot_format_dot_v1_dot_format__pb2.MaintainRequest.SerializeToString,
            rat_dot_format_dot_v1_dot_format__pb2.MaintainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
