# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rat.scheduler.v1 import scheduler_pb2 as rat_dot_scheduler_dot_v1_dot_scheduler__pb2


class SchedulerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Schedule = channel.unary_unary(
                '/rat.scheduler.v1.SchedulerService/Schedule',
                request_serializer=rat_dot_scheduler_dot_v1_dot_scheduler__pb2.ScheduleRequest.SerializeToString,
                response_deserializer=rat_dot_scheduler_dot_v1_dot_scheduler__pb2.ScheduleResponse.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/rat.scheduler.v1.SchedulerService/Cancel',
                request_serializer=rat_dot_scheduler_dot_v1_dot_scheduler__pb2.CancelRequest.SerializeToString,
                response_deserializer=rat_dot_scheduler_dot_v1_dot_scheduler__pb2.CancelResponse.FromString,
                _registered_method=True)
        self.WatchDue = channel.unary_stream(
                '/rat.scheduler.v1.SchedulerService/WatchDue',
                request_serializer=rat_dot_scheduler_dot_v1_dot_scheduler__pb2.WatchDueRequest.SerializeToString,
                response_deserializer=rat_dot_scheduler_dot_v1_dot_scheduler__pb2.WatchDueResponse.FromString,
                _registered_method=True)


class SchedulerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Schedule(self, request, context):
        """rat://scheduler/v1/schedule — register a trigger (cron expr or one-shot).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """rat://scheduler/v1/cancel — remove a previously-registered trigger.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchDue(self, request, context):
        """rat://scheduler/v1/watch-due — stream of triggers as they fire. The
        reconciler consumes this to know a pipeline is due.

        DELIVERY SEMANTICS (reviews/06 API-11, pinned at freeze): AT-LEAST-ONCE. A
        fired trigger MAY be redelivered (e.g. if the consumer reconnects), so the
        reconciler MUST treat WatchDue delivery as idempotent — it keys actions by
        (trigger_id, fired_at_unix_ms) and ignores a duplicate. The scheduler does
        NOT guarantee a trigger is delivered exactly once or that a missed delivery
        is dropped; a consumer that was disconnected when a trigger fired re-derives
        due-ness from declared schedule state on reconnect (the reconciler already
        re-evaluates schedules each loop). A richer ack/lease mechanism is additive
        (GA); the at-least-once guarantee is what's pinned now.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Schedule': grpc.unary_unary_rpc_method_handler(
                    servicer.Schedule,
                    request_deserializer=rat_dot_scheduler_dot_v1_dot_scheduler__pb2.ScheduleRequest.FromString,
                    response_serializer=rat_dot_scheduler_dot_v1_dot_scheduler__pb2.ScheduleResponse.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=rat_dot_scheduler_dot_v1_dot_scheduler__pb2.CancelRequest.FromString,
                    response_serializer=rat_dot_scheduler_dot_v1_dot_scheduler__pb2.CancelResponse.SerializeToString,
            ),
            'WatchDue': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchDue,
                    request_deserializer=rat_dot_scheduler_dot_v1_dot_scheduler__pb2.WatchDueRequest.FromString,
                    response_serializer=rat_dot_scheduler_dot_v1_dot_scheduler__pb2.WatchDueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rat.scheduler.v1.SchedulerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rat.scheduler.v1.SchedulerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SchedulerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Schedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rat.scheduler.v1.SchedulerService/Schedule',
            rat_dot_scheduler_dot_v1_dot_scheduler__pb2.ScheduleRequest.SerializeToString,
            rat_dot_scheduler_dot_v1_dot_scheduler__pb2.ScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rat.scheduler.v1.SchedulerService/Cancel',
            rat_dot_scheduler_dot_v1_dot_scheduler__pb2.CancelRequest.SerializeToString,
            rat_dot_scheduler_dot_v1_dot_scheduler__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchDue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rat.scheduler.v1.SchedulerService/WatchDue',
            rat_dot_scheduler_dot_v1_dot_scheduler__pb2.WatchDueRequest.SerializeToString,
            rat_dot_scheduler_dot_v1_dot_scheduler__pb2.WatchDueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
