// Tenancy axis service contract. Status: v1 (frozen — rat/1.2; ADR-003: control-plane = one ref + conformance).
//
// A `kind: tenancy` plugin decides tenant-boundary questions the core asks at
// decision points (a permission check, a sharing grant, a quota test).
//
// Capability mapping:
//   rat://tenancy/v1/decide -> Decide (a generic decision hook)
//
// C7 — TENANCY IS STRUCTURAL, NOT ADVISORY (reviews/00 Theme 4, reviews/01
// Finding 3): the tenant dimension lives in core primitives (RequestContext.identity.tenant
// threads every RPC; the state gateway namespaces by it; storage vends creds
// scoped to it). This plugin does NOT re-implement isolation — the core enforces
// it structurally. The plugin only answers POLICY questions the core can't
// hardcode (e.g. "may tenant A share dataset X with tenant B?"). The dangerous
// reading the review flagged — "isolation is an emergent property of 4 plugins
// agreeing" — is rejected: isolation is the core's job; this plugin is policy on
// top of an already-enforced boundary.
//
// ERROR MODEL (reviews/06 C-5 / freeze-blocker #9): same convention as
// identity.Authorize — transport/operational failures use gRPC status; a deny on
// a successful Decide uses the in-band `allowed` bool + enumerated `deny_code`;
// `reason` is LOG/AUDIT-ONLY and MUST NOT drive caller logic (enumeration oracle).

// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file rat/tenancy/v1/tenancy.proto (package rat.tenancy.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DecideRequest, DecideResponse } from "./tenancy_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service rat.tenancy.v1.TenancyService
 */
export const TenancyService = {
  typeName: "rat.tenancy.v1.TenancyService",
  methods: {
    /**
     * rat://tenancy/v1/decide — answer a policy decision the core poses at a hook
     * point. The core enforces the verdict; the plugin only computes it.
     *
     * @generated from rpc rat.tenancy.v1.TenancyService.Decide
     */
    decide: {
      name: "Decide",
      I: DecideRequest,
      O: DecideResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

