// Tenancy axis service contract. Status: v1 (frozen — rat/1.2; ADR-003: control-plane = one ref + conformance).
//
// A `kind: tenancy` plugin decides tenant-boundary questions the core asks at
// decision points (a permission check, a sharing grant, a quota test).
//
// Capability mapping:
//   rat://tenancy/v1/decide -> Decide (a generic decision hook)
//
// C7 — TENANCY IS STRUCTURAL, NOT ADVISORY (reviews/00 Theme 4, reviews/01
// Finding 3): the tenant dimension lives in core primitives (RequestContext.identity.tenant
// threads every RPC; the state gateway namespaces by it; storage vends creds
// scoped to it). This plugin does NOT re-implement isolation — the core enforces
// it structurally. The plugin only answers POLICY questions the core can't
// hardcode (e.g. "may tenant A share dataset X with tenant B?"). The dangerous
// reading the review flagged — "isolation is an emergent property of 4 plugins
// agreeing" — is rejected: isolation is the core's job; this plugin is policy on
// top of an already-enforced boundary.
//
// v1 SCOPE — ISOLATION-ONLY (Q02 PU-4, ADR-017; ratified 2026-06-02): v1 tenancy is
// ISOLATION-ONLY. The core structurally enforces tenant ISOLATION (equality on
// RequestContext.identity.tenant across the state gateway, storage cred-vending, and
// the invoke gateway), and this plugin may DECIDE permission/quota questions the core
// then enforces. But DECISION_KIND_SHARING is ADVISORY-NOT-ENFORCED in v1: there is
// deliberately NO frozen primitive by which an *allowed* cross-tenant share is
// ACTIONED — no delegated-tenant / grant shape exists in the state or storage wire, so
// a plugin returning allowed=true for a SHARING decision computes a verdict the core
// CANNOT carry into a cross-tenant grant. Actioned cross-tenant sharing + hierarchical
// tenancy are a deferred `v2` (a delegation primitive in state/storage — its own ADR,
// only if a user pulls for it). Treat DECISION_KIND_SHARING as informational /
// policy-signalling in v1, not as an enforceable grant. (Q02 architect F5: "decidable
// but un-actionable"; the cheap, honest scope is to enforce only the isolation v1
// actually has.)
//
// ERROR MODEL (reviews/06 C-5 / freeze-blocker #9): same convention as
// identity.Authorize — transport/operational failures use gRPC status; a deny on
// a successful Decide uses the in-band `allowed` bool + enumerated `deny_code`;
// `reason` is LOG/AUDIT-ONLY and MUST NOT drive caller logic (enumeration oracle).

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file rat/tenancy/v1/tenancy.proto (package rat.tenancy.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_rat_common_v1_annotations } from "../../common/v1/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file rat/tenancy/v1/tenancy.proto.
 */
export const file_rat_tenancy_v1_tenancy: GenFile = /*@__PURE__*/
  fileDesc("ChxyYXQvdGVuYW5jeS92MS90ZW5hbmN5LnByb3RvEg5yYXQudGVuYW5jeS52MSJ2Cg1EZWNpZGVSZXF1ZXN0EioKBGtpbmQYAiABKA4yHC5yYXQudGVuYW5jeS52MS5EZWNpc2lvbktpbmQSFgoOc3ViamVjdF9hY3Rpb24YAyABKAkSGwoTY291bnRlcnBhcnR5X3RlbmFudBgEIAEoCUoECAEQAiJeCg5EZWNpZGVSZXNwb25zZRIPCgdhbGxvd2VkGAEgASgIEisKCWRlbnlfY29kZRgCIAEoDjIYLnJhdC50ZW5hbmN5LnYxLkRlbnlDb2RlEg4KBnJlYXNvbhgDIAEoCSp/CgxEZWNpc2lvbktpbmQSHQoZREVDSVNJT05fS0lORF9VTlNQRUNJRklFRBAAEhwKGERFQ0lTSU9OX0tJTkRfUEVSTUlTU0lPThABEhkKFURFQ0lTSU9OX0tJTkRfU0hBUklORxACEhcKE0RFQ0lTSU9OX0tJTkRfUVVPVEEQAyqGAQoIRGVueUNvZGUSGQoVREVOWV9DT0RFX1VOU1BFQ0lGSUVEEAASHgoaREVOWV9DT0RFX1BPTElDWV9GT1JCSURERU4QARIcChhERU5ZX0NPREVfUVVPVEFfRVhDRUVERUQQAhIhCh1ERU5ZX0NPREVfQ1JPU1NfVEVOQU5UX0RFTklFRBADMnYKDlRlbmFuY3lTZXJ2aWNlEmQKBkRlY2lkZRIdLnJhdC50ZW5hbmN5LnYxLkRlY2lkZVJlcXVlc3QaHi5yYXQudGVuYW5jeS52MS5EZWNpZGVSZXNwb25zZSIbipciF3JhdDovL3RlbmFuY3kvdjEvZGVjaWRlQjVaM2dpdGh1Yi5jb20vcmF0LWRldi9yYXQvZ2VuL3JhdC90ZW5hbmN5L3YxO3RlbmFuY3l2MWIGcHJvdG8z", [file_rat_common_v1_annotations]);

/**
 * @generated from message rat.tenancy.v1.DecideRequest
 */
export type DecideRequest = Message<"rat.tenancy.v1.DecideRequest"> & {
  /**
   * @generated from field: rat.tenancy.v1.DecisionKind kind = 2;
   */
  kind: DecisionKind;

  /**
   * The action/resource under question (e.g. "share:dataset/orders").
   *
   * @generated from field: string subject_action = 3;
   */
  subjectAction: string;

  /**
   * For cross-tenant decisions: the other tenant involved (empty otherwise).
   *
   * @generated from field: string counterparty_tenant = 4;
   */
  counterpartyTenant: string;
};

/**
 * Describes the message rat.tenancy.v1.DecideRequest.
 * Use `create(DecideRequestSchema)` to create a new message.
 */
export const DecideRequestSchema: GenMessage<DecideRequest> = /*@__PURE__*/
  messageDesc(file_rat_tenancy_v1_tenancy, 0);

/**
 * @generated from message rat.tenancy.v1.DecideResponse
 */
export type DecideResponse = Message<"rat.tenancy.v1.DecideResponse"> & {
  /**
   * @generated from field: bool allowed = 1;
   */
  allowed: boolean;

  /**
   * Machine-readable deny reason when allowed=false. UNSPECIFIED when allowed.
   *
   * @generated from field: rat.tenancy.v1.DenyCode deny_code = 2;
   */
  denyCode: DenyCode;

  /**
   * Human-readable reason — LOG/AUDIT-ONLY (enumeration-oracle risk). Callers
   * branch on deny_code.
   *
   * @generated from field: string reason = 3;
   */
  reason: string;
};

/**
 * Describes the message rat.tenancy.v1.DecideResponse.
 * Use `create(DecideResponseSchema)` to create a new message.
 */
export const DecideResponseSchema: GenMessage<DecideResponse> = /*@__PURE__*/
  messageDesc(file_rat_tenancy_v1_tenancy, 1);

/**
 * @generated from enum rat.tenancy.v1.DecisionKind
 */
export enum DecisionKind {
  /**
   * @generated from enum value: DECISION_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: DECISION_KIND_PERMISSION = 1;
   */
  PERMISSION = 1,

  /**
   * v1: ADVISORY-NOT-ENFORCED — decidable but NOT actioned (no delegated-tenant grant
   * primitive in the v1 wire). See the "v1 SCOPE — ISOLATION-ONLY" note above
   * (Q02 PU-4 / ADR-017). Actioned sharing is a deferred v2.
   *
   * @generated from enum value: DECISION_KIND_SHARING = 2;
   */
  SHARING = 2,

  /**
   * @generated from enum value: DECISION_KIND_QUOTA = 3;
   */
  QUOTA = 3,
}

/**
 * Describes the enum rat.tenancy.v1.DecisionKind.
 */
export const DecisionKindSchema: GenEnum<DecisionKind> = /*@__PURE__*/
  enumDesc(file_rat_tenancy_v1_tenancy, 0);

/**
 * Machine-readable deny reason for Decide. Callers branch on this, never on the
 * free-text reason (anti-enumeration-oracle; see ERROR MODEL above).
 *
 * @generated from enum rat.tenancy.v1.DenyCode
 */
export enum DenyCode {
  /**
   * not a deny (allowed=true) OR reason not supplied
   *
   * @generated from enum value: DENY_CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * a tenancy policy forbids it
   *
   * @generated from enum value: DENY_CODE_POLICY_FORBIDDEN = 1;
   */
  POLICY_FORBIDDEN = 1,

  /**
   * a quota/limit was exceeded
   *
   * @generated from enum value: DENY_CODE_QUOTA_EXCEEDED = 2;
   */
  QUOTA_EXCEEDED = 2,

  /**
   * the cross-tenant share/access is denied
   *
   * @generated from enum value: DENY_CODE_CROSS_TENANT_DENIED = 3;
   */
  CROSS_TENANT_DENIED = 3,
}

/**
 * Describes the enum rat.tenancy.v1.DenyCode.
 */
export const DenyCodeSchema: GenEnum<DenyCode> = /*@__PURE__*/
  enumDesc(file_rat_tenancy_v1_tenancy, 1);

/**
 * @generated from service rat.tenancy.v1.TenancyService
 */
export const TenancyService: GenService<{
  /**
   * rat://tenancy/v1/decide — answer a policy decision the core poses at a hook
   * point. The core enforces the verdict; the plugin only computes it.
   *
   * @generated from rpc rat.tenancy.v1.TenancyService.Decide
   */
  decide: {
    methodKind: "unary";
    input: typeof DecideRequestSchema;
    output: typeof DecideResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_rat_tenancy_v1_tenancy, 0);

