# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rat/observability/v1/observability.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'rat/observability/v1/observability.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(rat/observability/v1/observability.proto\x12\x14rat.observability.v1\"\xb1\x02\n\x0eTelemetryPoint\x12\x34\n\x04type\x18\x01 \x01(\x0e\x32 .rat.observability.v1.SignalTypeR\x04type\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n\x05value\x18\x03 \x01(\x01R\x05value\x12T\n\nattributes\x18\x04 \x03(\x0b\x32\x34.rat.observability.v1.TelemetryPoint.AttributesEntryR\nattributes\x12*\n\x11timestamp_unix_ms\x18\x05 \x01(\x03R\x0ftimestampUnixMs\x1a=\n\x0f\x41ttributesEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"S\n\rIngestRequest\x12<\n\x06points\x18\x02 \x03(\x0b\x32$.rat.observability.v1.TelemetryPointR\x06pointsJ\x04\x08\x01\x10\x02\"H\n\x0eIngestResponse\x12\x1a\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x03R\x08\x61\x63\x63\x65pted\x12\x1a\n\x08rejected\x18\x02 \x01(\x03R\x08rejected*l\n\nSignalType\x12\x1b\n\x17SIGNAL_TYPE_UNSPECIFIED\x10\x00\x12\x16\n\x12SIGNAL_TYPE_METRIC\x10\x01\x12\x14\n\x10SIGNAL_TYPE_SPAN\x10\x02\x12\x13\n\x0fSIGNAL_TYPE_LOG\x10\x03\x32o\n\x14ObservabilityService\x12W\n\x06Ingest\x12#.rat.observability.v1.IngestRequest\x1a$.rat.observability.v1.IngestResponse(\x01\x30\x01\x42\x41Z?github.com/rat-dev/rat/gen/rat/observability/v1;observabilityv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rat.observability.v1.observability_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z?github.com/rat-dev/rat/gen/rat/observability/v1;observabilityv1'
  _globals['_TELEMETRYPOINT_ATTRIBUTESENTRY']._loaded_options = None
  _globals['_TELEMETRYPOINT_ATTRIBUTESENTRY']._serialized_options = b'8\001'
  _globals['_SIGNALTYPE']._serialized_start=533
  _globals['_SIGNALTYPE']._serialized_end=641
  _globals['_TELEMETRYPOINT']._serialized_start=67
  _globals['_TELEMETRYPOINT']._serialized_end=372
  _globals['_TELEMETRYPOINT_ATTRIBUTESENTRY']._serialized_start=311
  _globals['_TELEMETRYPOINT_ATTRIBUTESENTRY']._serialized_end=372
  _globals['_INGESTREQUEST']._serialized_start=374
  _globals['_INGESTREQUEST']._serialized_end=457
  _globals['_INGESTRESPONSE']._serialized_start=459
  _globals['_INGESTRESPONSE']._serialized_end=531
  _globals['_OBSERVABILITYSERVICE']._serialized_start=643
  _globals['_OBSERVABILITYSERVICE']._serialized_end=754
# @@protoc_insertion_point(module_scope)
