# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rat.strategy.v1 import strategy_pb2 as rat_dot_strategy_dot_v1_dot_strategy__pb2


class StrategyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Apply = channel.unary_unary(
                '/rat.strategy.v1.StrategyService/Apply',
                request_serializer=rat_dot_strategy_dot_v1_dot_strategy__pb2.ApplyRequest.SerializeToString,
                response_deserializer=rat_dot_strategy_dot_v1_dot_strategy__pb2.ApplyResponse.FromString,
                _registered_method=True)


class StrategyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Apply(self, request, context):
        """rat://strategy/v1/apply — apply the strategy for one pipeline run. The
        strategy orchestrates its required capabilities (e.g. Resolve source via a
        a format capability, transform via a runtime, Write back via a
        format capability) — but it does so by capability, never by plugin name.
        The strategy reaches those providers through the core capability-invoke
        gateway (core/v1 Invoke, ADR-005), which resolves each capability URI to a
        concrete provider via the registry and mediates the call.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StrategyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Apply': grpc.unary_unary_rpc_method_handler(
                    servicer.Apply,
                    request_deserializer=rat_dot_strategy_dot_v1_dot_strategy__pb2.ApplyRequest.FromString,
                    response_serializer=rat_dot_strategy_dot_v1_dot_strategy__pb2.ApplyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rat.strategy.v1.StrategyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rat.strategy.v1.StrategyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StrategyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Apply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rat.strategy.v1.StrategyService/Apply',
            rat_dot_strategy_dot_v1_dot_strategy__pb2.ApplyRequest.SerializeToString,
            rat_dot_strategy_dot_v1_dot_strategy__pb2.ApplyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
