// Scheduler-backend axis service contract. Status: v1 (frozen — rat/1.2; ADR-003: control-plane = one ref + conformance).
//
// A `kind: scheduler-backend` plugin (in-process timer, cron, Temporal,
// cloud scheduler) owns "fire this at this time / on this interval". The
// reconciler asks it WHEN; the reconciler still decides WHAT (overview.md
// reconciliation model — the scheduler is a clock, not an orchestrator).
//
// Capability mapping:
//   rat://scheduler/v1/schedule   -> Schedule
//   rat://scheduler/v1/cancel     -> Cancel
//   rat://scheduler/v1/watch-due  -> WatchDue (stream of fired triggers)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rat/scheduler/v1/scheduler.proto

package schedulerv1

import (
	_ "github.com/squat-collective/rat-v3/gen/rat/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScheduleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Caller-chosen id, used to cancel + to correlate fired triggers.
	TriggerId string `protobuf:"bytes,2,opt,name=trigger_id,json=triggerId,proto3" json:"trigger_id,omitempty"`
	// Cron expression; if empty, `at_unix_ms` is used for a one-shot.
	Cron          string `protobuf:"bytes,3,opt,name=cron,proto3" json:"cron,omitempty"`
	AtUnixMs      int64  `protobuf:"varint,4,opt,name=at_unix_ms,json=atUnixMs,proto3" json:"at_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleRequest) Reset() {
	*x = ScheduleRequest{}
	mi := &file_rat_scheduler_v1_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleRequest) ProtoMessage() {}

func (x *ScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rat_scheduler_v1_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleRequest.ProtoReflect.Descriptor instead.
func (*ScheduleRequest) Descriptor() ([]byte, []int) {
	return file_rat_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *ScheduleRequest) GetTriggerId() string {
	if x != nil {
		return x.TriggerId
	}
	return ""
}

func (x *ScheduleRequest) GetCron() string {
	if x != nil {
		return x.Cron
	}
	return ""
}

func (x *ScheduleRequest) GetAtUnixMs() int64 {
	if x != nil {
		return x.AtUnixMs
	}
	return 0
}

type ScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TriggerId     string                 `protobuf:"bytes,1,opt,name=trigger_id,json=triggerId,proto3" json:"trigger_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleResponse) Reset() {
	*x = ScheduleResponse{}
	mi := &file_rat_scheduler_v1_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleResponse) ProtoMessage() {}

func (x *ScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rat_scheduler_v1_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleResponse.ProtoReflect.Descriptor instead.
func (*ScheduleResponse) Descriptor() ([]byte, []int) {
	return file_rat_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *ScheduleResponse) GetTriggerId() string {
	if x != nil {
		return x.TriggerId
	}
	return ""
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TriggerId     string                 `protobuf:"bytes,2,opt,name=trigger_id,json=triggerId,proto3" json:"trigger_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_rat_scheduler_v1_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rat_scheduler_v1_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_rat_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *CancelRequest) GetTriggerId() string {
	if x != nil {
		return x.TriggerId
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cancelled     bool                   `protobuf:"varint,1,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_rat_scheduler_v1_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rat_scheduler_v1_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_rat_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *CancelResponse) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

type WatchDueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchDueRequest) Reset() {
	*x = WatchDueRequest{}
	mi := &file_rat_scheduler_v1_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchDueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchDueRequest) ProtoMessage() {}

func (x *WatchDueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rat_scheduler_v1_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchDueRequest.ProtoReflect.Descriptor instead.
func (*WatchDueRequest) Descriptor() ([]byte, []int) {
	return file_rat_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{4}
}

// One fired trigger.
type WatchDueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TriggerId     string                 `protobuf:"bytes,1,opt,name=trigger_id,json=triggerId,proto3" json:"trigger_id,omitempty"`
	FiredAtUnixMs int64                  `protobuf:"varint,2,opt,name=fired_at_unix_ms,json=firedAtUnixMs,proto3" json:"fired_at_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchDueResponse) Reset() {
	*x = WatchDueResponse{}
	mi := &file_rat_scheduler_v1_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchDueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchDueResponse) ProtoMessage() {}

func (x *WatchDueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rat_scheduler_v1_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchDueResponse.ProtoReflect.Descriptor instead.
func (*WatchDueResponse) Descriptor() ([]byte, []int) {
	return file_rat_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *WatchDueResponse) GetTriggerId() string {
	if x != nil {
		return x.TriggerId
	}
	return ""
}

func (x *WatchDueResponse) GetFiredAtUnixMs() int64 {
	if x != nil {
		return x.FiredAtUnixMs
	}
	return 0
}

var File_rat_scheduler_v1_scheduler_proto protoreflect.FileDescriptor

const file_rat_scheduler_v1_scheduler_proto_rawDesc = "" +
	"\n" +
	" rat/scheduler/v1/scheduler.proto\x12\x10rat.scheduler.v1\x1a\x1frat/common/v1/annotations.proto\"h\n" +
	"\x0fScheduleRequest\x12\x1d\n" +
	"\n" +
	"trigger_id\x18\x02 \x01(\tR\ttriggerId\x12\x12\n" +
	"\x04cron\x18\x03 \x01(\tR\x04cron\x12\x1c\n" +
	"\n" +
	"at_unix_ms\x18\x04 \x01(\x03R\batUnixMsJ\x04\b\x01\x10\x02\"1\n" +
	"\x10ScheduleResponse\x12\x1d\n" +
	"\n" +
	"trigger_id\x18\x01 \x01(\tR\ttriggerId\"4\n" +
	"\rCancelRequest\x12\x1d\n" +
	"\n" +
	"trigger_id\x18\x02 \x01(\tR\ttriggerIdJ\x04\b\x01\x10\x02\".\n" +
	"\x0eCancelResponse\x12\x1c\n" +
	"\tcancelled\x18\x01 \x01(\bR\tcancelled\"\x17\n" +
	"\x0fWatchDueRequestJ\x04\b\x01\x10\x02\"Z\n" +
	"\x10WatchDueResponse\x12\x1d\n" +
	"\n" +
	"trigger_id\x18\x01 \x01(\tR\ttriggerId\x12'\n" +
	"\x10fired_at_unix_ms\x18\x02 \x01(\x03R\rfiredAtUnixMs2\xe9\x02\n" +
	"\x10SchedulerService\x12r\n" +
	"\bSchedule\x12!.rat.scheduler.v1.ScheduleRequest\x1a\".rat.scheduler.v1.ScheduleResponse\"\x1f\x8a\x97\"\x1brat://scheduler/v1/schedule\x12j\n" +
	"\x06Cancel\x12\x1f.rat.scheduler.v1.CancelRequest\x1a .rat.scheduler.v1.CancelResponse\"\x1d\x8a\x97\"\x19rat://scheduler/v1/cancel\x12u\n" +
	"\bWatchDue\x12!.rat.scheduler.v1.WatchDueRequest\x1a\".rat.scheduler.v1.WatchDueResponse\" \x8a\x97\"\x1crat://scheduler/v1/watch-due0\x01BEZCgithub.com/squat-collective/rat-v3/gen/rat/scheduler/v1;schedulerv1b\x06proto3"

var (
	file_rat_scheduler_v1_scheduler_proto_rawDescOnce sync.Once
	file_rat_scheduler_v1_scheduler_proto_rawDescData []byte
)

func file_rat_scheduler_v1_scheduler_proto_rawDescGZIP() []byte {
	file_rat_scheduler_v1_scheduler_proto_rawDescOnce.Do(func() {
		file_rat_scheduler_v1_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rat_scheduler_v1_scheduler_proto_rawDesc), len(file_rat_scheduler_v1_scheduler_proto_rawDesc)))
	})
	return file_rat_scheduler_v1_scheduler_proto_rawDescData
}

var file_rat_scheduler_v1_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rat_scheduler_v1_scheduler_proto_goTypes = []any{
	(*ScheduleRequest)(nil),  // 0: rat.scheduler.v1.ScheduleRequest
	(*ScheduleResponse)(nil), // 1: rat.scheduler.v1.ScheduleResponse
	(*CancelRequest)(nil),    // 2: rat.scheduler.v1.CancelRequest
	(*CancelResponse)(nil),   // 3: rat.scheduler.v1.CancelResponse
	(*WatchDueRequest)(nil),  // 4: rat.scheduler.v1.WatchDueRequest
	(*WatchDueResponse)(nil), // 5: rat.scheduler.v1.WatchDueResponse
}
var file_rat_scheduler_v1_scheduler_proto_depIdxs = []int32{
	0, // 0: rat.scheduler.v1.SchedulerService.Schedule:input_type -> rat.scheduler.v1.ScheduleRequest
	2, // 1: rat.scheduler.v1.SchedulerService.Cancel:input_type -> rat.scheduler.v1.CancelRequest
	4, // 2: rat.scheduler.v1.SchedulerService.WatchDue:input_type -> rat.scheduler.v1.WatchDueRequest
	1, // 3: rat.scheduler.v1.SchedulerService.Schedule:output_type -> rat.scheduler.v1.ScheduleResponse
	3, // 4: rat.scheduler.v1.SchedulerService.Cancel:output_type -> rat.scheduler.v1.CancelResponse
	5, // 5: rat.scheduler.v1.SchedulerService.WatchDue:output_type -> rat.scheduler.v1.WatchDueResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rat_scheduler_v1_scheduler_proto_init() }
func file_rat_scheduler_v1_scheduler_proto_init() {
	if File_rat_scheduler_v1_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rat_scheduler_v1_scheduler_proto_rawDesc), len(file_rat_scheduler_v1_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rat_scheduler_v1_scheduler_proto_goTypes,
		DependencyIndexes: file_rat_scheduler_v1_scheduler_proto_depIdxs,
		MessageInfos:      file_rat_scheduler_v1_scheduler_proto_msgTypes,
	}.Build()
	File_rat_scheduler_v1_scheduler_proto = out.File
	file_rat_scheduler_v1_scheduler_proto_goTypes = nil
	file_rat_scheduler_v1_scheduler_proto_depIdxs = nil
}
