// Observability axis service contract. Status: v1 (frozen — rat/1.2; ADR-003: control-plane = one ref + conformance).
//
// A `kind: observability` plugin (Prometheus, OTel collector, Datadog) RECEIVES
// telemetry the core + plugins emit and ships it onward.
//
// IMPORTANT (reviews/00 Theme 1 + reviews/03 I1): the core's OWN observability
// (its `/metrics`, its OTel spans, its reconcile-loop SLIs) is NATIVE — it does
// NOT depend on any observability plugin being installed. This axis is for
// EXPORT/fan-out + enriching with plugin-supplied telemetry, not for making the
// platform's own health opt-in. "observability: none" must still leave the core
// self-observable. This proto is therefore an export sink, not the source of
// truth for core health.
//
// Capability mapping:
//   rat://observability/v1/ingest -> Ingest (stream of telemetry points)

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file rat/observability/v1/observability.proto (package rat.observability.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_rat_common_v1_annotations } from "../../common/v1/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file rat/observability/v1/observability.proto.
 */
export const file_rat_observability_v1_observability: GenFile = /*@__PURE__*/
  fileDesc("CihyYXQvb2JzZXJ2YWJpbGl0eS92MS9vYnNlcnZhYmlsaXR5LnByb3RvEhRyYXQub2JzZXJ2YWJpbGl0eS52MSL1AQoOVGVsZW1ldHJ5UG9pbnQSLgoEdHlwZRgBIAEoDjIgLnJhdC5vYnNlcnZhYmlsaXR5LnYxLlNpZ25hbFR5cGUSDAoEbmFtZRgCIAEoCRINCgV2YWx1ZRgDIAEoARJICgphdHRyaWJ1dGVzGAQgAygLMjQucmF0Lm9ic2VydmFiaWxpdHkudjEuVGVsZW1ldHJ5UG9pbnQuQXR0cmlidXRlc0VudHJ5EhkKEXRpbWVzdGFtcF91bml4X21zGAUgASgDGjEKD0F0dHJpYnV0ZXNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBIksKDUluZ2VzdFJlcXVlc3QSNAoGcG9pbnRzGAIgAygLMiQucmF0Lm9ic2VydmFiaWxpdHkudjEuVGVsZW1ldHJ5UG9pbnRKBAgBEAIiNAoOSW5nZXN0UmVzcG9uc2USEAoIYWNjZXB0ZWQYASABKAMSEAoIcmVqZWN0ZWQYAiABKAMqbAoKU2lnbmFsVHlwZRIbChdTSUdOQUxfVFlQRV9VTlNQRUNJRklFRBAAEhYKElNJR05BTF9UWVBFX01FVFJJQxABEhQKEFNJR05BTF9UWVBFX1NQQU4QAhITCg9TSUdOQUxfVFlQRV9MT0cQAzKSAQoUT2JzZXJ2YWJpbGl0eVNlcnZpY2USegoGSW5nZXN0EiMucmF0Lm9ic2VydmFiaWxpdHkudjEuSW5nZXN0UmVxdWVzdBokLnJhdC5vYnNlcnZhYmlsaXR5LnYxLkluZ2VzdFJlc3BvbnNlIiGKlyIdcmF0Oi8vb2JzZXJ2YWJpbGl0eS92MS9pbmdlc3QoATABQkFaP2dpdGh1Yi5jb20vcmF0LWRldi9yYXQvZ2VuL3JhdC9vYnNlcnZhYmlsaXR5L3YxO29ic2VydmFiaWxpdHl2MWIGcHJvdG8z", [file_rat_common_v1_annotations]);

/**
 * @generated from message rat.observability.v1.TelemetryPoint
 */
export type TelemetryPoint = Message<"rat.observability.v1.TelemetryPoint"> & {
  /**
   * @generated from field: rat.observability.v1.SignalType type = 1;
   */
  type: SignalType;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * Numeric value for metrics; ignored for spans/logs.
   *
   * @generated from field: double value = 3;
   */
  value: number;

  /**
   * Structured attributes (incl. trace_id/run_id for correlation — C1).
   *
   * @generated from field: map<string, string> attributes = 4;
   */
  attributes: { [key: string]: string };

  /**
   * @generated from field: int64 timestamp_unix_ms = 5;
   */
  timestampUnixMs: bigint;
};

/**
 * Describes the message rat.observability.v1.TelemetryPoint.
 * Use `create(TelemetryPointSchema)` to create a new message.
 */
export const TelemetryPointSchema: GenMessage<TelemetryPoint> = /*@__PURE__*/
  messageDesc(file_rat_observability_v1_observability, 0);

/**
 * @generated from message rat.observability.v1.IngestRequest
 */
export type IngestRequest = Message<"rat.observability.v1.IngestRequest"> & {
  /**
   * @generated from field: repeated rat.observability.v1.TelemetryPoint points = 2;
   */
  points: TelemetryPoint[];
};

/**
 * Describes the message rat.observability.v1.IngestRequest.
 * Use `create(IngestRequestSchema)` to create a new message.
 */
export const IngestRequestSchema: GenMessage<IngestRequest> = /*@__PURE__*/
  messageDesc(file_rat_observability_v1_observability, 1);

/**
 * Acknowledgement for the batches received so far on this bidi stream. The sink
 * emits one per inbound batch (or periodically); counts are cumulative for the
 * stream so the emitter can track progress and apply backpressure.
 *
 * @generated from message rat.observability.v1.IngestResponse
 */
export type IngestResponse = Message<"rat.observability.v1.IngestResponse"> & {
  /**
   * @generated from field: int64 accepted = 1;
   */
  accepted: bigint;

  /**
   * @generated from field: int64 rejected = 2;
   */
  rejected: bigint;
};

/**
 * Describes the message rat.observability.v1.IngestResponse.
 * Use `create(IngestResponseSchema)` to create a new message.
 */
export const IngestResponseSchema: GenMessage<IngestResponse> = /*@__PURE__*/
  messageDesc(file_rat_observability_v1_observability, 2);

/**
 * @generated from enum rat.observability.v1.SignalType
 */
export enum SignalType {
  /**
   * @generated from enum value: SIGNAL_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SIGNAL_TYPE_METRIC = 1;
   */
  METRIC = 1,

  /**
   * @generated from enum value: SIGNAL_TYPE_SPAN = 2;
   */
  SPAN = 2,

  /**
   * @generated from enum value: SIGNAL_TYPE_LOG = 3;
   */
  LOG = 3,
}

/**
 * Describes the enum rat.observability.v1.SignalType.
 */
export const SignalTypeSchema: GenEnum<SignalType> = /*@__PURE__*/
  enumDesc(file_rat_observability_v1_observability, 0);

/**
 * @generated from service rat.observability.v1.ObservabilityService
 */
export const ObservabilityService: GenService<{
  /**
   * rat://observability/v1/ingest — stream telemetry into the sink.
   *
   * BIDI-STREAMING (reviews/06 API-4 / freeze-blocker #9): the old shape was
   * client-streaming with a SINGLE terminal ack — for a process-lifetime
   * telemetry stream the sink would ack only at stream close (≈never), giving no
   * backpressure and no partial-failure feedback. Bidi lets the sink return an
   * IngestResponse per batch (or periodically), so the emitter sees accepted /
   * rejected counts incrementally and can flow-control. Streaming-shape changes
   * are wire-breaking, hence pre-freeze.
   *
   * @generated from rpc rat.observability.v1.ObservabilityService.Ingest
   */
  ingest: {
    methodKind: "bidi_streaming";
    input: typeof IngestRequestSchema;
    output: typeof IngestResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_rat_observability_v1_observability, 0);

