// Engine axis service contract. Status: v1 (frozen — rat/1, ADR-009).
//
// A `kind: engine` plugin (DuckDB, ClickHouse, Spark, Trino, BigQuery) turns
// SQL into Arrow. It is the compute axis: the strategy/runtime hand it SQL +
// table refs; it executes and returns an Arrow stream descriptor.
//
// Capability mapping (machine-readable via (rat.common.v1.capability) — #5):
//   rat://engine/v1/execute -> Execute (run a statement, no rows expected back)
//   rat://engine/v1/query   -> Query   (SELECT -> Arrow stream)
//   rat://engine/v1/preview -> Preview (bounded sample, for UI/inspection)
//
// NOTE (reviews/06 I-3 "split engine.Execute"): engine needs NO per-mode split —
// unlike format.Write (which was one RPC keyed by a WriteMode enum), engine's
// three methods are ALREADY distinct RPCs mapping 1:1 to three capabilities. The
// fix engine needed was the machine-readable capability binding (below), not a
// split. Recorded so the deviation from the blocker's wording is explicit.
//
// C6: each capability has a golden-data conformance vector (the engine ↔ format
// handoff is where "fits != works" bites hardest — reviews/00 Theme 4).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rat/engine/v1/engine.proto

package enginev1

import (
	v1 "github.com/squat-collective/rat-v3/gen/rat/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Sql   string                 `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	// Tables referenced by the statement, so the core can resolve providers and
	// the engine can bind them without parsing SQL for refs.
	Tables        []*v1.TableRef `protobuf:"bytes,3,rep,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_rat_engine_v1_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rat_engine_v1_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_rat_engine_v1_engine_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *ExecuteRequest) GetTables() []*v1.TableRef {
	if x != nil {
		return x.Tables
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *v1.WriteResult        `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_rat_engine_v1_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rat_engine_v1_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_rat_engine_v1_engine_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteResponse) GetResult() *v1.WriteResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	Tables        []*v1.TableRef         `protobuf:"bytes,3,rep,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_rat_engine_v1_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rat_engine_v1_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_rat_engine_v1_engine_proto_rawDescGZIP(), []int{2}
}

func (x *QueryRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *QueryRequest) GetTables() []*v1.TableRef {
	if x != nil {
		return x.Tables
	}
	return nil
}

type QueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Out-of-band Arrow endpoint to pull result batches from.
	Stream        *v1.ArrowStream `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_rat_engine_v1_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rat_engine_v1_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_rat_engine_v1_engine_proto_rawDescGZIP(), []int{3}
}

func (x *QueryResponse) GetStream() *v1.ArrowStream {
	if x != nil {
		return x.Stream
	}
	return nil
}

type PreviewRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Sql    string                 `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	Tables []*v1.TableRef         `protobuf:"bytes,3,rep,name=tables,proto3" json:"tables,omitempty"`
	// Max rows to return in the sample.
	Limit         int64 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewRequest) Reset() {
	*x = PreviewRequest{}
	mi := &file_rat_engine_v1_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewRequest) ProtoMessage() {}

func (x *PreviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rat_engine_v1_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewRequest.ProtoReflect.Descriptor instead.
func (*PreviewRequest) Descriptor() ([]byte, []int) {
	return file_rat_engine_v1_engine_proto_rawDescGZIP(), []int{4}
}

func (x *PreviewRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *PreviewRequest) GetTables() []*v1.TableRef {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *PreviewRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PreviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        *v1.ArrowStream        `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewResponse) Reset() {
	*x = PreviewResponse{}
	mi := &file_rat_engine_v1_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewResponse) ProtoMessage() {}

func (x *PreviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rat_engine_v1_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewResponse.ProtoReflect.Descriptor instead.
func (*PreviewResponse) Descriptor() ([]byte, []int) {
	return file_rat_engine_v1_engine_proto_rawDescGZIP(), []int{5}
}

func (x *PreviewResponse) GetStream() *v1.ArrowStream {
	if x != nil {
		return x.Stream
	}
	return nil
}

var File_rat_engine_v1_engine_proto protoreflect.FileDescriptor

const file_rat_engine_v1_engine_proto_rawDesc = "" +
	"\n" +
	"\x1arat/engine/v1/engine.proto\x12\rrat.engine.v1\x1a\x1frat/common/v1/annotations.proto\x1a\x18rat/common/v1/data.proto\"Y\n" +
	"\x0eExecuteRequest\x12\x10\n" +
	"\x03sql\x18\x02 \x01(\tR\x03sql\x12/\n" +
	"\x06tables\x18\x03 \x03(\v2\x17.rat.common.v1.TableRefR\x06tablesJ\x04\b\x01\x10\x02\"E\n" +
	"\x0fExecuteResponse\x122\n" +
	"\x06result\x18\x01 \x01(\v2\x1a.rat.common.v1.WriteResultR\x06result\"W\n" +
	"\fQueryRequest\x12\x10\n" +
	"\x03sql\x18\x02 \x01(\tR\x03sql\x12/\n" +
	"\x06tables\x18\x03 \x03(\v2\x17.rat.common.v1.TableRefR\x06tablesJ\x04\b\x01\x10\x02\"C\n" +
	"\rQueryResponse\x122\n" +
	"\x06stream\x18\x01 \x01(\v2\x1a.rat.common.v1.ArrowStreamR\x06stream\"o\n" +
	"\x0ePreviewRequest\x12\x10\n" +
	"\x03sql\x18\x02 \x01(\tR\x03sql\x12/\n" +
	"\x06tables\x18\x03 \x03(\v2\x17.rat.common.v1.TableRefR\x06tables\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x03R\x05limitJ\x04\b\x01\x10\x02\"E\n" +
	"\x0fPreviewResponse\x122\n" +
	"\x06stream\x18\x01 \x01(\v2\x1a.rat.common.v1.ArrowStreamR\x06stream2\xbc\x02\n" +
	"\rEngineService\x12e\n" +
	"\aExecute\x12\x1d.rat.engine.v1.ExecuteRequest\x1a\x1e.rat.engine.v1.ExecuteResponse\"\x1b\x8a\x97\"\x17rat://engine/v1/execute\x12]\n" +
	"\x05Query\x12\x1b.rat.engine.v1.QueryRequest\x1a\x1c.rat.engine.v1.QueryResponse\"\x19\x8a\x97\"\x15rat://engine/v1/query\x12e\n" +
	"\aPreview\x12\x1d.rat.engine.v1.PreviewRequest\x1a\x1e.rat.engine.v1.PreviewResponse\"\x1b\x8a\x97\"\x17rat://engine/v1/previewB?Z=github.com/squat-collective/rat-v3/gen/rat/engine/v1;enginev1b\x06proto3"

var (
	file_rat_engine_v1_engine_proto_rawDescOnce sync.Once
	file_rat_engine_v1_engine_proto_rawDescData []byte
)

func file_rat_engine_v1_engine_proto_rawDescGZIP() []byte {
	file_rat_engine_v1_engine_proto_rawDescOnce.Do(func() {
		file_rat_engine_v1_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rat_engine_v1_engine_proto_rawDesc), len(file_rat_engine_v1_engine_proto_rawDesc)))
	})
	return file_rat_engine_v1_engine_proto_rawDescData
}

var file_rat_engine_v1_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rat_engine_v1_engine_proto_goTypes = []any{
	(*ExecuteRequest)(nil),  // 0: rat.engine.v1.ExecuteRequest
	(*ExecuteResponse)(nil), // 1: rat.engine.v1.ExecuteResponse
	(*QueryRequest)(nil),    // 2: rat.engine.v1.QueryRequest
	(*QueryResponse)(nil),   // 3: rat.engine.v1.QueryResponse
	(*PreviewRequest)(nil),  // 4: rat.engine.v1.PreviewRequest
	(*PreviewResponse)(nil), // 5: rat.engine.v1.PreviewResponse
	(*v1.TableRef)(nil),     // 6: rat.common.v1.TableRef
	(*v1.WriteResult)(nil),  // 7: rat.common.v1.WriteResult
	(*v1.ArrowStream)(nil),  // 8: rat.common.v1.ArrowStream
}
var file_rat_engine_v1_engine_proto_depIdxs = []int32{
	6, // 0: rat.engine.v1.ExecuteRequest.tables:type_name -> rat.common.v1.TableRef
	7, // 1: rat.engine.v1.ExecuteResponse.result:type_name -> rat.common.v1.WriteResult
	6, // 2: rat.engine.v1.QueryRequest.tables:type_name -> rat.common.v1.TableRef
	8, // 3: rat.engine.v1.QueryResponse.stream:type_name -> rat.common.v1.ArrowStream
	6, // 4: rat.engine.v1.PreviewRequest.tables:type_name -> rat.common.v1.TableRef
	8, // 5: rat.engine.v1.PreviewResponse.stream:type_name -> rat.common.v1.ArrowStream
	0, // 6: rat.engine.v1.EngineService.Execute:input_type -> rat.engine.v1.ExecuteRequest
	2, // 7: rat.engine.v1.EngineService.Query:input_type -> rat.engine.v1.QueryRequest
	4, // 8: rat.engine.v1.EngineService.Preview:input_type -> rat.engine.v1.PreviewRequest
	1, // 9: rat.engine.v1.EngineService.Execute:output_type -> rat.engine.v1.ExecuteResponse
	3, // 10: rat.engine.v1.EngineService.Query:output_type -> rat.engine.v1.QueryResponse
	5, // 11: rat.engine.v1.EngineService.Preview:output_type -> rat.engine.v1.PreviewResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_rat_engine_v1_engine_proto_init() }
func file_rat_engine_v1_engine_proto_init() {
	if File_rat_engine_v1_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rat_engine_v1_engine_proto_rawDesc), len(file_rat_engine_v1_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rat_engine_v1_engine_proto_goTypes,
		DependencyIndexes: file_rat_engine_v1_engine_proto_depIdxs,
		MessageInfos:      file_rat_engine_v1_engine_proto_msgTypes,
	}.Build()
	File_rat_engine_v1_engine_proto = out.File
	file_rat_engine_v1_engine_proto_goTypes = nil
	file_rat_engine_v1_engine_proto_depIdxs = nil
}
